
'use client';

export interface EducationQualification {
    id: number;
    level: string;
    course: string;
}

export const EDUCATION_QUALIFICATIONS: EducationQualification[] = [
    { id: 1, level: 'Middle School Education', course: 'CLASS 8' },
    { id: 2, level: 'Secondary Education', course: 'CLASS 9' },
    { id: 3, level: 'Secondary Education', course: 'SSLC' },
    { id: 4, level: 'Diploma (SSLC)', course: 'Vocational Diploma in Refrigeration & Air Conditioning Technician' },
    { id: 5, level: 'Diploma (SSLC)', course: 'Vocational Diploma in Vehicle Mechanic' },
    { id: 6, level: 'Diploma (SSLC)', course: 'Vocational Diploma in Fashion Design & Garment Making' },
    { id: 7, level: 'Diploma (SSLC)', course: 'Vocational Diploma in Beauty Therapist' },
    { id: 8, level: 'Diploma (SSLC)', course: 'Vocational Diploma in Office Automation' },
    { id: 9, level: 'Diploma (SSLC)', course: 'Vocational Diploma in In-Design (Digital Layout)' },
    { id: 10, level: 'Diploma (SSLC)', course: 'Vocational Diploma in Acupressure Therapist' },
    { id: 11, level: 'Diploma (SSLC)', course: 'Vocational Diploma in General Duty Assistant' },
    { id: 12, level: 'Diploma (SSLC)', course: 'Diploma in Archaeology & Epigraphy' },
    { id: 13, level: 'Diploma (SSLC)', course: 'Diploma in Tourism & Tour Operations Management' },
    { id: 14, level: 'Diploma (SSLC)', course: 'Diploma in Cooperative Management' },
    { id: 15, level: 'Diploma (SSLC)', course: 'Diploma in Journalism & Mass Communication' },
    { id: 16, level: 'Diploma (SSLC)', course: 'Diploma in Taxation' },
    { id: 17, level: 'Diploma (SSLC)', course: 'Diploma in Labour Law' },
    { id: 18, level: 'Diploma (SSLC)', course: 'Diploma in Public Administration' },
    { id: 19, level: 'Diploma (SSLC)', course: 'Diploma in Police Administration' },
    { id: 20, level: 'Diploma (SSLC)', course: 'Diploma in Tamil Pulavar (Scholarly Studies)' },
    { id: 21, level: 'Diploma (SSLC)', course: 'Diploma in Tamil Pandit Training' },
    { id: 22, level: 'Diploma (SSLC)', course: 'Diploma in Tamil Journalism' },
    { id: 23, level: 'Diploma (SSLC)', course: 'Diploma in Insurance & Risk Management' },
    { id: 24, level: 'Diploma (SSLC)', course: 'Diploma in Human Rights' },
    { id: 25, level: 'Diploma (SSLC)', course: 'Medical Laboratory Technology (DMLT)' },
    { id: 26, level: 'Diploma (SSLC)', course: 'X-Ray / Imaging Technology' },
    { id: 27, level: 'Diploma (SSLC)', course: 'Optometry' },
    { id: 28, level: 'Diploma (SSLC)', course: 'Physiotherapy Technician' },
    { id: 29, level: 'Diploma (SSLC)', course: 'Emergency Care / Accident & Emergency Technology' },
    { id: 30, level: 'Diploma (SSLC)', course: 'Dialysis Technology' },
    { id: 31, level: 'Diploma (SSLC)', course: 'Patient Care / Nursing' },
    { id: 32, level: 'Diploma (SSLC)', course: 'Mushroom Cultivation & allied agri-enterprises' },
    { id: 33, level: 'Diploma (SSLC)', course: 'OTHERS' },
    { id: 34, level: 'Higher Secondary Education', course: 'CLASS 11' },
    { id: 35, level: 'Higher Secondary Education', course: 'HSC' },
    { id: 36, level: 'Diploma (HSC)', course: 'Diploma in Medical Laboratory Technology (DMLT)' },
    { id: 37, level: 'Diploma (HSC)', course: 'Diploma in X-Ray & Imaging Technology' },
    { id: 38, level: 'Diploma (HSC)', course: 'Diploma in Operation Theatre Technology' },
    { id: 39, level: 'Diploma (HSC)', course: 'Diploma in Anesthesia Technology' },
    { id: 40, level: 'Diploma (HSC)', course: 'Diploma in Accident & Emergency Technology' },
    { id: 41, level: 'Diploma (HSC)', course: 'Diploma in Critical Care Management' },
    { id: 42, level: 'Diploma (HSC)', course: 'Diploma in Patient Care (Nursing)' },
    { id: 43, level: 'Diploma (HSC)', course: 'Diploma in Physician Assistant' },
    { id: 44, level: 'Diploma (HSC)', course: 'Dialysis Technology Diploma' },
    { id: 45, level: 'Diploma (HSC)', course: 'Medical Record Science Diploma' },
    { id: 46, level: 'Diploma (HSC)', course: 'Diploma in Teacher Education (D.El.Ed. / D.T.Ed.)' },
    { id: 47, level: 'Diploma (HSC)', course: 'Diploma in Physical Education (D.P.Ed.)' },
    { id: 48, level: 'Diploma (HSC)', course: 'Diploma in Pharmacy (D.Pharm)' },
    { id: 49, level: 'Diploma (HSC)', course: 'Diploma in Visual Communication' },
    { id: 50, level: 'Diploma (HSC)', course: 'Diploma in Journalism' },
    { id: 51, level: 'Diploma (HSC)', course: 'Diploma in Entrepreneurship Development' },
    { id: 52, level: 'Diploma (HSC)', course: 'Diploma in Direction (Film)' },
    { id: 53, level: 'Diploma (HSC)', course: 'Diploma in Practical Accounting' },
    { id: 54, level: 'Diploma (HSC)', course: 'Diploma in E-Commerce and Accounting' },
    { id: 55, level: 'Diploma (HSC)', course: 'Diploma in Banking Management' },
    { id: 56, level: 'Diploma (HSC)', course: 'Industrial Aquaculture Technology Diploma' },
    { id: 57, level: 'Diploma (HSC)', course: 'OTHERS' },
    { id: 58, level: 'Polytechnic', course: 'Polytechnic Diploma Courses in Tamil Nadu (Engineering & Technology)' },
    { id: 59, level: 'Polytechnic', course: 'Civil Engineering' },
    { id: 60, level: 'Polytechnic', course: 'Architectural Assistantship' },
    { id: 61, level: 'Polytechnic', course: 'Mechanical Engineering' },
    { id: 62, level: 'Polytechnic', course: 'Automobile Engineering' },
    { id: 63, level: 'Polytechnic', course: 'Production Engineering' },
    { id: 64, level: 'Polytechnic', course: 'Metallurgy' },
    { id: 65, level: 'Polytechnic', course: 'Marine Engineering' },
    { id: 66, level: 'Polytechnic', course: 'Electrical and Electronics Engineering (EEE)' },
    { id: 67, level: 'Polytechnic', course: 'Electronics and Communication Engineering (ECE)' },
    { id: 68, level: 'Polytechnic', course: 'Instrumentation and Control Engineering' },
    { id: 69, level: 'Polytechnic', course: 'Information Technology' },
    { id: 70, level: 'Polytechnic', course: 'Mechatronics Engineering' },
    { id: 71, level: 'Polytechnic', course: 'Electronics (Robotics)' },
    { id: 72, level: 'Polytechnic', course: 'Computer Engineering' },
    { id: 73, level: 'Polytechnic', course: 'Computer Networking' },
    { id: 74, level: 'Polytechnic', course: '3D Animation and Graphics' },
    { id: 75, level: 'Polytechnic', course: 'Textile Technology' },
    { id: 76, level: 'Polytechnic', course: 'Textile Processing' },
    { id: 77, level: 'Polytechnic', course: 'Textile Marketing and Management' },
    { id: 78, level: 'Polytechnic', course: 'Garment Technology' },
    { id: 79, level: 'Polytechnic', course: 'Textile Technology (Knitting)' },
    { id: 80, level: 'Polytechnic', course: 'Apparel Technology' },
    { id: 81, level: 'Polytechnic', course: 'Sugar Technology' },
    { id: 82, level: 'Polytechnic', course: 'Petrochemical Engineering' },
    { id: 83, level: 'Polytechnic', course: 'Chemical Engineering' },
    { id: 84, level: 'Polytechnic', course: 'Leather Technology (Footwear)' },
    { id: 85, level: 'Polytechnic', course: 'Modern Office Practice' },
    { id: 86, level: 'Polytechnic', course: 'Aircraft Maintenance Engineering (Avionics)' },
    { id: 87, level: 'Polytechnic', course: 'Aeronautical Engineering' },
    { id: 88, level: 'Polytechnic', course: 'Medical Electronics' },
    { id: 89, level: 'Polytechnic', course: 'Printing Technology' },
    { id: 90, level: 'Polytechnic', course: 'Industrial Safety' },
    { id: 91, level: 'Polytechnic', course: 'Hotel Management and Catering Technology' },
    { id: 92, level: 'Polytechnic', course: 'Mechanical Engineering (Tool and Die)' },
    { id: 93, level: 'Polytechnic', course: 'Mechanical Engineering (Refrigeration & Air-Conditioning)' },
    { id: 94, level: 'Polytechnic', course: 'Agricultural Technology' },
    { id: 95, level: 'Polytechnic', course: 'Fashion Technology' },
    { id: 96, level: 'Polytechnic', course: 'Textile Technology (Design & Weaving)' },
    { id: 97, level: 'Polytechnic', course: 'Textile Technology (Man-made Fibre)' },
    { id: 98, level: 'Polytechnic', course: 'Applied Arts and Crafts (Fashion & Apparel Design)' },
    { id: 99, level: 'Polytechnic', course: 'Textile Technology (Knitting & Garment Technology)' },
    { id: 100, level: 'Polytechnic', course: 'Civil Engineering (Sandwich Course)' },
    { id: 101, level: 'Polytechnic', course: 'Mechanical Engineering (Sandwich)' },
    { id: 102, level: 'Polytechnic', course: 'Mechanical Engineering (Foundry) (Sandwich)' },
    { id: 103, level: 'Polytechnic', course: 'Mechanical Engineering (Machine Tool Maintenance & Repairs) (Sandwich)' },
    { id: 104, level: 'Polytechnic', course: 'Electrical and Electronics Engineering (Sandwich)' },
    { id: 105, level: 'Polytechnic', course: 'Mechatronics Engineering (Sandwich)' },
    { id: 106, level: 'Polytechnic', course: 'Polymer Technology (Sandwich)' },
    { id: 107, level: 'Polytechnic', course: 'Chemical Engineering (Sandwich)' },
    { id: 108, level: 'Polytechnic', course: 'Ceramic Technology (Sandwich)' },
    { id: 109, level: 'Polytechnic', course: 'Leather Technology (Sandwich)' },
    { id: 110, level: 'Polytechnic', course: 'Robotics and Automation Engineering' },
    { id: 111, level: 'Polytechnic', course: 'Civil Engineering (Part-Time)' },
    { id: 112, level: 'Polytechnic', course: 'Mechanical Engineering (Part-Time)' },
    { id: 113, level: 'Polytechnic', course: 'Electrical and Electronics Engineering (Part-Time)' },
    { id: 114, level: 'Polytechnic', course: 'Electronics and Communication Engineering (Part-Time)' },
    { id: 115, level: 'Polytechnic', course: 'Civil and Environmental Engineering' },
    { id: 116, level: 'Polytechnic', course: 'Communication and Computer Networking' },
    { id: 117, level: 'Polytechnic', course: 'Artificial Intelligence and Machine Learning' },
    { id: 118, level: 'Polytechnic', course: 'Automation and Robotics' },
    { id: 119, level: 'Polytechnic', course: 'Logistics Technology' },
    { id: 120, level: 'Polytechnic', course: 'Automobile Engineering (Sandwich)' },
    { id: 121, level: 'Polytechnic', course: 'Mechanical Engineering (CAD)' },
    { id: 122, level: 'Polytechnic', course: 'Office Management and Computer Applications' },
    { id: 123, level: 'Polytechnic', course: 'ECG Technology' },
    { id: 124, level: 'Polytechnic', course: 'Web Technologies' },
    { id: 125, level: 'Polytechnic', course: 'Biomedical Electronics' },
    { id: 126, level: 'Polytechnic', course: 'Interior Decoration' },
    { id: 127, level: 'Polytechnic', course: 'Tamil Medium Civil Engineering' },
    { id: 128, level: 'Polytechnic', course: 'Tamil Medium Mechanical Engineering' },
    { id: 129, level: 'Polytechnic', course: 'Electronics and Communication Engineering (Sandwich)' },
    { id: 130, level: 'Polytechnic', course: 'Mechanical Engineering – Automobile (Sandwich)' },
    { id: 131, level: 'Polytechnic', course: 'Computer Technology (Sandwich)' },
    { id: 132, level: 'Polytechnic', course: 'Digital Manufacturing Technologies' },
    { id: 133, level: 'Polytechnic', course: 'Electrical Engineering & Electric Vehicle Technology' },
    { id: 134, level: 'Polytechnic', course: 'Refrigeration and Air Conditioning' },
    { id: 135, level: 'Polytechnic', course: 'Diploma in Architecture' },
    { id: 136, level: 'Polytechnic', course: 'Computer Engineering & IoT (Internet of Things)' },
    { id: 137, level: 'Polytechnic', course: 'Paper Technology' },
    { id: 138, level: 'Polytechnic', course: 'Electrical Engineering – Electric Vehicle Technology (Sandwich)' },
    { id: 139, level: 'Polytechnic', course: 'Direction, Screenplay & TV Production' },
    { id: 140, level: 'Polytechnic', course: 'OTHERS' },
    { id: 141, level: 'Undergraduate (UG) Education', course: 'B.A. English Literature' },
    { id: 142, level: 'Undergraduate (UG) Education', course: 'B.A. Tamil Literature' },
    { id: 143, level: 'Undergraduate (UG) Education', course: 'B.A. Economics' },
    { id: 144, level: 'Undergraduate (UG) Education', course: 'B.A. History' },
    { id: 145, level: 'Undergraduate (UG) Education', course: 'B.A. Sociology' },
    { id: 146, level: 'Undergraduate (UG) Education', course: 'B.A. Arabic' },
    { id: 147, level: 'Undergraduate (UG) Education', course: 'B.A. Hindi' },
    { id: 148, level: 'Undergraduate (UG) Education', course: 'B.A. Criminology & Police Administration' },
    { id: 149, level: 'Undergraduate (UG) Education', course: 'B.A. Political Science' },
    { id: 150, level: 'Undergraduate (UG) Education', course: 'B.A. Journalism and Mass Communication' },
    { id: 151, level: 'Undergraduate (UG) Education', course: 'B.A. Public Administration' },
    { id: 152, level: 'Undergraduate (UG) Education', course: 'B.A. Tourism & Travel Management' },
    { id: 153, level: 'Undergraduate (UG) Education', course: 'B.Com. (General)' },
    { id: 154, level: 'Undergraduate (UG) Education', course: 'B.Com. Corporate Secretaryship' },
    { id: 155, level: 'Undergraduate (UG) Education', course: 'B.Com. Accounting & Finance' },
    { id: 156, level: 'Undergraduate (UG) Education', course: 'B.Com. Bank Management' },
    { id: 157, level: 'Undergraduate (UG) Education', course: 'B.Com. Marketing' },
    { id: 158, level: 'Undergraduate (UG) Education', course: 'B.Com. Finance & Taxation' },
    { id: 159, level: 'Undergraduate (UG) Education', course: 'B.Com. Business Process Services (BPS)' },
    { id: 160, level: 'Undergraduate (UG) Education', course: 'B.B.A. (General)' },
    { id: 161, level: 'Undergraduate (UG) Education', course: 'B.B.A. Retail Management' },
    { id: 162, level: 'Undergraduate (UG) Education', course: 'B.B.A. Aviation' },
    { id: 163, level: 'Undergraduate (UG) Education', course: 'B.B.A. Logistics' },
    { id: 164, level: 'Undergraduate (UG) Education', course: 'B.C.A. (Computer Applications)' },
    { id: 165, level: 'Undergraduate (UG) Education', course: 'B.A. LL.B.' },
    { id: 166, level: 'Undergraduate (UG) Education', course: 'B.B.A. LL.B.' },
    { id: 167, level: 'Undergraduate (UG) Education', course: 'B.Com. LL.B.' },
    { id: 168, level: 'Undergraduate (UG) Education', course: 'B.Sc. LL.B.' },
    { id: 169, level: 'Undergraduate (UG) Education', course: 'LL.B.' },
    { id: 170, level: 'Undergraduate (UG) Education', course: 'B.Sc. Physics' },
    { id: 171, level: 'Undergraduate (UG) Education', course: 'B.Sc. Chemistry' },
    { id: 172, level: 'Undergraduate (UG) Education', course: 'B.Sc. Mathematics' },
    { id: 173, level: 'Undergraduate (UG) Education', course: 'B.Sc. Statistics' },
    { id: 174, level: 'Undergraduate (UG) Education', course: 'B.Sc. Computer Science' },
    { id: 175, level: 'Undergraduate (UG) Education', course: 'B.Sc. Computer Science (Artificial Intelligence)' },
    { id: 176, level: 'Undergraduate (UG) Education', course: 'B.Sc. Software Engineering' },
    { id: 177, level: 'Undergraduate (UG) Education', course: 'B.Sc. Computer Technology' },
    { id: 178, level: 'Undergraduate (UG) Education', course: 'B.Sc. Information Technology' },
    { id: 179, level: 'Undergraduate (UG) Education', course: 'B.Sc. Electronics & Communication Systems' },
    { id: 180, level: 'Undergraduate (UG) Education', course: 'B.Sc. Aircraft Maintenance Science' },
    { id: 181, level: 'Undergraduate (UG) Education', course: 'B.Sc. Botany' },
    { id: 182, level: 'Undergraduate (UG) Education', course: 'B.Sc. Zoology' },
    { id: 183, level: 'Undergraduate (UG) Education', course: 'B.Sc. Advanced Zoology & Biotechnology' },
    { id: 184, level: 'Undergraduate (UG) Education', course: 'B.Sc. Plant Biology & Plant Biotechnology' },
    { id: 185, level: 'Undergraduate (UG) Education', course: 'B.Sc. Biotechnology' },
    { id: 186, level: 'Undergraduate (UG) Education', course: 'B.Sc. Biochemistry' },
    { id: 187, level: 'Undergraduate (UG) Education', course: 'B.Sc. Microbiology' },
    { id: 188, level: 'Undergraduate (UG) Education', course: 'B.Sc. Nanoscience' },
    { id: 189, level: 'Undergraduate (UG) Education', course: 'B.Sc. Food Science & Nutrition' },
    { id: 190, level: 'Undergraduate (UG) Education', course: 'B.Sc. Food and Dairy Technology' },
    { id: 191, level: 'Undergraduate (UG) Education', course: 'B.Sc. Visual Communication' },
    { id: 192, level: 'Undergraduate (UG) Education', course: 'B.Sc. Interior Design & Décor' },
    { id: 193, level: 'Undergraduate (UG) Education', course: 'B.Sc. Psychology' },
    { id: 194, level: 'Undergraduate (UG) Education', course: 'B.Sc. (Hons.) Agriculture' },
    { id: 195, level: 'Undergraduate (UG) Education', course: 'B.Sc. Agriculture (Tamil Medium)' },
    { id: 196, level: 'Undergraduate (UG) Education', course: 'B.Sc. (Hons.) Horticulture' },
    { id: 197, level: 'Undergraduate (UG) Education', course: 'B.Sc. Horticulture (Tamil Medium)' },
    { id: 198, level: 'Undergraduate (UG) Education', course: 'B.Sc. (Hons.) Sericulture' },
    { id: 199, level: 'Undergraduate (UG) Education', course: 'B.Sc. (Hons.) Forestry' },
    { id: 200, level: 'Undergraduate (UG) Education', course: 'B.Sc. (Hons.) Food, Nutrition & Dietetics' },
    { id: 201, level: 'Undergraduate (UG) Education', course: 'B.Sc. (Hons.) Agri Business Management' },
    { id: 202, level: 'Undergraduate (UG) Education', course: 'B.Tech. Agricultural Engineering' },
    { id: 203, level: 'Undergraduate (UG) Education', course: 'B.Tech. Energy & Environmental Engineering' },
    { id: 204, level: 'Undergraduate (UG) Education', course: 'B.Tech. Biotechnology' },
    { id: 205, level: 'Undergraduate (UG) Education', course: 'B.Tech. Bioinformatics' },
    { id: 206, level: 'Undergraduate (UG) Education', course: 'B.Tech. Agriculture Information Technology' },
    { id: 207, level: 'Undergraduate (UG) Education', course: 'B.Tech. Food Technology' },
    { id: 208, level: 'Undergraduate (UG) Education', course: 'B.Sc. Hotel and Catering Management' },
    { id: 209, level: 'Undergraduate (UG) Education', course: 'B.Sc. Catering Science and Hotel Management' },
    { id: 210, level: 'Undergraduate (UG) Education', course: 'B.Sc. Hospitality and Hotel Administration' },
    { id: 211, level: 'Undergraduate (UG) Education', course: 'B.P.Ed. (Bachelor of Physical Education)' },
    { id: 212, level: 'Undergraduate (UG) Education', course: 'B.V.Sc. & A.H. (Veterinary Science)' },
    { id: 213, level: 'Undergraduate (UG) Education', course: 'BPT (Bachelor of Physiotherapy)' },
    { id: 214, level: 'Undergraduate (UG) Education', course: 'BOT (Bachelor of Occupational Therapy)' },
    { id: 215, level: 'Undergraduate (UG) Education', course: 'B.Optom (Optometry)' },
    { id: 216, level: 'Undergraduate (UG) Education', course: 'B.Sc. Clinical Nutrition & Dietetics' },
    { id: 217, level: 'Undergraduate (UG) Education', course: 'B.Sc. Medical Laboratory Technology (MLT)' },
    { id: 218, level: 'Undergraduate (UG) Education', course: 'B.Sc. Allied Health Sciences (various specializations)' },
    { id: 219, level: 'Undergraduate (UG) Education', course: 'B.Tech. Artificial Intelligence & Machine Learning' },
    { id: 220, level: 'Undergraduate (UG) Education', course: 'B.Tech. Artificial Intelligence & Data Science' },
    { id: 221, level: 'Undergraduate (UG) Education', course: 'OTHERS' },
    { id: 222, level: 'Teacher Training / Education', course: 'D.El.Ed.' },
    { id: 223, level: 'Teacher Training / Education', course: 'B.Ed.' },
    { id: 224, level: 'Teacher Training / Education', course: 'M.Ed.' },
    { id: 225, level: 'Teacher Training / Education', course: 'OTHERS' },
    { id: 226, level: 'Postgraduate (PG) Education', course: 'M.A. English Literature' },
    { id: 227, level: 'Postgraduate (PG) Education', course: 'M.A. Tamil Literature' },
    { id: 228, level: 'Postgraduate (PG) Education', course: 'M.A. Economics' },
    { id: 229, level: 'Postgraduate (PG) Education', course: 'M.A. History' },
    { id: 230, level: 'Postgraduate (PG) Education', course: 'M.A. Sociology' },
    { id: 231, level: 'Postgraduate (PG) Education', course: 'M.A. Political Science' },
    { id: 232, level: 'Postgraduate (PG) Education', course: 'M.A. Public Administration' },
    { id: 233, level: 'Postgraduate (PG) Education', course: 'M.A. Journalism & Mass Communication' },
    { id: 234, level: 'Postgraduate (PG) Education', course: 'M.A. Criminology & Police Administration' },
    { id: 235, level: 'Postgraduate (PG) Education', course: 'M.A. Tourism & Travel Management' },
    { id: 236, level: 'Postgraduate (PG) Education', course: 'M.A. Philosophy' },
    { id: 237, level: 'Postgraduate (PG) Education', course: 'M.A. Social Work (MSW)' },
    { id: 238, level: 'Postgraduate (PG) Education', course: 'M.Com. (General)' },
    { id: 239, level: 'Postgraduate (PG) Education', course: 'M.Com. Corporate Secretaryship' },
    { id: 240, level: 'Postgraduate (PG) Education', course: 'M.Com. Accounting & Finance' },
    { id: 241, level: 'Postgraduate (PG) Education', course: 'M.Com. Bank Management' },
    { id: 242, level: 'Postgraduate (PG) Education', course: 'M.Com. Marketing' },
    { id: 243, level: 'Postgraduate (PG) Education', course: 'M.Com. Finance & Taxation' },
    { id: 244, level: 'Postgraduate (PG) Education', course: 'MBA (General)' },
    { id: 245, level: 'Postgraduate (PG) Education', course: 'MBA Human Resource Management' },
    { id: 246, level: 'Postgraduate (PG) Education', course: 'MBA Finance' },
    { id: 247, level: 'Postgraduate (PG) Education', course: 'MBA Marketing' },
    { id: 248, level: 'Postgraduate (PG) Education', course: 'MBA Operations Management' },
    { id: 249, level: 'Postgraduate (PG) Education', course: 'MBA International Business' },
    { id: 250, level: 'Postgraduate (PG) Education', course: 'MBA Logistics & Supply Chain Management' },
    { id: 251, level: 'Postgraduate (PG) Education', course: 'MBA Hospital Administration' },
    { id: 252, level: 'Postgraduate (PG) Education', course: 'MBA Aviation Management' },
    { id: 253, level: 'Postgraduate (PG) Education', course: 'MBA Agri Business Management' },
    { id: 254, level: 'Postgraduate (PG) Education', course: 'MCA (Master of Computer Applications)' },
    { id: 255, level: 'Postgraduate (PG) Education', course: 'LLM (Master of Law) – General' },
    { id: 256, level: 'Postgraduate (PG) Education', course: 'LLM Constitutional & Administrative Law' },
    { id: 257, level: 'Postgraduate (PG) Education', course: 'LLM Corporate & Business Law' },
    { id: 258, level: 'Postgraduate (PG) Education', course: 'LLM Criminal Law & Criminal Justice Administration' },
    { id: 259, level: 'Postgraduate (PG) Education', course: 'LLM International Law & Organizations' },
    { id: 260, level: 'Postgraduate (PG) Education', course: 'LLM Intellectual Property Rights Law' },
    { id: 261, level: 'Postgraduate (PG) Education', course: 'LLM Environmental Law' },
    { id: 262, level: 'Postgraduate (PG) Education', course: 'M.Sc. Physics' },
    { id: 263, level: 'Postgraduate (PG) Education', course: 'M.Sc. Chemistry' },
    { id: 264, level: 'Postgraduate (PG) Education', course: 'M.Sc. Mathematics' },
    { id: 265, level: 'Postgraduate (PG) Education', course: 'M.Sc. Statistics' },
    { id: 266, level: 'Postgraduate (PG) Education', course: 'M.Sc. Computer Science' },
    { id: 267, level: 'Postgraduate (PG) Education', course: 'M.Sc. Information Technology' },
    { id: 268, level: 'Postgraduate (PG) Education', course: 'M.Sc. Electronics & Communication Science' },
    { id: 269, level: 'Postgraduate (PG) Education', course: 'M.Sc. Data Science' },
    { id: 270, level: 'Postgraduate (PG) Education', course: 'M.Sc. Artificial Intelligence' },
    { id: 271, level: 'Postgraduate (PG) Education', course: 'M.Sc. Biotechnology' },
    { id: 272, level: 'Postgraduate (PG) Education', course: 'M.Sc. Microbiology' },
    { id: 273, level: 'Postgraduate (PG) Education', course: 'M.Sc. Biochemistry' },
    { id: 274, level: 'Postgraduate (PG) Education', course: 'M.Sc. Environmental Science' },
    { id: 275, level: 'Postgraduate (PG) Education', course: 'M.Sc. Botany' },
    { id: 276, level: 'Postgraduate (PG) Education', course: 'M.Sc. Zoology' },
    { id: 277, level: 'Postgraduate (PG) Education', course: 'M.Sc. Plant Biology & Plant Biotechnology' },
    { id: 278, level: 'Postgraduate (PG) Education', course: 'M.Sc. Applied Psychology' },
    { id: 279, level: 'Postgraduate (PG) Education', course: 'M.Sc. Clinical Psychology' },
    { id: 280, level: 'Postgraduate (PG) Education', course: 'M.Sc. Nanoscience & Nanotechnology' },
    { id: 281, level: 'Postgraduate (PG) Education', course: 'M.Sc. Food Science & Nutrition' },
    { id: 282, level: 'Postgraduate (PG) Education', course: 'M.Sc. Visual Communication' },
    { id: 283, level: 'Postgraduate (PG) Education', course: 'M.Sc. Geography' },
    { id: 284, level: 'Postgraduate (PG) Education', course: 'M.Sc. Geology' },
    { id: 285, level: 'Postgraduate (PG) Education', course: 'M.Sc. (Agriculture) – various specializations' },
    { id: 286, level: 'Postgraduate (PG) Education', course: 'M.Sc. Horticulture – specializations' },
    { id: 287, level: 'Postgraduate (PG) Education', course: 'M.Sc. Forestry' },
    { id: 288, level: 'Postgraduate (PG) Education', course: 'M.Sc. Sericulture' },
    { id: 289, level: 'Postgraduate (PG) Education', course: 'M.Sc. Seed Science & Technology' },
    { id: 290, level: 'Postgraduate (PG) Education', course: 'M.Sc. Agricultural Economics' },
    { id: 291, level: 'Postgraduate (PG) Education', course: 'M.Sc. Agricultural Extension' },
    { id: 292, level: 'Postgraduate (PG) Education', course: 'M.Tech. Agricultural Engineering' },
    { id: 293, level: 'Postgraduate (PG) Education', course: 'M.Tech. Food Technology' },
    { id: 294, level: 'Postgraduate (PG) Education', course: 'M.Tech. Bioinformatics' },
    { id: 295, level: 'Postgraduate (PG) Education', course: 'M.Tech. Environmental Engineering' },
    { id: 296, level: 'Postgraduate (PG) Education', course: 'M.Sc. Hotel & Catering Management' },
    { id: 297, level: 'Postgraduate (PG) Education', course: 'M.Sc. Hospitality & Tourism Management' },
    { id: 298, level: 'Postgraduate (PG) Education', course: 'M.P.Ed. (Master of Physical Education)' },
    { id: 299, level: 'Postgraduate (PG) Education', course: 'M.Sc. Sports Science' },
    { id: 300, level: 'Postgraduate (PG) Education', course: 'M.V.Sc. (Master of Veterinary Science)' },
    { id: 301, level: 'Postgraduate (PG) Education', course: 'MPT (Master of Physiotherapy)' },
    { id: 302, level: 'Postgraduate (PG) Education', course: 'MOT (Master of Occupational Therapy)' },
    { id: 303, level: 'Postgraduate (PG) Education', course: 'M.Optom (Master of Optometry)' },
    { id: 304, level: 'Postgraduate (PG) Education', course: 'M.Sc. Clinical Nutrition & Dietetics' },
    { id: 305, level: 'Postgraduate (PG) Education', course: 'M.Sc. Medical Laboratory Technology' },
    { id: 306, level: 'Postgraduate (PG) Education', course: 'M.Sc. Nursing' },
    { id: 307, level: 'Postgraduate (PG) Education', course: 'Master of Public Health (MPH)' },
    { id: 308, level: 'Postgraduate (PG) Education', course: 'Doctor of Pharmacy (Pharm.D – Post Baccalaureate)' },
    { id: 309, level: 'Postgraduate (PG) Education', course: 'M.E. / M.Tech. Civil Engineering' },
    { id: 310, level: 'Postgraduate (PG) Education', course: 'M.E. / M.Tech. Mechanical Engineering' },
    { id: 311, level: 'Postgraduate (PG) Education', course: 'M.E. / M.Tech. Electrical & Electronics Engineering' },
    { id: 312, level: 'Postgraduate (PG) Education', course: 'M.E. / M.Tech. Electronics & Communication Engineering' },
    { id: 313, level: 'Postgraduate (PG) Education', course: 'M.E. / M.Tech. Computer Science & Engineering' },
    { id: 314, level: 'Postgraduate (PG) Education', course: 'M.E. / M.Tech. Information Technology' },
    { id: 315, level: 'Postgraduate (PG) Education', course: 'M.Tech. Artificial Intelligence & Data Science' },
    { id: 316, level: 'Postgraduate (PG) Education', course: 'M.Tech. Artificial Intelligence & Machine Learning' },
    { id: 317, level: 'Postgraduate (PG) Education', course: 'M.Tech. Software Engineering' },
    { id: 318, level: 'Postgraduate (PG) Education', course: 'M.Tech. Biotechnology' },
    { id: 319, level: 'Postgraduate (PG) Education', course: 'M.Tech. Nanotechnology' },
    { id: 320, level: 'Postgraduate (PG) Education', course: 'M.Tech. VLSI Design' },
    { id: 321, level: 'Postgraduate (PG) Education', course: 'M.Tech. Robotics & Automation' },
    { id: 322, level: 'Postgraduate (PG) Education', course: 'OTHERS' },
    { id: 323, level: 'UG - Engineering', course: 'B.E. Civil Engineering' },
    { id: 324, level: 'UG - Engineering', course: 'B.E. Mechanical Engineering' },
    { id: 325, level: 'UG - Engineering', course: 'B.E. Electrical & Electronics Engineering (EEE)' },
    { id: 326, level: 'UG - Engineering', course: 'B.E. Electronics & Communication Engineering (ECE)' },
    { id: 327, level: 'UG - Engineering', course: 'B.E. Computer Science & Engineering (CSE)' },
    { id: 328, level: 'UG - Engineering', course: 'B.Tech. Information Technology (IT)' },
    { id: 329, level: 'UG - Engineering', course: 'B.E. Computer & Communication Engineering' },
    { id: 330, level: 'UG - Engineering', course: 'B.E. Artificial Intelligence & Data Science' },
    { id: 331, level: 'UG - Engineering', course: 'B.E. Artificial Intelligence & Machine Learning' },
    { id: 332, level: 'UG - Engineering', course: 'B.E. Cyber Security' },
    { id: 333, level: 'UG - Engineering', course: 'B.E. Software Engineering' },
    { id: 334, level: 'UG - Engineering', course: 'B.E. Computer Science & Business Systems' },
    { id: 335, level: 'UG - Engineering', course: 'B.E. Electronics & Instrumentation Engineering' },
    { id: 336, level: 'UG - Engineering', course: 'B.E. Instrumentation & Control Engineering' },
    { id: 337, level: 'UG - Engineering', course: 'B.E. Electronics & Biomedical Engineering (Bio-Medical)' },
    { id: 338, level: 'UG - Engineering', course: 'B.E. Medical Electronics' },
    { id: 339, level: 'UG - Engineering', course: 'B.E. Electrical & Computer Engineering' },
    { id: 340, level: 'UG - Engineering', course: 'B.E. Production Engineering' },
    { id: 341, level: 'UG - Engineering', course: 'B.E. Manufacturing Engineering' },
    { id: 342, level: 'UG - Engineering', course: 'B.E. Mechatronics Engineering' },
    { id: 343, level: 'UG - Engineering', course: 'B.E. Industrial Engineering' },
    { id: 344, level: 'UG - Engineering', course: 'B.E. Automobile Engineering' },
    { id: 345, level: 'UG - Engineering', course: 'B.E. Aeronautical Engineering' },
    { id: 346, level: 'UG - Engineering', course: 'B.E. Aerospace Engineering' },
    { id: 347, level: 'UG - Engineering', course: 'B.E. Marine Engineering' },
    { id: 348, level: 'UG - Engineering', course: 'B.E. Mining Engineering' },
    { id: 349, level: 'UG - Engineering', course: 'B.Tech. Chemical Engineering' },
    { id: 350, level: 'UG - Engineering', course: 'B.Tech. Petroleum Engineering' },
    { id: 351, level: 'UG - Engineering', course: 'B.Tech. Petrochemical Engineering' },
    { id: 352, level: 'UG - Engineering', course: 'B.Tech. Pharmaceutical Engineering' },
    { id: 353, level: 'UG - Engineering', course: 'B.Tech. Plastics Technology' },
    { id: 354, level: 'UG - Engineering', course: 'B.Tech. Polymer Engineering' },
    { id: 355, level: 'UG - Engineering', course: 'B.Tech. Textile Technology' },
    { id: 356, level: 'UG - Engineering', course: 'B.Tech. Textile Chemistry' },
    { id: 357, level: 'UG - Engineering', course: 'B.Tech. Leather Technology' },
    { id: 358, level: 'UG - Engineering', course: 'B.Tech. Rubber Technology' },
    { id: 359, level: 'UG - Engineering', course: 'B.Tech. Ceramic Technology' },
    { id: 360, level: 'UG - Engineering', course: 'B.Tech. Printing Technology' },
    { id: 361, level: 'UG - Engineering', course: 'B.Tech. Biotechnology' },
    { id: 362, level: 'UG - Engineering', course: 'B.Tech. Bioinformatics' },
    { id: 363, level: 'UG - Engineering', course: 'B.Tech. Food Technology' },
    { id: 364, level: 'UG - Engineering', course: 'B.Tech. Agriculture & Irrigation Engineering' },
    { id: 365, level: 'UG - Engineering', course: 'B.E. Agricultural & Farm Engineering' },
    { id: 366, level: 'UG - Engineering', course: 'B.Tech. Environmental Engineering' },
    { id: 367, level: 'UG - Engineering', course: 'B.E. Naval Architecture & Offshore Engineering' },
    { id: 368, level: 'UG - Engineering', course: 'B.E. Marine Engineering' },
    { id: 369, level: 'UG - Engineering', course: 'B.E. Robotics & Automation' },
    { id: 370, level: 'UG - Engineering', course: 'B.E. Internet of Things (IoT)' },
    { id: 371, level: 'UG - Engineering', course: 'B.E. Cloud Computing & Big Data' },
    { id: 372, level: 'UG - Engineering', course: 'B.E. Artificial Intelligence & Robotics' },
    { id: 373, level: 'UG - Engineering', course: 'B.Tech. Fashion Technology' },
    { id: 374, level: 'UG - Engineering', course: 'B.Tech. Textile Engineering' },
    { id: 375, level: 'UG - Engineering', course: 'B.Tech. Geo-Informatics Engineering' },
    { id: 376, level: 'UG - Engineering', course: 'B.Tech. Medical Biotechnology' },
    { id: 377, level: 'UG - Engineering', course: 'OTHERS' },
    { id: 378, level: 'PG - Engineering', course: 'M.E. Civil Engineering' },
    { id: 379, level: 'PG - Engineering', course: 'M.E. Structural Engineering' },
    { id: 380, level: 'PG - Engineering', course: 'M.E. Environmental Engineering' },
    { id: 381, level: 'PG - Engineering', course: 'M.E. Construction Engineering & Management' },
    { id: 382, level: 'PG - Engineering', course: 'M.E. Transportation Engineering' },
    { id: 383, level: 'PG - Engineering', course: 'M.E. Geotechnical Engineering' },
    { id: 384, level: 'PG - Engineering', course: 'M.E. Water Resources Engineering' },
    { id: 385, level: 'PG - Engineering', course: 'M.E. Irrigation Water Management' },
    { id: 386, level: 'PG - Engineering', course: 'M.E. Mechanical Engineering' },
    { id: 387, level: 'PG - Engineering', course: 'M.E. Engineering Design' },
    { id: 388, level: 'PG - Engineering', course: 'M.E. Thermal Engineering' },
    { id: 389, level: 'PG - Engineering', course: 'M.E. Manufacturing Engineering' },
    { id: 390, level: 'PG - Engineering', course: 'M.E. Industrial Engineering' },
    { id: 391, level: 'PG - Engineering', course: 'M.E. CAD / CAM (Computer-Aided Design & Manufacturing)' },
    { id: 392, level: 'PG - Engineering', course: 'M.E. Automobile Engineering' },
    { id: 393, level: 'PG - Engineering', course: 'M.E. Mechatronics Engineering' },
    { id: 394, level: 'PG - Engineering', course: 'M.E. Energy Engineering' },
    { id: 395, level: 'PG - Engineering', course: 'M.E. Electrical Engineering' },
    { id: 396, level: 'PG - Engineering', course: 'M.E. Power Systems Engineering' },
    { id: 397, level: 'PG - Engineering', course: 'M.E. Power Electronics & Drives' },
    { id: 398, level: 'PG - Engineering', course: 'M.E. Control & Instrumentation Engineering' },
    { id: 399, level: 'PG - Engineering', course: 'M.E. Applied Electronics' },
    { id: 400, level: 'PG - Engineering', course: 'M.E. VLSI Design' },
    { id: 401, level: 'PG - Engineering', course: 'M.E. Communication Systems' },
    { id: 402, level: 'PG - Engineering', course: 'M.E. Embedded Systems Technologies' },
    { id: 403, level: 'PG - Engineering', course: 'M.E. Microelectronics' },
    { id: 404, level: 'PG - Engineering', course: 'M.E. Medical Electronics' },
    { id: 405, level: 'PG - Engineering', course: 'M.E. Computer Science & Engineering' },
    { id: 406, level: 'PG - Engineering', course: 'M.Tech. Information Technology' },
    { id: 407, level: 'PG - Engineering', course: 'M.E. Software Engineering' },
    { id: 408, level: 'PG - Engineering', course: 'M.E. Data Science' },
    { id: 409, level: 'PG - Engineering', course: 'M.E. Artificial Intelligence & Machine Learning' },
    { id: 410, level: 'PG - Engineering', course: 'M.E. Cyber Security' },
    { id: 411, level: 'PG - Engineering', course: 'M.E. Internet of Things (IoT)' },
    { id: 412, level: 'PG - Engineering', course: 'M.E. Cloud Computing' },
    { id: 413, level: 'PG - Engineering', course: 'M.E. Big Data Analytics' },
    { id: 414, level: 'PG - Engineering', course: 'M.Tech. Computational Engineering' },
    { id: 415, level: 'PG - Engineering', course: 'M.Tech. Chemical Engineering' },
    { id: 416, level: 'PG - Engineering', course: 'M.Tech. Biotechnology' },
    { id: 417, level: 'PG - Engineering', course: 'M.Tech. Bioprocess Technology' },
    { id: 418, level: 'PG - Engineering', course: 'M.Tech. Food Technology' },
    { id: 419, level: 'PG - Engineering', course: 'M.Tech. Pharmaceutical Engineering' },
    { id: 420, level: 'PG - Engineering', course: 'M.Tech. Petroleum Refining & Petrochemicals' },
    { id: 421, level: 'PG - Engineering', course: 'M.Tech. Textile Technology' },
    { id: 422, level: 'PG - Engineering', course: 'M.Tech. Polymer Technology' },
    { id: 423, level: 'PG - Engineering', course: 'M.Tech. Ceramic Technology' },
    { id: 424, level: 'PG - Engineering', course: 'M.Tech. Printing Technology' },
    { id: 425, level: 'PG - Engineering', course: 'M.Tech. Rubber Technology' },
    { id: 426, level: 'PG - Engineering', course: 'M.Tech. Nano Science & Technology' },
    { id: 427, level: 'PG - Engineering', course: 'M.Tech. Materials Science' },
    { id: 428, level: 'PG - Engineering', course: 'M.E. Aeronautical Engineering' },
    { id: 429, level: 'PG - Engineering', course: 'M.E. Aerospace Engineering' },
    { id: 430, level: 'PG - Engineering', course: 'M.E. Avionics' },
    { id: 431, level: 'PG - Engineering', course: 'M.E. Marine Engineering' },
    { id: 432, level: 'PG - Engineering', course: 'M.E. Naval Architecture & Offshore Engineering' },
    { id: 433, level: 'PG - Engineering', course: 'M.E. Robotics & Automation' },
    { id: 434, level: 'PG - Engineering', course: 'M.E. Industrial Safety Engineering' },
    { id: 435, level: 'PG - Engineering', course: 'M.E. Reliability Engineering' },
    { id: 436, level: 'PG - Engineering', course: 'M.E. Green Energy Technology' },
    { id: 437, level: 'PG - Engineering', course: 'M.Tech. Remote Sensing & Geo-Informatics' },
    { id: 438, level: 'PG - Engineering', course: 'M.Tech. Environmental Management' },
    { id: 439, level: 'PG - Engineering', course: 'M.Tech. Bioinformatics' },
    { id: 440, level: 'PG - Engineering', course: 'OTHERS' },
];

