
export interface MgnregsData {
  type: string;
  category: string;
  subCategory: string;
  codeNumber: string;
}

export const MOCK_MGNREGS_DATA: MgnregsData[] = [
    { type: 'FM - Financial Misappropriation', category: 'Payment to Person Who did not Work', subCategory: 'Amount misappropriated by individuals through Fake entries', codeNumber: 'FM-1.1' },
    { type: 'FM - Financial Misappropriation', category: 'Payment to Person Who did not Work', subCategory: 'Payment made but no work was done', codeNumber: 'FM-1.2' },
    { type: 'FM - Financial Misappropriation', category: 'Payment to Person Who did not Work', subCategory: 'Payment to person who did not work', codeNumber: 'FM-1.3' },
    { type: 'FM - Financial Misappropriation', category: 'Payment to Person Who did not Work', subCategory: 'Payment to non -existent person', codeNumber: 'FM-1.4' },
    { type: 'FM - Financial Misappropriation', category: 'Payment to Person Who did not Work', subCategory: 'Payment to migrated person', codeNumber: 'FM-1.5' },
    { type: 'FM - Financial Misappropriation', category: 'Payment to Person Who did not Work', subCategory: 'Payment to person (Mates; Panchayat President; Secretary; Ward Members and other influential persons and their relatives) who did not work', codeNumber: 'FM-1.6' },
    { type: 'FM - Financial Misappropriation', category: 'Payment to Person Who did not Work', subCategory: 'Payment to person employed full -time elsewhere (Government; School; private firm etc.)', codeNumber: 'FM-1.7' },
    { type: 'FM - Financial Misappropriation', category: 'Payment to Person Who did not Work', subCategory: 'Payment to person under 18 years who did not work', codeNumber: 'FM-1.8' },
    { type: 'FM - Financial Misappropriation', category: 'Payment to Person Who did not Work', subCategory: 'Wages paid to a person twice on the same date', codeNumber: 'FM-1.9' },
    { type: 'FM - Financial Misappropriation', category: 'Payment to Person Who did not Work', subCategory: 'Worksite Facilitator has got been paid as worker also on the same date', codeNumber: 'FM-1.10' },
    { type: 'FM - Financial Misappropriation', category: 'Payment to Person Who did not Work', subCategory: 'Person not present in NMR has been included in the FTO', codeNumber: 'FM-1.11' },
    { type: 'FM - Financial Misappropriation', category: 'Payment to Person Who did not Work', subCategory: 'Person has got more wages than what was due to him', codeNumber: 'FM-1.12' },
    { type: 'FM - Financial Misappropriation', category: 'Payment to Person Who did not Work', subCategory: 'payment made to Dead person', codeNumber: 'FM-1.13' },
    { type: 'FM - Financial Misappropriation', category: 'Payment to Person Who did not Work', subCategory: 'Payment to person for work done by machine', codeNumber: 'FM-1.14' },
    { type: 'FM - Financial Misappropriation', category: 'Payment to Person Who did not Work', subCategory: 'Person A’s wages have gone to Person B', codeNumber: 'FM-1.15' },
    { type: 'FM - Financial Misappropriation', category: 'Payment to Person Who did not Work', subCategory: 'Payment to person who did not work but work was done', codeNumber: 'FM-1.16' },
    { type: 'FM - Financial Misappropriation', category: 'Bribes', subCategory: 'Complaint- Money was collected for issuing Job card', codeNumber: 'FM-2.1' },
    { type: 'FM - Financial Misappropriation', category: 'Bribes', subCategory: 'Complaint-money was collected for taking photographs', codeNumber: 'FM-2.2' },
    { type: 'FM - Financial Misappropriation', category: 'Bribes', subCategory: 'Complaint-money was collected for opening bank/Post Office account', codeNumber: 'FM-2.3' },
    { type: 'FM - Financial Misappropriation', category: 'Bribes', subCategory: 'Complaint-commission is withheld during wage payment', codeNumber: 'FM-2.4' },
    { type: 'FM - Financial Misappropriation', category: 'Bribes', subCategory: 'Business correspondent/Bank/Post Office takes a commission during wage payment', codeNumber: 'FM-2.5' },
    { type: 'FM - Financial Misappropriation', category: 'Bribes', subCategory: 'Complaint-money was collected for allotting individual work', codeNumber: 'FM-2.6' },
    { type: 'FM - Financial Misappropriation', category: 'Work Related', subCategory: 'Work was not done /No work found at the work site', codeNumber: 'FM-3.1' },
    { type: 'FM - Financial Misappropriation', category: 'Work Related', subCategory: 'Saplings were not planted in plantation work', codeNumber: 'FM-3.2' },
    { type: 'FM - Financial Misappropriation', category: 'Work Related', subCategory: 'Farm Pond was not constructed', codeNumber: 'FM-3.3' },
    { type: 'FM - Financial Misappropriation', category: 'Work Related', subCategory: 'No trace of work now', codeNumber: 'FM-3.4' },
    { type: 'FM - Financial Misappropriation', category: 'Work Related', subCategory: 'No trace of planted saplings', codeNumber: 'FM-3.5' },
    { type: 'FM - Financial Misappropriation', category: 'Work Related', subCategory: 'Work was done through contractors', codeNumber: 'FM-3.6' },
    { type: 'FM - Financial Misappropriation', category: 'Work Related', subCategory: 'Work was done through machines', codeNumber: 'FM-3.7' },
    { type: 'FM - Financial Misappropriation', category: 'Work Related', subCategory: 'Work was allotted to ineligible beneficiary', codeNumber: 'FM-3.8' },
    { type: 'FM - Financial Misappropriation', category: 'Work Related', subCategory: 'Inappropriate work was executed', codeNumber: 'FM-3.9' },
    { type: 'FM - Financial Misappropriation', category: 'Work Related', subCategory: 'IHHL not constructed but payment has been made', codeNumber: 'FM-3.10' },
    { type: 'FM - Financial Misappropriation', category: 'Work Related', subCategory: 'Amount paid for already for constructed IHHL', codeNumber: 'FM-3.11' },
    { type: 'FM - Financial Misappropriation', category: 'Work Related', subCategory: 'Payment has been made twice for the same work', codeNumber: 'FM-3.12' },
    { type: 'FM - Financial Misappropriation', category: 'Material Procurement', subCategory: 'Material have been procured high rate', codeNumber: 'FM-4.1' },
    { type: 'FM - Financial Misappropriation', category: 'Material Procurement', subCategory: 'Poor quality material has been used', codeNumber: 'FM-4.2' },
    { type: 'FM - Financial Misappropriation', category: 'Material Procurement', subCategory: 'Fake bills', codeNumber: 'FM-4.3' },
    { type: 'FM - Financial Misappropriation', category: 'Material Procurement', subCategory: 'Booked expenses have not been spent', codeNumber: 'FM-4.4' },
    { type: 'FM - Financial Misappropriation', category: 'Material Procurement', subCategory: 'Amount of material purchased is less than specified in the bills', codeNumber: 'FM-4.5' },
    { type: 'FM - Financial Misappropriation', category: 'Others', subCategory: 'Muster roll not found in worksite', codeNumber: 'FM-5.1' },
    { type: 'FM - Financial Misappropriation', category: 'Others', subCategory: 'Workers found in worksite with no name in muster roll', codeNumber: 'FM-5.2' },
    { type: 'FM - Financial Misappropriation', category: 'Others', subCategory: 'Inappropriate administrative expenses', codeNumber: 'FM-5.3' },
    { type: 'FM - Financial Misappropriation', category: 'Others', subCategory: 'Skilled expenditure has been paid at higher rates', codeNumber: 'FM-5.4' },
    { type: 'FM - Financial Misappropriation', category: 'Others', subCategory: 'Payment to worker without job cards', codeNumber: 'FM-5.5' },
    { type: 'FM - Financial Misappropriation', category: 'Others', subCategory: 'Payment to person through someone else’s job card', codeNumber: 'FM-5.6' },
    { type: 'FM - Financial Misappropriation', category: 'Others', subCategory: 'Family having more than one job card has been paid for more than 100 days', codeNumber: 'FM-5.7' },
    { type: 'FM - Financial Misappropriation', category: 'Others', subCategory: 'Wages have been withdrawn from the worker’s account but has not been paid to the worker.', codeNumber: 'FM-5.8' },
    { type: 'FD - Financial Deviation', category: 'Records not produced', subCategory: 'Record not produced for social audit', codeNumber: 'FD-1.1' },
    { type: 'FD - Financial Deviation', category: 'Records not produced', subCategory: 'NMRs not produced for social audit', codeNumber: 'FD-1.2' },
    { type: 'FD - Financial Deviation', category: 'Records not produced', subCategory: 'Wage lists not produced for social audit', codeNumber: 'FD-1.3' },
    { type: 'FD - Financial Deviation', category: 'Records not produced', subCategory: 'FTOs not produced for social audit', codeNumber: 'FD-1.4' },
    { type: 'FD - Financial Deviation', category: 'Records not produced', subCategory: 'M Books not produced for social audit', codeNumber: 'FD-1.5' },
    { type: 'FD - Financial Deviation', category: 'Records not produced', subCategory: 'Bills and vouchers not produced for social audit', codeNumber: 'FD-1.6' },
    { type: 'FD - Financial Deviation', category: 'Records not produced', subCategory: 'Work records (Gram sabha resolution; Administrative & Technical Sanction; Technical Estimate not produced for social audit)', codeNumber: 'FD-1.7' },
    { type: 'FD - Financial Deviation', category: 'Records not produced', subCategory: 'Work records (Completion reports; Photos; Asset Register not produced for social audit)', codeNumber: 'FD-1.8' },
    { type: 'FD - Financial Deviation', category: 'Records not produced', subCategory: 'Other records not produced', codeNumber: 'FD-1.9' },
    { type: 'FD - Financial Deviation', category: 'Work selection', subCategory: 'Work taken up without Gram sabha approval', codeNumber: 'FD-2.1' },
    { type: 'FD - Financial Deviation', category: 'Work selection', subCategory: 'Work taken up without Administrative Sanction', codeNumber: 'FD-2.2' },
    { type: 'FD - Financial Deviation', category: 'Work selection', subCategory: 'Work taken up Without Technical Estimate', codeNumber: 'FD-2.3' },
    { type: 'FD - Financial Deviation', category: 'Work selection', subCategory: 'Work taken up Without Technical Sanction', codeNumber: 'FD-2.4' },
    { type: 'FD - Financial Deviation', category: 'Work selection', subCategory: 'Incomplete technical estimate (No pre-measurement; No FMP sketch; No photos; No site Map)', codeNumber: 'FD-2.5' },
    { type: 'FD - Financial Deviation', category: 'Work selection', subCategory: 'Sanction of ineligible work', codeNumber: 'FD-2.6' },
    { type: 'FD - Financial Deviation', category: 'Work selection', subCategory: 'Excess values in technical estimate', codeNumber: 'FD-2.7' },
    { type: 'FD - Financial Deviation', category: 'Work selection', subCategory: 'Work on private land-beneficiary does not have job card', codeNumber: 'FD-2.8' },
    { type: 'FD - Financial Deviation', category: 'Work selection', subCategory: 'Works on private land-beneficiaries were not selected as per norms', codeNumber: 'FD-2.9' },
    { type: 'FD - Financial Deviation', category: 'Work selection', subCategory: 'Same work was done in some other scheme also', codeNumber: 'FD-2.10' },
    { type: 'FD - Financial Deviation', category: 'Work selection', subCategory: 'Same work has been taken up repeatedly', codeNumber: 'FD-2.11' },
    { type: 'FD - Financial Deviation', category: 'Work selection', subCategory: 'Administrative sanction was for one work but some other work was done', codeNumber: 'FD-2.12' },
    { type: 'FD - Financial Deviation', category: 'Work selection', subCategory: 'Pubilc work has been done in private land', codeNumber: 'FD-2.13' },
    { type: 'FD - Financial Deviation', category: 'Work selection', subCategory: 'Work on private land - beneficiary did not work in the work site', codeNumber: 'FD-2.14' },
    { type: 'FD - Financial Deviation', category: 'Work records', subCategory: 'Expenditure amount is greater than the amount sanctioned', codeNumber: 'FD-3.1' },
    { type: 'FD - Financial Deviation', category: 'Work records', subCategory: 'Expenditure amount is greater than the revised amount sanctioned', codeNumber: 'FD-3.2' },
    { type: 'FD - Financial Deviation', category: 'Work records', subCategory: 'Payment has been made without MBook entries', codeNumber: 'FD-3.3' },
    { type: 'FD - Financial Deviation', category: 'Work records', subCategory: 'Payment has been made without Programme Officer’s order', codeNumber: 'FD-3.4' },
    { type: 'FD - Financial Deviation', category: 'Work records', subCategory: 'Excess payment due to arithmetic errors in M Book', codeNumber: 'FD-3.5' },
    { type: 'FD - Financial Deviation', category: 'Work records', subCategory: 'Payment made as per NMR is higher than the amount recorded in the MBook', codeNumber: 'FD-3.6' },
    { type: 'FD - Financial Deviation', category: 'Work records', subCategory: 'Payment made is higher than what was sanctioned in NMR', codeNumber: 'FD-3.7' },
    { type: 'FD - Financial Deviation', category: 'Work records', subCategory: 'Payment has been booked under some other work in the MIS', codeNumber: 'FD-3.8' },
    { type: 'FD - Financial Deviation', category: 'Work records', subCategory: 'Payment has been made without check measurement and super check measurement', codeNumber: 'FD-3.9' },
    { type: 'FD - Financial Deviation', category: 'Work records', subCategory: 'Final payment has been made without super check measurement', codeNumber: 'FD-3.10' },
    { type: 'FD - Financial Deviation', category: 'Work execution', subCategory: 'Significant differences between measurement at work site and recorded values in MBook', codeNumber: 'FD-4.1' },
    { type: 'FD - Financial Deviation', category: 'Work execution', subCategory: 'Full amount for partially constructed IHHL', codeNumber: 'FD-4.2' },
    { type: 'FD - Financial Deviation', category: 'Work execution', subCategory: 'Proportionate Expenditure wise work is not done', codeNumber: 'FD-4.3' },
    { type: 'PV - Process Violation', category: 'Denial Of Entitlements', subCategory: 'No process to collect work application', codeNumber: 'PV-1.1' },
    { type: 'PV - Process Violation', category: 'Denial Of Entitlements', subCategory: 'Non -payment of un-employment allowance', codeNumber: 'PV-1.2' },
    { type: 'PV - Process Violation', category: 'Denial Of Entitlements', subCategory: 'Non -payment of compensation for delayed wages', codeNumber: 'PV-1.3' },
    { type: 'PV - Process Violation', category: 'Denial Of Entitlements', subCategory: 'Non -payment of transportation allowance', codeNumber: 'PV-1.4' },
    { type: 'PV - Process Violation', category: 'Denial Of Entitlements', subCategory: 'People eligible to receive job cards are denied job cards', codeNumber: 'PV-1.5' },
    { type: 'PV - Process Violation', category: 'Denial Of Entitlements', subCategory: 'People eligible to come work are denied work', codeNumber: 'PV-1.6' },
    { type: 'PV - Process Violation', category: 'Denial Of Entitlements', subCategory: 'People receiving OAP are denied job cards', codeNumber: 'PV-1.7' },
    { type: 'PV - Process Violation', category: 'Denial Of Entitlements', subCategory: 'People receiving OAP are denied work', codeNumber: 'PV-1.8' },
    { type: 'PV - Process Violation', category: 'Denial Of Entitlements', subCategory: 'Differently abled people are denied job cards', codeNumber: 'PV-1.9' },
    { type: 'PV - Process Violation', category: 'Denial Of Entitlements', subCategory: 'Differently abled people are denied work', codeNumber: 'PV-1.10' },
    { type: 'PV - Process Violation', category: 'Denial Of Entitlements', subCategory: 'Work site facilities are not provided', codeNumber: 'PV-1.11' },
    { type: 'PV - Process Violation', category: 'Denial Of Entitlements', subCategory: 'No work suitable for particularly vulnerable groups', codeNumber: 'PV-1.12' },
    { type: 'PV - Process Violation', category: 'Denial Of Entitlements', subCategory: 'Separate schedule of rates for particularly vulnerable groups has not been fixed', codeNumber: 'PV-1.13' },
    { type: 'PV - Process Violation', category: 'Transparency And Accountability', subCategory: 'Rozgar Diwass is not conducted once in every month', codeNumber: 'PV-2.1' },
    { type: 'PV - Process Violation', category: 'Transparency And Accountability', subCategory: 'Awareness on MGNREGS implementation process is very poor', codeNumber: 'PV-2.2' },
    { type: 'PV - Process Violation', category: 'Transparency And Accountability', subCategory: 'Citizen information board are not put up', codeNumber: 'PV-2.3' },
    { type: 'PV - Process Violation', category: 'Transparency And Accountability', subCategory: 'Job Cards are not with workers', codeNumber: 'PV-2.4' },
    { type: 'PV - Process Violation', category: 'Transparency And Accountability', subCategory: 'Workers do not have pass book', codeNumber: 'PV-2.5' },
    { type: 'PV - Process Violation', category: 'Transparency And Accountability', subCategory: 'NMRs are not maintained in the work site', codeNumber: 'PV-2.6' },
    { type: 'PV - Process Violation', category: 'Transparency And Accountability', subCategory: 'Pay slip are not issued to workers', codeNumber: 'PV-2.7' },
    { type: 'PV - Process Violation', category: 'Transparency And Accountability', subCategory: 'Concurrent Social Audit does not take place', codeNumber: 'PV-2.8' },
    { type: 'PV - Process Violation', category: 'Transparency And Accountability', subCategory: 'No process to collect records and act on grievances', codeNumber: 'PV-2.9' },
    { type: 'PV - Process Violation', category: 'Transparency And Accountability', subCategory: 'NMRs are not publicly read out at the work site', codeNumber: 'PV-2.10' },
    { type: 'PV - Process Violation', category: 'Transparency And Accountability', subCategory: 'Measurement is not done in the presence of workers', codeNumber: 'PV-2.11' },
    { type: 'PV - Process Violation', category: 'Transparency And Accountability', subCategory: 'Gram Panchayat Office has not displayed shelf of project; works taken up and amount spent', codeNumber: 'PV-2.12' },
    { type: 'PV - Process Violation', category: 'Transparency And Accountability', subCategory: 'Wall writing have not been done', codeNumber: 'PV-2.13' },
    { type: 'PV - Process Violation', category: 'Transparency And Accountability', subCategory: 'Poor co-operation from the implementation team for Social Audit from the Panchayat', codeNumber: 'PV-2.14' },
    { type: 'PV - Process Violation', category: 'Transparency And Accountability', subCategory: 'Poor co-operation from the implementation team for Social Audit from the block', codeNumber: 'PV-2.15' },
    { type: 'PV - Process Violation', category: 'Transparency And Accountability', subCategory: 'Panchayat Registers not produced for social audit', codeNumber: 'PV-2.16' },
    { type: 'PV - Process Violation', category: 'Transparency And Accountability', subCategory: 'Block registers not been produced for social audit', codeNumber: 'PV-2.17' },
    { type: 'PV - Process Violation', category: 'Financial', subCategory: 'Advance received for administrative expenses has not been settled', codeNumber: 'PV-3.1' },
    { type: 'PV - Process Violation', category: 'Financial', subCategory: 'Material expense issue', codeNumber: 'PV-3.2' },
    { type: 'PV - Process Violation', category: 'Financial', subCategory: 'Administrative expense issue', codeNumber: 'PV-3.3' },
    { type: 'PV - Process Violation', category: 'Work Selection', subCategory: 'Systematic and for participatory planning exercise to identify works was not conducted', codeNumber: 'PV-4.1' },
    { type: 'PV - Process Violation', category: 'Work Selection', subCategory: 'Work selection is not done through Gram sabha. Resolution', codeNumber: 'PV-4.2' },
    { type: 'PV - Process Violation', category: 'Work Selection', subCategory: 'Shelf of work is not available', codeNumber: 'PV-4.3' },
    { type: 'PV - Process Violation', category: 'Work Execution', subCategory: 'Work has not been completed for a long time', codeNumber: 'PV-5.1' },
    { type: 'PV - Process Violation', category: 'Work Execution', subCategory: 'Overseer/Tech. Asst. does not visit the work site regularly', codeNumber: 'PV-5.2' },
    { type: 'PV - Process Violation', category: 'Work Quality', subCategory: 'Quality of work is poor', codeNumber: 'PV-6.1' },
    { type: 'PV - Process Violation', category: 'Work Quality', subCategory: 'Work is not useful for the community', codeNumber: 'PV-6.2' },
    { type: 'PV - Process Violation', category: 'Work Quality', subCategory: 'Failure to safeguard and maintained completed work', codeNumber: 'PV-6.3' },
    { type: 'PV - Process Violation', category: 'Work Quality', subCategory: 'Missing trees/ plantation /Farm Pond', codeNumber: 'PV-6.4' },
    { type: 'PV - Process Violation', category: 'Work Quality', subCategory: 'Asset has been destroyed', codeNumber: 'PV-6.5' },
    { type: 'PV - Process Violation', category: 'Maintenance Of Registers And Record', subCategory: 'Difference in the days worked and wages earned between job card and online entry', codeNumber: 'PV-7.1' },
    { type: 'PV - Process Violation', category: 'Maintenance Of Registers And Record', subCategory: 'Online details about family (Name; Age; Caste; Relationship etc.) is wrong', codeNumber: 'PV-7.2' },
    { type: 'PV - Process Violation', category: 'Maintenance Of Registers And Record', subCategory: 'Job card application register is poorly maintained', codeNumber: 'PV-7.3' },
    { type: 'PV - Process Violation', category: 'Maintenance Of Registers And Record', subCategory: 'Many corrections in job card application register', codeNumber: 'PV-7.4' },
    { type: 'PV - Process Violation', category: 'Maintenance Of Registers And Record', subCategory: 'Mismatch between block and panchayat job card register', codeNumber: 'PV-7.5' },
    { type: 'PV - Process Violation', category: 'Maintenance Of Registers And Record', subCategory: 'Mismatch between block and panchayat NMR register', codeNumber: 'PV-7.6' },
    { type: 'PV - Process Violation', category: 'Maintenance Of Registers And Record', subCategory: 'Variation in signature/thumb- print between NMR and job card application register', codeNumber: 'PV-7.7' },
    { type: 'PV - Process Violation', category: 'Maintenance Of Registers And Record', subCategory: 'Mismatch between NMR and Measurement Book', codeNumber: 'PV-7.8' },
    { type: 'PV - Process Violation', category: 'Maintenance Of Registers And Record', subCategory: 'Mismatch between Measurement Book and completion report', codeNumber: 'PV-7.9' },
    { type: 'PV - Process Violation', category: 'Maintenance Of Registers And Record', subCategory: 'Many corrections have been made in the NMRs', codeNumber: 'PV-7.10' },
    { type: 'PV - Process Violation', category: 'Maintenance Of Registers And Record', subCategory: 'Job cards have been maintained poorly', codeNumber: 'PV-7.11' },
    { type: 'PV - Process Violation', category: 'Maintenance Of Registers And Record', subCategory: 'NMRs have been maintained poorly', codeNumber: 'PV-7.12' },
    { type: 'PV - Process Violation', category: 'Maintenance Of Registers And Record', subCategory: 'Panchayat registers have been maintained poorly', codeNumber: 'PV-7.13' },
    { type: 'PV - Process Violation', category: 'Maintenance Of Registers And Record', subCategory: 'Block registers have been maintained poorly', codeNumber: 'PV-7.14' },
    { type: 'PV - Process Violation', category: 'Maintenance Of Registers And Record', subCategory: 'Asset Register is poorly maintained', codeNumber: 'PV-7.15' },
    { type: 'PV - Process Violation', category: 'Maintenance Of Registers And Record', subCategory: 'Measurement Books have been maintained poorly', codeNumber: 'PV-7.16' },
    { type: 'PV - Process Violation', category: 'Maintenance Of Registers And Record', subCategory: 'Same account number credited with more than one person’s wage', codeNumber: 'PV-7.17' },
    { type: 'PV - Process Violation', category: 'Maintenance Of Registers And Record', subCategory: 'Multiple job cards have been issued to the same family', codeNumber: 'PV-7.18' },
    { type: 'PV - Process Violation', category: 'Maintenance Of Registers And Record', subCategory: 'Worker is present in multiple job cards', codeNumber: 'PV-7.19' },
    { type: 'PV - Process Violation', category: 'Maintenance Of Registers And Record', subCategory: 'Other records irregularity', codeNumber: 'PV-7.20' },
    { type: 'PV - Process Violation', category: 'Maintenance Of Registers And Record', subCategory: 'Photos in 3 stages not available', codeNumber: 'PV-7.21' },
    { type: 'PV - Process Violation', category: 'Maintenance Of Registers And Record', subCategory: 'Register 1 not maintained', codeNumber: 'PV-7.22' },
    { type: 'PV - Process Violation', category: 'Maintenance Of Registers And Record', subCategory: 'Completion report has not been prepared even after the final bill has been made', codeNumber: 'PV-7.23' },
    { type: 'PV - Process Violation', category: 'Administration', subCategory: 'Staff vacancies have led in the poor implementation', codeNumber: 'PV-8.1' },
    { type: 'PV - Process Violation', category: 'Administration', subCategory: 'Mates have not been trained properly', codeNumber: 'PV-8.2' },
    { type: 'PV - Process Violation', category: 'Administration', subCategory: 'No administrative expenses are paid to the panchayat', codeNumber: 'PV-83' },
    { type: 'PV - Process Violation', category: 'Administration', subCategory: 'Failure to follow the prescribed procedure in the selection of Mate', codeNumber: 'PV-8.4' },
    { type: 'PV - Process Violation', category: 'Administration', subCategory: 'Works are allotted to different hamlet only on specific periods', codeNumber: 'PV-8.5' },
    { type: 'PV - Process Violation', category: 'Administration', subCategory: 'Payment not done through eFMS for non-exempt panchayats', codeNumber: 'PV-8.6' },
    { type: 'PV - Process Violation', category: 'Administration', subCategory: 'Irregularity in selection of mate', codeNumber: 'PV-8.7' },
    { type: 'PV - Process Violation', category: 'Administration', subCategory: 'Ineligible people have been issued job cards', codeNumber: 'PV-8.8' },
    { type: 'PV - Process Violation', category: 'Administration', subCategory: 'Families have been issued more than 1 job card', codeNumber: 'PV-8.9' },
    { type: 'PV - Process Violation', category: 'Administration', subCategory: 'Mate not available at work site', codeNumber: 'PV-8.10' },
    { type: 'GR - Grievances', category: 'Job Card Related', subCategory: 'Complaint – Job card not updated', codeNumber: 'G-1.1' },
    { type: 'GR - Grievances', category: 'Job Card Related', subCategory: 'Application for new job card', codeNumber: 'G-1.2' },
    { type: 'GR - Grievances', category: 'Job Card Related', subCategory: 'Application for renewal of job card', codeNumber: 'G-1.3' },
    { type: 'GR - Grievances', category: 'Job Card Related', subCategory: 'Application for replacement of lost job card', codeNumber: 'G-1.4' },
    { type: 'GR - Grievances', category: 'Job Card Related', subCategory: 'Application to correct wrong entries in the job card (Name; Husband/Father name; caste; age; address; work entries etc)', codeNumber: 'G-1.5' },
    { type: 'GR - Grievances', category: 'Job Card Related', subCategory: 'Application to add additional family members', codeNumber: 'G-1.6' },
    { type: 'GR - Grievances', category: 'Job Card Related', subCategory: 'Complaint – unable to get job card', codeNumber: 'G-1.7' },
    { type: 'GR - Grievances', category: 'Job Card Related', subCategory: 'Compliant- unable to renew job card', codeNumber: 'G-1.8' },
    { type: 'GR - Grievances', category: 'Job Card Related', subCategory: 'Complaint-unable to get replacement for lost job card', codeNumber: 'G-1.9' },
    { type: 'GR - Grievances', category: 'Job Card Related', subCategory: 'Complaint-unable to correct wrong entries in JC', codeNumber: 'G-1.10' },
    { type: 'GR - Grievances', category: 'Job Card Related', subCategory: 'Complaint-unable to add additional family member', codeNumber: 'G-1.11' },
    { type: 'GR - Grievances', category: 'Job Card Related', subCategory: 'Compliant-job card has been borrowed by someone else', codeNumber: 'G-112' },
    { type: 'GR - Grievances', category: 'Job Card Related', subCategory: 'Complaint –JC has been borrowed by implementing officials', codeNumber: 'G-1.13' },
    { type: 'GR - Grievances', category: 'Aadhar /Bank Account Related', subCategory: 'Application for Aadhar card', codeNumber: 'G-2.1' },
    { type: 'GR - Grievances', category: 'Aadhar /Bank Account Related', subCategory: 'Complaint-unable to get Aadhar card', codeNumber: 'G-2.2' },
    { type: 'GR - Grievances', category: 'Aadhar /Bank Account Related', subCategory: 'Application for bank account', codeNumber: 'G-2.3' },
    { type: 'GR - Grievances', category: 'Aadhar /Bank Account Related', subCategory: 'Complaint-unable to open bank account', codeNumber: 'G-2.4' },
    { type: 'GR - Grievances', category: 'Aadhar /Bank Account Related', subCategory: 'Application for Post office account', codeNumber: 'G-2.5' },
    { type: 'GR - Grievances', category: 'Aadhar /Bank Account Related', subCategory: 'Application for bank pass book', codeNumber: 'G-2.6' },
    { type: 'GR - Grievances', category: 'Aadhar /Bank Account Related', subCategory: 'Complaint-unable to get bank pass book', codeNumber: 'G-2.7' },
    { type: 'GR - Grievances', category: 'Aadhar /Bank Account Related', subCategory: 'Application for post office pass book', codeNumber: 'G-2.8' },
    { type: 'GR - Grievances', category: 'Aadhar /Bank Account Related', subCategory: 'Complaint-unable to get post office pass book', codeNumber: 'G-2.9' },
    { type: 'GR - Grievances', category: 'Aadhar /Bank Account Related', subCategory: 'Complaint-unable to get bank/post office pass book', codeNumber: 'G-2.10' },
    { type: 'GR - Grievances', category: 'Aadhar /Bank Account Related', subCategory: 'Unable to link bank account with Aadhar', codeNumber: 'G-2.11' },
    { type: 'GR - Grievances', category: 'Aadhar /Bank Account Related', subCategory: 'Aadhar account linked with wrong bank account', codeNumber: 'G-2.12' },
    { type: 'GR - Grievances', category: 'Work Related', subCategory: 'Application for work', codeNumber: 'G-3.1' },
    { type: 'GR - Grievances', category: 'Work Related', subCategory: 'Complaint-unable to get work', codeNumber: 'G-3.2' },
    { type: 'GR - Grievances', category: 'Work Related', subCategory: 'Complaint-work application is not accepted', codeNumber: 'G-3.3' },
    { type: 'GR - Grievances', category: 'Work Related', subCategory: 'Application for work was not acted upon', codeNumber: 'G-3.4' },
    { type: 'GR - Grievances', category: 'Work Related', subCategory: 'Application for more than 100 days work', codeNumber: 'G-3.5' },
    { type: 'GR - Grievances', category: 'Work Related', subCategory: 'Complaint-discrimination in the allotment of work', codeNumber: 'G-3.6' },
    { type: 'GR - Grievances', category: 'Work Site Facilities', subCategory: 'Complaint –non provision of work site facilities', codeNumber: 'G-4.1' },
    { type: 'GR - Grievances', category: 'Work Site Facilities', subCategory: 'Complaint-non provision of drinking water at work site', codeNumber: 'G-4.2' },
    { type: 'GR - Grievances', category: 'Work Site Facilities', subCategory: 'Compliant-Non provision of Shade at work site', codeNumber: 'G-4.3' },
    { type: 'GR - Grievances', category: 'Work Site Facilities', subCategory: 'Non- provision of Crèche for children at work site', codeNumber: 'G-4.4' },
    { type: 'GR - Grievances', category: 'Wages Related', subCategory: 'Application for minimum wages to be raised', codeNumber: 'G-5.1' },
    { type: 'GR - Grievances', category: 'Wages Related', subCategory: 'Complaint-non -payment of minimum wages', codeNumber: 'G-5.2' },
    { type: 'GR - Grievances', category: 'Wages Related', subCategory: 'Complaint-application for payment of delayed wages', codeNumber: 'G-5.3' },
    { type: 'GR - Grievances', category: 'Wages Related', subCategory: 'Complaint-application for payment of non- paid wages', codeNumber: 'G-5.4' },
    { type: 'GR - Grievances', category: 'Wages Related', subCategory: 'Person has worked but name is not in NMR and has not got been paid', codeNumber: 'G-5.5' },
    { type: 'GR - Grievances', category: 'Wages Related', subCategory: 'Person has worked but has not been paid because his family had already completed 100 days', codeNumber: 'G-5.6' },
    { type: 'GR - Grievances', category: 'Wages Related', subCategory: 'Differently abled people have not been paid their entitled wages', codeNumber: 'G-5.7' },
    { type: 'GR - Grievances', category: 'Wages Related', subCategory: 'Complaint-application for payment of skilled work/material cost in individual work', codeNumber: 'G-5.8' },
    { type: 'GR - Grievances', category: 'Wages Related', subCategory: 'Complaint-application for payment of transportation allowance', codeNumber: 'G-5.9' },
    { type: 'GR - Grievances', category: 'Wages Related', subCategory: 'Complaint-application for payment of compensation for delayed wages', codeNumber: 'G-5.10' },
    { type: 'GR - Grievances', category: 'Wages Related', subCategory: 'Complaint-application for payment of Unemployment allowance', codeNumber: 'G-5.11' },
    { type: 'GR - Grievances', category: 'Wages Related', subCategory: 'Complaint-No information is given about wage rate and amount paid', codeNumber: 'G-5.12' },
    { type: 'GR - Grievances', category: 'Wages Related', subCategory: 'Complaint-wage slip is not given', codeNumber: 'G-513' },
    { type: 'GR - Grievances', category: 'Wages Related', subCategory: 'Complaint-difficulty in withdrawing wages from bank/post office', codeNumber: 'G-5.14' },
    { type: 'GR - Grievances', category: 'Injury/ Death', subCategory: 'Complaint –application to pay wage compensation for injury arising out of and in the course of employment', codeNumber: 'G-6.1' },
    { type: 'GR - Grievances', category: 'Injury/ Death', subCategory: 'Complaint –application to compensation for permanently disability / death by accident Arising out of and in the course of employment', codeNumber: 'G-6.2' },
    { type: 'GR - Grievances', category: 'Individual Assets Relate', subCategory: 'Application for provision of Farm Pond', codeNumber: 'G-7.1' },
    { type: 'GR - Grievances', category: 'Individual Assets Relate', subCategory: 'Application for plantation work in individual land', codeNumber: 'G-7.2' },
    { type: 'GR - Grievances', category: 'Individual Assets Relate', subCategory: 'Application for house under IAY scheme', codeNumber: 'G-7.3' },
    { type: 'GR - Grievances', category: 'Individual Assets Relate', subCategory: 'Application for house under CMGHS scheme', codeNumber: 'G-7.4' },
    { type: 'GR - Grievances', category: 'Individual Assets Relate', subCategory: 'Application for Asset in individual land', codeNumber: 'G-7.5' },
    { type: 'GR - Grievances', category: 'Individual Assets Relate', subCategory: 'Application for provision of IHHL', codeNumber: 'G-7.6' },
    { type: 'GR - Grievances', category: 'Individual Assets Relate', subCategory: 'Application for provision of Animal Shelter', codeNumber: 'G-7.7' },
    { type: 'GR - Grievances', category: 'Public Work Relate', subCategory: 'Application for public canal work to be taken up', codeNumber: 'G-8.1' },
    { type: 'GR - Grievances', category: 'Public Work Relate', subCategory: 'Application for public tank work to be taken up', codeNumber: 'G-8.2' },
    { type: 'GR - Grievances', category: 'Public Work Relate', subCategory: 'Application for a PDS building to be built', codeNumber: 'G-8.3' },
    { type: 'GR - Grievances', category: 'Public Work Relate', subCategory: 'Application for a Anganwadi building to be built', codeNumber: 'G-8.4' },
    { type: 'GR - Grievances', category: 'Public Work Relate', subCategory: 'Application for a library building to be built', codeNumber: 'G-8.5' },
    { type: 'GR - Grievances', category: 'Gram Sabha Relate', subCategory: 'Gram sabha is not held regularly', codeNumber: 'G-9.1' },
    { type: 'GR - Grievances', category: 'Gram Sabha Relate', subCategory: 'Adequate information is not given about Gram sabha', codeNumber: 'G-9.2' },
    { type: 'GR - Grievances', category: 'Gram Sabha Relate', subCategory: 'Works are not selected in the Gram sabha', codeNumber: 'G-9.3' },
    { type: 'GR - Grievances', category: 'Gram Sabha Relate', subCategory: 'Mates are not selected in the Gram sabha', codeNumber: 'G-9.4' },
    { type: 'GR - Grievances', category: 'Complaint On Specific Individuals', subCategory: 'Complaint on Post office/Post man', codeNumber: 'G-10.1' },
    { type: 'GR - Grievances', category: 'Complaint On Specific Individuals', subCategory: 'Complaint on banking correspondent', codeNumber: 'G-10.2' },
    { type: 'GR - Grievances', category: 'Complaint On Specific Individuals', subCategory: 'Complaint on Panchayat Secretary', codeNumber: 'G-10.3' },
    { type: 'GR - Grievances', category: 'Complaint On Specific Individuals', subCategory: 'Complaint on Work site Supervisor', codeNumber: 'G-10.4' },
    { type: 'GR - Grievances', category: 'Complaint On Specific Individuals', subCategory: 'Complaint on Panchayat President', codeNumber: 'G-10.5' },
    { type: 'GR - Grievances', category: 'Complaint On Specific Individuals', subCategory: 'Complaint on Ward member', codeNumber: 'G-10.6' },
    { type: 'GR - Grievances', category: 'Complaint On Specific Individuals', subCategory: 'Complaint on Technical staff', codeNumber: 'G-10.7' },
    { type: 'GR - Grievances', category: 'Complaint On Specific Individuals', subCategory: 'Complaint on other persons', codeNumber: 'G-10.8' },
    { type: 'GR - Grievances', category: 'Others', subCategory: 'Complaint-application to redress grievance was not registered or acted upon', codeNumber: 'G-11.1' },
];

    