
import type { Metadata } from 'next';
import './globals.css';
import { Toaster } from "@/components/ui/toaster";
import { AuthProvider } from '@/hooks/use-auth';
import { LogoProvider } from '@/hooks/use-logo';
import Script from 'next/script';

export const metadata: Metadata = {
  title: 'SastaPage',
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=PT+Sans:wght@400;700&family=Impact&display=swap" rel="stylesheet" />
        <Script src="https://ai.bhashini.gov.in/javascript/bhashini-embed.js" strategy="afterInteractive" />
      </head>
      <body className="font-body antialiased">
        <AuthProvider>
          <LogoProvider>
            {children}
          </LogoProvider>
        </AuthProvider>
        <Toaster />
      </body>
    </html>
  );
}
