import type { Panchayat } from './types';

export const CUDDALORE_PANCHAYATS: Panchayat[] = [
    { district: 'CUDDALORE', block: 'CUDDALORE', name: 'Azhagiyanatham', lgdCode: '222359' },
    { district: 'CUDDALORE', block: 'CUDDALORE', name: 'Annavalli', lgdCode: '222360' },
    { district: 'CUDDALORE', block: 'CUDDALORE', name: 'Arisiperiyankuppam', lgdCode: '222361' },
    { district: 'CUDDALORE', block: 'CUDDALORE', name: 'Chellancherry', lgdCode: '222363' },
    { district: 'CUDDALORE', block: 'CUDDALORE', name: 'C. N. Palayam', lgdCode: '222362' },
    { district: 'CUDDALORE', block: 'CUDDALORE', name: 'Cuddalore O. T(non Municipal)', lgdCode: '222364' },
    { district: 'CUDDALORE', block: 'CUDDALORE', name: 'Gunduuppalavadi', lgdCode: '222366' },
    { district: 'CUDDALORE', block: 'CUDDALORE', name: 'Karaikadu', lgdCode: '222368' },
    { district: 'CUDDALORE', block: 'CUDDALORE', name: 'Karamanikuppam', lgdCode: '222370' },
    { district: 'CUDDALORE', block: 'CUDDALORE', name: 'Karaimedu', lgdCode: '222369' },
    { district: 'CUDDALORE', block: 'CUDDALORE', name: 'Karaiyeravittakuppam', lgdCode: '222367' },
    { district: 'CUDDALORE', block: 'CUDDALORE', name: 'Karanapattu', lgdCode: '222371' },
    { district: 'CUDDALORE', block: 'CUDDALORE', name: 'Keelalinjipattu', lgdCode: '222372' },
    { district: 'CUDDALORE', block: 'CUDDALORE', name: 'Kilinjikuppam', lgdCode: '222374' },
    { district: 'CUDDALORE', block: 'CUDDALORE', name: 'Kelkumaramangalam', lgdCode: '222373' },
    { district: 'CUDDALORE', block: 'CUDDALORE', name: 'Kodukkanpalayam', lgdCode: '222375' },
    { district: 'CUDDALORE', block: 'CUDDALORE', name: 'Gunamangalam', lgdCode: '222365' },
    { district: 'CUDDALORE', block: 'CUDDALORE', name: 'Kondur', lgdCode: '222376' },
    { district: 'CUDDALORE', block: 'CUDDALORE', name: 'Kudikadu', lgdCode: '222377' },
    { district: 'CUDDALORE', block: 'CUDDALORE', name: 'Kumalankulam', lgdCode: '222378' },
    { district: 'CUDDALORE', block: 'CUDDALORE', name: 'Madalapattu', lgdCode: '222379' },
    { district: 'CUDDALORE', block: 'CUDDALORE', name: 'M. P. Agaram', lgdCode: '222380' },
    { district: 'CUDDALORE', block: 'CUDDALORE', name: 'Maruthadu', lgdCode: '222381' },
    { district: 'CUDDALORE', block: 'CUDDALORE', name: 'Melalinjipattu', lgdCode: '222382' },
    { district: 'CUDDALORE', block: 'CUDDALORE', name: 'Naduveerapattu', lgdCode: '222383' },
    { district: 'CUDDALORE', block: 'CUDDALORE', name: 'Nallathur', lgdCode: '222384' },
    { district: 'CUDDALORE', block: 'CUDDALORE', name: 'Nanamedu', lgdCode: '222385' },
    { district: 'CUDDALORE', block: 'CUDDALORE', name: 'Nathapattu', lgdCode: '222386' },
    { district: 'CUDDALORE', block: 'CUDDALORE', name: 'Pachayankuppam', lgdCode: '222387' },
    { district: 'CUDDALORE', block: 'CUDDALORE', name: 'Pathirikuppam', lgdCode: '222389' },
    { district: 'CUDDALORE', block: 'CUDDALORE', name: 'Pallipattu', lgdCode: '222388' },
    { district: 'CUDDALORE', block: 'CUDDALORE', name: 'Periyakankanankuppam', lgdCode: '222390' },
    { district: 'CUDDALORE', block: 'CUDDALORE', name: 'Pillali', lgdCode: '222391' },
    { district: 'CUDDALORE', block: 'CUDDALORE', name: 'Pudukadai', lgdCode: '222392' },
    { district: 'CUDDALORE', block: 'CUDDALORE', name: 'Ramapuram', lgdCode: '222393' },
    { district: 'CUDDALORE', block: 'CUDDALORE', name: 'Sedapalayam', lgdCode: '222394' },
    { district: 'CUDDALORE', block: 'CUDDALORE', name: 'Semmankuppam', lgdCode: '222395' },
    { district: 'CUDDALORE', block: 'CUDDALORE', name: 'Singirikudi', lgdCode: '222396' },
    { district: 'CUDDALORE', block: 'CUDDALORE', name: 'Thennampakkam', lgdCode: '222397' },
    { district: 'CUDDALORE', block: 'CUDDALORE', name: 'Thookanampakkam', lgdCode: '222401' },
    { district: 'CUDDALORE', block: 'CUDDALORE', name: 'Thirumanikuzhi', lgdCode: '222398' },
    { district: 'CUDDALORE', block: 'CUDDALORE', name: 'Thirupanampakkam', lgdCode: '222399' },
    { district: 'CUDDALORE', block: 'CUDDALORE', name: 'Thiruvandipuram', lgdCode: '222400' },
    { district: 'CUDDALORE', block: 'CUDDALORE', name: 'Thottapattu', lgdCode: '222402' },
    { district: 'CUDDALORE', block: 'CUDDALORE', name: 'Uchimedu', lgdCode: '222403' },
    { district: 'CUDDALORE', block: 'CUDDALORE', name: 'Ulleripattu', lgdCode: '222404' },
    { district: 'CUDDALORE', block: 'CUDDALORE', name: 'Vanamadevi', lgdCode: '222405' },
    { district: 'CUDDALORE', block: 'CUDDALORE', name: 'Varakalpattu', lgdCode: '222406' },
    { district: 'CUDDALORE', block: 'CUDDALORE', name: 'Vellakarai', lgdCode: '222407' },
    { district: 'CUDDALORE', block: 'CUDDALORE', name: 'Vellapakkam', lgdCode: '222408' },
    { district: 'CUDDALORE', block: 'CUDDALORE', name: 'Vilangalpattu', lgdCode: '222409' },
    { district: 'CUDDALORE', block: 'ANNAGRAMAM', name: 'Agaram', lgdCode: '222317' },
    { district: 'CUDDALORE', block: 'ANNAGRAMAM', name: 'Akkadavalli', lgdCode: '222318' },
    { district: 'CUDDALORE', block: 'ANNAGRAMAM', name: 'Azhagaperumalkuppam', lgdCode: '222319' },
    { district: 'CUDDALORE', block: 'ANNAGRAMAM', name: 'Aviyanur', lgdCode: '222320' },
    { district: 'CUDDALORE', block: 'ANNAGRAMAM', name: 'Chinnapettai', lgdCode: '222322' },
    { district: 'CUDDALORE', block: 'ANNAGRAMAM', name: 'Chitharasur', lgdCode: '222323' },
    { district: 'CUDDALORE', block: 'ANNAGRAMAM', name: 'Ezhumedu', lgdCode: '222325' },
    { district: 'CUDDALORE', block: 'ANNAGRAMAM', name: 'Enathirimangalam', lgdCode: '222326' },
    { district: 'CUDDALORE', block: 'ANNAGRAMAM', name: 'Eaithanur', lgdCode: '222324' },
    { district: 'CUDDALORE', block: 'ANNAGRAMAM', name: 'Kallipattu', lgdCode: '222327' },
    { district: 'CUDDALORE', block: 'ANNAGRAMAM', name: 'Kandrakottai', lgdCode: '222328' },
    { district: 'CUDDALORE', block: 'ANNAGRAMAM', name: 'Kanisapakkam', lgdCode: '222329' },
    { district: 'CUDDALORE', block: 'ANNAGRAMAM', name: 'Karumbur', lgdCode: '222330' },
    { district: 'CUDDALORE', block: 'ANNAGRAMAM', name: 'Kavanoor', lgdCode: '222331' },
    { district: 'CUDDALORE', block: 'ANNAGRAMAM', name: 'Keelarungunam', lgdCode: '222332' },
    { district: 'CUDDALORE', block: 'ANNAGRAMAM', name: 'Keelkavarapattu', lgdCode: '222333' },
    { district: 'CUDDALORE', block: 'ANNAGRAMAM', name: 'Kozhipakkam', lgdCode: '222337' },
    { district: 'CUDDALORE', block: 'ANNAGRAMAM', name: 'Kongarayanur', lgdCode: '222334' },
    { district: 'CUDDALORE', block: 'ANNAGRAMAM', name: 'Korathi', lgdCode: '222335' },
    { district: 'CUDDALORE', block: 'ANNAGRAMAM', name: 'Kotlampakkam', lgdCode: '222336' },
    { district: 'CUDDALORE', block: 'ANNAGRAMAM', name: 'Maligaimedu', lgdCode: '222339' },
    { district: 'CUDDALORE', block: 'ANNAGRAMAM', name: 'Melkavarapattu', lgdCode: '222340' },
    { district: 'CUDDALORE', block: 'ANNAGRAMAM', name: 'Melkumaramangalam', lgdCode: '222338' },
    { district: 'CUDDALORE', block: 'ANNAGRAMAM', name: 'Narimedu', lgdCode: '222341' },
    { district: 'CUDDALORE', block: 'ANNAGRAMAM', name: 'Natham', lgdCode: '222342' },
    { district: 'CUDDALORE', block: 'ANNAGRAMAM', name: 'Oraiyur', lgdCode: '222343' },
    { district: 'CUDDALORE', block: 'ANNAGRAMAM', name: 'Pagandai', lgdCode: '222344' },
    { district: 'CUDDALORE', block: 'ANNAGRAMAM', name: 'Paithampadi', lgdCode: '222345' },
    { district: 'CUDDALORE', block: 'ANNAGRAMAM', name: 'Pallavarayanatham', lgdCode: '222346' },
    { district: 'CUDDALORE', block: 'ANNAGRAMAM', name: 'Palur', lgdCode: '222347' },
    { district: 'CUDDALORE', block: 'ANNAGRAMAM', name: 'Panapakkam', lgdCode: '222348' },
    { district: 'CUDDALORE', block: 'ANNAGRAMAM', name: 'Bandrakottai', lgdCode: '222321' },
    { district: 'CUDDALORE', block: 'ANNAGRAMAM', name: 'Perumalnayakkanpalayam', lgdCode: '222349' },
    { district: 'CUDDALORE', block: 'ANNAGRAMAM', name: 'Poondi', lgdCode: '222350' },
    { district: 'CUDDALORE', block: 'ANNAGRAMAM', name: 'Pulavanur', lgdCode: '222351' },
    { district: 'CUDDALORE', block: 'ANNAGRAMAM', name: 'Sanniyasipettai', lgdCode: '222352' },
    { district: 'CUDDALORE', block: 'ANNAGRAMAM', name: 'Sathipattu', lgdCode: '222353' },
    { district: 'CUDDALORE', block: 'ANNAGRAMAM', name: 'Sundaravandi', lgdCode: '222354' },
    { district: 'CUDDALORE', block: 'ANNAGRAMAM', name: 'Thattampalayam', lgdCode: '222355' },
    { district: 'CUDDALORE', block: 'ANNAGRAMAM', name: 'Thirasu', lgdCode: '222356' },
    { district: 'CUDDALORE', block: 'ANNAGRAMAM', name: 'Thiruthuraiyur', lgdCode: '222357' },
    { district: 'CUDDALORE', block: 'ANNAGRAMAM', name: 'Varinjipakkam', lgdCode: '222358' },
    { district: 'CUDDALORE', block: 'PANRUTI', name: 'Alagappasamuthiram', lgdCode: '222863' },
    { district: 'CUDDALORE', block: 'PANRUTI', name: 'Anguchettipalayam', lgdCode: '222864' },
    { district: 'CUDDALORE', block: 'PANRUTI', name: 'Arasadikuppam', lgdCode: '222865' },
    { district: 'CUDDALORE', block: 'PANRUTI', name: 'Ealanthampattu', lgdCode: '222866' },
    { district: 'CUDDALORE', block: 'PANRUTI', name: 'Kadampuliyur', lgdCode: '222867' },
    { district: 'CUDDALORE', block: 'PANRUTI', name: 'Karukkai', lgdCode: '222868' },
    { district: 'CUDDALORE', block: 'PANRUTI', name: 'Kattukudalur', lgdCode: '222869' },
    { district: 'CUDDALORE', block: 'PANRUTI', name: 'Keeliruppu', lgdCode: '222871' },
    { district: 'CUDDALORE', block: 'PANRUTI', name: 'Keelkangeyankuppam', lgdCode: '222872' },
    { district: 'CUDDALORE', block: 'PANRUTI', name: 'Keelmampattu', lgdCode: '222873' },
    { district: 'CUDDALORE', block: 'PANRUTI', name: 'Keelakuppam', lgdCode: '222870' },
    { district: 'CUDDALORE', block: 'PANRUTI', name: 'Kolapakkam', lgdCode: '222874' },
    { district: 'CUDDALORE', block: 'PANRUTI', name: 'Kudumiyankuppam', lgdCode: '222875' },
    { district: 'CUDDALORE', block: 'PANRUTI', name: 'Lakshmi Narayanapuram', lgdCode: '222876' },
    { district: 'CUDDALORE', block: 'PANRUTI', name: 'Maligampattu', lgdCode: '222877' },
    { district: 'CUDDALORE', block: 'PANRUTI', name: 'Manamthavilnthaputhur', lgdCode: '222878' },
    { district: 'CUDDALORE', block: 'PANRUTI', name: 'Manapakkam', lgdCode: '222879' },
    { district: 'CUDDALORE', block: 'PANRUTI', name: 'Marungur', lgdCode: '222880' },
    { district: 'CUDDALORE', block: 'PANRUTI', name: 'Meliruppu', lgdCode: '222881' },
    { district: 'CUDDALORE', block: 'PANRUTI', name: 'Melkangeyankuppam', lgdCode: '222882' },
    { district: 'CUDDALORE', block: 'PANRUTI', name: 'Melmampattu', lgdCode: '222883' },
    { district: 'CUDDALORE', block: 'PANRUTI', name: 'Nadukuppam', lgdCode: '222884' },
    { district: 'CUDDALORE', block: 'PANRUTI', name: 'Natham', lgdCode: '222885' },
    { district: 'CUDDALORE', block: 'PANRUTI', name: 'Pannikankuppam', lgdCode: '222886' },
    { district: 'CUDDALORE', block: 'PANRUTI', name: 'Perperiyankuppam', lgdCode: '222888' },
    { district: 'CUDDALORE', block: 'PANRUTI', name: 'Periyakattupalayam', lgdCode: '222887' },
    { district: 'CUDDALORE', block: 'PANRUTI', name: 'Poongunam', lgdCode: '222889' },
    { district: 'CUDDALORE', block: 'PANRUTI', name: 'Purangani', lgdCode: '222890' },
    { district: 'CUDDALORE', block: 'PANRUTI', name: 'Rayarpalayam', lgdCode: '222891' },
    { district: 'CUDDALORE', block: 'PANRUTI', name: 'Semakottai', lgdCode: '222892' },
    { district: 'CUDDALORE', block: 'PANRUTI', name: 'Semmedu', lgdCode: '222893' },
    { district: 'CUDDALORE', block: 'PANRUTI', name: 'Silambinathanpet', lgdCode: '222894' },
    { district: 'CUDDALORE', block: 'PANRUTI', name: 'Sirugramam', lgdCode: '222895' },
    { district: 'CUDDALORE', block: 'PANRUTI', name: 'Siruvathur', lgdCode: '222896' },
    { district: 'CUDDALORE', block: 'PANRUTI', name: 'Sorathur', lgdCode: '222897' },
    { district: 'CUDDALORE', block: 'PANRUTI', name: 'Thalampattu', lgdCode: '222898' },
    { district: 'CUDDALORE', block: 'PANRUTI', name: 'Thiruvamoor', lgdCode: '222899' },
    { district: 'CUDDALORE', block: 'PANRUTI', name: 'Vallam', lgdCode: '222900' },
    { district: 'CUDDALORE', block: 'PANRUTI', name: 'Veerasingankuppam', lgdCode: '222902' },
    { district: 'CUDDALORE', block: 'PANRUTI', name: 'Veeraperumanallur', lgdCode: '222901' },
    { district: 'CUDDALORE', block: 'PANRUTI', name: 'Vegakollai', lgdCode: '222903' },
    { district: 'CUDDALORE', block: 'PANRUTI', name: 'Visoor', lgdCode: '222904' },
    { district: 'CUDDALORE', block: 'KURINJIPADI', name: 'Annathanampettai', lgdCode: '222642' },
    { district: 'CUDDALORE', block: 'KURINJIPADI', name: 'Ambalavananpettai', lgdCode: '222640' },
    { district: 'CUDDALORE', block: 'KURINJIPADI', name: 'Ayeekuppam', lgdCode: '222646' },
    { district: 'CUDDALORE', block: 'KURINJIPADI', name: 'Agaram', lgdCode: '222638' },
    { district: 'CUDDALORE', block: 'KURINJIPADI', name: 'Anukkampattu', lgdCode: '222643' },
    { district: 'CUDDALORE', block: 'KURINJIPADI', name: 'Alapakkam', lgdCode: '222639' },
    { district: 'CUDDALORE', block: 'KURINJIPADI', name: 'Athinarayanapuram', lgdCode: '222645' },
    { district: 'CUDDALORE', block: 'KURINJIPADI', name: 'Andarmullipallam', lgdCode: '222641' },
    { district: 'CUDDALORE', block: 'KURINJIPADI', name: 'Arangamangalam', lgdCode: '222644' },
    { district: 'CUDDALORE', block: 'KURINJIPADI', name: 'Adoor Agaram', lgdCode: '222637' },
    { district: 'CUDDALORE', block: 'KURINJIPADI', name: 'Boothampadi', lgdCode: '222647' },
    { district: 'CUDDALORE', block: 'KURINJIPADI', name: 'Kuruvappanpettai', lgdCode: '222660' },
    { district: 'CUDDALORE', block: 'KURINJIPADI', name: 'Koranapattu', lgdCode: '222655' },
    { district: 'CUDDALORE', block: 'KURINJIPADI', name: 'Keezhur', lgdCode: '222653' },
    { district: 'CUDDALORE', block: 'KURINJIPADI', name: 'Kothandaramapuram', lgdCode: '222656' },
    { district: 'CUDDALORE', block: 'KURINJIPADI', name: 'Krishnankuppam', lgdCode: '222658' },
    { district: 'CUDDALORE', block: 'KURINJIPADI', name: 'Kayalpattu', lgdCode: '222652' },
    { district: 'CUDDALORE', block: 'KURINJIPADI', name: 'Kannadi', lgdCode: '222650' },
    { district: 'CUDDALORE', block: 'KURINJIPADI', name: 'Karunguzhi', lgdCode: '222651' },
    { district: 'CUDDALORE', block: 'KURINJIPADI', name: 'Kolakudi', lgdCode: '222654' },
    { district: 'CUDDALORE', block: 'KURINJIPADI', name: 'Kalkunam', lgdCode: '222648' },
    { district: 'CUDDALORE', block: 'KURINJIPADI', name: 'Kothavacherry', lgdCode: '222657' },
    { district: 'CUDDALORE', block: 'KURINJIPADI', name: 'Kundiamallur', lgdCode: '222659' },
    { district: 'CUDDALORE', block: 'KURINJIPADI', name: 'Kallaiyankuppam', lgdCode: '222649' },
    { district: 'CUDDALORE', block: 'KURINJIPADI', name: 'Madhanagopalapuram', lgdCode: '222661' },
    { district: 'CUDDALORE', block: 'KURINJIPADI', name: 'Maruvai', lgdCode: '222662' },
    { district: 'CUDDALORE', block: 'KURINJIPADI', name: 'Melapudupettai', lgdCode: '222663' },
    { district: 'CUDDALORE', block: 'KURINJIPADI', name: 'Nainarkuppam', lgdCode: '222664' },
    { district: 'CUDDALORE', block: 'KURINJIPADI', name: 'Puliyur', lgdCode: '222667' },
    { district: 'CUDDALORE', block: 'KURINJIPADI', name: 'Poovanikuppam', lgdCode: '222666' },
    { district: 'CUDDALORE', block: 'KURINJIPADI', name: 'Pethanaikkankuppam', lgdCode: '222665' },
    { district: 'CUDDALORE', block: 'KURINJIPADI', name: 'Renganathapuram', lgdCode: '222668' },
    { district: 'CUDDALORE', block: 'KURINJIPADI', name: 'Sammattikuppam', lgdCode: '222669' },
    { district: 'CUDDALORE', block: 'KURINJIPADI', name: 'Sirupalaiyur', lgdCode: '222670' },
    { district: 'CUDDALORE', block: 'KURINJIPADI', name: 'Thondamanatham', lgdCode: '222677' },
    { district: 'CUDDALORE', block: 'KURINJIPADI', name: 'Thiyagavalli', lgdCode: '222676' },
    { district: 'CUDDALORE', block: 'KURINJIPADI', name: 'Thambipettaipalayam', lgdCode: '222673' },
    { district: 'CUDDALORE', block: 'KURINJIPADI', name: 'Thiruchopuram', lgdCode: '222675' },
    { district: 'CUDDALORE', block: 'KURINJIPADI', name: 'Thambipettai', lgdCode: '222672' },
    { district: 'CUDDALORE', block: 'KURINJIPADI', name: 'Thaiyalkunampattinam', lgdCode: '222671' },
    { district: 'CUDDALORE', block: 'KURINJIPADI', name: 'Theerthanagiri', lgdCode: '222674' },
    { district: 'CUDDALORE', block: 'KURINJIPADI', name: 'Venkatampettai', lgdCode: '222684' },
    { district: 'CUDDALORE', block: 'KURINJIPADI', name: 'Vadakuthu', lgdCode: '222679' },
    { district: 'CUDDALORE', block: 'KURINJIPADI', name: 'Vadakkumelur', lgdCode: '222678' },
    { district: 'CUDDALORE', block: 'KURINJIPADI', name: 'Vanathirayapuram', lgdCode: '222680' },
    { district: 'CUDDALORE', block: 'KURINJIPADI', name: 'Vazhuthalampattu', lgdCode: '222683' },
    { district: 'CUDDALORE', block: 'KURINJIPADI', name: 'Virupatchi', lgdCode: '222685' },
    { district: 'CUDDALORE', block: 'KURINJIPADI', name: 'Vandiyampallam', lgdCode: '222681' },
    { district: 'CUDDALORE', block: 'KURINJIPADI', name: 'Varatharajanpettai', lgdCode: '222682' },
    { district: 'CUDDALORE', block: 'KURINJIPADI', name: 'Perumathur', lgdCode: '254893' },
    { district: 'CUDDALORE', block: 'KURINJIPADI', name: 'Indira Nagar', lgdCode: '254894' },
    { district: 'CUDDALORE', block: 'KATTUMANNAR KOIL', name: 'Achalpuram', lgdCode: '222463' },
    { district: 'CUDDALORE', block: 'KATTUMANNAR KOIL', name: 'Agaraputhur', lgdCode: '222464' },
    { district: 'CUDDALORE', block: 'KATTUMANNAR KOIL', name: 'Azhangathan', lgdCode: '222465' },
    { district: 'CUDDALORE', block: 'KATTUMANNAR KOIL', name: 'Azhinjimangalam', lgdCode: '222466' },
    { district: 'CUDDALORE', block: 'KATTUMANNAR KOIL', name: 'Aranthangi', lgdCode: '222467' },
    { district: 'CUDDALORE', block: 'KATTUMANNAR KOIL', name: 'Ayangudi', lgdCode: '222468' },
    { district: 'CUDDALORE', block: 'KATTUMANNAR KOIL', name: 'Chettithangal', lgdCode: '222469' },
    { district: 'CUDDALORE', block: 'KATTUMANNAR KOIL', name: 'Eachampoondi', lgdCode: '222470' },
    { district: 'CUDDALORE', block: 'KATTUMANNAR KOIL', name: 'Kalnattampuliyur', lgdCode: '222476' },
    { district: 'CUDDALORE', block: 'KATTUMANNAR KOIL', name: 'Kandamangalam', lgdCode: '254895' },
    { district: 'CUDDALORE', block: 'KATTUMANNAR KOIL', name: 'Kanjankollai', lgdCode: '222478' },
    { district: 'CUDDALORE', block: 'KATTUMANNAR KOIL', name: 'Karunakaranallur', lgdCode: '222479' },
    { district: 'CUDDALORE', block: 'KATTUMANNAR KOIL', name: 'Keezhakadambur', lgdCode: '222480' },
    { district: 'CUDDALORE', block: 'KATTUMANNAR KOIL', name: 'Keelpuliyampattu', lgdCode: '222481' },
    { district: 'CUDDALORE', block: 'KATTUMANNAR KOIL', name: 'Kollumedu', lgdCode: '222483' },
    { district: 'CUDDALORE', block: 'KATTUMANNAR KOIL', name: 'Kondasamuthiram', lgdCode: '222484' },
    { district: 'CUDDALORE', block: 'KATTUMANNAR KOIL', name: 'Gunavasal', lgdCode: '222473' },
    { district: 'CUDDALORE', block: 'KATTUMANNAR KOIL', name: 'Kunjamedu', lgdCode: '222486' },
    { district: 'CUDDALORE', block: 'KATTUMANNAR KOIL', name: 'K. Poovizhunthanallur', lgdCode: '222474' },
    { district: 'CUDDALORE', block: 'KATTUMANNAR KOIL', name: 'Kurungudi', lgdCode: '222487' },
    { district: 'CUDDALORE', block: 'KATTUMANNAR KOIL', name: 'M. Adhanur', lgdCode: '222488' },
    { district: 'CUDDALORE', block: 'KATTUMANNAR KOIL', name: 'Mamangalam', lgdCode: '222491' },
    { district: 'CUDDALORE', block: 'KATTUMANNAR KOIL', name: 'Maniyam Adoor', lgdCode: '222492' },
    { district: 'CUDDALORE', block: 'KATTUMANNAR KOIL', name: 'Ma. Uthamasozhagan', lgdCode: '222489' },
    { district: 'CUDDALORE', block: 'KATTUMANNAR KOIL', name: 'Melakadambur', lgdCode: '222493' },
    { district: 'CUDDALORE', block: 'KATTUMANNAR KOIL', name: 'Melradhambur', lgdCode: '222495' },
    { district: 'CUDDALORE', block: 'KATTUMANNAR KOIL', name: 'Moovur', lgdCode: '222496' },
    { district: 'CUDDALORE', block: 'KATTUMANNAR KOIL', name: 'Muttam', lgdCode: '222497' },
    { district: 'CUDDALORE', block: 'KATTUMANNAR KOIL', name: 'Nathamalai', lgdCode: '222499' },
    { district: 'CUDDALORE', block: 'KATTUMANNAR KOIL', name: 'Nattarmangalam', lgdCode: '222500' },
    { district: 'CUDDALORE', block: 'KATTUMANNAR KOIL', name: 'Pazhanjanallur', lgdCode: '222501' },
    { district: 'CUDDALORE', block: 'KATTUMANNAR KOIL', name: 'Rayanallur', lgdCode: '222502' },
    { district: 'CUDDALORE', block: 'KATTUMANNAR KOIL', name: 'Reddiyur', lgdCode: '222503' },
    { district: 'CUDDALORE', block: 'KATTUMANNAR KOIL', name: 'Sithamalli', lgdCode: '222506' },
    { district: 'CUDDALORE', block: 'KATTUMANNAR KOIL', name: 'Shandan', lgdCode: '222504' },
    { district: 'CUDDALORE', block: 'KATTUMANNAR KOIL', name: 'Sirukattur', lgdCode: '222505' },
    { district: 'CUDDALORE', block: 'KATTUMANNAR KOIL', name: 'T. Arulmozhidevan', lgdCode: '222510' },
    { district: 'CUDDALORE', block: 'KATTUMANNAR KOIL', name: 'Thiruchinnapuram', lgdCode: '222512' },
    { district: 'CUDDALORE', block: 'KATTUMANNAR KOIL', name: 'Thorappu', lgdCode: '222513' },
    { district: 'CUDDALORE', block: 'KATTUMANNAR KOIL', name: 'Vanamadevi', lgdCode: '222514' },
    { district: 'CUDDALORE', block: 'KATTUMANNAR KOIL', name: 'Veerananallur', lgdCode: '222515' },
    { district: 'CUDDALORE', block: 'KATTUMANNAR KOIL', name: 'Veeranandhapuram', lgdCode: '222516' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'Agaranallur', lgdCode: '222580' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'Alkondanatham', lgdCode: '222581' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'C. Arasur', lgdCode: '222583' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'Ma. Arasur', lgdCode: '222601' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'Athipattu', lgdCode: '222582' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'Chettikattalai', lgdCode: '222586' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'Chidambaram Non Municipal', lgdCode: '222587' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'Edaiyar', lgdCode: '222588' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'Elanangoor', lgdCode: '222589' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'Elleri', lgdCode: '222590' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'Jayankondapattinam', lgdCode: '222591' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'Kadavacherry', lgdCode: '222592' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'Karuppur', lgdCode: '222593' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'Kattukudalur', lgdCode: '222594' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'Keelathangudi', lgdCode: '222597' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'Keelagundalapadi', lgdCode: '222596' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'Keelaparuthikudi', lgdCode: '222595' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'Ma. Kolakkudi', lgdCode: '222602' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'Kumaratchi', lgdCode: '222600' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'Koothankoil', lgdCode: '222598' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'Kuduvelichavadi', lgdCode: '222599' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'Madharsudamani', lgdCode: '222605' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'Melaparuthikudi', lgdCode: '222607' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'Meiyathur', lgdCode: '222606' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'Mullangudi', lgdCode: '222608' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'Nalamputhur', lgdCode: '222609' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'Nandhimangalam', lgdCode: '222610' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'Nanjalur', lgdCode: '222611' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'Nedumbur', lgdCode: '222612' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'Neivasal', lgdCode: '222613' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'Ma. Udaiyur', lgdCode: '222604' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'Parivilagam', lgdCode: '222614' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'Perampattu', lgdCode: '222615' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'Poolamedu', lgdCode: '222616' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'Ma. Puliyangudi', lgdCode: '222603' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'T. Puthur', lgdCode: '222624' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'Ruthirasolai', lgdCode: '222617' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'Saliyanthoppu', lgdCode: '222618' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'Sarvarajanpettai', lgdCode: '222619' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'Sivapuri', lgdCode: '222621' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'Sivayam', lgdCode: '222622' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'Solakkur', lgdCode: '222623' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'Sirakizhanthanallur', lgdCode: '222620' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'C. Thandeswaranallur', lgdCode: '222584' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'Thavarthampattu', lgdCode: '222625' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'Themmur', lgdCode: '222626' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'Therkkumangudi', lgdCode: '222627' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'Thirunaraiyur', lgdCode: '222628' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'Usuppur', lgdCode: '222629' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'Vadakkumangudi', lgdCode: '222630' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'Vadamoor', lgdCode: '222631' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'Vaiyur', lgdCode: '222632' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'C. Vakkaramari', lgdCode: '222585' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'Vallampadugai', lgdCode: '222633' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'Varahoor', lgdCode: '222634' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'Vellur', lgdCode: '222635' },
    { district: 'CUDDALORE', block: 'KUMARATCHI', name: 'Vennaiyur', lgdCode: '222636' },
    { district: 'CUDDALORE', block: 'KEERAPALAYAM', name: 'K.Adoor', lgdCode: '222527' },
    { district: 'CUDDALORE', block: 'KEERAPALAYAM', name: 'Ayeepettai', lgdCode: '222517' },
    { district: 'CUDDALORE', block: 'KEERAPALAYAM', name: 'Ayyanur-akkaramangalam', lgdCode: '222518' },
    { district: 'CUDDALORE', block: 'KEERAPALAYAM', name: 'Boothangudi', lgdCode: '222519' },
    { district: 'CUDDALORE', block: 'KEERAPALAYAM', name: 'Devangudi', lgdCode: '222523' },
    { district: 'CUDDALORE', block: 'KEERAPALAYAM', name: 'Edaiyanpalchorry', lgdCode: '222524' },
    { district: 'CUDDALORE', block: 'KEERAPALAYAM', name: 'Ennanagaram', lgdCode: '222525' },
    { district: 'CUDDALORE', block: 'KEERAPALAYAM', name: 'Kaliyamalai', lgdCode: '222529' },
    { district: 'CUDDALORE', block: 'KEERAPALAYAM', name: 'Kanthakumaran', lgdCode: '222530' },
    { district: 'CUDDALORE', block: 'KEERAPALAYAM', name: 'Kannangudi', lgdCode: '222531' },
    { district: 'CUDDALORE', block: 'KEERAPALAYAM', name: 'Keerapalayam', lgdCode: '222534' },
    { district: 'CUDDALORE', block: 'KEERAPALAYAM', name: 'Keezhnatham', lgdCode: '222533' },
    { district: 'CUDDALORE', block: 'KEERAPALAYAM', name: 'Kiliyanur', lgdCode: '222535' },
    { district: 'CUDDALORE', block: 'KEERAPALAYAM', name: 'Koolapadi', lgdCode: '222536' },
    { district: 'CUDDALORE', block: 'KEERAPALAYAM', name: 'Mugaiyur', lgdCode: '222542' },
    { district: 'CUDDALORE', block: 'KEERAPALAYAM', name: 'Mathuranthaganallur', lgdCode: '222539' },
    { district: 'CUDDALORE', block: 'KEERAPALAYAM', name: 'T.Manalur', lgdCode: '222563' },
    { district: 'CUDDALORE', block: 'KEERAPALAYAM', name: 'C.Melavanniyur', lgdCode: '222520' },
    { district: 'CUDDALORE', block: 'KEERAPALAYAM', name: 'T.Neduncherry', lgdCode: '222564' },
    { district: 'CUDDALORE', block: 'KEERAPALAYAM', name: 'Orathur', lgdCode: '222546' },
    { district: 'CUDDALORE', block: 'KEERAPALAYAM', name: 'Odakkanallur', lgdCode: '222545' },
    { district: 'CUDDALORE', block: 'KEERAPALAYAM', name: 'Palayanserthangudi', lgdCode: '222549' },
    { district: 'CUDDALORE', block: 'KEERAPALAYAM', name: 'Pannapattu', lgdCode: '222550' },
    { district: 'CUDDALORE', block: 'KEERAPALAYAM', name: 'Paradhur', lgdCode: '222551' },
    { district: 'CUDDALORE', block: 'KEERAPALAYAM', name: 'Perungaloor', lgdCode: '222552' },
    { district: 'CUDDALORE', block: 'KEERAPALAYAM', name: 'Poonthottam', lgdCode: '222556' },
    { district: 'CUDDALORE', block: 'KEERAPALAYAM', name: 'Poorthangudi', lgdCode: '222554' },
    { district: 'CUDDALORE', block: 'KEERAPALAYAM', name: 'Sakkankudi', lgdCode: '222558' },
    { district: 'CUDDALORE', block: 'KEERAPALAYAM', name: 'C.Sathamangalam', lgdCode: '222521' },
    { district: 'CUDDALORE', block: 'KEERAPALAYAM', name: 'Sengalmedu', lgdCode: '222559' },
    { district: 'CUDDALORE', block: 'KEERAPALAYAM', name: 'Sethiyur', lgdCode: '222560' },
    { district: 'CUDDALORE', block: 'KEERAPALAYAM', name: 'Sirugalur', lgdCode: '222561' },
    { district: 'CUDDALORE', block: 'KEERAPALAYAM', name: 'Tharasur', lgdCode: '222565' },
    { district: 'CUDDALORE', block: 'KEERAPALAYAM', name: 'Thenharirajapuram', lgdCode: '222566' },
    { district: 'CUDDALORE', block: 'KEERAPALAYAM', name: 'Therkkuviruthangan', lgdCode: '222567' },
    { district: 'CUDDALORE', block: 'KEERAPALAYAM', name: 'Thunisiramedu', lgdCode: '222568' },
    { district: 'CUDDALORE', block: 'KEERAPALAYAM', name: 'Vadaharirajapuram', lgdCode: '222570' },
    { district: 'CUDDALORE', block: 'KEERAPALAYAM', name: 'Vadapakkam', lgdCode: '222572' },
    { district: 'CUDDALORE', block: 'KEERAPALAYAM', name: 'Vaakkur', lgdCode: '222569' },
    { district: 'CUDDALORE', block: 'KEERAPALAYAM', name: 'Vazhaikollai', lgdCode: '222576' },
    { district: 'CUDDALORE', block: 'KEERAPALAYAM', name: 'Vayalur', lgdCode: '222575' },
    { district: 'CUDDALORE', block: 'KEERAPALAYAM', name: 'C.Veerasozhagan', lgdCode: '222522' },
    { district: 'CUDDALORE', block: 'KEERAPALAYAM', name: 'Velliyagudi', lgdCode: '222578' },
    { district: 'CUDDALORE', block: 'KEERAPALAYAM', name: 'Veiyaloor', lgdCode: '222577' },
    { district: 'CUDDALORE', block: 'KEERAPALAYAM', name: 'Vilagam', lgdCode: '222579' },
    { district: 'CUDDALORE', block: 'MELBHUVANAGIRI', name: 'B. Adhanoor', lgdCode: '222757' },
    { district: 'CUDDALORE', block: 'MELBHUVANAGIRI', name: 'Agara Alambadi', lgdCode: '222752' },
    { district: 'CUDDALORE', block: 'MELBHUVANAGIRI', name: 'Kasba Alambadi', lgdCode: '222767' },
    { district: 'CUDDALORE', block: 'MELBHUVANAGIRI', name: 'Azhichikudi', lgdCode: '222753' },
    { district: 'CUDDALORE', block: 'MELBHUVANAGIRI', name: 'Ambalpuram', lgdCode: '222754' },
    { district: 'CUDDALORE', block: 'MELBHUVANAGIRI', name: 'Ammankuppam', lgdCode: '222755' },
    { district: 'CUDDALORE', block: 'MELBHUVANAGIRI', name: 'Anaivari', lgdCode: '222756' },
    { district: 'CUDDALORE', block: 'MELBHUVANAGIRI', name: 'Boothavarayanpettai', lgdCode: '222759' },
    { district: 'CUDDALORE', block: 'MELBHUVANAGIRI', name: 'Chinnanerkunam', lgdCode: '222761' },
    { district: 'CUDDALORE', block: 'MELBHUVANAGIRI', name: 'B-sitheri', lgdCode: '222788' },
    { district: 'CUDDALORE', block: 'MELBHUVANAGIRI', name: 'Chokkankollai', lgdCode: '222762' },
    { district: 'CUDDALORE', block: 'MELBHUVANAGIRI', name: 'Ellaikudi', lgdCode: '222763' },
    { district: 'CUDDALORE', block: 'MELBHUVANAGIRI', name: 'Erumbur', lgdCode: '222764' },
    { district: 'CUDDALORE', block: 'MELBHUVANAGIRI', name: 'Jayankondam', lgdCode: '222765' },
    { district: 'CUDDALORE', block: 'MELBHUVANAGIRI', name: 'Kathazhai', lgdCode: '222768' },
    { district: 'CUDDALORE', block: 'MELBHUVANAGIRI', name: 'Karaimedu', lgdCode: '222766' },
    { district: 'CUDDALORE', block: 'MELBHUVANAGIRI', name: 'Kilavadinatham', lgdCode: '222770' },
    { district: 'CUDDALORE', block: 'MELBHUVANAGIRI', name: 'Kizhamungiladi', lgdCode: '222771' },
    { district: 'CUDDALORE', block: 'MELBHUVANAGIRI', name: 'Vadakrishnapuram', lgdCode: '222795' },
    { district: 'CUDDALORE', block: 'MELBHUVANAGIRI', name: 'P. Kolakudi', lgdCode: '222783' },
    { district: 'CUDDALORE', block: 'MELBHUVANAGIRI', name: 'Kummudimoolai', lgdCode: '222772' },
    { district: 'CUDDALORE', block: 'MELBHUVANAGIRI', name: 'Lalpuram', lgdCode: '222773' },
    { district: 'CUDDALORE', block: 'MELBHUVANAGIRI', name: 'B. Odaiyur', lgdCode: '222758' },
    { district: 'CUDDALORE', block: 'MELBHUVANAGIRI', name: 'Maruthur', lgdCode: '222775' },
    { district: 'CUDDALORE', block: 'MELBHUVANAGIRI', name: 'Melannuvampattu', lgdCode: '222778' },
    { district: 'CUDDALORE', block: 'MELBHUVANAGIRI', name: 'Melamanakudi', lgdCode: '222776' },
    { district: 'CUDDALORE', block: 'MELBHUVANAGIRI', name: 'Melamoongiladi', lgdCode: '222777' },
    { district: 'CUDDALORE', block: 'MELBHUVANAGIRI', name: 'Miralur', lgdCode: '222780' },
    { district: 'CUDDALORE', block: 'MELBHUVANAGIRI', name: 'C. Mutlur', lgdCode: '222760' },
    { district: 'CUDDALORE', block: 'MELBHUVANAGIRI', name: 'Nathamedu', lgdCode: '222781' },
    { district: 'CUDDALORE', block: 'MELBHUVANAGIRI', name: 'Nellikollai', lgdCode: '222782' },
    { district: 'CUDDALORE', block: 'MELBHUVANAGIRI', name: 'Manjakollai', lgdCode: '222774' },
    { district: 'CUDDALORE', block: 'MELBHUVANAGIRI', name: 'Periyanerkunam', lgdCode: '222784' },
    { district: 'CUDDALORE', block: 'MELBHUVANAGIRI', name: 'Pinnalur', lgdCode: '222785' },
    { district: 'CUDDALORE', block: 'MELBHUVANAGIRI', name: 'Prasannaramapuram', lgdCode: '222786' },
    { district: 'CUDDALORE', block: 'MELBHUVANAGIRI', name: 'Sathapadi', lgdCode: '222787' },
    { district: 'CUDDALORE', block: 'MELBHUVANAGIRI', name: 'Vadathalaikulam', lgdCode: '222796' },
    { district: 'CUDDALORE', block: 'MELBHUVANAGIRI', name: 'Theethampalayam', lgdCode: '222789' },
    { district: 'CUDDALORE', block: 'MELBHUVANAGIRI', name: 'Therkkuthittai', lgdCode: '222790' },
    { district: 'CUDDALORE', block: 'MELBHUVANAGIRI', name: 'Thillainayagapuram', lgdCode: '222791' },
    { district: 'CUDDALORE', block: 'MELBHUVANAGIRI', name: 'Thurinjikollai', lgdCode: '222792' },
    { district: 'CUDDALORE', block: 'MELBHUVANAGIRI', name: 'Uluthur', lgdCode: '222793' },
    { district: 'CUDDALORE', block: 'MELBHUVANAGIRI', name: 'Vadakkuthittai', lgdCode: '222794' },
    { district: 'CUDDALORE', block: 'MELBHUVANAGIRI', name: 'Melvalayamadevi', lgdCode: '222779' },
    { district: 'CUDDALORE', block: 'MELBHUVANAGIRI', name: 'Keelvalayamadevi', lgdCode: '222769' },
    { district: 'CUDDALORE', block: 'MELBHUVANAGIRI', name: 'Vatharayanthethu', lgdCode: '222797' },
    { district: 'CUDDALORE', block: 'MELBHUVANAGIRI', name: 'Veeramudaiyanatham', lgdCode: '222798' },
    { district: 'CUDDALORE', block: 'PARANGIPETTAI', name: 'Adivaraganallur', lgdCode: '222905' },
    { district: 'CUDDALORE', block: 'PARANGIPETTAI', name: 'Ariyakoshti', lgdCode: '222906' },
    { district: 'CUDDALORE', block: 'PARANGIPETTAI', name: 'Arunmozhidevan', lgdCode: '222907' },
    { district: 'CUDDALORE', block: 'PARANGIPETTAI', name: 'Ayeepuram', lgdCode: '222908' },
    { district: 'CUDDALORE', block: 'PARANGIPETTAI', name: 'Chinnakomatti', lgdCode: '222912' },
    { district: 'CUDDALORE', block: 'PARANGIPETTAI', name: 'Chinnur Pudupettai', lgdCode: '222913' },
    { district: 'CUDDALORE', block: 'PARANGIPETTAI', name: 'Kavarapattu', lgdCode: '222915' },
    { district: 'CUDDALORE', block: 'PARANGIPETTAI', name: 'Kanagarapattu', lgdCode: '222914' },
    { district: 'CUDDALORE', block: 'PARANGIPETTAI', name: 'Keelamanakudi', lgdCode: '222917' },
    { district: 'CUDDALORE', block: 'PARANGIPETTAI', name: 'Keel anuvampattu', lgdCode: '222916' },
    { district: 'CUDDALORE', block: 'PARANGIPETTAI', name: 'Keelaperambai', lgdCode: '222918' },
    { district: 'CUDDALORE', block: 'PARANGIPETTAI', name: 'Keelathirukalipalai', lgdCode: '222919' },
    { district: 'CUDDALORE', block: 'PARANGIPETTAI', name: 'C.Kothankudi', lgdCode: '222911' },
    { district: 'CUDDALORE', block: 'PARANGIPETTAI', name: 'Kothattai', lgdCode: '222920' },
    { district: 'CUDDALORE', block: 'PARANGIPETTAI', name: 'Kovilampoondi', lgdCode: '222921' },
    { district: 'CUDDALORE', block: 'PARANGIPETTAI', name: 'Kumaramangalam', lgdCode: '222922' },
    { district: 'CUDDALORE', block: 'PARANGIPETTAI', name: 'Kuriyamangalam', lgdCode: '222923' },
    { district: 'CUDDALORE', block: 'PARANGIPETTAI', name: 'B.Maduvangarai', lgdCode: '222909' },
    { district: 'CUDDALORE', block: 'PARANGIPETTAI', name: 'Manikollai', lgdCode: '222924' },
    { district: 'CUDDALORE', block: 'PARANGIPETTAI', name: 'Manjakuzhi', lgdCode: '222925' },
    { district: 'CUDDALORE', block: 'PARANGIPETTAI', name: 'Meethikudi', lgdCode: '222926' },
    { district: 'CUDDALORE', block: 'PARANGIPETTAI', name: 'Melathirukalipalai', lgdCode: '222927' },
    { district: 'CUDDALORE', block: 'PARANGIPETTAI', name: 'B.Mutlur', lgdCode: '222910' },
    { district: 'CUDDALORE', block: 'PARANGIPETTAI', name: 'Nakkaravandankudi', lgdCode: '222928' },
    { district: 'CUDDALORE', block: 'PARANGIPETTAI', name: 'Nanjamahathuvalgai', lgdCode: '222929' },
    { district: 'CUDDALORE', block: 'PARANGIPETTAI', name: 'Pallipadai', lgdCode: '222930' },
    { district: 'CUDDALORE', block: 'PARANGIPETTAI', name: 'Periyakomatti', lgdCode: '222931' },
    { district: 'CUDDALORE', block: 'PARANGIPETTAI', name: 'Periyapattu', lgdCode: '222932' },
    { district: 'CUDDALORE', block: 'PARANGIPETTAI', name: 'Pichavaram', lgdCode: '222933' },
    { district: 'CUDDALORE', block: 'PARANGIPETTAI', name: 'Pinnathur', lgdCode: '222934' },
    { district: 'CUDDALORE', block: 'PARANGIPETTAI', name: 'Poovalai', lgdCode: '222935' },
    { district: 'CUDDALORE', block: 'PARANGIPETTAI', name: 'Senthirakillai', lgdCode: '222936' },
    { district: 'CUDDALORE', block: 'PARANGIPETTAI', name: 'Silambimangalam', lgdCode: '222937' },
    { district: 'CUDDALORE', block: 'PARANGIPETTAI', name: 'Thandavarayansozhaganpettai', lgdCode: '222938' },
    { district: 'CUDDALORE', block: 'PARANGIPETTAI', name: 'Thatchakadu', lgdCode: '222939' },
    { district: 'CUDDALORE', block: 'PARANGIPETTAI', name: 'Thillaividangan', lgdCode: '222940' },
    { district: 'CUDDALORE', block: 'PARANGIPETTAI', name: 'Uthamasozhamangalam', lgdCode: '222941' },
    { district: 'CUDDALORE', block: 'PARANGIPETTAI', name: 'Vasaputhur', lgdCode: '222942' },
    { district: 'CUDDALORE', block: 'PARANGIPETTAI', name: 'Vayalamoor', lgdCode: '222943' },
    { district: 'CUDDALORE', block: 'PARANGIPETTAI', name: 'Velangipattu', lgdCode: '222944' },
    { district: 'CUDDALORE', block: 'PARANGIPETTAI', name: 'Villiyanallur', lgdCode: '222945' },
    { district: 'CUDDALORE', block: 'VRIDHACHALAM', name: 'Alichikudi', lgdCode: '222947' },
    { district: 'CUDDALORE', block: 'VRIDHACHALAM', name: 'Aladi', lgdCode: '222946' },
    { district: 'CUDDALORE', block: 'VRIDHACHALAM', name: 'Chinnaparur', lgdCode: '222949' },
    { district: 'CUDDALORE', block: 'VRIDHACHALAM', name: 'Chinnakandiyankuppam', lgdCode: '222948' },
    { district: 'CUDDALORE', block: 'VRIDHACHALAM', name: 'Edachithur', lgdCode: '222951' },
    { district: 'CUDDALORE', block: 'VRIDHACHALAM', name: 'Edaiyur', lgdCode: '222952' },
    { district: 'CUDDALORE', block: 'VRIDHACHALAM', name: 'Earumanur', lgdCode: '222950' },
    { district: 'CUDDALORE', block: 'VRIDHACHALAM', name: 'Gopurapuram', lgdCode: '222953' },
    { district: 'CUDDALORE', block: 'VRIDHACHALAM', name: 'Ka. Elamangalam', lgdCode: '222954' },
    { district: 'CUDDALORE', block: 'VRIDHACHALAM', name: 'Katchirayanatham', lgdCode: '222957' },
    { district: 'CUDDALORE', block: 'VRIDHACHALAM', name: 'Kattiyanallur', lgdCode: '222958' },
    { district: 'CUDDALORE', block: 'VRIDHACHALAM', name: 'Karnatham', lgdCode: '222955' },
    { district: 'CUDDALORE', block: 'VRIDHACHALAM', name: 'Karuvepilankurichi', lgdCode: '222956' },
    { district: 'CUDDALORE', block: 'VRIDHACHALAM', name: 'Kattuparur', lgdCode: '222959' },
    { district: 'CUDDALORE', block: 'VRIDHACHALAM', name: 'Kodukkur', lgdCode: '222962' },
    { district: 'CUDDALORE', block: 'VRIDHACHALAM', name: 'Komangalam', lgdCode: '222963' },
    { district: 'CUDDALORE', block: 'VRIDHACHALAM', name: 'Kovilanur', lgdCode: '222964' },
    { district: 'CUDDALORE', block: 'VRIDHACHALAM', name: 'Kuppanatham', lgdCode: '222965' },
    { district: 'CUDDALORE', block: 'VRIDHACHALAM', name: 'Ko. Pavalangudi', lgdCode: '222960' },
    { district: 'CUDDALORE', block: 'VRIDHACHALAM', name: 'Ko. Poovanur', lgdCode: '222961' },
    { district: 'CUDDALORE', block: 'VRIDHACHALAM', name: 'Mu. Agaram', lgdCode: '222971' },
    { district: 'CUDDALORE', block: 'VRIDHACHALAM', name: 'M. Parur', lgdCode: '222966' },
    { district: 'CUDDALORE', block: 'VRIDHACHALAM', name: 'M. Patti', lgdCode: '222967' },
    { district: 'CUDDALORE', block: 'VRIDHACHALAM', name: 'M. Pudhur', lgdCode: '222968' },
    { district: 'CUDDALORE', block: 'VRIDHACHALAM', name: 'Mathur', lgdCode: '222970' },
    { district: 'CUDDALORE', block: 'VRIDHACHALAM', name: 'Mugundanallur', lgdCode: '222972' },
    { district: 'CUDDALORE', block: 'VRIDHACHALAM', name: 'Manavalanallur', lgdCode: '222969' },
    { district: 'CUDDALORE', block: 'VRIDHACHALAM', name: 'Narumanam', lgdCode: '222973' },
    { district: 'CUDDALORE', block: 'VRIDHACHALAM', name: 'Puthukooraipet', lgdCode: '222979' },
    { district: 'CUDDALORE', block: 'VRIDHACHALAM', name: 'Paravalur', lgdCode: '222974' },
    { district: 'CUDDALORE', block: 'VRIDHACHALAM', name: 'Puliyur', lgdCode: '222978' },
    { district: 'CUDDALORE', block: 'VRIDHACHALAM', name: 'Perambalur', lgdCode: '222976' },
    { district: 'CUDDALORE', block: 'VRIDHACHALAM', name: 'Periyavadavadi', lgdCode: '222977' },
    { district: 'CUDDALORE', block: 'VRIDHACHALAM', name: 'Peralaiyur', lgdCode: '222975' },
    { district: 'CUDDALORE', block: 'VRIDHACHALAM', name: 'Rajendirapattinam', lgdCode: '222980' },
    { district: 'CUDDALORE', block: 'VRIDHACHALAM', name: 'Rubanarayananallur', lgdCode: '222981' },
    { district: 'CUDDALORE', block: 'VRIDHACHALAM', name: 'Sathiyavadi', lgdCode: '222982' },
    { district: 'CUDDALORE', block: 'VRIDHACHALAM', name: 'Sathukudal Melpathi', lgdCode: '222984' },
    { district: 'CUDDALORE', block: 'VRIDHACHALAM', name: 'Sathukudal Keelpathi', lgdCode: '222983' },
    { district: 'CUDDALORE', block: 'VRIDHACHALAM', name: 'Sitherikuppam', lgdCode: '222987' },
    { district: 'CUDDALORE', block: 'VRIDHACHALAM', name: 'Siruvambar', lgdCode: '222986' },
    { district: 'CUDDALORE', block: 'VRIDHACHALAM', name: 'Sembalakurichi', lgdCode: '222985' },
    { district: 'CUDDALORE', block: 'VRIDHACHALAM', name: 'Thottikuppam', lgdCode: '222991' },
    { district: 'CUDDALORE', block: 'VRIDHACHALAM', name: 'T. V. Puthur', lgdCode: '222989' },
    { district: 'CUDDALORE', block: 'VRIDHACHALAM', name: 'Thoravalur', lgdCode: '222990' },
    { district: 'CUDDALORE', block: 'VRIDHACHALAM', name: 'T. Mavidanthal', lgdCode: '222988' },
    { district: 'CUDDALORE', block: 'VRIDHACHALAM', name: 'Vijayamanagaram', lgdCode: '222994' },
    { district: 'CUDDALORE', block: 'VRIDHACHALAM', name: 'Vannankudikadu', lgdCode: '222992' },
    { district: 'CUDDALORE', block: 'VRIDHACHALAM', name: 'Visaloor', lgdCode: '222996' },
    { district: 'CUDDALORE', block: 'VRIDHACHALAM', name: 'Vilankattur', lgdCode: '222995' },
    { district: 'CUDDALORE', block: 'VRIDHACHALAM', name: 'Vettakudi', lgdCode: '222993' },
    { district: 'CUDDALORE', block: 'KAMMAPURAM', name: 'Ammeri', lgdCode: '222411' },
    { district: 'CUDDALORE', block: 'KAMMAPURAM', name: 'Gopalapuram', lgdCode: '222415' },
    { district: 'CUDDALORE', block: 'KAMMAPURAM', name: 'Iruppu', lgdCode: '222417' },
    { district: 'CUDDALORE', block: 'KAMMAPURAM', name: 'Iruppukurichi', lgdCode: '222418' },
    { district: 'CUDDALORE', block: 'KAMMAPURAM', name: 'Irulakurichi', lgdCode: '222416' },
    { district: 'CUDDALORE', block: 'KAMMAPURAM', name: 'Kammapuram', lgdCode: '222419' },
    { district: 'CUDDALORE', block: 'KAMMAPURAM', name: 'Karkudal', lgdCode: '222420' },
    { district: 'CUDDALORE', block: 'KAMMAPURAM', name: 'Su. Keenanur', lgdCode: '222453' },
    { district: 'CUDDALORE', block: 'KAMMAPURAM', name: 'Keelpathi', lgdCode: '222424' },
    { district: 'CUDDALORE', block: 'KAMMAPURAM', name: 'Ko. Athanur', lgdCode: '222425' },
    { district: 'CUDDALORE', block: 'KAMMAPURAM', name: 'Ko. Mavidnathal', lgdCode: '222426' },
    { district: 'CUDDALORE', block: 'KAMMAPURAM', name: 'Kolliruppu', lgdCode: '222427' },
    { district: 'CUDDALORE', block: 'KAMMAPURAM', name: 'Kottagam', lgdCode: '222428' },
    { district: 'CUDDALORE', block: 'KAMMAPURAM', name: 'Kottumulai', lgdCode: '222430' },
    { district: 'CUDDALORE', block: 'KAMMAPURAM', name: 'Kotteri', lgdCode: '222429' },
    { district: 'CUDDALORE', block: 'KAMMAPURAM', name: 'V. Kumaramangalam', lgdCode: '222431' },
    { district: 'CUDDALORE', block: 'KAMMAPURAM', name: 'Koonankurichi', lgdCode: '222432' },
    { district: 'CUDDALORE', block: 'KAMMAPURAM', name: 'Manakollai', lgdCode: '222433' },
    { district: 'CUDDALORE', block: 'KAMMAPURAM', name: 'Melpathi', lgdCode: '222436' },
    { district: 'CUDDALORE', block: 'KAMMAPURAM', name: 'Muthanai', lgdCode: '222439' },
    { district: 'CUDDALORE', block: 'KAMMAPURAM', name: 'Mudapuli', lgdCode: '222437' },
    { district: 'CUDDALORE', block: 'KAMMAPURAM', name: 'Mummudicholagan', lgdCode: '222438' },
    { district: 'CUDDALORE', block: 'KAMMAPURAM', name: 'Nadiapattu', lgdCode: '222440' },
    { district: 'CUDDALORE', block: 'KAMMAPURAM', name: 'Neyveli', lgdCode: '222441' },
    { district: 'CUDDALORE', block: 'KAMMAPURAM', name: 'Palakollai', lgdCode: '222442' },
    { district: 'CUDDALORE', block: 'KAMMAPURAM', name: 'Palayapattinam', lgdCode: '222443' },
    { district: 'CUDDALORE', block: 'KAMMAPURAM', name: 'Periyakappankulam', lgdCode: '222444' },
    { district: 'CUDDALORE', block: 'KAMMAPURAM', name: 'Periyakurichi', lgdCode: '222445' },
    { district: 'CUDDALORE', block: 'KAMMAPURAM', name: 'Perundurai', lgdCode: '222446' },
    { district: 'CUDDALORE', block: 'KAMMAPURAM', name: 'Peruvarappur', lgdCode: '222447' },
    { district: 'CUDDALORE', block: 'KAMMAPURAM', name: 'Sathamangalam', lgdCode: '222448' },
    { district: 'CUDDALORE', block: 'KAMMAPURAM', name: 'Sathapadi', lgdCode: '222449' },
    { district: 'CUDDALORE', block: 'KAMMAPURAM', name: 'Seplanatham North', lgdCode: '222450' },
    { district: 'CUDDALORE', block: 'KAMMAPURAM', name: 'Seplanatham South', lgdCode: '222451' },
    { district: 'CUDDALORE', block: 'KAMMAPURAM', name: 'Siruvarappur', lgdCode: '222452' },
    { district: 'CUDDALORE', block: 'KAMMAPURAM', name: 'Dharmanallur', lgdCode: '222414' },
    { district: 'CUDDALORE', block: 'KAMMAPURAM', name: 'U. Adhanur', lgdCode: '222456' },
    { district: 'CUDDALORE', block: 'KAMMAPURAM', name: 'U. Agaram', lgdCode: '222457' },
    { district: 'CUDDALORE', block: 'KAMMAPURAM', name: 'U. Kolapakkam', lgdCode: '222458' },
    { district: 'CUDDALORE', block: 'KAMMAPURAM', name: 'U. Mangalam', lgdCode: '222459' },
    { district: 'CUDDALORE', block: 'KAMMAPURAM', name: 'Uthangal', lgdCode: '222460' },
    { district: 'CUDDALORE', block: 'KAMMAPURAM', name: 'Uyyakondaravi', lgdCode: '222461' },
    { district: 'CUDDALORE', block: 'KAMMAPURAM', name: 'Vadakku Vellore', lgdCode: '222462' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Adhamangalam', lgdCode: '222802' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Adhiyur', lgdCode: '222803' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'A.Agaram', lgdCode: '222799' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Ivathagudi', lgdCode: '222811' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Arugeri', lgdCode: '222804' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'A.Chithur', lgdCode: '222800' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Dheevalur', lgdCode: '222805' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Eraiyur', lgdCode: '222806' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Erappavur', lgdCode: '222807' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Gudalur', lgdCode: '222809' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Elangiyanur', lgdCode: '222810' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Karaiyur', lgdCode: '222812' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Kattumailur', lgdCode: '222813' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Ganapathikurichi', lgdCode: '222808' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Keelakurichi', lgdCode: '222814' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Kilimangalam', lgdCode: '222815' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Kodikalam', lgdCode: '222817' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Konur', lgdCode: '222818' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Kosapallam', lgdCode: '222819' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Kothattai', lgdCode: '222820' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Ko.Kothanur', lgdCode: '222816' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Pa.Kothanur', lgdCode: '222838' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Kovilur', lgdCode: '222821' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Kurukathancheri', lgdCode: '222822' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Maduravalli', lgdCode: '222823' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Maligaimedu', lgdCode: '222825' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Maligaikottam', lgdCode: '222824' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Mannampadi', lgdCode: '222826' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Maruthathur', lgdCode: '222827' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'A.Marur', lgdCode: '222801' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Melur', lgdCode: '222829' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Me.Mathur', lgdCode: '222828' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Murugankudi', lgdCode: '222830' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Nagar', lgdCode: '222832' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Nallur', lgdCode: '222833' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'N.Naraiyur', lgdCode: '222831' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Narasingamangalam', lgdCode: '222834' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Niramani', lgdCode: '222835' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Pasikulam', lgdCode: '222839' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Pelanthurai', lgdCode: '222840' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Pe.Ponneri', lgdCode: '222836' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Pe.Poovanur', lgdCode: '222837' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Periyanesalur', lgdCode: '222841' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Pinjanur', lgdCode: '222842' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Poolambadi', lgdCode: '222843' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'T.Pudaiyur', lgdCode: '222851' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Sathiyam', lgdCode: '222844' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Sepakkam', lgdCode: '222845' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Sethuvarayankuppam', lgdCode: '222846' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Sevur', lgdCode: '222847' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Sirumangalam', lgdCode: '222848' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Sirunesalur', lgdCode: '222849' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Soundracholapuram', lgdCode: '222850' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Thalanallur', lgdCode: '222852' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Thirupayar', lgdCode: '222853' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Thiruvattathurai', lgdCode: '222854' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Tholar', lgdCode: '222855' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Thuraiyur', lgdCode: '222856' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Vadakarai', lgdCode: '222857' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Valasai', lgdCode: '222858' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Vannathur', lgdCode: '222859' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Varambanur', lgdCode: '222860' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Venkarumbur', lgdCode: '222861' },
    { district: 'CUDDALORE', block: 'NALLUR', name: 'Veppur', lgdCode: '222862' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Adari', lgdCode: '222686' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Akkanur', lgdCode: '222687' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Alambadi', lgdCode: '222688' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Alathur', lgdCode: '222689' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Arangur', lgdCode: '222690' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Arasangudi', lgdCode: '222691' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Avatti', lgdCode: '222692' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Avinangudi', lgdCode: '222693' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Chitheri', lgdCode: '222695' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Edacheruvai', lgdCode: '222697' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Ezhuthur', lgdCode: '222698' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Ja. Endal', lgdCode: '222699' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'T. Endal', lgdCode: '222741' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Kallur', lgdCode: '222701' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Kandamathan', lgdCode: '222702' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Kazhudur', lgdCode: '222703' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Kanchirankulam', lgdCode: '222700' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'E. Keeranur', lgdCode: '222696' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Keelacheruvai', lgdCode: '222704' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Keelakalpoondi', lgdCode: '222705' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Keelorathur', lgdCode: '222706' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Kodangudi', lgdCode: '222707' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Korakkai', lgdCode: '222708' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Korakkavadi', lgdCode: '222709' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Ma. Kothanur', lgdCode: '222711' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Ivanur', lgdCode: '222694' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Lakkur', lgdCode: '222710' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Mangalur', lgdCode: '222715' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Mangulam', lgdCode: '222716' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Malayanur', lgdCode: '222714' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Melathanur', lgdCode: '222717' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Melakalpoondi', lgdCode: '222718' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'S. Naraiyur', lgdCode: '222735' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Navalur', lgdCode: '222719' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Nedungulam', lgdCode: '222720' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Nithinatham', lgdCode: '222721' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Orangur', lgdCode: '222722' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Panayandur', lgdCode: '222723' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Passar', lgdCode: '222724' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Pattakurichi', lgdCode: '222725' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Pattur', lgdCode: '222726' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Perumulai', lgdCode: '222727' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Pothiramangalam', lgdCode: '222729' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Poyanapadi', lgdCode: '222728' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Ma. Podaiyur', lgdCode: '222712' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Ma. Puthur', lgdCode: '222713' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Pulikarambalur', lgdCode: '222730' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Pullur', lgdCode: '222732' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Pulivalam', lgdCode: '222731' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Ramanatham', lgdCode: '222733' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Rettakurichi', lgdCode: '222734' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'S. Pudur', lgdCode: '222736' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Sirukarambalur', lgdCode: '222738' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Sirumulai', lgdCode: '222739' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Sevveri', lgdCode: '222737' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Sirupakkam', lgdCode: '222740' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Thatchur', lgdCode: '222742' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Thozhudur', lgdCode: '222743' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Thondankurichi', lgdCode: '222744' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Vadakarampoondi', lgdCode: '222745' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Vadapathy', lgdCode: '222746' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Vagaiyur', lgdCode: '222747' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Vallimaduram', lgdCode: '222749' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Vaiyangudi', lgdCode: '222748' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Venganur', lgdCode: '222750' },
    { district: 'CUDDALORE', block: 'MANGALUR', name: 'Vinayaganandal', lgdCode: '222751' },
    { district: 'CUDDALORE', block: 'SRIMUSHNAM', name: 'Essanur', lgdCode: '222471' },
    { district: 'CUDDALORE', block: 'SRIMUSHNAM', name: 'Kallipadi', lgdCode: '222475' },
    { district: 'CUDDALORE', block: 'SRIMUSHNAM', name: 'Kandiyankuppam', lgdCode: '222477' },
    { district: 'CUDDALORE', block: 'SRIMUSHNAM', name: 'Kokkarasanpettai', lgdCode: '222482' },
    { district: 'CUDDALORE', block: 'SRIMUSHNAM', name: 'Kozhai', lgdCode: '222485' },
    { district: 'CUDDALORE', block: 'SRIMUSHNAM', name: 'Gunamangalam', lgdCode: '222472' },
    { district: 'CUDDALORE', block: 'SRIMUSHNAM', name: 'Madhakalirmanickam', lgdCode: '222490' },
    { district: 'CUDDALORE', block: 'SRIMUSHNAM', name: 'Melpuliyangudi', lgdCode: '222494' },
    { district: 'CUDDALORE', block: 'SRIMUSHNAM', name: 'Nagarapadi', lgdCode: '222498' },
    { district: 'CUDDALORE', block: 'SRIMUSHNAM', name: 'Sriadhivaraganallur', lgdCode: '222507' },
    { district: 'CUDDALORE', block: 'SRIMUSHNAM', name: 'Srineduncheri', lgdCode: '222508' },
    { district: 'CUDDALORE', block: 'SRIMUSHNAM', name: 'Sriputhur', lgdCode: '222509' },
    { district: 'CUDDALORE', block: 'SRIMUSHNAM', name: 'Theethampattu', lgdCode: '222511' },
    { district: 'CUDDALORE', block: 'SRIMUSHNAM', name: 'Gudalaiyathur', lgdCode: '222526' },
    { district: 'CUDDALORE', block: 'SRIMUSHNAM', name: 'Kaanur', lgdCode: '222528' },
    { district: 'CUDDALORE', block: 'SRIMUSHNAM', name: 'Kavalakudi', lgdCode: '222532' },
    { district: 'CUDDALORE', block: 'SRIMUSHNAM', name: 'Kothandavilagam', lgdCode: '222537' },
    { district: 'CUDDALORE', block: 'SRIMUSHNAM', name: 'Kumarakudi', lgdCode: '222538' },
    { district: 'CUDDALORE', block: 'SRIMUSHNAM', name: 'Mazhavarayanallur', lgdCode: '222540' },
    { district: 'CUDDALORE', block: 'SRIMUSHNAM', name: 'Mudikandanallur', lgdCode: '222541' },
    { district: 'CUDDALORE', block: 'SRIMUSHNAM', name: 'Nandeeswaramangalam', lgdCode: '222543' },
    { district: 'CUDDALORE', block: 'SRIMUSHNAM', name: 'Nangudi', lgdCode: '222544' },
    { district: 'CUDDALORE', block: 'SRIMUSHNAM', name: 'Palayankottai Keel', lgdCode: '222547' },
    { district: 'CUDDALORE', block: 'SRIMUSHNAM', name: 'Palayankottai Mel', lgdCode: '222548' },
    { district: 'CUDDALORE', block: 'SRIMUSHNAM', name: 'Perur', lgdCode: '222553' },
    { district: 'CUDDALORE', block: 'SRIMUSHNAM', name: 'Pudaiyur', lgdCode: '222555' },
    { district: 'CUDDALORE', block: 'SRIMUSHNAM', name: 'Ramapuram', lgdCode: '222557' },
    { district: 'CUDDALORE', block: 'SRIMUSHNAM', name: 'Sozhatharam', lgdCode: '222562' },
    { district: 'CUDDALORE', block: 'SRIMUSHNAM', name: 'Vadakkupalayam', lgdCode: '222571' },
    { district: 'CUDDALORE', block: 'SRIMUSHNAM', name: 'Valasakkadu', lgdCode: '222573' },
    { district: 'CUDDALORE', block: 'SRIMUSHNAM', name: 'Vattathur', lgdCode: '222574' },
    { district: 'CUDDALORE', block: 'SRIMUSHNAM', name: 'Devangudi', lgdCode: '222413' },
    { district: 'CUDDALORE', block: 'SRIMUSHNAM', name: 'Karmangudi', lgdCode: '222421' },
    { district: 'CUDDALORE', block: 'SRIMUSHNAM', name: 'Kavanur', lgdCode: '222422' },
    { district: 'CUDDALORE', block: 'SRIMUSHNAM', name: 'Keelapalaiyur', lgdCode: '222423' },
    { district: 'CUDDALORE', block: 'SRIMUSHNAM', name: 'C. Keeranur', lgdCode: '222412' },
    { district: 'CUDDALORE', block: 'SRIMUSHNAM', name: 'Marugur', lgdCode: '222434' },
    { district: 'CUDDALORE', block: 'SRIMUSHNAM', name: 'Melapalaiyur', lgdCode: '222435' },
    { district: 'CUDDALORE', block: 'SRIMUSHNAM', name: 'T. Pavazhangudi', lgdCode: '222454' },
    { district: 'CUDDALORE', block: 'SRIMUSHNAM', name: 'K. Thozhur', lgdCode: '222455' },
    { district: 'CUDDALORE', block: '