
import type { Panchayat } from './types';

export const KALLAKURICHI_PANCHAYATS: Panchayat[] = [
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'ALUR', lgdCode: '233685' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'ARIYUR', lgdCode: '233686' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'ARUMBAKKAM', lgdCode: '233687' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'ARUTHANGUDI', lgdCode: '233688' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'ATHANDAMARUDHUR', lgdCode: '233689' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'AVI.KOLAPAKKAM', lgdCode: '233690' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'AVIYUR', lgdCode: '233691' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'SOLAVANDIPURAM', lgdCode: '233725' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'DEVIAGARAM', lgdCode: '233692' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'EDAIYUR', lgdCode: '233693' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'ELRAMPATTU', lgdCode: '233694' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'ERAVALLAM', lgdCode: '233695' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'KADIYAR', lgdCode: '233697' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'KANAKANANDAL', lgdCode: '233698' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'KARADI', lgdCode: '233699' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'KATTUPAIYUR', lgdCode: '233700' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'KEELATHALANUR', lgdCode: '233701' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'KEERANUR .T', lgdCode: '233702' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'KODIYUR', lgdCode: '233703' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'KOLAPARAI', lgdCode: '233704' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'KOMALUR', lgdCode: '233705' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'KONAKKALAVADI', lgdCode: '233706' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'KOOVANUR', lgdCode: '233707' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'MADAMPOONDI', lgdCode: '233708' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'MELATHALANUR', lgdCode: '233709' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'MEMALUR', lgdCode: '233710' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'MOHALAR', lgdCode: '233711' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'D.MUDIYANUR', lgdCode: '233712' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'MUTHALUR', lgdCode: '233713' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'NARIYANTHAL', lgdCode: '233714' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'NEDUMUDAIYAN', lgdCode: '233715' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'PADIYANTHAL', lgdCode: '233716' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'PANAPPADI', lgdCode: '233717' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'PAZHANGUR', lgdCode: '233718' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'PERIYANUR', lgdCode: '233719' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'PO.MEIYUR', lgdCode: '233720' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'PONNIYANTHAL', lgdCode: '233721' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'POOMARI', lgdCode: '233722' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'SANGHIYAM', lgdCode: '233723' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'SENGANANKOLLAI', lgdCode: '233724' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'JA. SITHAMOOR', lgdCode: '233696' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'THAGADI', lgdCode: '233726' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'THANAKANANTHAL', lgdCode: '233727' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'THIMMACHUR', lgdCode: '233728' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'THIRUPALAPANDHAL', lgdCode: '233729' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'THURINJIPATTU', lgdCode: '233730' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'VADAKKUNEMILY', lgdCode: '233731' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'VADAMALAYANUR', lgdCode: '233732' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'VADAMARUDHUR', lgdCode: '233733' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'VEERATAGARAM', lgdCode: '233734' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'VENGUR', lgdCode: '233735' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'VILLIVALAM', lgdCode: '233736' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'ATHIPAKKAM .T', lgdCode: '233393' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'SADAIKATTI', lgdCode: '233431' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'KOZHUNTHIRAMPAATU', lgdCode: '233414' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'KULADEEPAMANGALAM', lgdCode: '233415' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'KALUMALAM', lgdCode: '233404' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'NEDUNGAMPATTU', lgdCode: '233424' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'VILANTHAI', lgdCode: '233446' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'SORAIYAPATTU', lgdCode: '233437' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'ANDIKUZHI', lgdCode: '233737' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'ARINATHAM', lgdCode: '233738' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'ADHANUR', lgdCode: '233739' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'ATHUR', lgdCode: '233740' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'DEVIYANANDAL', lgdCode: '233741' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'ESWARAKANDANALLUR', lgdCode: '233742' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'IRUNDHAI', lgdCode: '233743' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'KALAMARUDHUR', lgdCode: '233744' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'KALAVANUR', lgdCode: '233745' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'KAMPATTU', lgdCode: '233746' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'KILAKKUMARUDHUR', lgdCode: '233747' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'KOOVAGAM', lgdCode: '233748' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'KORATTUR', lgdCode: '233749' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'KU. KALLAKURICHI', lgdCode: '233750' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'A.KURUMBUR', lgdCode: '233751' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'MADAPPATTU', lgdCode: '233752' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'MATHIYANUR', lgdCode: '233753' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'MEPULIYUR', lgdCode: '233754' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'METTATHUR', lgdCode: '233755' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'NACHIYARPET', lgdCode: '233756' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'NAGAR', lgdCode: '233757' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'NANNARAM', lgdCode: '233758' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'NEMILI .U', lgdCode: '233759' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'ODAIYANANDAL', lgdCode: '233760' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'ODAPPANKUPPAM', lgdCode: '233761' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'ORATHUR .T', lgdCode: '233762' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'PA. KILLANUR', lgdCode: '233763' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'PADHUR', lgdCode: '233764' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'PANDUR', lgdCode: '254897' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'PARIKKAL', lgdCode: '233765' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'PERUMBAKKAM', lgdCode: '233766' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'PERUMPATTU', lgdCode: '233767' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'PU. MAMPAKKAM', lgdCode: '233769' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'SEMMANANDAL', lgdCode: '233770' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'SEMMANANGOOR', lgdCode: '233771' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'SENDAMANGALAM', lgdCode: '233772' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'SENDANADU', lgdCode: '233773' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'SENGURICHI', lgdCode: '233774' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'SIRULAPATTU', lgdCode: '233775' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'SIRUTHANUR', lgdCode: '233776' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'SOMASIPALAYAM', lgdCode: '233777' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'THIRUNAVALUR', lgdCode: '233778' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'VANAMPATTU', lgdCode: '233779' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'VELUR', lgdCode: '233780' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'A. Athipakkam', lgdCode: '233781' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Alangiri', lgdCode: '233782' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Anganur', lgdCode: '233783' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Asanur', lgdCode: '233784' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Athaiyur', lgdCode: '233785' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Dhamal', lgdCode: '233827' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Ellaigiramam', lgdCode: '233787' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Emam', lgdCode: '233788' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Eraiyur', lgdCode: '233789' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Gunamangalam', lgdCode: '233790' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Kattuedayar', lgdCode: '233791' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Kattunemily', lgdCode: '233792' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Kattusellur', lgdCode: '233793' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Kiliyur', lgdCode: '233794' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Kolathur. A', lgdCode: '233795' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Koothanur', lgdCode: '233796' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Koovadu', lgdCode: '233797' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Kumaramangalam. A', lgdCode: '233798' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Kunjaram', lgdCode: '233799' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Kunnathur. M', lgdCode: '233800' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Mazhavarayanur. A', lgdCode: '233801' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Moolasamuthiram', lgdCode: '233802' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Neivanai', lgdCode: '233803' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Nathamoor', lgdCode: '233804' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Nedumanur', lgdCode: '233805' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Nonaiyavadi', lgdCode: '233806' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Pali', lgdCode: '233807' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Pallavadi', lgdCode: '233808' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Parinthal', lgdCode: '233809' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Periyakurukkai', lgdCode: '233810' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Pidagam', lgdCode: '233811' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Pinnalvadi', lgdCode: '233812' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Pu. Killanur', lgdCode: '233813' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Pu. Konalavadi', lgdCode: '233814' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Pu. Malayanur', lgdCode: '233815' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Pugaipatti', lgdCode: '233816' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Pullur', lgdCode: '233817' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Puthamangalam', lgdCode: '233818' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'R. R. Kuppam', lgdCode: '233819' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Sathanur. A', lgdCode: '233820' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Seekkampattu', lgdCode: '233821' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Sembimadevi', lgdCode: '233822' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'S. Malayanur', lgdCode: '254898' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Sikkadu', lgdCode: '233824' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Sirupakkam', lgdCode: '233825' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Seedevi', lgdCode: '233826' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Thanam', lgdCode: '233786' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Thenkunam', lgdCode: '233828' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Thiruppaiyar', lgdCode: '233829' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Vadakurumbur', lgdCode: '233830' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Vadamambakkam', lgdCode: '233831' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Veeramangalam', lgdCode: '233832' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Vellaiyur', lgdCode: '233833' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'AGARAKOTTALAM', lgdCode: '233026' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'KA. ALAMBALAM', lgdCode: '233032' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'ALATHUR', lgdCode: '233027' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'ARIYAPERUMANUR', lgdCode: '233028' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'KA. CHELLAMPATTU', lgdCode: '233033' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'EDUTHAVAINATHAM', lgdCode: '233029' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'ERAVAR', lgdCode: '233030' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'INDILI', lgdCode: '233031' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'KARADICHITHUR', lgdCode: '233035' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'KATTANANDAL', lgdCode: '233036' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'MADHAVACHEERY', lgdCode: '233037' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'MADUR', lgdCode: '233038' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'MALAIKOTTALAM', lgdCode: '233039' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'KA. MAMANANDAL', lgdCode: '233034' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'MANMALAI', lgdCode: '233040' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'MATHUR', lgdCode: '233041' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'MELUR', lgdCode: '233042' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'MOHUR', lgdCode: '233043' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'NEELAMANGALAM', lgdCode: '233044' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'NIRAIMATHI', lgdCode: '233045' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'PALAYAM .V', lgdCode: '233046' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'PALRAMPATTU', lgdCode: '233047' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'PARAMANATHAM', lgdCode: '233048' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'PARIGAM', lgdCode: '233049' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'PERUMANGALAM', lgdCode: '233050' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'PERUVANGUR', lgdCode: '233051' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'PORPADAKURICHI', lgdCode: '233052' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'PUKKIRAVARI', lgdCode: '233053' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'RENGANATHAPURAM', lgdCode: '233054' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'SEMBADAKURICHI', lgdCode: '233055' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'SIRUMANGALAM', lgdCode: '233056' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'SIRUVANGUR', lgdCode: '233057' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'SIRUVATHUR', lgdCode: '233058' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'SOMANDARGUDI', lgdCode: '233059' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'THANDALAI', lgdCode: '233060' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'THATCHUR', lgdCode: '233061' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'THAVADIPATTU', lgdCode: '233062' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'THENKEERANUR', lgdCode: '233063' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'THENTHORASALUR', lgdCode: '233064' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'VANAVAREDDY', lgdCode: '233065' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'VANIYANDAL', lgdCode: '233066' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'VANNANJUR .M', lgdCode: '233067' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'VARADAPPANUR', lgdCode: '233068' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'VEERASOLAPURAM', lgdCode: '233069' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'VILAMBAR', lgdCode: '233070' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'VINAITHEERTHAPURAM', lgdCode: '233071' },
    { district: 'KALLAKURICHI', block: 'CHINNASALEM', name: 'ALAMABALAM .V', lgdCode: '232916' },
    { district: 'KALLAKURICHI', block: 'CHINNASALEM', name: 'AMMAIYAGARAM', lgdCode: '232917' },
    { district: 'KALLAKURICHI', block: 'CHINNASALEM', name: 'AMMAKALATHUR', lgdCode: '232918' },
    { district: 'KALLAKURICHI', block: 'CHINNASALEM', name: 'ANUMANANDAL', lgdCode: '232919' },
    { district: 'KALLAKURICHI', block: 'CHINNASALEM', name: 'BANGARAM', lgdCode: '232920' },
    { district: 'KALLAKURICHI', block: 'CHINNASALEM', name: 'ELAVADI', lgdCode: '232921' },
    { district: 'KALLAKURICHI', block: 'CHINNASALEM', name: 'ELIYATHUR', lgdCode: '232922' },
    { district: 'KALLAKURICHI', block: 'CHINNASALEM', name: 'ERIYUR', lgdCode: '232923' },
    { district: 'KALLAKURICHI', block: 'CHINNASALEM', name: 'ERVAIPATTINAM', lgdCode: '232924' },
    { district: 'KALLAKURICHI', block: 'CHINNASALEM', name: 'ESANTHAI', lgdCode: '232925' },
    { district: 'KALLAKURICHI', block: 'CHINNASALEM', name: 'KADATHUR', lgdCode: '232926' },
    { district: 'KALLAKURICHI', block: 'CHINNASALEM', name: 'KALASAMUDRAM', lgdCode: '232927' },
    { district: 'KALLAKURICHI', block: 'CHINNASALEM', name: 'KALLANATHAM', lgdCode: '232928' },
    { district: 'KALLAKURICHI', block: 'CHINNASALEM', name: 'KANIYAMOOR', lgdCode: '232929' },
    { district: 'KALLAKURICHI', block: 'CHINNASALEM', name: 'KARANUR', lgdCode: '232930' },
    { district: 'KALLAKURICHI', block: 'CHINNASALEM', name: 'KARUNDHALAKURICHI', lgdCode: '232932' },
    { district: 'KALLAKURICHI', block: 'CHINNASALEM', name: 'KARUNKUZHI', lgdCode: '232931' },
    { district: 'KALLAKURICHI', block: 'CHINNASALEM', name: 'KOOGAIYUR', lgdCode: '232933' },
    { district: 'KALLAKURICHI', block: 'CHINNASALEM', name: 'KUDIRAICHANDAL', lgdCode: '232934' },
    { district: 'KALLAKURICHI', block: 'CHINNASALEM', name: 'KURAL', lgdCode: '232935' },
    { district: 'KALLAKURICHI', block: 'CHINNASALEM', name: 'MAMANDUR .V', lgdCode: '232936' },
    { district: 'KALLAKURICHI', block: 'CHINNASALEM', name: 'MATTIGAIKURICHI', lgdCode: '232937' },
    { district: 'KALLAKURICHI', block: 'CHINNASALEM', name: 'MELNARIYAPPANUR', lgdCode: '232938' },
    { district: 'KALLAKURICHI', block: 'CHINNASALEM', name: 'MOONGILPADI', lgdCode: '232939' },
    { district: 'KALLAKURICHI', block: 'CHINNASALEM', name: 'NAGAKUPPAM', lgdCode: '232940' },
    { district: 'KALLAKURICHI', block: 'CHINNASALEM', name: 'NAINARPALAYAM', lgdCode: '232941' },
    { district: 'KALLAKURICHI', block: 'CHINNASALEM', name: 'NALLATHUR', lgdCode: '232942' },
    { district: 'KALLAKURICHI', block: 'CHINNASALEM', name: 'NAMACHIVAYAPURAM', lgdCode: '232943' },
    { district: 'KALLAKURICHI', block: 'CHINNASALEM', name: 'PAITHANTHURAI', lgdCode: '232944' },
    { district: 'KALLAKURICHI', block: 'CHINNASALEM', name: 'PAKKAMBADI', lgdCode: '232945' },
    { district: 'KALLAKURICHI', block: 'CHINNASALEM', name: 'PANDIYANKUPPAM', lgdCode: '232946' },
    { district: 'KALLAKURICHI', block: 'CHINNASALEM', name: 'PETHANUR', lgdCode: '232947' },
    { district: 'KALLAKURICHI', block: 'CHINNASALEM', name: 'PETHASAMUDRAM', lgdCode: '232948' },
    { district: 'KALLAKURICHI', block: 'CHINNASALEM', name: 'POONDI', lgdCode: '232949' },
    { district: 'KALLAKURICHI', block: 'CHINNASALEM', name: 'RAYAPPANUR', lgdCode: '232950' },
    { district: 'KALLAKURICHI', block: 'CHINNASALEM', name: 'RAYARPALAYAM', lgdCode: '232951' },
    { district: 'KALLAKURICHI', block: 'CHINNASALEM', name: 'SADAYAMPATTU', lgdCode: '232952' },
    { district: 'KALLAKURICHI', block: 'CHINNASALEM', name: 'SEMBAKURICHI', lgdCode: '232953' },
    { district: 'KALLAKURICHI', block: 'CHINNASALEM', name: 'THAGAMTHEERTHAPURAM', lgdCode: '232954' },
    { district: 'KALLAKURICHI', block: 'CHINNASALEM', name: 'THAGARAI', lgdCode: '232955' },
    { district: 'KALLAKURICHI', block: 'CHINNASALEM', name: 'THENCHETTIYANDAL', lgdCode: '232956' },
    { district: 'KALLAKURICHI', block: 'CHINNASALEM', name: 'THENGIYANATHAM', lgdCode: '232957' },
    { district: 'KALLAKURICHI', block: 'CHINNASALEM', name: 'THENSIRUVALUR', lgdCode: '232958' },
    { district: 'KALLAKURICHI', block: 'CHINNASALEM', name: 'THIMMAPURAM', lgdCode: '232959' },
    { district: 'KALLAKURICHI', block: 'CHINNASALEM', name: 'THOTTAPADI', lgdCode: '232960' },
    { district: 'KALLAKURICHI', block: 'CHINNASALEM', name: 'THOTTIAM', lgdCode: '232961' },
    { district: 'KALLAKURICHI', block: 'CHINNASALEM', name: 'ULAGANKATHAN', lgdCode: '232962' },
    { district: 'KALLAKURICHI', block: 'CHINNASALEM', name: 'ULAGIYANALLUR', lgdCode: '232963' },
    { district: 'KALLAKURICHI', block: 'CHINNASALEM', name: 'VASUDEVANUR .A', lgdCode: '232965' },
    { district: 'KALLAKURICHI', block: 'CHINNASALEM', name: 'V.P.AGARAM', lgdCode: '232964' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'Andhiyur', lgdCode: '233499' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'Ariyalur', lgdCode: '233500' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'Arckavadi', lgdCode: '233501' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'Arumbarampattu', lgdCode: '233502' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'Athiyur', lgdCode: '233503' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'Aviriyur', lgdCode: '233504' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'Eduthanur', lgdCode: '233505' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'Elayanarkuppam', lgdCode: '233506' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'Erudaiyampattu', lgdCode: '233508' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'Endhal', lgdCode: '233507' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'Jambadai', lgdCode: '233509' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'Kadambur', lgdCode: '233510' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'Kaduvanur', lgdCode: '233511' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'Kallipadi', lgdCode: '233512' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'Kanankadu', lgdCode: '233513' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'Karaiyampalayam', lgdCode: '233514' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'Keelpadi', lgdCode: '233515' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'Kunniyur', lgdCode: '233516' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'La. Gudalore', lgdCode: '233517' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'Maiyanur', lgdCode: '233518' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'Mandagapadi', lgdCode: '233519' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'Maniyandhal', lgdCode: '233520' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'Marur', lgdCode: '233521' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'Melaplangur', lgdCode: '233522' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'Muttiyam', lgdCode: '233524' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'Munivalai', lgdCode: '233523' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'Noorolai', lgdCode: '233525' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'Odiyandhal', lgdCode: '233526' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'Pakkam', lgdCode: '233527' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'Palayasiruvangur', lgdCode: '233528' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'Pallipattu', lgdCode: '233529' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'Pasar', lgdCode: '233530' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'Pavandhur', lgdCode: '233531' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'Peral', lgdCode: '233532' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'Periyakolliyur', lgdCode: '233533' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'Periyapagandai', lgdCode: '233534' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'Porpalampattu', lgdCode: '233536' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'Pirividayampattu', lgdCode: '233535' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'Rishivandiyam', lgdCode: '233537' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'Sathaputhur', lgdCode: '233538' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'Seerpathanallur', lgdCode: '233540' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'Seerpanandhal', lgdCode: '233539' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'Sirupanaiyur', lgdCode: '233541' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'Sithal', lgdCode: '233542' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'Soolankurichi', lgdCode: '233543' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'Suthamalai', lgdCode: '233544' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'Tholuvanthangal', lgdCode: '233546' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'Thiruvarangam', lgdCode: '233545' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'Vadamamandhur', lgdCode: '233547' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'Vanapuram', lgdCode: '233548' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'Vengalam', lgdCode: '233550' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'Velanandhal', lgdCode: '233549' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'Yal', lgdCode: '233551' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'ATHIYANTHAL', lgdCode: '233394' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'DEVARADIYARKUPPAM', lgdCode: '233397' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'JAMBAI', lgdCode: '233400' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'KANGIYANUR', lgdCode: '233406' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'MELANTHAL', lgdCode: '233419' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'MURUKKAMPADY', lgdCode: '233422' },
    { district: 'KALLAKURICHI', block: 'RISHIVANDIYAM', name: 'CHITHAPATTINAM', lgdCode: '233435' },
    { district: 'KALLAKURICHI', block: 'SANKARAPURAM', name: 'ARASAMPATTU', lgdCode: '233552' },
    { district: 'KALLAKURICHI', block: 'SANKARAPURAM', name: 'ARULAMPADI', lgdCode: '233553' },
    { district: 'KALLAKURICHI', block: 'SANKARAPURAM', name: 'ARUR', lgdCode: '233554' },
    { district: 'KALLAKURICHI', block: 'SANKARAPURAM', name: 'BIRAMAKUNDAM', lgdCode: '233555' },
    { district: 'KALLAKURICHI', block: 'SANKARAPURAM', name: 'DEVAPANDALAM', lgdCode: '233557' },
    { district: 'KALLAKURICHI', block: 'SANKARAPURAM', name: 'KEELAPATTU', lgdCode: '233558' },
    { district: 'KALLAKURICHI', block: 'SANKARAPURAM', name: 'KIDAINGKUDAYANPATTU', lgdCode: '233559' },
    { district: 'KALLAKURICHI', block: 'SANKARAPURAM', name: 'KOSAPADI', lgdCode: '233560' },
    { district: 'KALLAKURICHI', block: 'SANKARAPURAM', name: 'KULATHUR .S', lgdCode: '233561' },
    { district: 'KALLAKURICHI', block: 'SANKARAPURAM', name: 'LACKYNAIKKANPATI', lgdCode: '233562' },
    { district: 'KALLAKURICHI', block: 'SANKARAPURAM', name: 'MANALUR', lgdCode: '233563' },
    { district: 'KALLAKURICHI', block: 'SANKARAPURAM', name: 'MANJAPUTHUR', lgdCode: '233564' },
    { district: 'KALLAKURICHI', block: 'SANKARAPURAM', name: 'MELAPATTU', lgdCode: '233565' },
    { district: 'KALLAKURICHI', block: 'SANKARAPURAM', name: 'MELSIRUVALUR', lgdCode: '233566' },
    { district: 'KALLAKURICHI', block: 'SANKARAPURAM', name: 'MOOKANUR', lgdCode: '233567' },
    { district: 'KALLAKURICHI', block: 'SANKARAPURAM', name: 'MOONGILTHURIPATTU', lgdCode: '233568' },
    { district: 'KALLAKURICHI', block: 'SANKARAPURAM', name: 'MURARPADU', lgdCode: '233569' },
    { district: 'KALLAKURICHI', block: 'SANKARAPURAM', name: 'NEDUMANUR', lgdCode: '233570' },
    { district: 'KALLAKURICHI', block: 'SANKARAPURAM', name: 'SOUNDIRAVALLIPALAYAM', lgdCode: '233583' },
    { district: 'KALLAKURICHI', block: 'SANKARAPURAM', name: 'PALAYANUR', lgdCode: '233572' },
    { district: 'KALLAKURICHI', block: 'SANKARAPURAM', name: 'PANDALAM .A', lgdCode: '233573' },
    { district: 'KALLAKURICHI', block: 'SANKARAPURAM', name: 'POIKUNAM', lgdCode: '233574' },
    { district: 'KALLAKURICHI', block: 'SANKARAPURAM', name: 'POOTAI', lgdCode: '233575' },
    { district: 'KALLAKURICHI', block: 'SANKARAPURAM', name: 'PORASAPATTU', lgdCode: '233576' },
    { district: 'KALLAKURICHI', block: 'SANKARAPURAM', name: 'POUNJIPATTU', lgdCode: '233577' },
    { district: 'KALLAKURICHI', block: 'SANKARAPURAM', name: 'PUDUPATTU', lgdCode: '233578' },
    { district: 'KALLAKURICHI', block: 'SANKARAPURAM', name: 'PUTHIRAMPATTU', lgdCode: '233579' },
    { district: 'KALLAKURICHI', block: 'SANKARAPURAM', name: 'RAMARAJAPURAM', lgdCode: '233580' },
    { district: 'KALLAKURICHI', block: 'SANKARAPURAM', name: 'RANGAPPANUR', lgdCode: '233581' },
    { district: 'KALLAKURICHI', block: 'SANKARAPURAM', name: 'RAVATHANALLUR', lgdCode: '233582' },
    { district: 'KALLAKURICHI', block: 'SANKARAPURAM', name: 'SELLAMPATTU', lgdCode: '254901' },
    { district: 'KALLAKURICHI', block: 'SANKARAPURAM', name: 'SEMBARAMPATTU', lgdCode: '233585' },
    { district: 'KALLAKURICHI', block: 'SANKARAPURAM', name: 'SESHASAMUTHIRAM', lgdCode: '233586' },
    { district: 'KALLAKURICHI', block: 'SANKARAPURAM', name: 'SOLAMPATTU', lgdCode: '233584' },
    { district: 'KALLAKURICHI', block: 'SANKARAPURAM', name: 'THIYAGARAJAPURAM', lgdCode: '233587' },
    { district: 'KALLAKURICHI', block: 'SANKARAPURAM', name: 'ULAGALAPADI', lgdCode: '233588' },
    { district: 'KALLAKURICHI', block: 'SANKARAPURAM', name: 'URANGANI', lgdCode: '233571' },
    { district: 'KALLAKURICHI', block: 'SANKARAPURAM', name: 'VALAYAMPATTU', lgdCode: '233592' },
    { district: 'KALLAKURICHI', block: 'SANKARAPURAM', name: 'VADACHETTIYANDAL', lgdCode: '233589' },
    { district: 'KALLAKURICHI', block: 'SANKARAPURAM', name: 'VADAKEERANUR', lgdCode: '233594' },
    { district: 'KALLAKURICHI', block: 'SANKARAPURAM', name: 'VADAPONPARAPPI', lgdCode: '233590' },
    { district: 'KALLAKURICHI', block: 'SANKARAPURAM', name: 'VADASIRUVALUR', lgdCode: '233591' },
    { district: 'KALLAKURICHI', block: 'SANKARAPURAM', name: 'VARAGUR', lgdCode: '233593' },
    { district: 'KALLAKURICHI', block: 'SANKARAPURAM', name: 'VIRIYUR', lgdCode: '233595' },
    { district: 'KALLAKURICHI', block: 'THIYAGADURGAM', name: 'ASAKALATHUR', lgdCode: '233596' },
    { district: 'KALLAKURICHI', block: 'THIYAGADURGAM', name: 'CHINNAMAMPATTU', lgdCode: '233597' },
    { district: 'KALLAKURICHI', block: 'THIYAGADURGAM', name: 'ERANJI', lgdCode: '233598' },
    { district: 'KALLAKURICHI', block: 'THIYAGADURGAM', name: 'EYYANUR', lgdCode: '233599' },
    { district: 'KALLAKURICHI', block: 'THIYAGADURGAM', name: 'GURUPEEDAPURAM', lgdCode: '233600' },
    { district: 'KALLAKURICHI', block: 'THIYAGADURGAM', name: 'KANANGUR', lgdCode: '233601' },
    { district: 'KALLAKURICHI', block: 'THIYAGADURGAM', name: 'KANDACHIMANGALAM', lgdCode: '233602' },
    { district: 'KALLAKURICHI', block: 'THIYAGADURGAM', name: 'KATCHAKUDI', lgdCode: '233603' },
    { district: 'KALLAKURICHI', block: 'THIYAGADURGAM', name: 'KONGARAYAPALAYAM', lgdCode: '233604' },
    { district: 'KALLAKURICHI', block: 'THIYAGADURGAM', name: 'KOONTHALUR', lgdCode: '233605' },
    { district: 'KALLAKURICHI', block: 'THIYAGADURGAM', name: 'KOOTHAKUDI', lgdCode: '233606' },
    { district: 'KALLAKURICHI', block: 'THIYAGADURGAM', name: 'KOTTAIYUR', lgdCode: '233607' },
    { district: 'KALLAKURICHI', block: 'THIYAGADURGAM', name: 'KUDIYANALLUR', lgdCode: '233608' },
    { district: 'KALLAKURICHI', block: 'THIYAGADURGAM', name: 'MADAM', lgdCode: '233609' },
    { district: 'KALLAKURICHI', block: 'THIYAGADURGAM', name: 'MELVIZHI', lgdCode: '233610' },
    { district: 'KALLAKURICHI', block: 'THIYAGADURGAM', name: 'MUDIYANUR', lgdCode: '233611' },
    { district: 'KALLAKURICHI', block: 'THIYAGADURGAM', name: 'NAGALUR', lgdCode: '233612' },
    { district: 'KALLAKURICHI', block: 'THIYAGADURGAM', name: 'NINNAIYUR', lgdCode: '233613' },
    { district: 'KALLAKURICHI', block: 'THIYAGADURGAM', name: 'OGAIYUR .S', lgdCode: '233614' },
    { district: 'KALLAKURICHI', block: 'THIYAGADURGAM', name: 'PALLAGACHERRI', lgdCode: '233615' },
    { district: 'KALLAKURICHI', block: 'THIYAGADURGAM', name: 'PANAYANGAL', lgdCode: '233616' },
    { district: 'KALLAKURICHI', block: 'THIYAGADURGAM', name: 'PEELAMEDU', lgdCode: '233617' },
    { district: 'KALLAKURICHI', block: 'THIYAGADURGAM', name: 'PORASAKURICHI', lgdCode: '233618' },
    { district: 'KALLAKURICHI', block: 'THIYAGADURGAM', name: 'PRITHIVIMANGALAM', lgdCode: '233619' },
    { district: 'KALLAKURICHI', block: 'THIYAGADURGAM', name: 'PUDU-UCHIMEDU', lgdCode: '233620' },
    { district: 'KALLAKURICHI', block: 'THIYAGADURGAM', name: 'SATHANUR', lgdCode: '233621' },
    { district: 'KALLAKURICHI', block: 'THIYAGADURGAM', name: 'SIRUNAGALUR', lgdCode: '233622' },
    { district: 'KALLAKURICHI', block: 'THIYAGADURGAM', name: 'SITHALUR', lgdCode: '233623' },
    { district: 'KALLAKURICHI', block: 'THIYAGADURGAM', name: 'SITHATHUR', lgdCode: '233624' },
    { district: 'KALLAKURICHI', block: 'THIYAGADURGAM', name: 'THIMMALAI', lgdCode: '233625' },
    { district: 'KALLAKURICHI', block: 'THIYAGADURGAM', name: 'THIYAGAI', lgdCode: '233626' },
    { district: 'KALLAKURICHI', block: 'THIYAGADURGAM', name: 'UDAYANACHI', lgdCode: '233627' },
    { district: 'KALLAKURICHI', block: 'THIYAGADURGAM', name: 'VADAPOONDI', lgdCode: '233628' },
    { district: 'KALLAKURICHI', block: 'THIYAGADURGAM', name: 'VADATHORASLUR', lgdCode: '233629' },
    { district: 'KALLAKURICHI', block: 'THIYAGADURGAM', name: 'VALAVANTHANKUPPAM', lgdCode: '233630' },
    { district: 'KALLAKURICHI', block: 'THIYAGADURGAM', name: 'VARANJARAM', lgdCode: '233631' },
    { district: 'KALLAKURICHI', block: 'THIYAGADURGAM', name: 'VELAKURICHI', lgdCode: '233632' },
    { district: 'KALLAKURICHI', block: 'THIYAGADURGAM', name: 'VENGAIVADI', lgdCode: '233633' },
    { district: 'KALLAKURICHI', block: 'THIYAGADURGAM', name: 'VILAKKUR', lgdCode: '233634' },
    { district: 'KALLAKURICHI', block: 'THIYAGADURGAM', name: 'VIRUGAVOOR', lgdCode: '233635' },
    { district: 'KALLAKURICHI', block: 'KALRAYAN HILLS', name: 'Arampoondi', lgdCode: '233072' },
    { district: 'KALLAKURICHI', block: 'KALRAYAN HILLS', name: 'Innadu', lgdCode: '233073' },
    { district: 'KALLAKURICHI', block: 'KALRAYAN HILLS', name: 'Kariyalor', lgdCode: '233074' },
    { district: 'KALLAKURICHI', block: 'KALRAYAN HILLS', name: 'Kilakkadu', lgdCode: '233075' },
    { district: 'KALLAKURICHI', block: 'KALRAYAN HILLS', name: 'Kundiyanatham', lgdCode: '233076' },
    { district: 'KALLAKURICHI', block: 'KALRAYAN HILLS', name: 'Maniyarpalayam', lgdCode: '233077' },
    { district: 'KALLAKURICHI', block: 'KALRAYAN HILLS', name: 'Melpacherry', lgdCode: '233078' },
    { district: 'KALLAKURICHI', block: 'KALRAYAN HILLS', name: 'Pacherry', lgdCode: '233079' },
    { district: 'KALLAKURICHI', block: 'KALRAYAN HILLS', name: 'Pottiyam', lgdCode: '233080' },
    { district: 'KALLAKURICHI', block: 'KALRAYAN HILLS', name: 'Serappattu', lgdCode: '233082' },
    { district: 'KALLAKURICHI', block: 'KALRAYAN HILLS', name: 'Thoradipattu', lgdCode: '233083' },
    { district: 'KALLAKURICHI', block: 'KALRAYAN HILLS', name: 'Vellimalai', lgdCode: '233085' },
    { district: 'KALLAKURICHI', block: 'KALRAYAN HILLS', name: 'Vengodu', lgdCode: '233086' },
    { district: 'KALLAKURICHI', block: 'KALRAYAN HILLS', name: 'Vanjikkuli', lgdCode: '233084' },
    { district: 'KALLAKURICHI', block: 'KALRAYAN HILLS', name: 'Pudupalapattu', lgdCode: '233081' }
];

