
import type { Panchayat } from './types';

export const KALLAKURICHI_PANCHAYATS: Panchayat[] = [
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'ALUR', lgdCode: '233685' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'ARIYUR', lgdCode: '233686' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'ARUMBAKKAM', lgdCode: '233687' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'ARUTHANGUDI', lgdCode: '233688' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'ATHANDAMARUDHUR', lgdCode: '233689' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'AVI.KOLAPAKKAM', lgdCode: '233690' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'AVIYUR', lgdCode: '233691' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'SOLAVANDIPURAM', lgdCode: '233725' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'DEVIAGARAM', lgdCode: '233692' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'EDAIYUR', lgdCode: '233693' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'ELRAMPATTU', lgdCode: '233694' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'ERAVALLAM', lgdCode: '233695' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'KADIYAR', lgdCode: '233697' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'KANAKANANDAL', lgdCode: '233698' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'KARADI', lgdCode: '233699' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'KATTUPAIYUR', lgdCode: '233700' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'KEELATHALANUR', lgdCode: '233701' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'KEERANUR .T', lgdCode: '233702' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'KODIYUR', lgdCode: '233703' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'KOLAPARAI', lgdCode: '233704' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'KOMALUR', lgdCode: '233705' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'KONAKKALAVADI', lgdCode: '233706' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'KOOVANUR', lgdCode: '233707' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'MADAMPOONDI', lgdCode: '233708' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'MELATHALANUR', lgdCode: '233709' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'MEMALUR', lgdCode: '233710' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'MOHALAR', lgdCode: '233711' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'D.MUDIYANUR', lgdCode: '233712' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'MUTHALUR', lgdCode: '233713' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'NARIYANTHAL', lgdCode: '233714' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'NEDUMUDAIYAN', lgdCode: '233715' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'PADIYANTHAL', lgdCode: '233716' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'PANAPPADI', lgdCode: '233717' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'PAZHANGUR', lgdCode: '233718' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'PERIYANUR', lgdCode: '233719' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'PO.MEIYUR', lgdCode: '233720' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'PONNIYANTHAL', lgdCode: '233721' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'POOMARI', lgdCode: '233722' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'SANGHIYAM', lgdCode: '233723' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'SENGANANKOLLAI', lgdCode: '233724' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'JA. SITHAMOOR', lgdCode: '233696' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'THAGADI', lgdCode: '233726' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'THANAKANANTHAL', lgdCode: '233727' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'THIMMACHUR', lgdCode: '233728' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'THIRUPALAPANDHAL', lgdCode: '233729' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'THURINJIPATTU', lgdCode: '233730' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'VADAKKUNEMILY', lgdCode: '233731' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'VADAMALAYANUR', lgdCode: '233732' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'VADAMARUDHUR', lgdCode: '233733' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'VEERATAGARAM', lgdCode: '233734' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'VENGUR', lgdCode: '233735' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'VILLIVALAM', lgdCode: '233736' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'ATHIPAKKAM .T', lgdCode: '233393' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'SADAIKATTI', lgdCode: '233431' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'KOZHUNTHIRAMPAATU', lgdCode: '233414' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'KULADEEPAMANGALAM', lgdCode: '233415' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'KALUMALAM', lgdCode: '233404' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'NEDUNGAMPATTU', lgdCode: '233424' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'VILANTHAI', lgdCode: '233446' },
    { district: 'KALLAKURICHI', block: 'TIRUKOILUR', name: 'SORAIYAPATTU', lgdCode: '233437' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'ANDIKUZHI', lgdCode: '233737' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'ARINATHAM', lgdCode: '233738' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'ADHANUR', lgdCode: '233739' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'ATHUR', lgdCode: '233740' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'DEVIYANANDAL', lgdCode: '233741' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'ESWARAKANDANALLUR', lgdCode: '233742' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'IRUNDHAI', lgdCode: '233743' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'KALAMARUDHUR', lgdCode: '233744' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'KALAVANUR', lgdCode: '233745' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'KAMPATTU', lgdCode: '233746' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'KILAKKUMARUDHUR', lgdCode: '233747' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'KOOVAGAM', lgdCode: '233748' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'KORATTUR', lgdCode: '233749' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'KU. KALLAKURICHI', lgdCode: '233750' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'A.KURUMBUR', lgdCode: '233751' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'MADAPPATTU', lgdCode: '233752' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'MATHIYANUR', lgdCode: '233753' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'MEPULIYUR', lgdCode: '233754' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'METTATHUR', lgdCode: '233755' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'NACHIYARPET', lgdCode: '233756' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'NAGAR', lgdCode: '233757' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'NANNARAM', lgdCode: '233758' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'NEMILI .U', lgdCode: '233759' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'ODAIYANANDAL', lgdCode: '233760' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'ODAPPANKUPPAM', lgdCode: '233761' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'ORATHUR .T', lgdCode: '233762' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'PA. KILLANUR', lgdCode: '233763' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'PADHUR', lgdCode: '233764' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'PANDUR', lgdCode: '254897' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'PARIKKAL', lgdCode: '233765' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'PERUMBAKKAM', lgdCode: '233766' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'PERUMPATTU', lgdCode: '233767' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'PU. MAMPAKKAM', lgdCode: '233769' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'SEMMANANDAL', lgdCode: '233770' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'SEMMANANGOOR', lgdCode: '233771' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'SENDAMANGALAM', lgdCode: '233772' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'SENDANADU', lgdCode: '233773' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'SENGURICHI', lgdCode: '233774' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'SIRULAPATTU', lgdCode: '233775' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'SIRUTHANUR', lgdCode: '233776' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'SOMASIPALAYAM', lgdCode: '233777' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'THIRUNAVALUR', lgdCode: '233778' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'VANAMPATTU', lgdCode: '233779' },
    { district: 'KALLAKURICHI', block: 'TIRUNAVALUR', name: 'VELUR', lgdCode: '233780' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'A. Athipakkam', lgdCode: '233781' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Alangiri', lgdCode: '233782' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Anganur', lgdCode: '233783' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Asanur', lgdCode: '233784' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Athaiyur', lgdCode: '233785' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Dhamal', lgdCode: '233827' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Ellaigiramam', lgdCode: '233787' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Emam', lgdCode: '233788' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Eraiyur', lgdCode: '233789' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Gunamangalam', lgdCode: '233790' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Kattuedayar', lgdCode: '233791' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Kattunemily', lgdCode: '233792' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Kattusellur', lgdCode: '233793' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Kiliyur', lgdCode: '233794' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Kolathur. A', lgdCode: '233795' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Koothanur', lgdCode: '233796' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Koovadu', lgdCode: '233797' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Kumaramangalam. A', lgdCode: '233798' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Kunjaram', lgdCode: '233799' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Kunnathur. M', lgdCode: '233800' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Mazhavarayanur. A', lgdCode: '233801' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Moolasamuthiram', lgdCode: '233802' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Neivanai', lgdCode: '233803' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Nathamoor', lgdCode: '233804' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Nedumanur', lgdCode: '233805' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Nonaiyavadi', lgdCode: '233806' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Pali', lgdCode: '233807' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Pallavadi', lgdCode: '233808' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Parinthal', lgdCode: '233809' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Periyakurukkai', lgdCode: '233810' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Pidagam', lgdCode: '233811' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Pinnalvadi', lgdCode: '233812' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Pu. Killanur', lgdCode: '233813' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Pu. Konalavadi', lgdCode: '233814' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Pu. Malayanur', lgdCode: '233815' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Pugaipatti', lgdCode: '233816' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Pullur', lgdCode: '233817' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Puthamangalam', lgdCode: '233818' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'R. R. Kuppam', lgdCode: '233819' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Sathanur. A', lgdCode: '233820' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Seekkampattu', lgdCode: '233821' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Sembimadevi', lgdCode: '233822' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'S. Malayanur', lgdCode: '254898' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Sikkadu', lgdCode: '233824' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Sirupakkam', lgdCode: '233825' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Seedevi', lgdCode: '233826' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Thanam', lgdCode: '233786' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Thenkunam', lgdCode: '233828' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Thiruppaiyar', lgdCode: '233829' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Vadakurumbur', lgdCode: '233830' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Vadamambakkam', lgdCode: '233831' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Veeramangalam', lgdCode: '233832' },
    { district: 'KALLAKURICHI', block: 'ULUNDURPET', name: 'Vellaiyur', lgdCode: '233833' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'AGARAKOTTALAM', lgdCode: '233026' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'KA. ALAMBALAM', lgdCode: '233032' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'ALATHUR', lgdCode: '233027' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'ARIYAPERUMANUR', lgdCode: '233028' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'KA. CHELLAMPATTU', lgdCode: '233033' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'EDUTHAVAINATHAM', lgdCode: '233029' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'ERAVAR', lgdCode: '233030' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'INDILI', lgdCode: '233031' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'KARADICHITHUR', lgdCode: '233035' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'KATTANANDAL', lgdCode: '233036' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'MADHAVACHEERY', lgdCode: '233037' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'MADUR', lgdCode: '233038' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'MALAIKOTTALAM', lgdCode: '233039' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'KA. MAMANANDAL', lgdCode: '233034' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'MANMALAI', lgdCode: '233040' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'MATHUR', lgdCode: '233041' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'MELUR', lgdCode: '233042' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'MOHUR', lgdCode: '233043' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'NEELAMANGALAM', lgdCode: '233044' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'NIRAIMATHI', lgdCode: '233045' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'PALAYAM .V', lgdCode: '233046' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'PALRAMPATTU', lgdCode: '233047' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'PARAMANATHAM', lgdCode: '233048' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'PARIGAM', lgdCode: '233049' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'PERUMANGALAM', lgdCode: '233050' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'PERUVANGUR', lgdCode: '233051' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'PORPADAKURICHI', lgdCode: '233052' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'PUKKIRAVARI', lgdCode: '233053' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'RENGANATHAPURAM', lgdCode: '233054' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'SEMBADAKURICHI', lgdCode: '233055' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'SIRUMANGALAM', lgdCode: '233056' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'SIRUVANGUR', lgdCode: '233057' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'SIRUVATHUR', lgdCode: '233058' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'SOMANDARGUDI', lgdCode: '233059' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'THANDALAI', lgdCode: '233060' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'THATCHUR', lgdCode: '233061' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'THAVADIPATTU', lgdCode: '233062' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'THENKEERANUR', lgdCode: '233063' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'THENTHORASALUR', lgdCode: '233064' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'VANAVAREDDY', lgdCode: '233065' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'VANIYANDAL', lgdCode: '233066' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'VANNANJUR .M', lgdCode: '233067' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'VARADAPPANUR', lgdCode: '233068' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'VEERASOLAPURAM', lgdCode: '233069' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'VILAMBAR', lgdCode: '233070' },
    { district: 'KALLAKURICHI', block: 'KALLAKURICHI', name: 'VINAITHEERTHAPURAM', lgdCode: '233071' }
];

