
import type { Panchayat } from './types';

export const KANNIYAKUMARI_PANCHAYATS: Panchayat[] = [
    { district: 'KANNIYAKUMARI', block: 'AGASTHEESWARAM', name: 'Eraviputhoor', lgdCode: '224528' },
    { district: 'KANNIYAKUMARI', block: 'AGASTHEESWARAM', name: 'Nalloor', lgdCode: '224534' },
    { district: 'KANNIYAKUMARI', block: 'AGASTHEESWARAM', name: 'Ramapuram', lgdCode: '224537' },
    { district: 'KANNIYAKUMARI', block: 'AGASTHEESWARAM', name: 'Therekalputhoor', lgdCode: '224539' },
    { district: 'KANNIYAKUMARI', block: 'AGASTHEESWARAM', name: 'Panchalingapuram', lgdCode: '224536' },
    { district: 'KANNIYAKUMARI', block: 'AGASTHEESWARAM', name: 'Kulasekarapuram', lgdCode: '224531' },
    { district: 'KANNIYAKUMARI', block: 'AGASTHEESWARAM', name: 'North Thamaraikulam', lgdCode: '224535' },
    { district: 'KANNIYAKUMARI', block: 'AGASTHEESWARAM', name: 'Swamithoppu', lgdCode: '224538' },
    { district: 'KANNIYAKUMARI', block: 'AGASTHEESWARAM', name: 'Leepuram', lgdCode: '224532' },
    { district: 'KANNIYAKUMARI', block: 'AGASTHEESWARAM', name: 'Maharajapuram', lgdCode: '224533' },
    { district: 'KANNIYAKUMARI', block: 'AGASTHEESWARAM', name: 'Kovalam', lgdCode: '224530' },
    { district: 'KANNIYAKUMARI', block: 'AGASTHEESWARAM', name: 'Karumpattoor', lgdCode: '224529' },
    { district: 'KANNIYAKUMARI', block: 'THOVALAI', name: 'Arumanallur', lgdCode: '224607' },
    { district: 'KANNIYAKUMARI', block: 'THOVALAI', name: 'Beemanagari', lgdCode: '224608' },
    { district: 'KANNIYAKUMARI', block: 'THOVALAI', name: 'Chenbagaramanputhoor', lgdCode: '224609' },
    { district: 'KANNIYAKUMARI', block: 'THOVALAI', name: 'Therisanamcope', lgdCode: '224619' },
    { district: 'KANNIYAKUMARI', block: 'THOVALAI', name: 'Erachakulam', lgdCode: '224610' },
    { district: 'KANNIYAKUMARI', block: 'THOVALAI', name: 'Esanthimangalam', lgdCode: '224611' },
    { district: 'KANNIYAKUMARI', block: 'THOVALAI', name: 'Kadukkarai', lgdCode: '224613' },
    { district: 'KANNIYAKUMARI', block: 'THOVALAI', name: 'Kattuputhoor', lgdCode: '224614' },
    { district: 'KANNIYAKUMARI', block: 'THOVALAI', name: 'Madhavalayam', lgdCode: '224615' },
    { district: 'KANNIYAKUMARI', block: 'THOVALAI', name: 'Sahayanagar', lgdCode: '224616' },
    { district: 'KANNIYAKUMARI', block: 'THOVALAI', name: 'Thadikarankonam', lgdCode: '224617' },
    { district: 'KANNIYAKUMARI', block: 'THOVALAI', name: 'Thellanthi', lgdCode: '224618' },
    { district: 'KANNIYAKUMARI', block: 'THOVALAI', name: 'Thidal', lgdCode: '224620' },
    { district: 'KANNIYAKUMARI', block: 'THOVALAI', name: 'Thirupathisaram', lgdCode: '224621' },
    { district: 'KANNIYAKUMARI', block: 'THOVALAI', name: 'Thovalai', lgdCode: '224622' },
    { district: 'KANNIYAKUMARI', block: 'THOVALAI', name: 'Gnalam', lgdCode: '224612' },
    { district: 'KANNIYAKUMARI', block: 'RAJAKKAMANGALAM', name: 'Athikattuvilai', lgdCode: '224578' },
    { district: 'KANNIYAKUMARI', block: 'RAJAKKAMANGALAM', name: 'Elluvilai', lgdCode: '224580' },
    { district: 'KANNIYAKUMARI', block: 'RAJAKKAMANGALAM', name: 'Kaniyakulam', lgdCode: '224581' },
    { district: 'KANNIYAKUMARI', block: 'RAJAKKAMANGALAM', name: 'Melakrishnanputhoor', lgdCode: '224584' },
    { district: 'KANNIYAKUMARI', block: 'RAJAKKAMANGALAM', name: 'Pallanthurai', lgdCode: '224586' },
    { district: 'KANNIYAKUMARI', block: 'RAJAKKAMANGALAM', name: 'Parakkai', lgdCode: '224587' },
    { district: 'KANNIYAKUMARI', block: 'RAJAKKAMANGALAM', name: 'Kesavanputhenthurai', lgdCode: '224582' },
    { district: 'KANNIYAKUMARI', block: 'RAJAKKAMANGALAM', name: 'Manakudi', lgdCode: '224583' },
    { district: 'KANNIYAKUMARI', block: 'RAJAKKAMANGALAM', name: 'Putheri', lgdCode: '224588' },
    { district: 'KANNIYAKUMARI', block: 'RAJAKKAMANGALAM', name: 'Rajakkamangalam', lgdCode: '224589' },
    { district: 'KANNIYAKUMARI', block: 'RAJAKKAMANGALAM', name: 'Melasankarankuzhi', lgdCode: '224585' },
    { district: 'KANNIYAKUMARI', block: 'RAJAKKAMANGALAM', name: 'Dharmapuram', lgdCode: '224579' },
    { district: 'KANNIYAKUMARI', block: 'THUCKALAY', name: 'Chadayamangalam', lgdCode: '224591' },
    { district: 'KANNIYAKUMARI', block: 'THUCKALAY', name: 'Kalkurichi', lgdCode: '224592' },
    { district: 'KANNIYAKUMARI', block: 'THUCKALAY', name: 'Muthalakurichi', lgdCode: '224594' },
    { district: 'KANNIYAKUMARI', block: 'THUCKALAY', name: 'Athivilai', lgdCode: '224590' },
    { district: 'KANNIYAKUMARI', block: 'THUCKALAY', name: 'Maruthoorkurichy', lgdCode: '224593' },
    { district: 'KANNIYAKUMARI', block: 'THUCKALAY', name: 'Nullivilai', lgdCode: '224595' },
    { district: 'KANNIYAKUMARI', block: 'THUCKALAY', name: 'Thickanamcode', lgdCode: '224596' },
    { district: 'KANNIYAKUMARI', block: 'KURUNTHANCODE', name: 'Kakkottuthalai', lgdCode: '224548' },
    { district: 'KANNIYAKUMARI', block: 'KURUNTHANCODE', name: 'Kattimancode', lgdCode: '224549' },
    { district: 'KANNIYAKUMARI', block: 'KURUNTHANCODE', name: 'Kurunthencode', lgdCode: '224550' },
    { district: 'KANNIYAKUMARI', block: 'KURUNTHANCODE', name: 'Thenkarai', lgdCode: '224555' },
    { district: 'KANNIYAKUMARI', block: 'KURUNTHANCODE', name: 'Nettancode', lgdCode: '224552' },
    { district: 'KANNIYAKUMARI', block: 'KURUNTHANCODE', name: 'Thalakulam', lgdCode: '224554' },
    { district: 'KANNIYAKUMARI', block: 'KURUNTHANCODE', name: 'Muttom', lgdCode: '224551' },
    { district: 'KANNIYAKUMARI', block: 'KURUNTHANCODE', name: 'Simoncolony', lgdCode: '224553' },
    { district: 'KANNIYAKUMARI', block: 'KURUNTHANCODE', name: 'Vellichandai', lgdCode: '224556' },
    { district: 'KANNIYAKUMARI', block: 'THIRUVATTAR', name: 'Aruvikkarai', lgdCode: '224597' },
    { district: 'KANNIYAKUMARI', block: 'THIRUVATTAR', name: 'Ayacode', lgdCode: '224598' },
    { district: 'KANNIYAKUMARI', block: 'THIRUVATTAR', name: 'Balamore', lgdCode: '224599' },
    { district: 'KANNIYAKUMARI', block: 'THIRUVATTAR', name: 'Cherukole', lgdCode: '224600' },
    { district: 'KANNIYAKUMARI', block: 'THIRUVATTAR', name: 'Kannanoor', lgdCode: '224601' },
    { district: 'KANNIYAKUMARI', block: 'THIRUVATTAR', name: 'Kumarankudy', lgdCode: '224603' },
    { district: 'KANNIYAKUMARI', block: 'THIRUVATTAR', name: 'Surulacode', lgdCode: '224605' },
    { district: 'KANNIYAKUMARI', block: 'THIRUVATTAR', name: 'Yettacode', lgdCode: '224606' },
    { district: 'KANNIYAKUMARI', block: 'THIRUVATTAR', name: 'Pechiparai', lgdCode: '224604' },
    { district: 'KANNIYAKUMARI', block: 'THIRUVATTAR', name: 'Kattathurai', lgdCode: '224602' },
    { district: 'KANNIYAKUMARI', block: 'KILLIYOOR', name: 'Thippiramalai', lgdCode: '224547' },
    { district: 'KANNIYAKUMARI', block: 'KILLIYOOR', name: 'Paloor', lgdCode: '224546' },
    { district: 'KANNIYAKUMARI', block: 'KILLIYOOR', name: 'Midalam', lgdCode: '224543' },
    { district: 'KANNIYAKUMARI', block: 'KILLIYOOR', name: 'Mathicode', lgdCode: '224542' },
    { district: 'KANNIYAKUMARI', block: 'KILLIYOOR', name: 'Kollenchy', lgdCode: '224541' },
    { district: 'KANNIYAKUMARI', block: 'KILLIYOOR', name: 'Nattalam', lgdCode: '224545' },
    { district: 'KANNIYAKUMARI', block: 'KILLIYOOR', name: 'Enayam Puthenthurai', lgdCode: '224540' },
    { district: 'KANNIYAKUMARI', block: 'KILLIYOOR', name: 'Mullanginavilai', lgdCode: '224544' },
    { district: 'KANNIYAKUMARI', block: 'MUNCHIRAI', name: 'Adaikkakuzhi', lgdCode: '224567' },
    { district: 'KANNIYAKUMARI', block: 'MUNCHIRAI', name: 'Choozal', lgdCode: '224568' },
    { district: 'KANNIYAKUMARI', block: 'MUNCHIRAI', name: 'Kulappuram', lgdCode: '224569' },
    { district: 'KANNIYAKUMARI', block: 'MUNCHIRAI', name: 'MUNCHIRAI', lgdCode: '224572' },
    { district: 'KANNIYAKUMARI', block: 'MUNCHIRAI', name: 'Mankadu', lgdCode: '224570' },
    { district: 'KANNIYAKUMARI', block: 'MUNCHIRAI', name: 'Nadaikavu', lgdCode: '224573' },
    { district: 'KANNIYAKUMARI', block: 'MUNCHIRAI', name: 'Vavarai', lgdCode: '224576' },
    { district: 'KANNIYAKUMARI', block: 'MUNCHIRAI', name: 'Thoothoor', lgdCode: '224575' },
    { district: 'KANNIYAKUMARI', block: 'MUNCHIRAI', name: 'Methukummal', lgdCode: '224571' },
    { district: 'KANNIYAKUMARI', block: 'MUNCHIRAI', name: 'Vilathurai', lgdCode: '224577' },
    { district: 'KANNIYAKUMARI', block: 'MUNCHIRAI', name: 'Painkulam', lgdCode: '224574' },
    { district: 'KANNIYAKUMARI', block: 'MELPURAM', name: 'Devicode', lgdCode: '224557' },
    { district: 'KANNIYAKUMARI', block: 'MELPURAM', name: 'Malayadi', lgdCode: '224558' },
    { district: 'KANNIYAKUMARI', block: 'MELPURAM', name: 'Mancode', lgdCode: '224560' },
    { district: 'KANNIYAKUMARI', block: 'MELPURAM', name: 'Maruthencode', lgdCode: '224561' },
    { district: 'KANNIYAKUMARI', block: 'MELPURAM', name: 'Manchalumoodu', lgdCode: '224559' },
    { district: 'KANNIYAKUMARI', block: 'MELPURAM', name: 'Muzhucode', lgdCode: '224562' },
    { district: 'KANNIYAKUMARI', block: 'MELPURAM', name: 'Puliyoor Salai', lgdCode: '224563' },
    { district: 'KANNIYAKUMARI', block: 'MELPURAM', name: 'Vanniyoor', lgdCode: '224564' },
    { district: 'KANNIYAKUMARI', block: 'MELPURAM', name: 'Vellamcode', lgdCode: '224565' },
    { district: 'KANNIYAKUMARI', block: 'MELPURAM', name: 'Vilavancode', lgdCode: '224566' },
];

    