
import type { Panchayat } from './types';

export const KARUR_PANCHAYATS: Panchayat[] = [
    { district: 'KARUR', block: 'KARUR', name: 'Authur poolampalayam', lgdCode: '224693' },
    { district: 'KARUR', block: 'KARUR', name: 'Kathaparai', lgdCode: '224695' },
    { district: 'KARUR', block: 'KARUR', name: 'Kombupalayam', lgdCode: '224696' },
    { district: 'KARUR', block: 'KARUR', name: 'Manmangalam', lgdCode: '224698' },
    { district: 'KARUR', block: 'KARUR', name: 'Minnampalli panchamadevi', lgdCode: '224697' },
    { district: 'KARUR', block: 'KARUR', name: 'Nanniyur', lgdCode: '224700' },
    { district: 'KARUR', block: 'KARUR', name: 'N.pugalur', lgdCode: '224699' },
    { district: 'KARUR', block: 'KARUR', name: 'Nerur (south)', lgdCode: '224702' },
    { district: 'KARUR', block: 'KARUR', name: 'Nerur (north)', lgdCode: '224701' },
    { district: 'KARUR', block: 'KARUR', name: 'P.kadambankurichi', lgdCode: '224694' },
    { district: 'KARUR', block: 'KARUR', name: 'Somur', lgdCode: '224703' },
    { district: 'KARUR', block: 'KARUR', name: 'Thirukkaduthurai', lgdCode: '224704' },
    { district: 'KARUR', block: 'KARUR', name: 'Vangal kuppuchipalayam', lgdCode: '224705' },
    { district: 'KARUR', block: 'KARUR', name: 'Vettamangalam', lgdCode: '224706' },
    { district: 'KARUR', block: 'THANTHONI', name: 'Andankoil east', lgdCode: '224743' },
    { district: 'KARUR', block: 'THANTHONI', name: 'Andankoil west', lgdCode: '224744' },
    { district: 'KARUR', block: 'THANTHONI', name: 'Appipalayam', lgdCode: '224745' },
    { district: 'KARUR', block: 'THANTHONI', name: 'Emoor', lgdCode: '224746' },
    { district: 'KARUR', block: 'THANTHONI', name: 'Jegadabi', lgdCode: '224747' },
    { district: 'KARUR', block: 'THANTHONI', name: 'Kakkavadi', lgdCode: '224749' },
    { district: 'KARUR', block: 'THANTHONI', name: 'Karuppampalayam', lgdCode: '224750' },
    { district: 'KARUR', block: 'THANTHONI', name: 'Koyampalli', lgdCode: '224751' },
    { district: 'KARUR', block: 'THANTHONI', name: 'K.Pitchampatti', lgdCode: '224748' },
    { district: 'KARUR', block: 'THANTHONI', name: 'Manavadi', lgdCode: '224752' },
    { district: 'KARUR', block: 'THANTHONI', name: 'Melapalayam', lgdCode: '224753' },
    { district: 'KARUR', block: 'THANTHONI', name: 'Mookkanangkurichi', lgdCode: '224754' },
    { district: 'KARUR', block: 'THANTHONI', name: 'Paganatham', lgdCode: '224755' },
    { district: 'KARUR', block: 'THANTHONI', name: 'Pallapalayam', lgdCode: '224756' },
    { district: 'KARUR', block: 'THANTHONI', name: 'Puthambur', lgdCode: '224757' },
    { district: 'KARUR', block: 'THANTHONI', name: 'Thalapatti', lgdCode: '224758' },
    { district: 'KARUR', block: 'THANTHONI', name: 'Velliyanai', lgdCode: '224759' },
    { district: 'KARUR', block: 'ARAVAKURICHI', name: 'Alamarathupatti', lgdCode: '224623' },
    { district: 'KARUR', block: 'ARAVAKURICHI', name: 'Ammapatti', lgdCode: '224624' },
    { district: 'KARUR', block: 'ARAVAKURICHI', name: 'Esanatham', lgdCode: '224626' },
    { district: 'KARUR', block: 'ARAVAKURICHI', name: 'Erumarpatty', lgdCode: '224625' },
    { district: 'KARUR', block: 'ARAVAKURICHI', name: 'Inanganur', lgdCode: '224627' },
    { district: 'KARUR', block: 'ARAVAKURICHI', name: 'Kodaiyur', lgdCode: '224628' },
    { district: 'KARUR', block: 'ARAVAKURICHI', name: 'Lingamanaikenpatti', lgdCode: '224629' },
    { district: 'KARUR', block: 'ARAVAKURICHI', name: 'Modakkur East', lgdCode: '224630' },
    { district: 'KARUR', block: 'ARAVAKURICHI', name: 'Modakkur West', lgdCode: '224631' },
    { district: 'KARUR', block: 'ARAVAKURICHI', name: 'Nagampalli', lgdCode: '224632' },
    { district: 'KARUR', block: 'ARAVAKURICHI', name: 'Periyamanjuvali', lgdCode: '224633' },
    { district: 'KARUR', block: 'ARAVAKURICHI', name: 'Pungambadi East', lgdCode: '224634' },
    { district: 'KARUR', block: 'ARAVAKURICHI', name: 'Pungambadi West', lgdCode: '224635' },
    { district: 'KARUR', block: 'ARAVAKURICHI', name: 'Santhapadi', lgdCode: '224638' },
    { district: 'KARUR', block: 'ARAVAKURICHI', name: 'Sendamangalam East', lgdCode: '224636' },
    { district: 'KARUR', block: 'ARAVAKURICHI', name: 'Sendamangalam West', lgdCode: '224637' },
    { district: 'KARUR', block: 'ARAVAKURICHI', name: 'Thethupatti', lgdCode: '224639' },
    { district: 'KARUR', block: 'ARAVAKURICHI', name: 'Velambadi', lgdCode: '224640' },
    { district: 'KARUR', block: 'ARAVAKURICHI', name: 'Venjamangudalur East', lgdCode: '224641' },
    { district: 'KARUR', block: 'ARAVAKURICHI', name: 'Venjamangudalur West', lgdCode: '224642' },
    { district: 'KARUR', block: 'K.PARAMATHI', name: 'P.ANAIPALAYAM', lgdCode: '224644' },
    { district: 'KARUR', block: 'K.PARAMATHI', name: 'ANJUR', lgdCode: '224643' },
    { district: 'KARUR', block: 'K.PARAMATHI', name: 'ARIYUR', lgdCode: '224645' },
    { district: 'KARUR', block: 'K.PARAMATHI', name: 'ATHIPALAYAM', lgdCode: '224646' },
    { district: 'KARUR', block: 'K.PARAMATHI', name: 'Chinnadharapuram', lgdCode: '224647' },
    { district: 'KARUR', block: 'K.PARAMATHI', name: 'ELAVANOOR', lgdCode: '224648' },
    { district: 'KARUR', block: 'K.PARAMATHI', name: 'GUDALUR EAST', lgdCode: '224649' },
    { district: 'KARUR', block: 'K.PARAMATHI', name: 'GUDALUR WEST', lgdCode: '224650' },
    { district: 'KARUR', block: 'K.PARAMATHI', name: 'KARVAZHI', lgdCode: '224653' },
    { district: 'KARUR', block: 'K.PARAMATHI', name: 'KARUDAYAMPALAYAM', lgdCode: '224652' },
    { district: 'KARUR', block: 'K.PARAMATHI', name: 'KODANTHUR', lgdCode: '224654' },
    { district: 'KARUR', block: 'K.PARAMATHI', name: 'KUPPAM', lgdCode: '224655' },
    { district: 'KARUR', block: 'K.PARAMATHI', name: 'MUNNUR', lgdCode: '224657' },
    { district: 'KARUR', block: 'K.PARAMATHI', name: 'MONJANUR', lgdCode: '224656' },
    { district: 'KARUR', block: 'K.PARAMATHI', name: 'NADANTHAI', lgdCode: '224658' },
    { district: 'KARUR', block: 'K.PARAMATHI', name: 'Nanjaikalakurichi', lgdCode: '224660' },
    { district: 'KARUR', block: 'K.PARAMATHI', name: 'Nedungur', lgdCode: '224659' },
    { district: 'KARUR', block: 'K.PARAMATHI', name: 'K.PARAMATHI', lgdCode: '224651' },
    { district: 'KARUR', block: 'K.PARAMATHI', name: 'PAVITHIRAM', lgdCode: '224661' },
    { district: 'KARUR', block: 'K.PARAMATHI', name: 'PUNJAIKALAKURICHI', lgdCode: '224662' },
    { district: 'KARUR', block: 'K.PARAMATHI', name: 'PUNNAM', lgdCode: '224663' },
    { district: 'KARUR', block: 'K.PARAMATHI', name: 'RAJAPURAM', lgdCode: '224664' },
    { district: 'KARUR', block: 'K.PARAMATHI', name: 'Soodamani', lgdCode: '224665' },
    { district: 'KARUR', block: 'K.PARAMATHI', name: 'THENNILAI EAST', lgdCode: '224666' },
    { district: 'KARUR', block: 'K.PARAMATHI', name: 'THENNILAI WEST', lgdCode: '224668' },
    { district: 'KARUR', block: 'K.PARAMATHI', name: 'THENNILAI SOUTH', lgdCode: '224667' },
    { district: 'KARUR', block: 'K.PARAMATHI', name: 'THOKKUPATTI', lgdCode: '224669' },
    { district: 'KARUR', block: 'K.PARAMATHI', name: 'THUKKACHI', lgdCode: '224670' },
    { district: 'KARUR', block: 'K.PARAMATHI', name: 'THUMBIVADI', lgdCode: '224671' },
    { district: 'KARUR', block: 'K.PARAMATHI', name: 'VISWANATHAPURI', lgdCode: '224672' },
    { district: 'KARUR', block: 'KULITHALAI', name: 'HIRANYAMANGALAM', lgdCode: '224730' },
    { district: 'KARUR', block: 'KULITHALAI', name: 'INUNGUR', lgdCode: '224731' },
    { district: 'KARUR', block: 'KULITHALAI', name: 'Karuvappanayakenpettai', lgdCode: '224732' },
    { district: 'KARUR', block: 'KULITHALAI', name: 'KUMARAMANGALAM', lgdCode: '224733' },
    { district: 'KARUR', block: 'KULITHALAI', name: 'MANATHATTAI', lgdCode: '224734' },
    { district: 'KARUR', block: 'KULITHALAI', name: 'NALLUR', lgdCode: '224735' },
    { district: 'KARUR', block: 'KULITHALAI', name: 'POYYAMANI', lgdCode: '224736' },
    { district: 'KARUR', block: 'KULITHALAI', name: 'RAJENDRAM', lgdCode: '224737' },
    { district: 'KARUR', block: 'KULITHALAI', name: 'SATHIYAMANGALAM', lgdCode: '224738' },
    { district: 'KARUR', block: 'KULITHALAI', name: 'SURIYANUR', lgdCode: '224739' },
    { district: 'KARUR', block: 'KULITHALAI', name: 'THIMMAMPATTI', lgdCode: '224740' },
    { district: 'KARUR', block: 'KULITHALAI', name: 'Vathiyam', lgdCode: '224742' },
    { district: 'KARUR', block: 'KULITHALAI', name: 'VAIGANALLUR', lgdCode: '224741' },
    { district: 'KARUR', block: 'KRISHNARAYAPURAM', name: 'Balarajapuram', lgdCode: '224707' },
    { district: 'KARUR', block: 'KRISHNARAYAPURAM', name: 'Chinthalavadi', lgdCode: '224708' },
    { district: 'KARUR', block: 'KRISHNARAYAPURAM', name: 'Kallappalli', lgdCode: '224709' },
    { district: 'KARUR', block: 'KRISHNARAYAPURAM', name: 'Kammanallur', lgdCode: '224710' },
    { district: 'KARUR', block: 'KRISHNARAYAPURAM', name: 'Karuppathur', lgdCode: '224711' },
    { district: 'KARUR', block: 'KRISHNARAYAPURAM', name: 'Kosur', lgdCode: '224712' },
    { district: 'KARUR', block: 'KRISHNARAYAPURAM', name: 'Mahadhanapuram', lgdCode: '224713' },
    { district: 'KARUR', block: 'KRISHNARAYAPURAM', name: 'Manavasi', lgdCode: '224714' },
    { district: 'KARUR', block: 'KRISHNARAYAPURAM', name: 'Mathagiri', lgdCode: '224715' },
    { district: 'KARUR', block: 'KRISHNARAYAPURAM', name: 'Mayanur', lgdCode: '224716' },
    { district: 'KARUR', block: 'KRISHNARAYAPURAM', name: 'Muthurengampatti', lgdCode: '224717' },
    { district: 'KARUR', block: 'KRISHNARAYAPURAM', name: 'Panjapatti', lgdCode: '224718' },
    { district: 'KARUR', block: 'KRISHNARAYAPURAM', name: 'Pappakkappatti', lgdCode: '224719' },
    { district: 'KARUR', block: 'KRISHNARAYAPURAM', name: 'Pillapalayam', lgdCode: '224720' },
    { district: 'KARUR', block: 'KRISHNARAYAPURAM', name: 'Pothuravutthanpatti', lgdCode: '224721' },
    { district: 'KARUR', block: 'KRISHNARAYAPURAM', name: 'Renganathapuram', lgdCode: '224722' },
    { district: 'KARUR', block: 'KRISHNARAYAPURAM', name: 'Sengal', lgdCode: '224723' },
    { district: 'KARUR', block: 'KRISHNARAYAPURAM', name: 'Sithalavai', lgdCode: '224724' },
    { district: 'KARUR', block: 'KRISHNARAYAPURAM', name: 'Sivayam', lgdCode: '224725' },
    { district: 'KARUR', block: 'KRISHNARAYAPURAM', name: 'Thirukkampuliyur', lgdCode: '224726' },
    { district: 'KARUR', block: 'KRISHNARAYAPURAM', name: 'Thondamanginam', lgdCode: '224727' },
    { district: 'KARUR', block: 'KRISHNARAYAPURAM', name: 'Vayalur', lgdCode: '224728' },
    { district: 'KARUR', block: 'KRISHNARAYAPURAM', name: 'Veeriyapalayam', lgdCode: '224729' },
    { district: 'KARUR', block: 'KADAVUR', name: 'Adhanur', lgdCode: '224673' },
    { district: 'KARUR', block: 'KADAVUR', name: 'Devarmalai', lgdCode: '224674' },
    { district: 'KARUR', block: 'KADAVUR', name: 'Kadavur', lgdCode: '224675' },
    { district: 'KARUR', block: 'KADAVUR', name: 'Kalayapatti', lgdCode: '224676' },
    { district: 'KARUR', block: 'KADAVUR', name: 'Keelappaguthi', lgdCode: '224677' },
    { district: 'KARUR', block: 'KADAVUR', name: 'Keeranur', lgdCode: '224678' },
    { district: 'KARUR', block: 'KADAVUR', name: 'Manjanaickenpatti', lgdCode: '224679' },
    { district: 'KARUR', block: 'KADAVUR', name: 'Mavathur', lgdCode: '224680' },
    { district: 'KARUR', block: 'KADAVUR', name: 'Melappaguthi', lgdCode: '224681' },
    { district: 'KARUR', block: 'KADAVUR', name: 'Mullipadi', lgdCode: '224682' },
    { district: 'KARUR', block: 'KADAVUR', name: 'Palaviduthi', lgdCode: '224683' },
    { district: 'KARUR', block: 'KADAVUR', name: 'Pappayambadi', lgdCode: '224685' },
    { district: 'KARUR', block: 'KADAVUR', name: 'Pannapatti', lgdCode: '224684' },
    { district: 'KARUR', block: 'KADAVUR', name: 'Sembiyanatham', lgdCode: '224686' },
    { district: 'KARUR', block: 'KADAVUR', name: 'Vadavambadi', lgdCode: '224689' },
    { district: 'KARUR', block: 'KADAVUR', name: 'Valvarmangalam', lgdCode: '224690' },
    { district: 'KARUR', block: 'KADAVUR', name: 'Varavanai', lgdCode: '224691' },
    { district: 'KARUR', block: 'KADAVUR', name: 'Tharagampatti', lgdCode: '224687' },
    { district: 'KARUR', block: 'KADAVUR', name: 'Thennilai', lgdCode: '224688' },
    { district: 'KARUR', block: 'KADAVUR', name: 'Vellapatti', lgdCode: '224692' },
    { district: 'KARUR', block: 'THOGAMALAI', name: 'Alathur', lgdCode: '224760' },
    { district: 'KARUR', block: 'THOGAMALAI', name: 'Archampatti', lgdCode: '224761' },
    { district: 'KARUR', block: 'THOGAMALAI', name: 'Chinnaiyampalayam', lgdCode: '224762' },
    { district: 'KARUR', block: 'THOGAMALAI', name: 'Gudalur', lgdCode: '224763' },
    { district: 'KARUR', block: 'THOGAMALAI', name: 'Kalladai', lgdCode: '224764' },
    { district: 'KARUR', block: 'THOGAMALAI', name: 'Kallai', lgdCode: '224765' },
    { district: 'KARUR', block: 'THOGAMALAI', name: 'Kalugur', lgdCode: '224766' },
    { district: 'KARUR', block: 'THOGAMALAI', name: 'Muthalaipatti', lgdCode: '224767' },
    { district: 'KARUR', block: 'THOGAMALAI', name: 'Naganur', lgdCode: '224768' },
    { district: 'KARUR', block: 'THOGAMALAI', name: 'Neithalur', lgdCode: '224769' },
    { district: 'KARUR', block: 'THOGAMALAI', name: 'Pathiripatti', lgdCode: '224770' },
    { district: 'KARUR', block: 'THOGAMALAI', name: 'Porunthalur', lgdCode: '224772' },
    { district: 'KARUR', block: 'THOGAMALAI', name: 'Pillur', lgdCode: '224771' },
    { district: 'KARUR', block: 'THOGAMALAI', name: 'Pulutheri', lgdCode: '224773' },
    { district: 'KARUR', block: 'THOGAMALAI', name: 'Puthur', lgdCode: '224774' },
    { district: 'KARUR', block: 'THOGAMALAI', name: 'R.t.malai', lgdCode: '224775' },
    { district: 'KARUR', block: 'THOGAMALAI', name: 'Seplapatti', lgdCode: '224776' },
    { district: 'KARUR', block: 'THOGAMALAI', name: 'Thalinji', lgdCode: '224777' },
    { district: 'KARUR', block: 'THOGAMALAI', name: 'Thogaimalai', lgdCode: '224778' },
    { district: 'KARUR', block: 'THOGAMALAI', name: 'Vadaseri', lgdCode: '224779' },
];
