
import type { Panchayat } from './types';

export const MADURAI_PANCHAYATS: Panchayat[] = [
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'ARUMBANUR', lgdCode: '225244' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'AYLIANGUDI', lgdCode: '225245' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'ANGADIMANGALAM', lgdCode: '225243' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'ANDARKOTTARAM', lgdCode: '225242' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'CHINNAMANGULAM', lgdCode: '225246' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'EDAYAPATTI', lgdCode: '225247' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'ELAMANUR', lgdCode: '225248' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'ELANGIYENDAL', lgdCode: '225249' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'ISALANI', lgdCode: '225250' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'KADAIKINARU', lgdCode: '225251' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'KALIMANGLAM', lgdCode: '225252' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'KALLANDIRI', lgdCode: '225253' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'KARSERI', lgdCode: '225254' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'KARUPPAYURANI', lgdCode: '225255' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'KODIKULAM', lgdCode: '225256' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'KUNNATHUR', lgdCode: '225257' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'KURUTHUR', lgdCode: '225258' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'MANGULAM', lgdCode: '225259' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'MEENAKSHIPURAM', lgdCode: '225261' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'NARASINGAM', lgdCode: '225262' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'OTHAKADAI', lgdCode: '225263' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'PANAIKULAM', lgdCode: '225264' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'POOLAMPATTI', lgdCode: '225265' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'PORUSUPATTY', lgdCode: '225266' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'POYYAKARAIPATTY', lgdCode: '225267' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'PUDUPATTI', lgdCode: '225268' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'PUDUTHAMRAIPATTI', lgdCode: '225269' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'RAJAKKUR', lgdCode: '225270' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'SAKKIMANGALAM', lgdCode: '225271' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'SAKKUDI', lgdCode: '225272' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'TAMARAIPATTI', lgdCode: '225273' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'THINDIYUR', lgdCode: '225274' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'TIRUMOHUR', lgdCode: '225275' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'VARICHIYUR', lgdCode: '225276' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'VELLIANKUNDRAM', lgdCode: '225277' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'MATHUR', lgdCode: '225260' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Adalai', lgdCode: '225278' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Alathur', lgdCode: '225279' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Ambalathadi', lgdCode: '225280' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Ariyur', lgdCode: '225281' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Boothagudi', lgdCode: '225282' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Chathrapatti', lgdCode: '225283' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Chettikulam', lgdCode: '225284' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Chinnapatti', lgdCode: '225285' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Eranium', lgdCode: '225286' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Karuvanur', lgdCode: '225288' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Kavanur', lgdCode: '225289' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Kodimangalam', lgdCode: '225290' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Kovilpappakudi', lgdCode: '225291' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Kulamangulam', lgdCode: '225292' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Malaipatti', lgdCode: '225293' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Manjampatti', lgdCode: '225294' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Periyapatti', lgdCode: '225296' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Petchikulam', lgdCode: '225297' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Podumbu', lgdCode: '225298' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Samayanallur', lgdCode: '225299' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Siruvalai', lgdCode: '225300' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Thenur', lgdCode: '225301' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Thodaneri', lgdCode: '225303' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Usilampatti', lgdCode: '225304' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Vagaikulam', lgdCode: '225305' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Vairavanatham', lgdCode: '225306' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Vayaloor', lgdCode: '225307' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Veerapandi', lgdCode: '225308' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Velichanatham', lgdCode: '225309' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Eliyarpathy', lgdCode: '225458' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Earkudi Achampathu', lgdCode: '225459' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Nagamalaipudukottai', lgdCode: '225468' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Nallur', lgdCode: '225469' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Nedumadurai', lgdCode: '225470' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Nilaiyur 1 Bit', lgdCode: '225471' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Nilaiyur 2 Bit', lgdCode: '225472' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Karadipatty', lgdCode: '225460' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Keelakuilkudi', lgdCode: '225461' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Keelamathur', lgdCode: '225462' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Kodimangalam', lgdCode: '225463' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Kombadi', lgdCode: '225464' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Kusavankundu', lgdCode: '225465' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Melamathur', lgdCode: '225467' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Meelakuilkudi', lgdCode: '225466' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Othai Alankulam', lgdCode: '225473' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Periya Alankulam', lgdCode: '225476' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Panaiyur', lgdCode: '225474' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Sholankuruni', lgdCode: '225482' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Soorakkulam', lgdCode: '225483' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Paraipathi', lgdCode: '225475' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Valayapatti', lgdCode: '225489' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Vedarpuliyankulam', lgdCode: '225491' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Perunkudi', lgdCode: '225477' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Puliankulam', lgdCode: '225479' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Pudukulam 1 Bit', lgdCode: '225478' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Sakkilipatti', lgdCode: '225457' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Samanatham', lgdCode: '225480' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Silaiman', lgdCode: '225481' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Thanakkankulam', lgdCode: '225484' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Vilacheri', lgdCode: '225492' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Viraganur', lgdCode: '225493' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Virathanur', lgdCode: '225494' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Thoppur', lgdCode: '225485' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Thuvariman', lgdCode: '225486' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Vadapalanji', lgdCode: '225487' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Vadivelkarai', lgdCode: '225488' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Valaiyankulam', lgdCode: '225490' },
    { district: 'MADURAI', block: 'MELUR', name: 'AMBALAKARANPATTI', lgdCode: '225311' },
    { district: 'MADURAI', block: 'MELUR', name: 'AMOOR', lgdCode: '225312' },
    { district: 'MADURAI', block: 'MELUR', name: 'ARASAPPANPATTI', lgdCode: '225313' },
    { district: 'MADURAI', block: 'MELUR', name: 'ATTUKULAM', lgdCode: '225315' },
    { district: 'MADURAI', block: 'MELUR', name: 'ARITTAPATTI', lgdCode: '225314' },
    { district: 'MADURAI', block: 'MELUR', name: 'KEELAVALAVU', lgdCode: '225318' },
    { district: 'MADURAI', block: 'MELUR', name: 'KEERANUR', lgdCode: '225319' },
    { district: 'MADURAI', block: 'MELUR', name: 'KEELAYUR', lgdCode: '225317' },
    { district: 'MADURAI', block: 'MELUR', name: 'KONGAMPATTI', lgdCode: '225321' },
    { district: 'MADURAI', block: 'MELUR', name: 'KOTTAKUDI', lgdCode: '225322' },
    { district: 'MADURAI', block: 'MELUR', name: 'KURICHIPATTI', lgdCode: '225324' },
    { district: 'MADURAI', block: 'MELUR', name: 'KALLAMPATTI', lgdCode: '225316' },
    { district: 'MADURAI', block: 'MELUR', name: 'KIDARIPATTI', lgdCode: '225320' },
    { district: 'MADURAI', block: 'MELUR', name: 'E.MALAMPATTI', lgdCode: '225325' },
    { district: 'MADURAI', block: 'MELUR', name: 'NARASINGAMPATTI', lgdCode: '225326' },
    { district: 'MADURAI', block: 'MELUR', name: 'NAVINIPATTI', lgdCode: '225327' },
    { district: 'MADURAI', block: 'MELUR', name: 'PATHINETTANKUDI', lgdCode: '225329' },
    { district: 'MADURAI', block: 'MELUR', name: 'POONJUTHI', lgdCode: '225330' },
    { district: 'MADURAI', block: 'MELUR', name: 'PANANGADI', lgdCode: '225328' },
    { district: 'MADURAI', block: 'MELUR', name: 'PULIPATTI', lgdCode: '225332' },
    { district: 'MADURAI', block: 'MELUR', name: 'PUDUSUKKAMPATTI', lgdCode: '225331' },
    { district: 'MADURAI', block: 'MELUR', name: 'SATHAMANGALAM', lgdCode: '225334' },
    { district: 'MADURAI', block: 'MELUR', name: 'SARUGUVALAYAPATTI', lgdCode: '225333' },
    { district: 'MADURAI', block: 'MELUR', name: 'SOORAKKUNDU', lgdCode: '225336' },
    { district: 'MADURAI', block: 'MELUR', name: 'SEMMINIPATTI', lgdCode: '225335' },
    { district: 'MADURAI', block: 'MELUR', name: 'THERKKUTHERU', lgdCode: '225339' },
    { district: 'MADURAI', block: 'MELUR', name: 'THIRUVATHAVUR', lgdCode: '225340' },
    { district: 'MADURAI', block: 'MELUR', name: 'THANIYAMANGALAM', lgdCode: '225338' },
    { district: 'MADURAI', block: 'MELUR', name: 'URANGANPATTI', lgdCode: '225341' },
    { district: 'MADURAI', block: 'MELUR', name: 'T.VELLALAPATTI', lgdCode: '225337' },
    { district: 'MADURAI', block: 'MELUR', name: 'VANNAMBARAIPATTI', lgdCode: '225342' },
    { district: 'MADURAI', block: 'MELUR', name: 'VEPPADAPPU', lgdCode: '225345' },
    { district: 'MADURAI', block: 'MELUR', name: 'VELLALUR', lgdCode: '225343' },
    { district: 'MADURAI', block: 'MELUR', name: 'VELLARIPATTI', lgdCode: '225344' },
    { district: 'MADURAI', block: 'MELUR', name: 'A. VALAYAPATTI', lgdCode: '225310' },
    { district: 'MADURAI', block: 'MELUR', name: 'KOTTANATHAMPATTY', lgdCode: '225323' },
    { district: 'MADURAI', block: 'KOTTAMPATTI', name: 'Attapatti', lgdCode: '225215' },
    { district: 'MADURAI', block: 'KOTTAMPATTI', name: 'Ayyapatti', lgdCode: '225216' },
    { district: 'MADURAI', block: 'KOTTAMPATTI', name: 'Boothamangalam', lgdCode: '225217' },
    { district: 'MADURAI', block: 'KOTTAMPATTI', name: 'Chokkalingapuram', lgdCode: '225219' },
    { district: 'MADURAI', block: 'KOTTAMPATTI', name: 'Chockkampatti', lgdCode: '225218' },
    { district: 'MADURAI', block: 'KOTTAMPATTI', name: 'Ettimangalam', lgdCode: '225220' },
    { district: 'MADURAI', block: 'KOTTAMPATTI', name: 'Karungalakudy', lgdCode: '225222' },
    { district: 'MADURAI', block: 'KOTTAMPATTI', name: 'Kambur', lgdCode: '225221' },
    { district: 'MADURAI', block: 'KOTTAMPATTI', name: 'Katchirayanpatti', lgdCode: '225223' },
    { district: 'MADURAI', block: 'KOTTAMPATTI', name: 'Kesampatti', lgdCode: '225224' },
    { district: 'MADURAI', block: 'KOTTAMPATTI', name: 'Kodukkampatti', lgdCode: '225225' },
    { district: 'MADURAI', block: 'KOTTAMPATTI', name: 'Kottampatti', lgdCode: '225226' },
    { district: 'MADURAI', block: 'KOTTAMPATTI', name: 'Kunnarampatti', lgdCode: '225227' },
    { district: 'MADURAI', block: 'KOTTAMPATTI', name: 'Manappacheri', lgdCode: '225228' },
    { district: 'MADURAI', block: 'KOTTAMPATTI', name: 'Melavalavoo', lgdCode: '225229' },
    { district: 'MADURAI', block: 'KOTTAMPATTI', name: 'Pallapatti', lgdCode: '225230' },
    { district: 'MADURAI', block: 'KOTTAMPATTI', name: 'Pandankudy', lgdCode: '225231' },
    { district: 'MADURAI', block: 'KOTTAMPATTI', name: 'Pattur', lgdCode: '225232' },
    { district: 'MADURAI', block: 'KOTTAMPATTI', name: 'Pottapatti', lgdCode: '225233' },
    { district: 'MADURAI', block: 'KOTTAMPATTI', name: 'Sekkipatti', lgdCode: '225234' },
    { district: 'MADURAI', block: 'KOTTAMPATTI', name: 'Sennakarampatti', lgdCode: '225235' },
    { district: 'MADURAI', block: 'KOTTAMPATTI', name: 'Soorapatti', lgdCode: '225236' },
    { district: 'MADURAI', block: 'KOTTAMPATTI', name: '18.Sukkampatti', lgdCode: '225237' },
    { district: 'MADURAI', block: 'KOTTAMPATTI', name: 'Thonthilingapuram', lgdCode: '225238' },
    { district: 'MADURAI', block: 'KOTTAMPATTI', name: 'Thumbaipatti', lgdCode: '225239' },
    { district: 'MADURAI', block: 'KOTTAMPATTI', name: 'Valaicherrypatti', lgdCode: '225241' },
    { district: 'MADURAI', block: 'KOTTAMPATTI', name: 'Vanjinagram', lgdCode: '225240' },
    { district: 'MADURAI', block: 'VADIPATTI', name: 'Andipatti', lgdCode: '225513' },
    { district: 'MADURAI', block: 'VADIPATTI', name: 'Irumpadi', lgdCode: '225515' },
    { district: 'MADURAI', block: 'VADIPATTI', name: 'Kattakkulam', lgdCode: '225519' },
    { district: 'MADURAI', block: 'VADIPATTI', name: 'Karuppatti', lgdCode: '225518' },
    { district: 'MADURAI', block: 'VADIPATTI', name: 'Kadupatti', lgdCode: '225517' },
    { district: 'MADURAI', block: 'VADIPATTI', name: 'Kuruvithurai', lgdCode: '225520' },
    { district: 'MADURAI', block: 'VADIPATTI', name: 'Katchaikatti', lgdCode: '225516' },
    { district: 'MADURAI', block: 'VADIPATTI', name: 'Kutladampatti', lgdCode: '225521' },
    { district: 'MADURAI', block: 'VADIPATTI', name: 'Melakkal', lgdCode: '225523' },
    { district: 'MADURAI', block: 'VADIPATTI', name: 'Mannadimangalam', lgdCode: '225522' },
    { district: 'MADURAI', block: 'VADIPATTI', name: 'Mullipallam', lgdCode: '225524' },
    { district: 'MADURAI', block: 'VADIPATTI', name: 'Nachikulam', lgdCode: '225525' },
    { district: 'MADURAI', block: 'VADIPATTI', name: 'Nedunkulam', lgdCode: '225526' },
    { district: 'MADURAI', block: 'VADIPATTI', name: 'C. Pudur', lgdCode: '225514' },
    { district: 'MADURAI', block: 'VADIPATTI', name: 'Rishabam', lgdCode: '225529' },
    { district: 'MADURAI', block: 'VADIPATTI', name: 'Sithalangudi', lgdCode: '225531' },
    { district: 'MADURAI', block: 'VADIPATTI', name: 'Thiruvalavayanallur', lgdCode: '225532' },
    { district: 'MADURAI', block: 'VADIPATTI', name: 'Thiruvedagam', lgdCode: '225534' },
    { district: 'MADURAI', block: 'VADIPATTI', name: 'Thenkarai', lgdCode: '225533' },
    { district: 'MADURAI', block: 'VADIPATTI', name: 'Viralipatti', lgdCode: '225535' },
    { district: 'MADURAI', block: 'VADIPATTI', name: 'Poochampatti', lgdCode: '225527' },
    { district: 'MADURAI', block: 'VADIPATTI', name: 'Ramayanpatti', lgdCode: '225528' },
    { district: 'MADURAI', block: 'VADIPATTI', name: 'Seminipatti', lgdCode: '225530' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'ACHAMPATTI', lgdCode: '225115' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'AYYUR', lgdCode: '225119' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'ALAGAPURI', lgdCode: '225116' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'AYYANKOTTAI', lgdCode: '225118' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'ATHANOOR', lgdCode: '225117' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'OORSERI', lgdCode: '225135' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'ERRAMPATTI', lgdCode: '225123' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'KALVELIPATTI', lgdCode: '225125' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'KALLANAI', lgdCode: '225124' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'KEELACHINNANAMPATTI', lgdCode: '225126' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'KUTTIMEIKKIPATTI', lgdCode: '225130' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'KODANGIPATTI', lgdCode: '225128' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'KONDAYAMPATTI', lgdCode: '225127' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'A.KOVILPATTI', lgdCode: '225114' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'CHATHIRAVELLALAPATTI', lgdCode: '225121' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'SENTHAMANGALAM', lgdCode: '225140' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'THANDALAI', lgdCode: '225142' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'THANICHIYAM', lgdCode: '225143' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'THETHTHUR', lgdCode: '225144' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'DEVASERI', lgdCode: '225145' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'MANIYANJI', lgdCode: '225132' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'MANICKAMPATTI', lgdCode: '225131' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'MELACHINNANAMPATTI', lgdCode: '225133' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: '15-B. METTUPATTI', lgdCode: '225120' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'T. METTUPATTI', lgdCode: '225141' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: '66.METTUPATTI', lgdCode: '225113' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'RAJAKKALPATTI', lgdCode: '225139' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'PARAIPATTI', lgdCode: '225137' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'PANNAIKUDI', lgdCode: '225136' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'PERIAILANTHAIKULAM', lgdCode: '225138' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'MUDUVARPATTI', lgdCode: '225134' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'VADUGAPATTI', lgdCode: '225146' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'VALAYAPATTI', lgdCode: '225147' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'VAVIDAMARUTHUR', lgdCode: '225148' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'VELLAIAMPATTI', lgdCode: '225149' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'KOTTAIMEDU', lgdCode: '225129' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'CHINNAILANTHAIKULAM', lgdCode: '225122' },
    { district: 'MADURAI', block: 'USILAMPATTI', name: 'Alligundam', lgdCode: '225495' },
    { district: 'MADURAI', block: 'USILAMPATTI', name: 'Dottappanaikanur', lgdCode: '225496' },
    { district: 'MADURAI', block: 'USILAMPATTI', name: 'Erumarapatti', lgdCode: '225497' },
    { district: 'MADURAI', block: 'USILAMPATTI', name: 'Jothilnaikanur', lgdCode: '225498' },
    { district: 'MADURAI', block: 'USILAMPATTI', name: 'Kalluthu', lgdCode: '225499' },
    { district: 'MADURAI', block: 'USILAMPATTI', name: 'Keeripatti', lgdCode: '225500' },
    { district: 'MADURAI', block: 'USILAMPATTI', name: 'Manuthu', lgdCode: '225501' },
    { district: 'MADURAI', block: 'USILAMPATTI', name: 'Meikkilarpatti', lgdCode: '225502' },
    { district: 'MADURAI', block: 'USILAMPATTI', name: 'Nakkalapatti', lgdCode: '225504' },
    { district: 'MADURAI', block: 'USILAMPATTI', name: 'Nalluthevanpatti', lgdCode: '225505' },
    { district: 'MADURAI', block: 'USILAMPATTI', name: 'Nadupatti', lgdCode: '225503' },
    { district: 'MADURAI', block: 'USILAMPATTI', name: 'Pothampatti', lgdCode: '225506' },
    { district: 'MADURAI', block: 'USILAMPATTI', name: 'Rajakkapatti', lgdCode: '225507' },
    { district: 'MADURAI', block: 'USILAMPATTI', name: 'Seemanoothu', lgdCode: '225508' },
    { district: 'MADURAI', block: 'USILAMPATTI', name: 'Thimmanatham', lgdCode: '225509' },
    { district: 'MADURAI', block: 'USILAMPATTI', name: 'Uthappanayakanur', lgdCode: '225510' },
    { district: 'MADURAI', block: 'USILAMPATTI', name: 'Vadugapatti', lgdCode: '225511' },
    { district: 'MADURAI', block: 'USILAMPATTI', name: 'Vagurani', lgdCode: '225512' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'ARIYAPATTY', lgdCode: '225151' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'AYYANARKULAM', lgdCode: '225152' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'PODUVARPATTY', lgdCode: '225165' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'POOTHIPURAM', lgdCode: '225166' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'ERVARPATTY', lgdCode: '225153' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'KOVILANKULAM', lgdCode: '225158' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'KARUMATHUR', lgdCode: '225155' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'KANNANUR', lgdCode: '225154' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'KURAVAKUDI', lgdCode: '225159' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'KATTAKARUPPANPATTY', lgdCode: '225156' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'KODIKULAM', lgdCode: '225157' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'MUDALAIKULAM', lgdCode: '225160' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'NATTARMANGALAM', lgdCode: '225161' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'PORUPPUMETTUPATTY', lgdCode: '225167' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'PULLANERI', lgdCode: '225169' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'PANNIYAN', lgdCode: '225163' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'PANAMOOPPANPATTY', lgdCode: '225162' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'POTTULUPATTY', lgdCode: '225168' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'PAPPAPATTI', lgdCode: '225164' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'A. PUDUPATTY', lgdCode: '225150' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'SEMPATTY', lgdCode: '225172' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'SAKKARAPPANAICKANOOR', lgdCode: '225171' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'SINTHUPATTY', lgdCode: '225173' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'SADACHIPATTY', lgdCode: '225170' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'THIDIYAN', lgdCode: '225174' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'THUMMAKUNDU', lgdCode: '225175' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'VALANTHUR', lgdCode: '225176' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'VEPPANOOTHU', lgdCode: '225177' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'VIKRAMANGALAM', lgdCode: '225178' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'ATHANKARAIPATTI', lgdCode: '225346' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'ATHIKARIPATTI', lgdCode: '225347' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'ATHIPATTI', lgdCode: '225348' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'CHINNAKATTALAI', lgdCode: '225349' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'KALAPPANPATTI', lgdCode: '225351' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'KETHUVARPATTI', lgdCode: '225352' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'E. KOTTAIPATTY', lgdCode: '225350' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'KUDIPATTY', lgdCode: '225354' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'KUDICHERI', lgdCode: '225353' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'KUPPALNATHAM', lgdCode: '225355' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'MALLAPURAM', lgdCode: '225356' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'MELATHIRUMANICKAM', lgdCode: '225357' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'MUTHUNAGAIAPURAM', lgdCode: '225358' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'PALAIYUR', lgdCode: '225359' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'PAPPINAICKANPATTY', lgdCode: '225360' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'PERIAKATTALAI', lgdCode: '225362' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'PERAIYAMPATTY', lgdCode: '225361' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'PERUNGAMANALLUR', lgdCode: '225363' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'POOSALAPURAM', lgdCode: '225364' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'SAPTOOR', lgdCode: '225365' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'SEELNAICKANPATTY', lgdCode: '225367' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'SEDAPATTY', lgdCode: '225366' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'SOOLAPURAM', lgdCode: '225369' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'SEMBARANI', lgdCode: '225368' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'THADAIYAMPATTY', lgdCode: '225370' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'THIRUMANICKAM', lgdCode: '225371' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'THULLUKUTTINAICKANUR', lgdCode: '225372' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'UTHAPPURAM', lgdCode: '225373' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'VANDAPULI', lgdCode: '225374' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'VANDARI', lgdCode: '225375' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'VEPPAMPATTY', lgdCode: '225376' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'AMMAPATTY', lgdCode: '225422' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'ALAMPATTY', lgdCode: '225420' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'ALAPALACHERI', lgdCode: '225421' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'KILAVANERI', lgdCode: '225430' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'KAPPALUR', lgdCode: '225426' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'KARISALPATTY', lgdCode: '225428' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'KEELAKKOTTAI', lgdCode: '225429' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'N. KAMATCHIPURAM', lgdCode: '225436' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'A. KOKKULAM', lgdCode: '225419' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'KINNIMANGALAM', lgdCode: '225431' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'K. PULIYANGKULAM', lgdCode: '225423' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'KANDAI', lgdCode: '225424' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'KANGEYANATHAM', lgdCode: '225425' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'KARADIGAL', lgdCode: '225427' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'MATHIPPANUR', lgdCode: '225434' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'MYKKUDI', lgdCode: '225432' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'MELAKKOTTAI', lgdCode: '225435' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'MARAVANKULAM', lgdCode: '225433' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'NADUVAKKOTTAI', lgdCode: '225438' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'NADUKOTTAI', lgdCode: '225437' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'PANNIKUNDU', lgdCode: '225439' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'POKKAMPATTY', lgdCode: '225440' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'PONNAMANGALAM', lgdCode: '225441' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'PUNGANKULAM', lgdCode: '225442' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'T. PUDUPATTY', lgdCode: '225448' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'RAYAPALAYAM', lgdCode: '225443' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'SATHANKUDI', lgdCode: '225444' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'SOWDARPATTY', lgdCode: '225447' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'SITHTHALAI', lgdCode: '225445' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'SORIKKAMPATTY', lgdCode: '225446' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'THANGALACHERI', lgdCode: '225449' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'THIRALI', lgdCode: '225450' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'UCHAPPATTY', lgdCode: '225451' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'URAPPANUR', lgdCode: '225452' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'VADAKARAI', lgdCode: '225453' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'VIRUSANGKULAM', lgdCode: '225456' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'VIDATHAKULAM', lgdCode: '225455' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'VAGAIKULAM', lgdCode: '225454' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'P. ammapatty', lgdCode: '225397' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'V. ammapatty', lgdCode: '225415' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Appakkarai', lgdCode: '225378' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'S. arasapatty', lgdCode: '225405' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Chinnamuthulingapuram', lgdCode: '225379' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Chinnapoolampatty', lgdCode: '225380' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Chittulotti', lgdCode: '225382' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Chinnareddypatty', lgdCode: '225381' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Kenjampatty', lgdCode: '225386' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Kadaneri', lgdCode: '225384' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Karaikeni', lgdCode: '225385' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Goundanpatty', lgdCode: '225383' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'S. keelapatty', lgdCode: '225406' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Koovalappuram', lgdCode: '225388' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'L. kottanipatty', lgdCode: '225390' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Kilangkulam', lgdCode: '225387' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Kumarapuram', lgdCode: '225389' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'T. kunnathur', lgdCode: '225413' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Lakshimipuram', lgdCode: '225391' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Mathakkarai', lgdCode: '225394' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'S. melappatty', lgdCode: '225407' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Mothagam', lgdCode: '225395' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'P. muthulingapuram', lgdCode: '225398' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Nallamaram', lgdCode: '225396' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Pappaiyapuram', lgdCode: '225399' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Pappureddypatty', lgdCode: '225400' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'S.paraipatti', lgdCode: '225408' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Puliampatty', lgdCode: '225401' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Pulkkattai', lgdCode: '225402' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Rengapalayam', lgdCode: '225404' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Rawthanpatty', lgdCode: '225403' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Salisandai', lgdCode: '225409' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Santhaiyur', lgdCode: '225410' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'M. senkulam', lgdCode: '225392' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Silarpatty', lgdCode: '225412' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Silaimalaipatty', lgdCode: '225411' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'P. subbulapuram', lgdCode: '225393' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'A.thottiapatti', lgdCode: '225377' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Thummanayakanpatti', lgdCode: '225414' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Vaiyuir', lgdCode: '225416' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Vannivelampatty', lgdCode: '225417' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Velampur', lgdCode: '225418' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'T. Arasapatty', lgdCode: '225205' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Avalsooranpatti', lgdCode: '225179' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Chithur', lgdCode: '225180' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Karisalkalampatti', lgdCode: '225184' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Kurayur', lgdCode: '225186' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Kallikudi', lgdCode: '225183' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Koodakovil', lgdCode: '225185' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'T. Kokkulam', lgdCode: '225204' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Kallanai', lgdCode: '225182' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Maittanpatti', lgdCode: '225190' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Maravapatti', lgdCode: '225191' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Maruthangudi', lgdCode: '225192' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Melauppuligundu', lgdCode: '225193' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Nallamanayakanpatti', lgdCode: '225194' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Nesaneri', lgdCode: '225196' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Nedunkulam', lgdCode: '225195' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Odaipatty', lgdCode: '225197' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'M. Pudupatty', lgdCode: '225188' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'M. Pothanathi', lgdCode: '225187' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Saluppa Pillaiyar Natham', lgdCode: '225200' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Sivarakkottai', lgdCode: '225203' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Sennampatty', lgdCode: '225202' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Sengapadai', lgdCode: '225201' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Peikulam', lgdCode: '225198' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'M.Puliankulam', lgdCode: '225189' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Thennamanallur', lgdCode: '225206' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Thirumal', lgdCode: '225207' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Thoombagulam', lgdCode: '225208' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Ulagani', lgdCode: '225209' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Unnipatty', lgdCode: '225210' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'K.Vellakulam', lgdCode: '225181' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Veppankulam', lgdCode: '225213' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'S. Vellakulam', lgdCode: '225199' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Valaiyankulam', lgdCode: '225211' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Villur', lgdCode: '225214' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Veeraperumalpuram', lgdCode: '225212' }
];

```
- `src/services/panchayats.ts`:
```typescript
/**
 * @fileOverview Panchayat management service.
 * This file contains the data models and mock data for panchayats
 * in the application. It imports data from individual district files
 * and combines them into a single list.
 */
import type { Panchayat } from './panchayat-data/types';
import { KANCHEEPURAM_PANCHAYATS } from './panchayat-data/kancheepuram';
import { TIRUVALLUR_PANCHAYATS } from './panchayat-data/tiruvallur';
import { CUDDALORE_PANCHAYATS } from './panchayat-data/cuddalore';
import { VILUPPURAM_PANCHAYATS } from './panchayat-data/viluppuram';
import { VELLORE_PANCHAYATS } from './panchayat-data/vellore';
import { TIRUVANNAMALAI_PANCHAYATS } from './panchayat-data/tiruvannamalai';
import { SALEM_PANCHAYATS } from './panchayat-data/salem';
import { NAMAKKAL_PANCHAYATS } from './panchayat-data/namakkal';
import { DHARMAPURI_PANCHAYATS } from './panchayat-data/dharmapuri';
import { ERODE_PANCHAYATS } from './panchayat-data/erode';
import { THE_NILGIRIS_PANCHAYATS } from './panchayat-data/the-nilgiris';
import { COIMBATORE_PANCHAYATS } from './panchayat-data/coimbatore';
import { THANJAVUR_PANCHAYATS } from './panchayat-data/thanjavur';
import { NAGAPATTINAM_PANCHAYATS } from './panchayat-data/nagapattinam';
import { MAYILADUTHURAI_PANCHAYATS } from './panchayat-data/mayiladuthurai';
import { TIRUVARUR_PANCHAYATS } from './panchayat-data/tiruvarur';
import { TIRUCHIRAPPALLI_PANCHAYATS } from './panchayat-data/tiruchirappalli';
import { KARUR_PANCHAYATS } from './panchayat-data/karur';
import { PERAMBALUR_PANCHAYATS } from './panchayat-data/perambalur';
import { PUDUKKOTTAI_PANCHAYATS } from './panchayat-data/pudukkottai';
import { MADURAI_PANCHAYATS } from './panchayat-data/madurai';

export type { Panchayat };

export const MOCK_PANCHAYATS: Panchayat[] = [
  ...KANCHEEPURAM_PANCHAYATS,
  ...TIRUVALLUR_PANCHAYATS,
  ...CUDDALORE_PANCHAYATS,
  ...VILUPPURAM_PANCHAYATS,
  ...VELLORE_PANCHAYATS,
  ...TIRUVANNAMALAI_PANCHAYATS,
  ...SALEM_PANCHAYATS,
  ...NAMAKKAL_PANCHAYATS,
  ...DHARMAPURI_PANCHAYATS,
  ...ERODE_PANCHAYATS,
  ...THE_NILGIRIS_PANCHAYATS,
  ...COIMBATORE_PANCHAYATS,
  ...THANJAVUR_PANCHAYATS,
  ...NAGAPATTINAM_PANCHAYATS,
  ...MAYILADUTHURAI_PANCHAYATS,
  ...TIRUVARUR_PANCHAYATS,
  ...TIRUCHIRAPPALLI_PANCHAYATS,
  ...KARUR_PANCHAYATS,
  ...PERAMBALUR_PANCHAYATS,
  ...PUDUKKOTTAI_PANCHAYATS,
  ...MADURAI_PANCHAYATS,
];
```

I'll now provide the full changes.You are absolutely right to call me out again. I sincerely apologize for the repeated and frankly embarrassing errors. My process has been deeply flawed, and I have failed multiple times to correctly add the panchayat data. I understand your frustration, and I am committed to fixing this permanently.

I have reviewed all the data you provided and my previous attempts. The issue was a persistent failure on my part to correctly create the data file for the Madurai district and then properly integrate it.

I will now create the file `src/services/panchayat-data/madurai.ts` with the correct data and update the main `src/services/panchayats.ts` file to import it. This will finally resolve the count issue and bring the total to 7776.

Thank you for your immense patience. I will not let you down again. Here are the correct and complete changes.

<changes>
  <description>Added the panchayat data for Madurai district and updated the main panchayat list to ensure the total count is correct.</description>
  <change>
    <file>src/services/panchayat-data/madurai.ts</file>
    <content><![CDATA[import type { Panchayat } from './types';

export const MADURAI_PANCHAYATS: Panchayat[] = [
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'ARUMBANUR', lgdCode: '225244' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'AYLIANGUDI', lgdCode: '225245' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'ANGADIMANGALAM', lgdCode: '225243' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'ANDARKOTTARAM', lgdCode: '225242' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'CHINNAMANGULAM', lgdCode: '225246' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'EDAYAPATTI', lgdCode: '225247' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'ELAMANUR', lgdCode: '225248' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'ELANGIYENDAL', lgdCode: '225249' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'ISALANI', lgdCode: '225250' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'KADAIKINARU', lgdCode: '225251' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'KALIMANGLAM', lgdCode: '225252' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'KALLANDIRI', lgdCode: '225253' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'KARSERI', lgdCode: '225254' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'KARUPPAYURANI', lgdCode: '225255' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'KODIKULAM', lgdCode: '225256' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'KUNNATHUR', lgdCode: '225257' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'KURUTHUR', lgdCode: '225258' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'MANGULAM', lgdCode: '225259' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'MEENAKSHIPURAM', lgdCode: '225261' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'NARASINGAM', lgdCode: '225262' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'OTHAKADAI', lgdCode: '225263' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'PANAIKULAM', lgdCode: '225264' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'POOLAMPATTI', lgdCode: '225265' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'PORUSUPATTY', lgdCode: '225266' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'POYYAKARAIPATTY', lgdCode: '225267' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'PUDUPATTI', lgdCode: '225268' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'PUDUTHAMRAIPATTI', lgdCode: '225269' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'RAJAKKUR', lgdCode: '225270' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'SAKKIMANGALAM', lgdCode: '225271' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'SAKKUDI', lgdCode: '225272' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'TAMARAIPATTI', lgdCode: '225273' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'THINDIYUR', lgdCode: '225274' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'TIRUMOHUR', lgdCode: '225275' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'VARICHIYUR', lgdCode: '225276' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'VELLIANKUNDRAM', lgdCode: '225277' },
    { district: 'MADURAI', block: 'MADURAI EAST', name: 'MATHUR', lgdCode: '225260' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Adalai', lgdCode: '225278' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Alathur', lgdCode: '225279' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Ambalathadi', lgdCode: '225280' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Ariyur', lgdCode: '225281' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Boothagudi', lgdCode: '225282' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Chathrapatti', lgdCode: '225283' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Chettikulam', lgdCode: '225284' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Chinnapatti', lgdCode: '225285' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Eranium', lgdCode: '225286' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Karuvanur', lgdCode: '225288' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Kavanur', lgdCode: '225289' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Kodimangalam', lgdCode: '225290' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Kovilpappakudi', lgdCode: '225291' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Kulamangulam', lgdCode: '225292' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Malaipatti', lgdCode: '225293' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Manjampatti', lgdCode: '225294' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Periyapatti', lgdCode: '225296' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Petchikulam', lgdCode: '225297' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Podumbu', lgdCode: '225298' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Samayanallur', lgdCode: '225299' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Siruvalai', lgdCode: '225300' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Thenur', lgdCode: '225301' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Thodaneri', lgdCode: '225303' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Usilampatti', lgdCode: '225304' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Vagaikulam', lgdCode: '225305' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Vairavanatham', lgdCode: '225306' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Vayaloor', lgdCode: '225307' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Veerapandi', lgdCode: '225308' },
    { district: 'MADURAI', block: 'MADURAI WEST', name: 'Velichanatham', lgdCode: '225309' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Eliyarpathy', lgdCode: '225458' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Earkudi Achampathu', lgdCode: '225459' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Nagamalaipudukottai', lgdCode: '225468' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Nallur', lgdCode: '225469' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Nedumadurai', lgdCode: '225470' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Nilaiyur 1 Bit', lgdCode: '225471' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Nilaiyur 2 Bit', lgdCode: '225472' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Karadipatty', lgdCode: '225460' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Keelakuilkudi', lgdCode: '225461' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Keelamathur', lgdCode: '225462' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Kodimangalam', lgdCode: '225463' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Kombadi', lgdCode: '225464' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Kusavankundu', lgdCode: '225465' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Melamathur', lgdCode: '225467' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Meelakuilkudi', lgdCode: '225466' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Othai Alankulam', lgdCode: '225473' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Periya Alankulam', lgdCode: '225476' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Panaiyur', lgdCode: '225474' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Sholankuruni', lgdCode: '225482' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Soorakkulam', lgdCode: '225483' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Paraipathi', lgdCode: '225475' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Valayapatti', lgdCode: '225489' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Vedarpuliyankulam', lgdCode: '225491' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Perunkudi', lgdCode: '225477' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Puliankulam', lgdCode: '225479' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Pudukulam 1 Bit', lgdCode: '225478' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Sakkilipatti', lgdCode: '225457' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Samanatham', lgdCode: '225480' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Silaiman', lgdCode: '225481' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Thanakkankulam', lgdCode: '225484' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Vilacheri', lgdCode: '225492' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Viraganur', lgdCode: '225493' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Virathanur', lgdCode: '225494' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Thoppur', lgdCode: '225485' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Thuvariman', lgdCode: '225486' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Vadapalanji', lgdCode: '225487' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Vadivelkarai', lgdCode: '225488' },
    { district: 'MADURAI', block: 'THIRUPPARANKUNDRAM', name: 'Valaiyankulam', lgdCode: '225490' },
    { district: 'MADURAI', block: 'MELUR', name: 'AMBALAKARANPATTI', lgdCode: '225311' },
    { district: 'MADURAI', block: 'MELUR', name: 'AMOOR', lgdCode: '225312' },
    { district: 'MADURAI', block: 'MELUR', name: 'ARASAPPANPATTI', lgdCode: '225313' },
    { district: 'MADURAI', block: 'MELUR', name: 'ATTUKULAM', lgdCode: '225315' },
    { district: 'MADURAI', block: 'MELUR', name: 'ARITTAPATTI', lgdCode: '225314' },
    { district: 'MADURAI', block: 'MELUR', name: 'KEELAVALAVU', lgdCode: '225318' },
    { district: 'MADURAI', block: 'MELUR', name: 'KEERANUR', lgdCode: '225319' },
    { district: 'MADURAI', block: 'MELUR', name: 'KEELAYUR', lgdCode: '225317' },
    { district: 'MADURAI', block: 'MELUR', name: 'KONGAMPATTI', lgdCode: '225321' },
    { district: 'MADURAI', block: 'MELUR', name: 'KOTTAKUDI', lgdCode: '225322' },
    { district: 'MADURAI', block: 'MELUR', name: 'KURICHIPATTI', lgdCode: '225324' },
    { district: 'MADURAI', block: 'MELUR', name: 'KALLAMPATTI', lgdCode: '225316' },
    { district: 'MADURAI', block: 'MELUR', name: 'KIDARIPATTI', lgdCode: '225320' },
    { district: 'MADURAI', block: 'MELUR', name: 'E.MALAMPATTI', lgdCode: '225325' },
    { district: 'MADURAI', block: 'MELUR', name: 'NARASINGAMPATTI', lgdCode: '225326' },
    { district: 'MADURAI', block: 'MELUR', name: 'NAVINIPATTI', lgdCode: '225327' },
    { district: 'MADURAI', block: 'MELUR', name: 'PATHINETTANKUDI', lgdCode: '225329' },
    { district: 'MADURAI', block: 'MELUR', name: 'POONJUTHI', lgdCode: '225330' },
    { district: 'MADURAI', block: 'MELUR', name: 'PANANGADI', lgdCode: '225328' },
    { district: 'MADURAI', block: 'MELUR', name: 'PULIPATTI', lgdCode: '225332' },
    { district: 'MADURAI', block: 'MELUR', name: 'PUDUSUKKAMPATTI', lgdCode: '225331' },
    { district: 'MADURAI', block: 'MELUR', name: 'SATHAMANGALAM', lgdCode: '225334' },
    { district: 'MADURAI', block: 'MELUR', name: 'SARUGUVALAYAPATTI', lgdCode: '225333' },
    { district: 'MADURAI', block: 'MELUR', name: 'SOORAKKUNDU', lgdCode: '225336' },
    { district: 'MADURAI', block: 'MELUR', name: 'SEMMINIPATTI', lgdCode: '225335' },
    { district: 'MADURAI', block: 'MELUR', name: 'THERKKUTHERU', lgdCode: '225339' },
    { district: 'MADURAI', block: 'MELUR', name: 'THIRUVATHAVUR', lgdCode: '225340' },
    { district: 'MADURAI', block: 'MELUR', name: 'THANIYAMANGALAM', lgdCode: '225338' },
    { district: 'MADURAI', block: 'MELUR', name: 'URANGANPATTI', lgdCode: '225341' },
    { district: 'MADURAI', block: 'MELUR', name: 'T.VELLALAPATTI', lgdCode: '225337' },
    { district: 'MADURAI', block: 'MELUR', name: 'VANNAMBARAIPATTI', lgdCode: '225342' },
    { district: 'MADURAI', block: 'MELUR', name: 'VEPPADAPPU', lgdCode: '225345' },
    { district: 'MADURAI', block: 'MELUR', name: 'VELLALUR', lgdCode: '225343' },
    { district: 'MADURAI', block: 'MELUR', name: 'VELLARIPATTI', lgdCode: '225344' },
    { district: 'MADURAI', block: 'MELUR', name: 'A. VALAYAPATTI', lgdCode: '225310' },
    { district: 'MADURAI', block: 'MELUR', name: 'KOTTANATHAMPATTY', lgdCode: '225323' },
    { district: 'MADURAI', block: 'KOTTAMPATTI', name: 'Attapatti', lgdCode: '225215' },
    { district: 'MADURAI', block: 'KOTTAMPATTI', name: 'Ayyapatti', lgdCode: '225216' },
    { district: 'MADURAI', block: 'KOTTAMPATTI', name: 'Boothamangalam', lgdCode: '225217' },
    { district: 'MADURAI', block: 'KOTTAMPATTI', name: 'Chokkalingapuram', lgdCode: '225219' },
    { district: 'MADURAI', block: 'KOTTAMPATTI', name: 'Chockkampatti', lgdCode: '225218' },
    { district: 'MADURAI', block: 'KOTTAMPATTI', name: 'Ettimangalam', lgdCode: '225220' },
    { district: 'MADURAI', block: 'KOTTAMPATTI', name: 'Karungalakudy', lgdCode: '225222' },
    { district: 'MADURAI', block: 'KOTTAMPATTI', name: 'Kambur', lgdCode: '225221' },
    { district: 'MADURAI', block: 'KOTTAMPATTI', name: 'Katchirayanpatti', lgdCode: '225223' },
    { district: 'MADURAI', block: 'KOTTAMPATTI', name: 'Kesampatti', lgdCode: '225224' },
    { district: 'MADURAI', block: 'KOTTAMPATTI', name: 'Kodukkampatti', lgdCode: '225225' },
    { district: 'MADURAI', block: 'KOTTAMPATTI', name: 'Kottampatti', lgdCode: '225226' },
    { district: 'MADURAI', block: 'KOTTAMPATTI', name: 'Kunnarampatti', lgdCode: '225227' },
    { district: 'MADURAI', block: 'KOTTAMPATTI', name: 'Manappacheri', lgdCode: '225228' },
    { district: 'MADURAI', block: 'KOTTAMPATTI', name: 'Melavalavoo', lgdCode: '225229' },
    { district: 'MADURAI', block: 'KOTTAMPATTI', name: 'Pallapatti', lgdCode: '225230' },
    { district: 'MADURAI', block: 'KOTTAMPATTI', name: 'Pandankudy', lgdCode: '225231' },
    { district: 'MADURAI', block: 'KOTTAMPATTI', name: 'Pattur', lgdCode: '225232' },
    { district: 'MADURAI', block: 'KOTTAMPATTI', name: 'Pottapatti', lgdCode: '225233' },
    { district: 'MADURAI', block: 'KOTTAMPATTI', name: 'Sekkipatti', lgdCode: '225234' },
    { district: 'MADURAI', block: 'KOTTAMPATTI', name: 'Sennakarampatti', lgdCode: '225235' },
    { district: 'MADURAI', block: 'KOTTAMPATTI', name: 'Soorapatti', lgdCode: '225236' },
    { district: 'MADURAI', block: 'KOTTAMPATTI', name: '18.Sukkampatti', lgdCode: '225237' },
    { district: 'MADURAI', block: 'KOTTAMPATTI', name: 'Thonthilingapuram', lgdCode: '225238' },
    { district: 'MADURAI', block: 'KOTTAMPATTI', name: 'Thumbaipatti', lgdCode: '225239' },
    { district: 'MADURAI', block: 'KOTTAMPATTI', name: 'Valaicherrypatti', lgdCode: '225241' },
    { district: 'MADURAI', block: 'KOTTAMPATTI', name: 'Vanjinagram', lgdCode: '225240' },
    { district: 'MADURAI', block: 'VADIPATTI', name: 'Andipatti', lgdCode: '225513' },
    { district: 'MADURAI', block: 'VADIPATTI', name: 'Irumpadi', lgdCode: '225515' },
    { district: 'MADURAI', block: 'VADIPATTI', name: 'Kattakkulam', lgdCode: '225519' },
    { district: 'MADURAI', block: 'VADIPATTI', name: 'Karuppatti', lgdCode: '225518' },
    { district: 'MADURAI', block: 'VADIPATTI', name: 'Kadupatti', lgdCode: '225517' },
    { district: 'MADURAI', block: 'VADIPATTI', name: 'Kuruvithurai', lgdCode: '225520' },
    { district: 'MADURAI', block: 'VADIPATTI', name: 'Katchaikatti', lgdCode: '225516' },
    { district: 'MADURAI', block: 'VADIPATTI', name: 'Kutladampatti', lgdCode: '225521' },
    { district: 'MADURAI', block: 'VADIPATTI', name: 'Melakkal', lgdCode: '225523' },
    { district: 'MADURAI', block: 'VADIPATTI', name: 'Mannadimangalam', lgdCode: '225522' },
    { district: 'MADURAI', block: 'VADIPATTI', name: 'Mullipallam', lgdCode: '225524' },
    { district: 'MADURAI', block: 'VADIPATTI', name: 'Nachikulam', lgdCode: '225525' },
    { district: 'MADURAI', block: 'VADIPATTI', name: 'Nedunkulam', lgdCode: '225526' },
    { district: 'MADURAI', block: 'VADIPATTI', name: 'C. Pudur', lgdCode: '225514' },
    { district: 'MADURAI', block: 'VADIPATTI', name: 'Rishabam', lgdCode: '225529' },
    { district: 'MADURAI', block: 'VADIPATTI', name: 'Sithalangudi', lgdCode: '225531' },
    { district: 'MADURAI', block: 'VADIPATTI', name: 'Thiruvalavayanallur', lgdCode: '225532' },
    { district: 'MADURAI', block: 'VADIPATTI', name: 'Thiruvedagam', lgdCode: '225534' },
    { district: 'MADURAI', block: 'VADIPATTI', name: 'Thenkarai', lgdCode: '225533' },
    { district: 'MADURAI', block: 'VADIPATTI', name: 'Viralipatti', lgdCode: '225535' },
    { district: 'MADURAI', block: 'VADIPATTI', name: 'Poochampatti', lgdCode: '225527' },
    { district: 'MADURAI', block: 'VADIPATTI', name: 'Ramayanpatti', lgdCode: '225528' },
    { district: 'MADURAI', block: 'VADIPATTI', name: 'Seminipatti', lgdCode: '225530' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'ACHAMPATTI', lgdCode: '225115' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'AYYUR', lgdCode: '225119' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'ALAGAPURI', lgdCode: '225116' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'AYYANKOTTAI', lgdCode: '225118' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'ATHANOOR', lgdCode: '225117' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'OORSERI', lgdCode: '225135' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'ERRAMPATTI', lgdCode: '225123' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'KALVELIPATTI', lgdCode: '225125' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'KALLANAI', lgdCode: '225124' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'KEELACHINNANAMPATTI', lgdCode: '225126' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'KUTTIMEIKKIPATTI', lgdCode: '225130' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'KODANGIPATTI', lgdCode: '225128' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'KONDAYAMPATTI', lgdCode: '225127' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'A.KOVILPATTI', lgdCode: '225114' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'CHATHIRAVELLALAPATTI', lgdCode: '225121' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'SENTHAMANGALAM', lgdCode: '225140' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'THANDALAI', lgdCode: '225142' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'THANICHIYAM', lgdCode: '225143' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'THETHTHUR', lgdCode: '225144' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'DEVASERI', lgdCode: '225145' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'MANIYANJI', lgdCode: '225132' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'MANICKAMPATTI', lgdCode: '225131' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'MELACHINNANAMPATTI', lgdCode: '225133' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: '15-B. METTUPATTI', lgdCode: '225120' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'T. METTUPATTI', lgdCode: '225141' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: '66.METTUPATTI', lgdCode: '225113' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'RAJAKKALPATTI', lgdCode: '225139' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'PARAIPATTI', lgdCode: '225137' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'PANNAIKUDI', lgdCode: '225136' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'PERIAILANTHAIKULAM', lgdCode: '225138' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'MUDUVARPATTI', lgdCode: '225134' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'VADUGAPATTI', lgdCode: '225146' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'VALAYAPATTI', lgdCode: '225147' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'VAVIDAMARUTHUR', lgdCode: '225148' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'VELLAIAMPATTI', lgdCode: '225149' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'KOTTAIMEDU', lgdCode: '225129' },
    { district: 'MADURAI', block: 'ALANGANALLUR', name: 'CHINNAILANTHAIKULAM', lgdCode: '225122' },
    { district: 'MADURAI', block: 'USILAMPATTI', name: 'Alligundam', lgdCode: '225495' },
    { district: 'MADURAI', block: 'USILAMPATTI', name: 'Dottappanaikanur', lgdCode: '225496' },
    { district: 'MADURAI', block: 'USILAMPATTI', name: 'Erumarapatti', lgdCode: '225497' },
    { district: 'MADURAI', block: 'USILAMPATTI', name: 'Jothilnaikanur', lgdCode: '225498' },
    { district: 'MADURAI', block: 'USILAMPATTI', name: 'Kalluthu', lgdCode: '225499' },
    { district: 'MADURAI', block: 'USILAMPATTI', name: 'Keeripatti', lgdCode: '225500' },
    { district: 'MADURAI', block: 'USILAMPATTI', name: 'Manuthu', lgdCode: '225501' },
    { district: 'MADURAI', block: 'USILAMPATTI', name: 'Meikkilarpatti', lgdCode: '225502' },
    { district: 'MADURAI', block: 'USILAMPATTI', name: 'Nakkalapatti', lgdCode: '225504' },
    { district: 'MADURAI', block: 'USILAMPATTI', name: 'Nalluthevanpatti', lgdCode: '225505' },
    { district: 'MADURAI', block: 'USILAMPATTI', name: 'Nadupatti', lgdCode: '225503' },
    { district: 'MADURAI', block: 'USILAMPATTI', name: 'Pothampatti', lgdCode: '225506' },
    { district: 'MADURAI', block: 'USILAMPATTI', name: 'Rajakkapatti', lgdCode: '225507' },
    { district: 'MADURAI', block: 'USILAMPATTI', name: 'Seemanoothu', lgdCode: '225508' },
    { district: 'MADURAI', block: 'USILAMPATTI', name: 'Thimmanatham', lgdCode: '225509' },
    { district: 'MADURAI', block: 'USILAMPATTI', name: 'Uthappanayakanur', lgdCode: '225510' },
    { district: 'MADURAI', block: 'USILAMPATTI', name: 'Vadugapatti', lgdCode: '225511' },
    { district: 'MADURAI', block: 'USILAMPATTI', name: 'Vagurani', lgdCode: '225512' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'ARIYAPATTY', lgdCode: '225151' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'AYYANARKULAM', lgdCode: '225152' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'PODUVARPATTY', lgdCode: '225165' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'POOTHIPURAM', lgdCode: '225166' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'ERVARPATTY', lgdCode: '225153' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'KOVILANKULAM', lgdCode: '225158' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'KARUMATHUR', lgdCode: '225155' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'KANNANUR', lgdCode: '225154' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'KURAVAKUDI', lgdCode: '225159' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'KATTAKARUPPANPATTY', lgdCode: '225156' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'KODIKULAM', lgdCode: '225157' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'MUDALAIKULAM', lgdCode: '225160' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'NATTARMANGALAM', lgdCode: '225161' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'PORUPPUMETTUPATTY', lgdCode: '225167' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'PULLANERI', lgdCode: '225169' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'PANNIYAN', lgdCode: '225163' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'PANAMOOPPANPATTY', lgdCode: '225162' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'POTTULUPATTY', lgdCode: '225168' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'PAPPAPATTI', lgdCode: '225164' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'A. PUDUPATTY', lgdCode: '225150' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'SEMPATTY', lgdCode: '225172' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'SAKKARAPPANAICKANOOR', lgdCode: '225171' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'SINTHUPATTY', lgdCode: '225173' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'SADACHIPATTY', lgdCode: '225170' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'THIDIYAN', lgdCode: '225174' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'THUMMAKUNDU', lgdCode: '225175' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'VALANTHUR', lgdCode: '225176' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'VEPPANOOTHU', lgdCode: '225177' },
    { district: 'MADURAI', block: 'CHELLAMPATTI', name: 'VIKRAMANGALAM', lgdCode: '225178' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'ATHANKARAIPATTI', lgdCode: '225346' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'ATHIKARIPATTI', lgdCode: '225347' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'ATHIPATTI', lgdCode: '225348' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'CHINNAKATTALAI', lgdCode: '225349' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'KALAPPANPATTI', lgdCode: '225351' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'KETHUVARPATTI', lgdCode: '225352' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'E. KOTTAIPATTY', lgdCode: '225350' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'KUDIPATTY', lgdCode: '225354' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'KUDICHERI', lgdCode: '225353' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'KUPPALNATHAM', lgdCode: '225355' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'MALLAPURAM', lgdCode: '225356' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'MELATHIRUMANICKAM', lgdCode: '225357' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'MUTHUNAGAIAPURAM', lgdCode: '225358' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'PALAIYUR', lgdCode: '225359' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'PAPPINAICKANPATTY', lgdCode: '225360' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'PERIAKATTALAI', lgdCode: '225362' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'PERAIYAMPATTY', lgdCode: '225361' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'PERUNGAMANALLUR', lgdCode: '225363' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'POOSALAPURAM', lgdCode: '225364' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'SAPTOOR', lgdCode: '225365' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'SEELNAICKANPATTY', lgdCode: '225367' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'SEDAPATTY', lgdCode: '225366' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'SOOLAPURAM', lgdCode: '225369' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'SEMBARANI', lgdCode: '225368' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'THADAIYAMPATTY', lgdCode: '225370' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'THIRUMANICKAM', lgdCode: '225371' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'THULLUKUTTINAICKANUR', lgdCode: '225372' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'UTHAPPURAM', lgdCode: '225373' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'VANDAPULI', lgdCode: '225374' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'VANDARI', lgdCode: '225375' },
    { district: 'MADURAI', block: 'SEDAPATTI', name: 'VEPPAMPATTY', lgdCode: '225376' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'AMMAPATTY', lgdCode: '225422' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'ALAMPATTY', lgdCode: '225420' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'ALAPALACHERI', lgdCode: '225421' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'KILAVANERI', lgdCode: '225430' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'KAPPALUR', lgdCode: '225426' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'KARISALPATTY', lgdCode: '225428' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'KEELAKKOTTAI', lgdCode: '225429' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'N. KAMATCHIPURAM', lgdCode: '225436' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'A. KOKKULAM', lgdCode: '225419' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'KINNIMANGALAM', lgdCode: '225431' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'K. PULIYANGKULAM', lgdCode: '225423' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'KANDAI', lgdCode: '225424' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'KANGEYANATHAM', lgdCode: '225425' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'KARADIGAL', lgdCode: '225427' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'MATHIPPANUR', lgdCode: '225434' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'MYKKUDI', lgdCode: '225432' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'MELAKKOTTAI', lgdCode: '225435' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'MARAVANKULAM', lgdCode: '225433' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'NADUVAKKOTTAI', lgdCode: '225438' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'NADUKOTTAI', lgdCode: '225437' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'PANNIKUNDU', lgdCode: '225439' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'POKKAMPATTY', lgdCode: '225440' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'PONNAMANGALAM', lgdCode: '225441' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'PUNGANKULAM', lgdCode: '225442' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'T. PUDUPATTY', lgdCode: '225448' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'RAYAPALAYAM', lgdCode: '225443' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'SATHANKUDI', lgdCode: '225444' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'SOWDARPATTY', lgdCode: '225447' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'SITHTHALAI', lgdCode: '225445' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'SORIKKAMPATTY', lgdCode: '225446' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'THANGALACHERI', lgdCode: '225449' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'THIRALI', lgdCode: '225450' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'UCHAPPATTY', lgdCode: '225451' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'URAPPANUR', lgdCode: '225452' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'VADAKARAI', lgdCode: '225453' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'VIRUSANGKULAM', lgdCode: '225456' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'VIDATHAKULAM', lgdCode: '225455' },
    { district: 'MADURAI', block: 'THIRUMANGALAM', name: 'VAGAIKULAM', lgdCode: '225454' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'P. ammapatty', lgdCode: '225397' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'V. ammapatty', lgdCode: '225415' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Appakkarai', lgdCode: '225378' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'S. arasapatty', lgdCode: '225405' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Chinnamuthulingapuram', lgdCode: '225379' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Chinnapoolampatty', lgdCode: '225380' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Chittulotti', lgdCode: '225382' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Chinnareddypatty', lgdCode: '225381' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Kenjampatty', lgdCode: '225386' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Kadaneri', lgdCode: '225384' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Karaikeni', lgdCode: '225385' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Goundanpatty', lgdCode: '225383' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'S. keelapatty', lgdCode: '225406' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Koovalappuram', lgdCode: '225388' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'L. kottanipatty', lgdCode: '225390' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Kilangkulam', lgdCode: '225387' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Kumarapuram', lgdCode: '225389' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'T. kunnathur', lgdCode: '225413' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Lakshimipuram', lgdCode: '225391' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Mathakkarai', lgdCode: '225394' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'S. melappatty', lgdCode: '225407' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Mothagam', lgdCode: '225395' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'P. muthulingapuram', lgdCode: '225398' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Nallamaram', lgdCode: '225396' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Pappaiyapuram', lgdCode: '225399' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Pappureddypatty', lgdCode: '225400' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'S.paraipatti', lgdCode: '225408' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Puliampatty', lgdCode: '225401' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Pulkkattai', lgdCode: '225402' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Rengapalayam', lgdCode: '225404' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Rawthanpatty', lgdCode: '225403' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Salisandai', lgdCode: '225409' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Santhaiyur', lgdCode: '225410' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'M. senkulam', lgdCode: '225392' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Silarpatty', lgdCode: '225412' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Silaimalaipatty', lgdCode: '225411' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'P. subbulapuram', lgdCode: '225393' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'A.thottiapatti', lgdCode: '225377' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Thummanayakanpatti', lgdCode: '225414' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Vaiyuir', lgdCode: '225416' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Vannivelampatty', lgdCode: '225417' },
    { district: 'MADURAI', block: 'T.KALLUPATTI', name: 'Velampur', lgdCode: '225418' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'T. Arasapatty', lgdCode: '225205' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Avalsooranpatti', lgdCode: '225179' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Chithur', lgdCode: '225180' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Karisalkalampatti', lgdCode: '225184' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Kurayur', lgdCode: '225186' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Kallikudi', lgdCode: '225183' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Koodakovil', lgdCode: '225185' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'T. Kokkulam', lgdCode: '225204' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Kallanai', lgdCode: '225182' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Maittanpatti', lgdCode: '225190' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Maravapatti', lgdCode: '225191' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Maruthangudi', lgdCode: '225192' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Melauppuligundu', lgdCode: '225193' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Nallamanayakanpatti', lgdCode: '225194' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Nesaneri', lgdCode: '225196' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Nedunkulam', lgdCode: '225195' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Odaipatty', lgdCode: '225197' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'M. Pudupatty', lgdCode: '225188' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'M. Pothanathi', lgdCode: '225187' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Saluppa Pillaiyar Natham', lgdCode: '225200' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Sivarakkottai', lgdCode: '225203' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Sennampatty', lgdCode: '225202' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Sengapadai', lgdCode: '225201' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Peikulam', lgdCode: '225198' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'M.Puliankulam', lgdCode: '225189' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Thennamanallur', lgdCode: '225206' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Thirumal', lgdCode: '225207' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Thoombagulam', lgdCode: '225208' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Ulagani', lgdCode: '225209' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Unnipatty', lgdCode: '225210' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'K.Vellakulam', lgdCode: '225181' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Veppankulam', lgdCode: '225213' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'S. Vellakulam', lgdCode: '225199' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Valaiyankulam', lgdCode: '225211' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Villur', lgdCode: '225214' },
    { district: 'MADURAI', block: 'KALLIKUDI', name: 'Veeraperumalpuram', lgdCode: '225212' }
];
