
import type { Panchayat } from './types';

export const NAGAPATTINAM_PANCHAYATS: Panchayat[] = [
    { district: 'NAGAPATTINAM', block: 'NAGAPATTINAM', name: 'Agalangan', lgdCode: '225748' },
    { district: 'NAGAPATTINAM', block: 'NAGAPATTINAM', name: 'Agraorathur', lgdCode: '225749' },
    { district: 'NAGAPATTINAM', block: 'NAGAPATTINAM', name: 'Akkaraipettai', lgdCode: '225750' },
    { district: 'NAGAPATTINAM', block: 'NAGAPATTINAM', name: 'Alangudi', lgdCode: '225751' },
    { district: 'NAGAPATTINAM', block: 'NAGAPATTINAM', name: 'Azhiyur', lgdCode: '225754' },
    { district: 'NAGAPATTINAM', block: 'NAGAPATTINAM', name: 'Andhanapeetai', lgdCode: '225752' },
    { district: 'NAGAPATTINAM', block: 'NAGAPATTINAM', name: 'Avarani', lgdCode: '225753' },
    { district: 'NAGAPATTINAM', block: 'NAGAPATTINAM', name: 'Ivanallur', lgdCode: '225755' },
    { district: 'NAGAPATTINAM', block: 'NAGAPATTINAM', name: 'Karuvelankadai', lgdCode: '225756' },
    { district: 'NAGAPATTINAM', block: 'NAGAPATTINAM', name: 'Kuruchi', lgdCode: '225757' },
    { district: 'NAGAPATTINAM', block: 'NAGAPATTINAM', name: 'Mahadanam', lgdCode: '225758' },
    { district: 'NAGAPATTINAM', block: 'NAGAPATTINAM', name: 'Manjakollai', lgdCode: '225759' },
    { district: 'NAGAPATTINAM', block: 'NAGAPATTINAM', name: 'Muttam', lgdCode: '225760' },
    { district: 'NAGAPATTINAM', block: 'NAGAPATTINAM', name: 'Orathur', lgdCode: '225761' },
    { district: 'NAGAPATTINAM', block: 'NAGAPATTINAM', name: 'Palaiyur', lgdCode: '225762' },
    { district: 'NAGAPATTINAM', block: 'NAGAPATTINAM', name: 'Pappakoil', lgdCode: '225763' },
    { district: 'NAGAPATTINAM', block: 'NAGAPATTINAM', name: 'Perunkadambanur', lgdCode: '225764' },
    { district: 'NAGAPATTINAM', block: 'NAGAPATTINAM', name: 'Poravacheri', lgdCode: '225765' },
    { district: 'NAGAPATTINAM', block: 'NAGAPATTINAM', name: 'Pudhucherry', lgdCode: '225766' },
    { district: 'NAGAPATTINAM', block: 'NAGAPATTINAM', name: 'Sembiyanmahadevi', lgdCode: '225768' },
    { district: 'NAGAPATTINAM', block: 'NAGAPATTINAM', name: 'Sangamangalam', lgdCode: '225767' },
    { district: 'NAGAPATTINAM', block: 'NAGAPATTINAM', name: 'Sikkal', lgdCode: '225769' },
    { district: 'NAGAPATTINAM', block: 'NAGAPATTINAM', name: 'Themangalam', lgdCode: '225770' },
    { district: 'NAGAPATTINAM', block: 'NAGAPATTINAM', name: 'Therku poigainallur', lgdCode: '225771' },
    { district: 'NAGAPATTINAM', block: 'NAGAPATTINAM', name: 'Thethi', lgdCode: '225772' },
    { district: 'NAGAPATTINAM', block: 'NAGAPATTINAM', name: 'Vadakku poigainallur', lgdCode: '225774' },
    { district: 'NAGAPATTINAM', block: 'NAGAPATTINAM', name: 'Vadagudi', lgdCode: '225773' },
    { district: 'NAGAPATTINAM', block: 'NAGAPATTINAM', name: 'Vadavur', lgdCode: '225775' },
    { district: 'NAGAPATTINAM', block: 'NAGAPATTINAM', name: 'Vadugacheri', lgdCode: '225776' },
    { district: 'NAGAPATTINAM', block: 'KEELAIYUR', name: 'CHINNATHUMBUR', lgdCode: '225536' },
    { district: 'NAGAPATTINAM', block: 'KEELAIYUR', name: 'ERAYANGUDI', lgdCode: '225538' },
    { district: 'NAGAPATTINAM', block: 'KEELAIYUR', name: 'ESANUR', lgdCode: '225539' },
    { district: 'NAGAPATTINAM', block: 'KEELAIYUR', name: 'ETTUKUDI', lgdCode: '225540' },
    { district: 'NAGAPATTINAM', block: 'KEELAIYUR', name: 'KARAPIDAGAI(NORTH)', lgdCode: '225541' },
    { district: 'NAGAPATTINAM', block: 'KEELAIYUR', name: 'KARAPIDAGAI(SOUTH)', lgdCode: '225542' },
    { district: 'NAGAPATTINAM', block: 'KEELAIYUR', name: 'KARUNKANNI', lgdCode: '225543' },
    { district: 'NAGAPATTINAM', block: 'KEELAIYUR', name: 'KIZHAPIDAGAI', lgdCode: '225545' },
    { district: 'NAGAPATTINAM', block: 'KEELAIYUR', name: 'KEELAIYUR', lgdCode: '225544' },
    { district: 'NAGAPATTINAM', block: 'KEELAIYUR', name: 'MADAPURAM', lgdCode: '225546' },
    { district: 'NAGAPATTINAM', block: 'KEELAIYUR', name: 'MEENAMANALLUR', lgdCode: '225547' },
    { district: 'NAGAPATTINAM', block: 'KEELAIYUR', name: 'MELAVALLAKARAI', lgdCode: '225548' },
    { district: 'NAGAPATTINAM', block: 'KEELAIYUR', name: 'PALAKURCHI', lgdCode: '225549' },
    { district: 'NAGAPATTINAM', block: 'KEELAIYUR', name: 'PRATHAMARAMAPURAM', lgdCode: '225550' },
    { district: 'NAGAPATTINAM', block: 'KEELAIYUR', name: 'PUDUPALLI', lgdCode: '225551' },
    { district: 'NAGAPATTINAM', block: 'KEELAIYUR', name: 'CHOLAVIDYHAPURAM', lgdCode: '225537' },
    { district: 'NAGAPATTINAM', block: 'KEELAIYUR', name: 'THALAYAMALAI', lgdCode: '225552' },
    { district: 'NAGAPATTINAM', block: 'KEELAIYUR', name: 'THANNILAPADI', lgdCode: '225553' },
    { district: 'NAGAPATTINAM', block: 'KEELAIYUR', name: 'THIRUKUVALAI', lgdCode: '225554' },
    { district: 'NAGAPATTINAM', block: 'KEELAIYUR', name: 'THIRUPOONDI(E)', lgdCode: '225555' },
    { district: 'NAGAPATTINAM', block: 'KEELAIYUR', name: 'THIRUPOONDI(W)', lgdCode: '225556' },
    { district: 'NAGAPATTINAM', block: 'KEELAIYUR', name: 'THIRUVOIMOORE', lgdCode: '225557' },
    { district: 'NAGAPATTINAM', block: 'KEELAIYUR', name: 'VALAKARAI', lgdCode: '225558' },
    { district: 'NAGAPATTINAM', block: 'KEELAIYUR', name: 'VEPPANCHERY', lgdCode: '225560' },
    { district: 'NAGAPATTINAM', block: 'KEELAIYUR', name: 'VENMANACHERY', lgdCode: '225559' },
    { district: 'NAGAPATTINAM', block: 'KEELAIYUR', name: 'VETTAIKARANIRUPPU', lgdCode: '225561' },
    { district: 'NAGAPATTINAM', block: 'KEELAIYUR', name: 'VILUNTHAMAVADI', lgdCode: '225562' },
    { district: 'NAGAPATTINAM', block: 'KILVELUR', name: 'AGARAKADAMBUNUR', lgdCode: '225568' },
    { district: 'NAGAPATTINAM', block: 'KILVELUR', name: '75 ANAKUDI', lgdCode: '225566' },
    { district: 'NAGAPATTINAM', block: 'KILVELUR', name: 'ANTHAKUDI', lgdCode: '225570' },
    { district: 'NAGAPATTINAM', block: 'KILVELUR', name: '119 ANAKUDI', lgdCode: '225564' },
    { district: 'NAGAPATTINAM', block: 'KILVELUR', name: 'ATHIPULIYUR', lgdCode: '225571' },
    { district: 'NAGAPATTINAM', block: 'KILVELUR', name: 'ATHAMANGALAM', lgdCode: '225567' },
    { district: 'NAGAPATTINAM', block: 'KILVELUR', name: 'ANAIMANGALAM', lgdCode: '225569' },
    { district: 'NAGAPATTINAM', block: 'KILVELUR', name: 'ERVANCHERY', lgdCode: '225574' },
    { district: 'NAGAPATTINAM', block: 'KILVELUR', name: 'ELUPPUR', lgdCode: '225572' },
    { district: 'NAGAPATTINAM', block: 'KILVELUR', name: 'ERUKKAI', lgdCode: '225573' },
    { district: 'NAGAPATTINAM', block: 'KILVELUR', name: 'KAKKAZHANI', lgdCode: '225575' },
    { district: 'NAGAPATTINAM', block: 'KILVELUR', name: 'KILLUKUDI', lgdCode: '225576' },
    { district: 'NAGAPATTINAM', block: 'KILVELUR', name: 'KODIYALATHUR', lgdCode: '225577' },
    { district: 'NAGAPATTINAM', block: 'KILVELUR', name: 'KOHOORE', lgdCode: '225578' },
    { district: 'NAGAPATTINAM', block: 'KILVELUR', name: 'KOILKANNAPPUR', lgdCode: '225579' },
    { district: 'NAGAPATTINAM', block: 'KILVELUR', name: 'KORATHANKUDI', lgdCode: '225581' },
    { district: 'NAGAPATTINAM', block: 'KILVELUR', name: 'KURUKKAATHI', lgdCode: '225582' },
    { district: 'NAGAPATTINAM', block: 'KILVELUR', name: 'KURUMANANKUDI', lgdCode: '225583' },
    { district: 'NAGAPATTINAM', block: 'KILVELUR', name: 'KOOTTHUR', lgdCode: '225580' },
    { district: 'NAGAPATTINAM', block: 'KILVELUR', name: '105 MANALUR', lgdCode: '225563' },
    { district: 'NAGAPATTINAM', block: 'KILVELUR', name: '64 MANALUR', lgdCode: '225565' },
    { district: 'NAGAPATTINAM', block: 'KILVELUR', name: 'OKKUR', lgdCode: '225585' },
    { district: 'NAGAPATTINAM', block: 'KILVELUR', name: 'PATTAMANGALAM', lgdCode: '225586' },
    { district: 'NAGAPATTINAM', block: 'KILVELUR', name: 'RADAMANGALAM', lgdCode: '225587' },
    { district: 'NAGAPATTINAM', block: 'KILVELUR', name: 'SATIYAKUDI', lgdCode: '225588' },
    { district: 'NAGAPATTINAM', block: 'KILVELUR', name: 'SERUNALLUR', lgdCode: '225589' },
    { district: 'NAGAPATTINAM', block: 'KILVELUR', name: 'SIGAR', lgdCode: '225590' },
    { district: 'NAGAPATTINAM', block: 'KILVELUR', name: 'THERKUPANAIYUR', lgdCode: '225591' },
    { district: 'NAGAPATTINAM', block: 'KILVELUR', name: 'THEVUR', lgdCode: '225592' },
    { district: 'NAGAPATTINAM', block: 'KILVELUR', name: 'MOHANUR', lgdCode: '225584' },
    { district: 'NAGAPATTINAM', block: 'KILVELUR', name: 'THIRUKANNANKUDI', lgdCode: '225593' },
    { district: 'NAGAPATTINAM', block: 'KILVELUR', name: 'VADAKARAI', lgdCode: '225595' },
    { district: 'NAGAPATTINAM', block: 'KILVELUR', name: 'VADAKALATHUR', lgdCode: '225594' },
    { district: 'NAGAPATTINAM', block: 'KILVELUR', name: 'VANDALUR', lgdCode: '225598' },
    { district: 'NAGAPATTINAM', block: 'KILVELUR', name: 'VALIVALAM', lgdCode: '225597' },
    { district: 'NAGAPATTINAM', block: 'KILVELUR', name: 'VENKIDANGAL', lgdCode: '225599' },
    { district: 'NAGAPATTINAM', block: 'KILVELUR', name: 'VADAKKUPANAIYUR', lgdCode: '225596' },
    { district: 'NAGAPATTINAM', block: 'KILVELUR', name: 'VENMANI', lgdCode: '225600' },
    { district: 'NAGAPATTINAM', block: 'THIRUMARUGAL', name: 'Agarakonthagai', lgdCode: '225896' },
    { district: 'NAGAPATTINAM', block: 'THIRUMARUGAL', name: 'Alathur', lgdCode: '225897' },
    { district: 'NAGAPATTINAM', block: 'THIRUMARUGAL', name: 'Ambal', lgdCode: '225898' },
    { district: 'NAGAPATTINAM', block: 'THIRUMARUGAL', name: 'Adhalaiyur', lgdCode: '225895' },
    { district: 'NAGAPATTINAM', block: 'THIRUMARUGAL', name: 'Edaiyathankudi', lgdCode: '225899' },
    { district: 'NAGAPATTINAM', block: 'THIRUMARUGAL', name: 'Enangudi', lgdCode: '225900' },
    { district: 'NAGAPATTINAM', block: 'THIRUMARUGAL', name: 'Ervancheri', lgdCode: '225902' },
    { district: 'NAGAPATTINAM', block: 'THIRUMARUGAL', name: 'Ervadi', lgdCode: '225901' },
    { district: 'NAGAPATTINAM', block: 'THIRUMARUGAL', name: 'Gopurajapuram', lgdCode: '225903' },
    { district: 'NAGAPATTINAM', block: 'THIRUMARUGAL', name: 'Kangalancheri', lgdCode: '225904' },
    { district: 'NAGAPATTINAM', block: 'THIRUMARUGAL', name: 'Karaiyur', lgdCode: '225905' },
    { district: 'NAGAPATTINAM', block: 'THIRUMARUGAL', name: 'Kattumavadi', lgdCode: '225906' },
    { district: 'NAGAPATTINAM', block: 'THIRUMARUGAL', name: 'Keelaputhanur', lgdCode: '225907' },
    { district: 'NAGAPATTINAM', block: 'THIRUMARUGAL', name: 'Keelathanjavur', lgdCode: '225908' },
    { district: 'NAGAPATTINAM', block: 'THIRUMARUGAL', name: 'Kongarayanallur', lgdCode: '225909' },
    { district: 'NAGAPATTINAM', block: 'THIRUMARUGAL', name: 'Kothamangalam', lgdCode: '225910' },
    { district: 'NAGAPATTINAM', block: 'THIRUMARUGAL', name: 'Kottarakudi', lgdCode: '225911' },
    { district: 'NAGAPATTINAM', block: 'THIRUMARUGAL', name: 'Kottur', lgdCode: '225912' },
    { district: 'NAGAPATTINAM', block: 'THIRUMARUGAL', name: 'Kuthalam', lgdCode: '225913' },
    { district: 'NAGAPATTINAM', block: 'THIRUMARUGAL', name: 'Marungur', lgdCode: '225914' },
    { district: 'NAGAPATTINAM', block: 'THIRUMARUGAL', name: 'Narimanam', lgdCode: '225915' },
    { district: 'NAGAPATTINAM', block: 'THIRUMARUGAL', name: 'Neikkuppai', lgdCode: '225916' },
    { district: 'NAGAPATTINAM', block: 'THIRUMARUGAL', name: 'Panangudi', lgdCode: '225917' },
    { district: 'NAGAPATTINAM', block: 'THIRUMARUGAL', name: 'Pandaravadai', lgdCode: '225918' },
    { district: 'NAGAPATTINAM', block: 'THIRUMARUGAL', name: 'Pillali', lgdCode: '225919' },
    { district: 'NAGAPATTINAM', block: 'THIRUMARUGAL', name: 'Polagam', lgdCode: '225920' },
    { district: 'NAGAPATTINAM', block: 'THIRUMARUGAL', name: 'Puthagaram', lgdCode: '225921' },
    { district: 'NAGAPATTINAM', block: 'THIRUMARUGAL', name: 'Raranthimangalam', lgdCode: '225922' },
    { district: 'NAGAPATTINAM', block: 'THIRUMARUGAL', name: 'Seshamoolai', lgdCode: '225924' },
    { district: 'NAGAPATTINAM', block: 'THIRUMARUGAL', name: 'Seeyathamangai', lgdCode: '225923' },
    { district: 'NAGAPATTINAM', block: 'THIRUMARUGAL', name: 'Thiruchankattangudi', lgdCode: '225925' },
    { district: 'NAGAPATTINAM', block: 'THIRUMARUGAL', name: 'Thirukkannapuram', lgdCode: '225926' },
    { district: 'NAGAPATTINAM', block: 'THIRUMARUGAL', name: 'Thirumarugal', lgdCode: '225927' },
    { district: 'NAGAPATTINAM', block: 'THIRUMARUGAL', name: 'Thirupayathangudi', lgdCode: '225928' },
    { district: 'NAGAPATTINAM', block: 'THIRUMARUGAL', name: 'Thirupugalur', lgdCode: '225929' },
    { district: 'NAGAPATTINAM', block: 'THIRUMARUGAL', name: 'Uthamacholapuram', lgdCode: '225930' },
    { district: 'NAGAPATTINAM', block: 'THIRUMARUGAL', name: 'Vadakarai', lgdCode: '225931' },
    { district: 'NAGAPATTINAM', block: 'THIRUMARUGAL', name: 'Valkudi', lgdCode: '225932' },
    { district: 'NAGAPATTINAM', block: 'THIRUMARUGAL', name: 'Virkudi', lgdCode: '225933' },
    { district: 'NAGAPATTINAM', block: 'THALAINAYAR', name: 'Aymoor', lgdCode: '225872' },
    { district: 'NAGAPATTINAM', block: 'THALAINAYAR', name: 'Avarikadu', lgdCode: '225871' },
    { district: 'NAGAPATTINAM', block: 'THALAINAYAR', name: 'Katchanagaram', lgdCode: '225875' },
    { district: 'NAGAPATTINAM', block: 'THALAINAYAR', name: 'Kallimedu', lgdCode: '225874' },
    { district: 'NAGAPATTINAM', block: 'THALAINAYAR', name: 'Kadanthethi', lgdCode: '225873' },
    { district: 'NAGAPATTINAM', block: 'THALAINAYAR', name: 'Kolappadu', lgdCode: '225876' },
    { district: 'NAGAPATTINAM', block: 'THALAINAYAR', name: 'Kothangudi', lgdCode: '225877' },
    { district: 'NAGAPATTINAM', block: 'THALAINAYAR', name: 'Kovilpathu', lgdCode: '225878' },
    { district: 'NAGAPATTINAM', block: 'THALAINAYAR', name: 'Manakkudi', lgdCode: '225879' },
    { district: 'NAGAPATTINAM', block: 'THALAINAYAR', name: 'Naluvedapathy', lgdCode: '225880' },
    { district: 'NAGAPATTINAM', block: 'THALAINAYAR', name: 'Nathapallam', lgdCode: '225881' },
    { district: 'NAGAPATTINAM', block: 'THALAINAYAR', name: 'Neermulai', lgdCode: '225882' },
    { district: 'NAGAPATTINAM', block: 'THALAINAYAR', name: 'Pangal', lgdCode: '225884' },
    { district: 'NAGAPATTINAM', block: 'THALAINAYAR', name: 'Panangadi', lgdCode: '225883' },
    { district: 'NAGAPATTINAM', block: 'THALAINAYAR', name: 'Pannatheru', lgdCode: '225885' },
    { district: 'NAGAPATTINAM', block: 'THALAINAYAR', name: 'Puthur', lgdCode: '225886' },
    { district: 'NAGAPATTINAM', block: 'THALAINAYAR', name: 'Sithaimoor', lgdCode: '225887' },
    { district: 'NAGAPATTINAM', block: 'THALAINAYAR', name: 'Thamaraipulam', lgdCode: '225888' },
    { district: 'NAGAPATTINAM', block: 'THALAINAYAR', name: 'Thiruvidamaruthur', lgdCode: '225889' },
    { district: 'NAGAPATTINAM', block: 'THALAINAYAR', name: 'Thulasapuram', lgdCode: '225890' },
    { district: 'NAGAPATTINAM', block: 'THALAINAYAR', name: 'Umbalacheri', lgdCode: '225891' },
    { district: 'NAGAPATTINAM', block: 'THALAINAYAR', name: 'Vadugoor', lgdCode: '225892' },
    { district: 'NAGAPATTINAM', block: 'THALAINAYAR', name: 'Vattakudi', lgdCode: '225893' },
    { district: 'NAGAPATTINAM', block: 'THALAINAYAR', name: 'Vellappallam', lgdCode: '225894' },
    { district: 'NAGAPATTINAM', block: 'VEDARANYAM', name: 'Adhanur', lgdCode: '225934' },
    { district: 'NAGAPATTINAM', block: 'VEDARANYAM', name: 'Annapettai', lgdCode: '225935' },
    { district: 'NAGAPATTINAM', block: 'VEDARANYAM', name: 'Ayakkaranpulam 1', lgdCode: '225936' },
    { district: 'NAGAPATTINAM', block: 'VEDARANYAM', name: 'Ayakkaranpulam 2', lgdCode: '225937' },
    { district: 'NAGAPATTINAM', block: 'VEDARANYAM', name: 'Ayakkaranpulam 3', lgdCode: '225938' },
    { district: 'NAGAPATTINAM', block: 'VEDARANYAM', name: 'Ayakkaranpulam 4', lgdCode: '225939' },
    { district: 'NAGAPATTINAM', block: 'VEDARANYAM', name: 'Chettipulam', lgdCode: '225940' },
    { district: 'NAGAPATTINAM', block: 'VEDARANYAM', name: 'Kadinelvayal', lgdCode: '225941' },
    { district: 'NAGAPATTINAM', block: 'VEDARANYAM', name: 'Kariyapattinam', lgdCode: '225942' },
    { district: 'NAGAPATTINAM', block: 'VEDARANYAM', name: 'Karuppampulam', lgdCode: '225943' },
    { district: 'NAGAPATTINAM', block: 'VEDARANYAM', name: 'Katharipulam', lgdCode: '225944' },
    { district: 'NAGAPATTINAM', block: 'VEDARANYAM', name: 'Kodiyakkarai', lgdCode: '225945' },
    { district: 'NAGAPATTINAM', block: 'VEDARANYAM', name: 'Kodiyakkadu', lgdCode: '225946' },
    { district: 'NAGAPATTINAM', block: 'VEDARANYAM', name: 'Kuravapulam', lgdCode: '225947' },
    { district: 'NAGAPATTINAM', block: 'VEDARANYAM', name: 'Maruthur north', lgdCode: '225948' },
    { district: 'NAGAPATTINAM', block: 'VEDARANYAM', name: 'Maruthur south', lgdCode: '225949' },
    { district: 'NAGAPATTINAM', block: 'VEDARANYAM', name: 'Moolakkarai', lgdCode: '225950' },
    { district: 'NAGAPATTINAM', block: 'VEDARANYAM', name: 'Nagakudaiyan', lgdCode: '225951' },
    { district: 'NAGAPATTINAM', block: 'VEDARANYAM', name: 'Neivilakku', lgdCode: '225952' },
    { district: 'NAGAPATTINAM', block: 'VEDARANYAM', name: 'Panchanathikulam east', lgdCode: '225953' },
    { district: 'NAGAPATTINAM', block: 'VEDARANYAM', name: 'Panchanathikulam middle', lgdCode: '225954' },
    { district: 'NAGAPATTINAM', block: 'VEDARANYAM', name: 'Panchanathikulam west', lgdCode: '225955' },
    { district: 'NAGAPATTINAM', block: 'VEDARANYAM', name: 'Pannal', lgdCode: '225956' },
    { district: 'NAGAPATTINAM', block: 'VEDARANYAM', name: 'Periyakuthagai', lgdCode: '225957' },
    { district: 'NAGAPATTINAM', block: 'VEDARANYAM', name: 'Piranthiyankarai', lgdCode: '225958' },
    { district: 'NAGAPATTINAM', block: 'VEDARANYAM', name: 'Pushpavanam', lgdCode: '225959' },
    { district: 'NAGAPATTINAM', block: 'VEDARANYAM', name: 'Senbagarayanallur', lgdCode: '225961' },
    { district: 'NAGAPATTINAM', block: 'VEDARANYAM', name: 'Sembodai', lgdCode: '225960' },
    { district: 'NAGAPATTINAM', block: 'VEDARANYAM', name: 'Thagattur', lgdCode: '225962' },
    { district: 'NAGAPATTINAM', block: 'VEDARANYAM', name: 'Thanikkottagam', lgdCode: '225963' },
    { district: 'NAGAPATTINAM', block: 'VEDARANYAM', name: 'Thennadar', lgdCode: '225964' },
    { district: 'NAGAPATTINAM', block: 'VEDARANYAM', name: 'Thethagudi north', lgdCode: '225965' },
    { district: 'NAGAPATTINAM', block: 'VEDARANYAM', name: 'Thethagudi south', lgdCode: '225966' },
    { district: 'NAGAPATTINAM', block: 'VEDARANYAM', name: 'Vadamazhai Manakkadu', lgdCode: '225967' },
    { district: 'NAGAPATTINAM', block: 'VEDARANYAM', name: 'Voimedu', lgdCode: '225968' },
    { district: 'NAGAPATTINAM', block: 'VEDARANYAM', name: 'Vanduvancheri', lgdCode: '225969' },
];
