
import type { Panchayat } from './types';

export const NAMAKKAL_PANCHAYATS: Panchayat[] = [
    { district: 'NAMAKKAL', block: 'Elachipalayam', name: '85 Goundampalayam', lgdCode: '225970' },
    { district: 'NAMAKKAL', block: 'Elachipalayam', name: '87 Goundampalayam', lgdCode: '225971' },
    { district: 'NAMAKKAL', block: 'Elachipalayam', name: 'Agaram', lgdCode: '225972' },
    { district: 'NAMAKKAL', block: 'Elachipalayam', name: 'Akalampatti', lgdCode: '225973' },
    { district: 'NAMAKKAL', block: 'Elachipalayam', name: 'Bommampatti', lgdCode: '225974' },
    { district: 'NAMAKKAL', block: 'Elachipalayam', name: 'Chinnamanali', lgdCode: '225975' },
    { district: 'NAMAKKAL', block: 'Elachipalayam', name: 'Elanagar', lgdCode: '225976' },
    { district: 'NAMAKKAL', block: 'Elachipalayam', name: 'Iluppuli', lgdCode: '225977' },
    { district: 'NAMAKKAL', block: 'Elachipalayam', name: 'Kilappalayam', lgdCode: '225978' },
    { district: 'NAMAKKAL', block: 'Elachipalayam', name: 'Kokkalai', lgdCode: '225979' },
    { district: 'NAMAKKAL', block: 'Elachipalayam', name: 'Konnaiyar', lgdCode: '225980' },
    { district: 'NAMAKKAL', block: 'Elachipalayam', name: 'Koothampoondi', lgdCode: '225981' },
    { district: 'NAMAKKAL', block: 'Elachipalayam', name: 'Kuppandapalayam', lgdCode: '225982' },
    { district: 'NAMAKKAL', block: 'Elachipalayam', name: 'Lathuvadi', lgdCode: '225983' },
    { district: 'NAMAKKAL', block: 'Elachipalayam', name: 'Manathi', lgdCode: '225984' },
    { district: 'NAMAKKAL', block: 'Elachipalayam', name: 'Mandagapalayam', lgdCode: '225985' },
    { district: 'NAMAKKAL', block: 'Elachipalayam', name: 'Marukkalampatti', lgdCode: '225986' },
    { district: 'NAMAKKAL', block: 'Elachipalayam', name: 'Mavureddipatti', lgdCode: '225987' },
    { district: 'NAMAKKAL', block: 'Elachipalayam', name: 'Molipalli', lgdCode: '225988' },
    { district: 'NAMAKKAL', block: 'Elachipalayam', name: 'Musiri', lgdCode: '225989' },
    { district: 'NAMAKKAL', block: 'Elachipalayam', name: 'Nallipalayam', lgdCode: '225990' },
    { district: 'NAMAKKAL', block: 'Elachipalayam', name: 'Pokkampalayam', lgdCode: '225992' },
    { district: 'NAMAKKAL', block: 'Elachipalayam', name: 'Pullagoundampatti', lgdCode: '225993' },
    { district: 'NAMAKKAL', block: 'Elachipalayam', name: 'Punjaipudupalayam', lgdCode: '225994' },
    { district: 'NAMAKKAL', block: 'Elachipalayam', name: 'Puthur East', lgdCode: '225995' },
    { district: 'NAMAKKAL', block: 'Elachipalayam', name: 'Sakthinaickenpalayam', lgdCode: '225996' },
    { district: 'NAMAKKAL', block: 'Elachipalayam', name: 'Thondipatti', lgdCode: '225997' },
    { district: 'NAMAKKAL', block: 'Elachipalayam', name: 'Unjanai', lgdCode: '225998' },
    { district: 'NAMAKKAL', block: 'Elachipalayam', name: 'Periyamanali', lgdCode: '225991' },
    { district: 'NAMAKKAL', block: 'ERUMAPATTY', name: 'ALANGANATHAM', lgdCode: '225999' },
    { district: 'NAMAKKAL', block: 'ERUMAPATTY', name: 'BODINAICKENPATTI', lgdCode: '226000' },
    { district: 'NAMAKKAL', block: 'ERUMAPATTY', name: 'BOMMASAMUTHIRAM', lgdCode: '226001' },
    { district: 'NAMAKKAL', block: 'ERUMAPATTY', name: 'DEVARAYAPURAM', lgdCode: '226002' },
    { district: 'NAMAKKAL', block: 'ERUMAPATTY', name: 'KAVAKARANPATTI', lgdCode: '226003' },
    { district: 'NAMAKKAL', block: 'ERUMAPATTY', name: 'KODIKKALPUDUR', lgdCode: '226004' },
    { district: 'NAMAKKAL', block: 'ERUMAPATTY', name: 'KONANGIPATTI', lgdCode: '226005' },
    { district: 'NAMAKKAL', block: 'ERUMAPATTY', name: 'M. METTUPATTI', lgdCode: '226006' },
    { district: 'NAMAKKAL', block: 'ERUMAPATTY', name: 'MUTHUGAPATTTI', lgdCode: '226007' },
    { district: 'NAMAKKAL', block: 'ERUMAPATTY', name: 'MUTTANCHETTI', lgdCode: '226008' },
    { district: 'NAMAKKAL', block: 'ERUMAPATTY', name: 'SARKARPALAYAPALAYAM', lgdCode: '226009' },
    { district: 'NAMAKKAL', block: 'ERUMAPATTY', name: 'PAVITHIRAM', lgdCode: '226010' },
    { district: 'NAMAKKAL', block: 'ERUMAPATTY', name: 'PAVITHIRAMPUDUR', lgdCode: '226011' },
    { district: 'NAMAKKAL', block: 'ERUMAPATTY', name: 'PERUMAPATTI', lgdCode: '226012' },
    { district: 'NAMAKKAL', block: 'ERUMAPATTY', name: 'POTTIREDDIPATTI', lgdCode: '226013' },
    { district: 'NAMAKKAL', block: 'ERUMAPATTY', name: 'PUDUKOTTAI', lgdCode: '226014' },
    { district: 'NAMAKKAL', block: 'ERUMAPATTY', name: 'REDDIPATTI', lgdCode: '226015' },
    { district: 'NAMAKKAL', block: 'ERUMAPATTY', name: 'SEVINTHIPATTI', lgdCode: '226016' },
    { district: 'NAMAKKAL', block: 'ERUMAPATTY', name: 'SIVANAICKENPATTI', lgdCode: '226017' },
    { district: 'NAMAKKAL', block: 'ERUMAPATTY', name: 'THIPRAMADEVI', lgdCode: '226018' },
    { district: 'NAMAKKAL', block: 'ERUMAPATTY', name: 'VADAVATHUR', lgdCode: '226019' },
    { district: 'NAMAKKAL', block: 'ERUMAPATTY', name: 'AGRAHARA VALAVANTHI', lgdCode: '226020' },
    { district: 'NAMAKKAL', block: 'ERUMAPATTY', name: 'VARADHARAJAPURAM', lgdCode: '226021' },
    { district: 'NAMAKKAL', block: 'ERUMAPATTY', name: 'VARAGUR', lgdCode: '226022' },
    { district: 'NAMAKKAL', block: 'KABILARMALAI', name: 'A Kunnathur', lgdCode: '226023' },
    { district: 'NAMAKKAL', block: 'KABILARMALAI', name: 'Anangur', lgdCode: '226024' },
    { district: 'NAMAKKAL', block: 'KABILARMALAI', name: 'Irukkur', lgdCode: '226025' },
    { district: 'NAMAKKAL', block: 'KABILARMALAI', name: 'Kabilakurichi', lgdCode: '226026' },
    { district: 'NAMAKKAL', block: 'KABILARMALAI', name: 'Kondalam', lgdCode: '226027' },
    { district: 'NAMAKKAL', block: 'KABILARMALAI', name: 'Koppanampalayam', lgdCode: '226028' },
    { district: 'NAMAKKAL', block: 'KABILARMALAI', name: 'Kothamangalam', lgdCode: '226029' },
    { district: 'NAMAKKAL', block: 'KABILARMALAI', name: 'Kupprikkapalayam', lgdCode: '226030' },
    { district: 'NAMAKKAL', block: 'KABILARMALAI', name: 'Kurumbalamahadevi', lgdCode: '226031' },
    { district: 'NAMAKKAL', block: 'KABILARMALAI', name: 'Periasolipalayam', lgdCode: '226032' },
    { district: 'NAMAKKAL', block: 'KABILARMALAI', name: 'Perunkurichi', lgdCode: '226033' },
    { district: 'NAMAKKAL', block: 'KABILARMALAI', name: 'Pilikkalpalayam', lgdCode: '226034' },
    { district: 'NAMAKKAL', block: 'KABILARMALAI', name: 'Selur', lgdCode: '226035' },
    { district: 'NAMAKKAL', block: 'KABILARMALAI', name: 'Sirunallikoil', lgdCode: '226036' },
    { district: 'NAMAKKAL', block: 'KABILARMALAI', name: 'Solasiramani', lgdCode: '226037' },
    { district: 'NAMAKKAL', block: 'KABILARMALAI', name: 'Sullipalayam', lgdCode: '226038' },
    { district: 'NAMAKKAL', block: 'KABILARMALAI', name: 'T Goundampalayam', lgdCode: '226039' },
    { district: 'NAMAKKAL', block: 'KABILARMALAI', name: 'Thidumal', lgdCode: '226040' },
    { district: 'NAMAKKAL', block: 'KABILARMALAI', name: 'Vadakaraiyattur', lgdCode: '226041' },
    { district: 'NAMAKKAL', block: 'KABILARMALAI', name: 'Zamin Elampalli', lgdCode: '226042' },
    { district: 'NAMAKKAL', block: 'KOLLIHILLS', name: 'Ariyur Nadu', lgdCode: '226044' },
    { district: 'NAMAKKAL', block: 'KOLLIHILLS', name: 'Bail Nadu', lgdCode: '226045' },
    { district: 'NAMAKKAL', block: 'KOLLIHILLS', name: 'Devannur Nadu', lgdCode: '226047' },
    { district: 'NAMAKKAL', block: 'KOLLIHILLS', name: 'Edapuli Nadu', lgdCode: '226048' },
    { district: 'NAMAKKAL', block: 'KOLLIHILLS', name: 'Gundur Nadu', lgdCode: '226049' },
    { district: 'NAMAKKAL', block: 'KOLLIHILLS', name: 'Gunduni Nadu', lgdCode: '226050' },
    { district: 'NAMAKKAL', block: 'KOLLIHILLS', name: 'Perakkarai Nadu', lgdCode: '226051' },
    { district: 'NAMAKKAL', block: 'KOLLIHILLS', name: 'Selur Nadu', lgdCode: '226052' },
    { district: 'NAMAKKAL', block: 'KOLLIHILLS', name: 'Chittoor Nadu', lgdCode: '226046' },
    { district: 'NAMAKKAL', block: 'KOLLIHILLS', name: 'Thinnanur Nadu', lgdCode: '226053' },
    { district: 'NAMAKKAL', block: 'KOLLIHILLS', name: 'Thirupuli Nadu', lgdCode: '226054' },
    { district: 'NAMAKKAL', block: 'KOLLIHILLS', name: 'Valappur Nadu', lgdCode: '226055' },
    { district: 'NAMAKKAL', block: 'KOLLIHILLS', name: 'Valavanthi Nadu', lgdCode: '226056' },
    { district: 'NAMAKKAL', block: 'KOLLIHILLS', name: 'Alathur Nadu', lgdCode: '226043' },
    { district: 'NAMAKKAL', block: 'MALLASAMUDRAM', name: 'Avinashipatti', lgdCode: '226057' },
    { district: 'NAMAKKAL', block: 'MALLASAMUDRAM', name: 'Ballakuli', lgdCode: '226058' },
    { district: 'NAMAKKAL', block: 'MALLASAMUDRAM', name: 'Ballakuli Agraharam', lgdCode: '226059' },
    { district: 'NAMAKKAL', block: 'MALLASAMUDRAM', name: 'Irukalur Pudupalayam', lgdCode: '226060' },
    { district: 'NAMAKKAL', block: 'MALLASAMUDRAM', name: 'Kallupalayam', lgdCode: '226061' },
    { district: 'NAMAKKAL', block: 'MALLASAMUDRAM', name: 'Karumanur', lgdCode: '226062' },
    { district: 'NAMAKKAL', block: 'MALLASAMUDRAM', name: 'Karungalpatti Agraharam', lgdCode: '226063' },
    { district: 'NAMAKKAL', block: 'MALLASAMUDRAM', name: 'Kolankondai', lgdCode: '226064' },
    { district: 'NAMAKKAL', block: 'MALLASAMUDRAM', name: 'Koothanatham', lgdCode: '226065' },
    { district: 'NAMAKKAL', block: 'MALLASAMUDRAM', name: 'Kottapalayam', lgdCode: '226066' },
    { district: 'NAMAKKAL', block: 'MALLASAMUDRAM', name: 'Kuppichipalayam', lgdCode: '226067' },
    { district: 'NAMAKKAL', block: 'MALLASAMUDRAM', name: 'Mallasamudram Melmugam', lgdCode: '226068' },
    { district: 'NAMAKKAL', block: 'MALLASAMUDRAM', name: 'Mamundi Agraharam', lgdCode: '226069' },
    { district: 'NAMAKKAL', block: 'MALLASAMUDRAM', name: 'Mangalam', lgdCode: '226070' },
    { district: 'NAMAKKAL', block: 'MALLASAMUDRAM', name: 'Maraparai', lgdCode: '226071' },
    { district: 'NAMAKKAL', block: 'MALLASAMUDRAM', name: 'Minnampalli', lgdCode: '226072' },
    { district: 'NAMAKKAL', block: 'MALLASAMUDRAM', name: 'Munjanur', lgdCode: '226074' },
    { district: 'NAMAKKAL', block: 'MALLASAMUDRAM', name: 'Morangam', lgdCode: '226073' },
    { district: 'NAMAKKAL', block: 'MALLASAMUDRAM', name: 'Nagarpalayam', lgdCode: '226075' },
    { district: 'NAMAKKAL', block: 'MALLASAMUDRAM', name: 'Palamedu', lgdCode: '226076' },
    { district: 'NAMAKKAL', block: 'MALLASAMUDRAM', name: 'Paruthipalli', lgdCode: '226077' },
    { district: 'NAMAKKAL', block: 'MALLASAMUDRAM', name: 'Pillanatham', lgdCode: '226078' },
    { district: 'NAMAKKAL', block: 'MALLASAMUDRAM', name: 'Ramapuram', lgdCode: '226079' },
    { district: 'NAMAKKAL', block: 'MALLASAMUDRAM', name: 'Sappayapuram', lgdCode: '226080' },
    { district: 'NAMAKKAL', block: 'MALLASAMUDRAM', name: 'Sarkar Mamundi', lgdCode: '226081' },
    { district: 'NAMAKKAL', block: 'MALLASAMUDRAM', name: 'Vandinatham', lgdCode: '226083' },
    { district: 'NAMAKKAL', block: 'MALLASAMUDRAM', name: 'Senbagamadevi', lgdCode: '226082' },
    { district: 'NAMAKKAL', block: 'MOHANUR', name: 'ANDAPURAM', lgdCode: '226084' },
    { district: 'NAMAKKAL', block: 'MOHANUR', name: 'ANIYAPURAM', lgdCode: '226085' },
    { district: 'NAMAKKAL', block: 'MOHANUR', name: 'ARASANATHAM', lgdCode: '226086' },
    { district: 'NAMAKKAL', block: 'MOHANUR', name: 'ARIYUR', lgdCode: '226087' },
    { district: 'NAMAKKAL', block: 'MOHANUR', name: 'AROOR', lgdCode: '226088' },
    { district: 'NAMAKKAL', block: 'MOHANUR', name: 'CHINNAPETHAMPATTI', lgdCode: '226089' },
    { district: 'NAMAKKAL', block: 'MOHANUR', name: 'K PUDUPALAYAM', lgdCode: '226090' },
    { district: 'NAMAKKAL', block: 'MOHANUR', name: 'KALIPALAYAM', lgdCode: '226091' },
    { district: 'NAMAKKAL', block: 'MOHANUR', name: 'KUMARAPALAYAM', lgdCode: '226093' },
    { district: 'NAMAKKAL', block: 'MOHANUR', name: 'LATHUVADI', lgdCode: '226094' },
    { district: 'NAMAKKAL', block: 'MOHANUR', name: 'MADAKASAMPATTI', lgdCode: '226095' },
    { district: 'NAMAKKAL', block: 'MOHANUR', name: 'MANAPALLI', lgdCode: '226096' },
    { district: 'NAMAKKAL', block: 'MOHANUR', name: 'N PUDUPATTI', lgdCode: '226097' },
    { district: 'NAMAKKAL', block: 'MOHANUR', name: 'NANJAI EDAYAR', lgdCode: '226098' },
    { district: 'NAMAKKAL', block: 'MOHANUR', name: 'OLAPALAYAM', lgdCode: '226099' },
    { district: 'NAMAKKAL', block: 'MOHANUR', name: 'ORUVANDUR', lgdCode: '226100' },
    { district: 'NAMAKKAL', block: 'MOHANUR', name: 'PARALI', lgdCode: '226101' },
    { district: 'NAMAKKAL', block: 'MOHANUR', name: 'PERAMANDAPALAYAM', lgdCode: '226102' },
    { district: 'NAMAKKAL', block: 'MOHANUR', name: 'PETTAPALAYAM', lgdCode: '226103' },
    { district: 'NAMAKKAL', block: 'MOHANUR', name: 'RASIPALAYAM', lgdCode: '226104' },
    { district: 'NAMAKKAL', block: 'MOHANUR', name: 'S VALAVANTHI', lgdCode: '226105' },
    { district: 'NAMAKKAL', block: 'MOHANUR', name: 'SENGAPALLI', lgdCode: '226106' },
    { district: 'NAMAKKAL', block: 'MOHANUR', name: 'THOLUR', lgdCode: '226107' },
    { district: 'NAMAKKAL', block: 'MOHANUR', name: 'VALAYAPPATTI', lgdCode: '226108' },
    { district: 'NAMAKKAL', block: 'MOHANUR', name: 'KOMARIPALAYAM', lgdCode: '226092' },
    { district: 'NAMAKKAL', block: 'NAMAKKAL', name: 'ANIYAR', lgdCode: '226127' },
    { district: 'NAMAKKAL', block: 'NAMAKKAL', name: 'AVALNAICKENPATTI', lgdCode: '226128' },
    { district: 'NAMAKKAL', block: 'NAMAKKAL', name: 'ERNAPURAM', lgdCode: '226129' },
    { district: 'NAMAKKAL', block: 'NAMAKKAL', name: 'KADAPALLI', lgdCode: '226130' },
    { district: 'NAMAKKAL', block: 'NAMAKKAL', name: 'KEELSATHAMPUR', lgdCode: '226131' },
    { district: 'NAMAKKAL', block: 'NAMAKKAL', name: 'KEERAMBUR', lgdCode: '226132' },
    { district: 'NAMAKKAL', block: 'NAMAKKAL', name: 'KONUR', lgdCode: '226133' },
    { district: 'NAMAKKAL', block: 'NAMAKKAL', name: 'MARAPPANAICKENPATTI', lgdCode: '226134' },
    { district: 'NAMAKKAL', block: 'NAMAKKAL', name: 'MARURPATTI', lgdCode: '226135' },
    { district: 'NAMAKKAL', block: 'NAMAKKAL', name: 'NARAVALUR', lgdCode: '226137' },
    { district: 'NAMAKKAL', block: 'NAMAKKAL', name: 'PERIAGOUNDAMPALAYAM', lgdCode: '226138' },
    { district: 'NAMAKKAL', block: 'NAMAKKAL', name: 'RASAMPALAYAM', lgdCode: '226139' },
    { district: 'NAMAKKAL', block: 'NAMAKKAL', name: 'RENGAPPANAICKENPALAYAM', lgdCode: '226140' },
    { district: 'NAMAKKAL', block: 'NAMAKKAL', name: 'SILUVAMPATTI', lgdCode: '226141' },
    { district: 'NAMAKKAL', block: 'NAMAKKAL', name: 'SINGILIPATTI', lgdCode: '226142' },
    { district: 'NAMAKKAL', block: 'NAMAKKAL', name: 'SIVIYAMPALAYAM', lgdCode: '226143' },
    { district: 'NAMAKKAL', block: 'NAMAKKAL', name: 'THALIGAI', lgdCode: '226144' },
    { district: 'NAMAKKAL', block: 'NAMAKKAL', name: 'THINDAMANGALAM', lgdCode: '226145' },
    { district: 'NAMAKKAL', block: 'NAMAKKAL', name: 'THOTTIPATTI', lgdCode: '226146' },
    { district: 'NAMAKKAL', block: 'NAMAKKAL', name: 'VAGURAMPATTI', lgdCode: '226147' },
    { district: 'NAMAKKAL', block: 'NAMAKKAL', name: 'VALLIPURAM', lgdCode: '226148' },
    { district: 'NAMAKKAL', block: 'NAMAKKAL', name: 'VASANTHAPURAM', lgdCode: '226149' },
    { district: 'NAMAKKAL', block: 'NAMAKKAL', name: 'VEESANAM', lgdCode: '226150' },
    { district: 'NAMAKKAL', block: 'NAMAKKAL', name: 'VETTAMBADI', lgdCode: '226151' },
    { district: 'NAMAKKAL', block: 'NAMAKKAL', name: 'VITTAMANAICKENPATTI', lgdCode: '226152' },
    { district: 'NAMAKKAL', block: 'NAMAGIRIPET', name: 'Oyilpatti', lgdCode: '226118' },
    { district: 'NAMAKKAL', block: 'NAMAGIRIPET', name: 'Eswaramurthipalayam', lgdCode: '226109' },
    { district: 'NAMAKKAL', block: 'NAMAGIRIPET', name: 'Karkoodalpatti', lgdCode: '226110' },
    { district: 'NAMAKKAL', block: 'NAMAGIRIPET', name: 'Mangalapuram', lgdCode: '226111' },
    { district: 'NAMAKKAL', block: 'NAMAGIRIPET', name: 'Mathuruttu', lgdCode: '226112' },
    { district: 'NAMAKKAL', block: 'NAMAGIRIPET', name: 'Moolakurichi', lgdCode: '226113' },
    { district: 'NAMAKKAL', block: 'NAMAGIRIPET', name: 'Moolapallipatti', lgdCode: '226114' },
    { district: 'NAMAKKAL', block: 'NAMAGIRIPET', name: 'Mullukurichi', lgdCode: '226115' },
    { district: 'NAMAKKAL', block: 'NAMAGIRIPET', name: 'Naraikinaru', lgdCode: '226116' },
    { district: 'NAMAKKAL', block: 'NAMAGIRIPET', name: 'Navalpatti', lgdCode: '226117' },
    { district: 'NAMAKKAL', block: 'NAMAGIRIPET', name: 'Unanthangal', lgdCode: '226125' },
    { district: 'NAMAKKAL', block: 'NAMAGIRIPET', name: 'Pachudaiyampalayam', lgdCode: '226119' },
    { district: 'NAMAKKAL', block: 'NAMAGIRIPET', name: 'Perappansolai', lgdCode: '226120' },
    { district: 'NAMAKKAL', block: 'NAMAGIRIPET', name: 'Perumagoundampalayam', lgdCode: '226121' },
    { district: 'NAMAKKAL', block: 'NAMAGIRIPET', name: 'T Jederpalayam', lgdCode: '226122' },
    { district: 'NAMAKKAL', block: 'NAMAGIRIPET', name: 'Thimmanaickenpatti', lgdCode: '226123' },
    { district: 'NAMAKKAL', block: 'NAMAGIRIPET', name: 'Thoppapatti', lgdCode: '226124' },
    { district: 'NAMAKKAL', block: 'NAMAGIRIPET', name: 'Vaduga Muniappampalayam', lgdCode: '226126' },
    { district: 'NAMAKKAL', block: 'PUDUCHATRAM', name: 'A K Samudram', lgdCode: '226188' },
    { district: 'NAMAKKAL', block: 'PUDUCHATRAM', name: 'Elur', lgdCode: '226189' },
    { district: 'NAMAKKAL', block: 'PUDUCHATRAM', name: 'Kadiranallur', lgdCode: '226190' },
    { district: 'NAMAKKAL', block: 'PUDUCHATRAM', name: 'Kalangani', lgdCode: '226191' },
    { district: 'NAMAKKAL', block: 'PUDUCHATRAM', name: 'Kalyani', lgdCode: '226192' },
    { district: 'NAMAKKAL', block: 'PUDUCHATRAM', name: 'Kannurpatti', lgdCode: '226193' },
    { district: 'NAMAKKAL', block: 'PUDUCHATRAM', name: 'Karadipatti', lgdCode: '226194' },
    { district: 'NAMAKKAL', block: 'PUDUCHATRAM', name: 'Karaikurichi', lgdCode: '226195' },
    { district: 'NAMAKKAL', block: 'PUDUCHATRAM', name: 'Karaikurichi Pudur', lgdCode: '226196' },
    { district: 'NAMAKKAL', block: 'PUDUCHATRAM', name: 'Lakkapuram', lgdCode: '226197' },
    { district: 'NAMAKKAL', block: 'PUDUCHATRAM', name: 'Minnampalli', lgdCode: '226198' },
    { district: 'NAMAKKAL', block: 'PUDUCHATRAM', name: 'Navanithottakurpatti', lgdCode: '226199' },
    { district: 'NAMAKKAL', block: 'PUDUCHATRAM', name: 'Pachal', lgdCode: '226200' },
    { district: 'NAMAKKAL', block: 'PUDUCHATRAM', name: 'Pappinaickenpatti', lgdCode: '226201' },
    { district: 'NAMAKKAL', block: 'PUDUCHATRAM', name: 'Sarkarnattamangalam', lgdCode: '226203' },
    { district: 'NAMAKKAL', block: 'PUDUCHATRAM', name: 'Sarkar Uduppam', lgdCode: '226202' },
    { district: 'NAMAKKAL', block: 'PUDUCHATRAM', name: 'Sellappampatti', lgdCode: '226204' },
    { district: 'NAMAKKAL', block: 'PUDUCHATRAM', name: 'Thalambadi', lgdCode: '226205' },
    { district: 'NAMAKKAL', block: 'PUDUCHATRAM', name: 'Thathathiripuram', lgdCode: '226206' },
    { district: 'NAMAKKAL', block: 'PUDUCHATRAM', name: 'Thathayangarpatti', lgdCode: '226207' },
    { district: 'NAMAKKAL', block: 'PUDUCHATRAM', name: 'Thirumalaipatti', lgdCode: '226208' },
    { district: 'NAMAKKAL', block: 'PARAMATHY', name: 'IRUTTANAI', lgdCode: '226168' },
    { district: 'NAMAKKAL', block: 'PARAMATHY', name: 'KOLARAM', lgdCode: '226169' },
    { district: 'NAMAKKAL', block: 'PARAMATHY', name: 'KOODACHERI', lgdCode: '226170' },
    { district: 'NAMAKKAL', block: 'PARAMATHY', name: 'Kodur', lgdCode: '226171' },
    { district: 'NAMAKKAL', block: 'PARAMATHY', name: 'KUNNAMALAI', lgdCode: '226172' },
    { district: 'NAMAKKAL', block: 'PARAMATHY', name: 'MANIANUR', lgdCode: '226173' },
    { district: 'NAMAKKAL', block: 'PARAMATHY', name: 'MANICKANATHAM', lgdCode: '226174' },
    { district: 'NAMAKKAL', block: 'PARAMATHY', name: 'MELSATHAMBUR', lgdCode: '226175' },
    { district: 'NAMAKKAL', block: 'PARAMATHY', name: 'NADANTHAI', lgdCode: '226176' },
    { district: 'NAMAKKAL', block: 'PARAMATHY', name: 'NALLUR', lgdCode: '226177' },
    { district: 'NAMAKKAL', block: 'PARAMATHY', name: 'PILLAIKALATHUR', lgdCode: '226178' },
    { district: 'NAMAKKAL', block: 'PARAMATHY', name: 'PILLUR', lgdCode: '226179' },
    { district: 'NAMAKKAL', block: 'PARAMATHY', name: 'PIRANTHAGAM', lgdCode: '226180' },
    { district: 'NAMAKKAL', block: 'PARAMATHY', name: 'RAMADEVAM', lgdCode: '226181' },
    { district: 'NAMAKKAL', block: 'PARAMATHY', name: 'SEERAPALLI', lgdCode: '226182' },
    { district: 'NAMAKKAL', block: 'PARAMATHY', name: 'SERUKKALAI', lgdCode: '226183' },
    { district: 'NAMAKKAL', block: 'PARAMATHY', name: 'SITHAMPOONDI', lgdCode: '226184' },
    { district: 'NAMAKKAL', block: 'PARAMATHY', name: 'SUNGAKARAMPATTI', lgdCode: '226185' },
    { district: 'NAMAKKAL', block: 'PARAMATHY', name: 'VEERANAMPALAYAM', lgdCode: '226186' },
    { district: 'NAMAKKAL', block: 'PARAMATHY', name: 'VILLIPALAYAM', lgdCode: '226187' },
    { district: 'NAMAKKAL', block: 'PALLIPALAYAM', name: 'Elanthakkuttai', lgdCode: '226153' },
    { district: 'NAMAKKAL', block: 'PALLIPALAYAM', name: 'Kadachanallur', lgdCode: '226154' },
    { district: 'NAMAKKAL', block: 'PALLIPALAYAM', name: 'Kalianur', lgdCode: '226155' },
    { district: 'NAMAKKAL', block: 'PALLIPALAYAM', name: 'Kalianur Agraharam', lgdCode: '226156' },
    { district: 'NAMAKKAL', block: 'PALLIPALAYAM', name: 'Kokkarayanpettai', lgdCode: '226157' },
    { district: 'NAMAKKAL', block: 'PALLIPALAYAM', name: 'Kuppandapalayam', lgdCode: '226158' },
    { district: 'NAMAKKAL', block: 'PALLIPALAYAM', name: 'Odappalli Agraharam', lgdCode: '226159' },
    { district: 'NAMAKKAL', block: 'PALLIPALAYAM', name: 'Patharai', lgdCode: '226163' },
    { district: 'NAMAKKAL', block: 'PALLIPALAYAM', name: 'Pallakkapalayam', lgdCode: '226160' },
    { district: 'NAMAKKAL', block: 'PALLIPALAYAM', name: 'Pallipalayam Agraharam', lgdCode: '226161' },
    { district: 'NAMAKKAL', block: 'PALLIPALAYAM', name: 'Pappampalayam', lgdCode: '226162' },
    { district: 'NAMAKKAL', block: 'PALLIPALAYAM', name: 'Puduppalayam Agraharam', lgdCode: '226164' },
    { district: 'NAMAKKAL', block: 'PALLIPALAYAM', name: 'Samayasangili Agraharam', lgdCode: '226165' },
    { district: 'NAMAKKAL', block: 'PALLIPALAYAM', name: 'Sowthapuram', lgdCode: '226166' },
    { district: 'NAMAKKAL', block: 'PALLIPALAYAM', name: 'Thattankuttai', lgdCode: '226167' },
    { district: 'NAMAKKAL', block: 'RASIPURAM', name: '85 R KOMARAPALAYAM', lgdCode: '226209' },
    { district: 'NAMAKKAL', block: 'RASIPURAM', name: 'ANAIPALAYAM', lgdCode: '226210' },
    { district: 'NAMAKKAL', block: 'RASIPURAM', name: 'ARASAPALAYAM', lgdCode: '226211' },
    { district: 'NAMAKKAL', block: 'RASIPURAM', name: 'BODINAICKENPATTI', lgdCode: '226212' },
    { district: 'NAMAKKAL', block: 'RASIPURAM', name: 'CHANDRASEKARAPURAM', lgdCode: '226213' },
    { district: 'NAMAKKAL', block: 'RASIPURAM', name: 'GOUNDAMPALAYAM', lgdCode: '226214' },
    { district: 'NAMAKKAL', block: 'RASIPURAM', name: 'KAKKAVERI', lgdCode: '226215' },
    { district: 'NAMAKKAL', block: 'RASIPURAM', name: 'KANAGABOMMAMPATTI', lgdCode: '226216' },
    { district: 'NAMAKKAL', block: 'RASIPURAM', name: 'KOONAVELAMPATTI', lgdCode: '226217' },
    { district: 'NAMAKKAL', block: 'RASIPURAM', name: 'KURUKKAPURAM', lgdCode: '226218' },
    { district: 'NAMAKKAL', block: 'RASIPURAM', name: 'M KONERIPATTI', lgdCode: '226219' },
    { district: 'NAMAKKAL', block: 'RASIPURAM', name: 'MALAIYAMPATTI', lgdCode: '226220' },
    { district: 'NAMAKKAL', block: 'RASIPURAM', name: 'MOLLAPALAYAM', lgdCode: '226221' },
    { district: 'NAMAKKAL', block: 'RASIPURAM', name: 'MURUNGAPATTI', lgdCode: '226222' },
    { district: 'NAMAKKAL', block: 'RASIPURAM', name: 'MUTHUKALIPATTI', lgdCode: '226223' },
    { district: 'NAMAKKAL', block: 'RASIPURAM', name: 'P AYEEPALAYAM', lgdCode: '226224' },
    { district: 'NAMAKKAL', block: 'RASIPURAM', name: 'P MUNIAPPAMPALAYAM', lgdCode: '226225' },
    { district: 'NAMAKKAL', block: 'RASIPURAM', name: 'PONKURICHI', lgdCode: '226226' },
    { district: 'NAMAKKAL', block: 'RASIPURAM', name: 'SINGALANDAPURAM', lgdCode: '226227' },
    { district: 'NAMAKKAL', block: 'RASIPURAM', name: 'VADUGAM', lgdCode: '226228' },
    { district: 'NAMAKKAL', block: 'SENDAMANGALAM', name: 'Akkiampatti', lgdCode: '226229' },
    { district: 'NAMAKKAL', block: 'SENDAMANGALAM', name: 'Belukurichi', lgdCode: '226230' },
    { district: 'NAMAKKAL', block: 'SENDAMANGALAM', name: 'Bommasamudram', lgdCode: '226231' },
    { district: 'NAMAKKAL', block: 'SENDAMANGALAM', name: 'Kalkurichi', lgdCode: '226232' },
    { district: 'NAMAKKAL', block: 'SENDAMANGALAM', name: 'Kondamanaickenpatti', lgdCode: '226233' },
    { district: 'NAMAKKAL', block: 'SENDAMANGALAM', name: 'Melapatti', lgdCode: '226234' },
    { district: 'NAMAKKAL', block: 'SENDAMANGALAM', name: 'Naducombai', lgdCode: '226235' },
    { district: 'NAMAKKAL', block: 'SENDAMANGALAM', name: 'Pachudaiyampatti', lgdCode: '226236' },
    { district: 'NAMAKKAL', block: 'SENDAMANGALAM', name: 'Pallipatti', lgdCode: '226237' },
    { district: 'NAMAKKAL', block: 'SENDAMANGALAM', name: 'Periakulam', lgdCode: '226238' },
    { district: 'NAMAKKAL', block: 'SENDAMANGALAM', name: 'Pottanam', lgdCode: '226239' },
    { district: 'NAMAKKAL', block: 'SENDAMANGALAM', name: 'Thuthikulam', lgdCode: '226240' },
    { district: 'NAMAKKAL', block: 'SENDAMANGALAM', name: 'Uthirakidikaval', lgdCode: '226241' },
    { district: 'NAMAKKAL', block: 'SENDAMANGALAM', name: 'Valavanthicombai', lgdCode: '226242' },
    { district: 'NAMAKKAL', block: 'TIRUCHENGODE', name: 'A erayamangalam', lgdCode: '226243' },
    { district: 'NAMAKKAL', block: 'TIRUCHENGODE', name: 'Anangoor', lgdCode: '226244' },
    { district: 'NAMAKKAL', block: 'TIRUCHENGODE', name: 'Andipalayam', lgdCode: '226245' },
    { district: 'NAMAKKAL', block: 'TIRUCHENGODE', name: 'Animoor', lgdCode: '226246' },
    { district: 'NAMAKKAL', block: 'TIRUCHENGODE', name: 'Chikkanaickanpalayam', lgdCode: '226247' },
    { district: 'NAMAKKAL', block: 'TIRUCHENGODE', name: 'Chitalandur', lgdCode: '226248' },
    { district: 'NAMAKKAL', block: 'TIRUCHENGODE', name: 'Devanankurichi', lgdCode: '226249' },
    { district: 'NAMAKKAL', block: 'TIRUCHENGODE', name: 'Emapalli', lgdCode: '226250' },
    { district: 'NAMAKKAL', block: 'TIRUCHENGODE', name: 'Karumapuram', lgdCode: '226251' },
    { district: 'NAMAKKAL', block: 'TIRUCHENGODE', name: 'Karuveppampatti', lgdCode: '226252' },
    { district: 'NAMAKKAL', block: 'TIRUCHENGODE', name: 'Modamangalam', lgdCode: '226253' },
    { district: 'NAMAKKAL', block: 'TIRUCHENGODE', name: 'Molasi', lgdCode: '226254' },
    { district: 'NAMAKKAL', block: 'TIRUCHENGODE', name: 'Pirithi', lgdCode: '226256' },
    { district: 'NAMAKKAL', block: 'TIRUCHENGODE', name: 'Patlur', lgdCode: '226255' },
    { district: 'NAMAKKAL', block: 'TIRUCHENGODE', name: 'Pudupuliampatti', lgdCode: '226257' },
    { district: 'NAMAKKAL', block: 'TIRUCHENGODE', name: 'O. rajapalayam', lgdCode: '226258' },
    { district: 'NAMAKKAL', block: 'TIRUCHENGODE', name: 'S erayamangalam', lgdCode: '226259' },
    { district: 'NAMAKKAL', block: 'TIRUCHENGODE', name: 'Sirumolasi', lgdCode: '226260' },
    { district: 'NAMAKKAL', block: 'TIRUCHENGODE', name: 'T goundampalayam', lgdCode: '226261' },
    { district: 'NAMAKKAL', block: 'TIRUCHENGODE', name: 'T kailasampalayam', lgdCode: '226262' },
    { district: 'NAMAKKAL', block: 'TIRUCHENGODE', name: 'T pudupalayam', lgdCode: '226263' },
    { district: 'NAMAKKAL', block: 'TIRUCHENGODE', name: 'Thanneerpandalpalayam', lgdCode: '226264' },
    { district: 'NAMAKKAL', block: 'TIRUCHENGODE', name: 'Thirumangalam', lgdCode: '226265' },
    { district: 'NAMAKKAL', block: 'TIRUCHENGODE', name: 'Thokkavadi', lgdCode: '226266' },
    { district: 'NAMAKKAL', block: 'TIRUCHENGODE', name: 'Varagoorampatti', lgdCode: '226267' },
    { district: 'NAMAKKAL', block: 'TIRUCHENGODE', name: 'Vattur', lgdCode: '226268' },
    { district: 'NAMAKKAL', block: 'VENNANDUR', name: 'Ananthagoundampalayam', lgdCode: '226269' },
    { district: 'NAMAKKAL', block: 'VENNANDUR', name: 'Akkaraipatti', lgdCode: '226270' },
    { district: 'NAMAKKAL', block: 'VENNANDUR', name: 'Alampatti', lgdCode: '226271' },
    { district: 'NAMAKKAL', block: 'VENNANDUR', name: 'Alavaipatti', lgdCode: '226272' },
    { district: 'NAMAKKAL', block: 'VENNANDUR', name: 'Kallankulam', lgdCode: '226273' },
    { district: 'NAMAKKAL', block: 'VENNANDUR', name: 'Kattanachampatti', lgdCode: '226274' },
    { district: 'NAMAKKAL', block: 'VENNANDUR', name: 'Keelur', lgdCode: '226275' },
    { district: 'NAMAKKAL', block: 'VENNANDUR', name: 'Kuttaladampatti', lgdCode: '226276' },
    { district: 'NAMAKKAL', block: 'VENNANDUR', name: 'Mathiyampatti', lgdCode: '226277' },
    { district: 'NAMAKKAL', block: 'VENNANDUR', name: 'Mattuvelampatti', lgdCode: '226278' },
    { district: 'NAMAKKAL', block: 'VENNANDUR', name: 'Minnakkal', lgdCode: '226279' },
    { district: 'NAMAKKAL', block: 'VENNANDUR', name: 'Moolakadu', lgdCode: '226280' },
    { district: 'NAMAKKAL', block: 'VENNANDUR', name: 'Nachipatti', lgdCode: '226281' },
    { district: 'NAMAKKAL', block: 'VENNANDUR', name: 'Nadupatti', lgdCode: '226282' },
    { district: 'NAMAKKAL', block: 'VENNANDUR', name: 'No 3 Komarapalayam', lgdCode: '226283' },
    { district: 'NAMAKKAL', block: 'VENNANDUR', name: 'O Sowthapuram', lgdCode: '226284' },
    { district: 'NAMAKKAL', block: 'VENNANDUR', name: 'Palanthinnipatti', lgdCode: '226285' },
    { district: 'NAMAKKAL', block: 'VENNANDUR', name: 'Pallavanaickenpatti', lgdCode: '226286' },
    { district: 'NAMAKKAL', block: 'VENNANDUR', name: 'Ponparappipatti', lgdCode: '226287' },
    { district: 'NAMAKKAL', block: 'VENNANDUR', name: 'R Pudupalayam', lgdCode: '226288' },
    { district: 'NAMAKKAL', block: 'VENNANDUR', name: 'Semmandapatti', lgdCode: '226289' },
    { district: 'NAMAKKAL', block: 'VENNANDUR', name: 'Thengalpalayam', lgdCode: '226290' },
    { district: 'NAMAKKAL', block: 'VENNANDUR', name: 'Thottiyapatti', lgdCode: '226291' },
    { district: 'NAMAKKAL', block: 'VENNANDUR', name: 'Thottiyavalasu', lgdCode: '226292' },
];
