
import type { Panchayat } from './types';

export const RAMANATHAPURAM_PANCHAYATS: Panchayat[] = [
    { district: 'RAMANATHAPURAM', block: 'MANDAPAM', name: 'Thangachimadam', lgdCode: '227274' },
    { district: 'RAMANATHAPURAM', block: 'MANDAPAM', name: 'Pamban', lgdCode: '227263' },
    { district: 'RAMANATHAPURAM', block: 'MANDAPAM', name: 'Valantharavai', lgdCode: '227276' },
    { district: 'RAMANATHAPURAM', block: 'MANDAPAM', name: 'Panaikulam', lgdCode: '227264' },
    { district: 'RAMANATHAPURAM', block: 'MANDAPAM', name: 'Pudumadam', lgdCode: '227268' },
    { district: 'RAMANATHAPURAM', block: 'MANDAPAM', name: 'Alagankulam', lgdCode: '227251' },
    { district: 'RAMANATHAPURAM', block: 'MANDAPAM', name: 'Enmanankondan', lgdCode: '227253' },
    { district: 'RAMANATHAPURAM', block: 'MANDAPAM', name: 'Vedalai', lgdCode: '227277' },
    { district: 'RAMANATHAPURAM', block: 'MANDAPAM', name: 'Pattinamkathan', lgdCode: '227265' },
    { district: 'RAMANATHAPURAM', block: 'MANDAPAM', name: 'Kusavankudi', lgdCode: '227258' },
    { district: 'RAMANATHAPURAM', block: 'MANDAPAM', name: 'Perungulam', lgdCode: '227266' },
    { district: 'RAMANATHAPURAM', block: 'MANDAPAM', name: 'Rettaiyurani', lgdCode: '227270' },
    { district: 'RAMANATHAPURAM', block: 'MANDAPAM', name: 'Attrangarai', lgdCode: '227252' },
    { district: 'RAMANATHAPURAM', block: 'MANDAPAM', name: 'Irumeni', lgdCode: '227254' },
    { district: 'RAMANATHAPURAM', block: 'MANDAPAM', name: 'Keelanagachi', lgdCode: '227261' },
    { district: 'RAMANATHAPURAM', block: 'MANDAPAM', name: 'Therbogi', lgdCode: '227275' },
    { district: 'RAMANATHAPURAM', block: 'MANDAPAM', name: 'Karan', lgdCode: '227255' },
    { district: 'RAMANATHAPURAM', block: 'MANDAPAM', name: 'Sathakonvalasai', lgdCode: '227271' },
    { district: 'RAMANATHAPURAM', block: 'MANDAPAM', name: 'Kumbaram', lgdCode: '227257' },
    { district: 'RAMANATHAPURAM', block: 'MANDAPAM', name: 'Manangudi', lgdCode: '227259' },
    { district: 'RAMANATHAPURAM', block: 'MANDAPAM', name: 'Thamaraikulam', lgdCode: '227273' },
    { district: 'RAMANATHAPURAM', block: 'MANDAPAM', name: 'Sembadaiyarkulam', lgdCode: '227272' },
    { district: 'RAMANATHAPURAM', block: 'MANDAPAM', name: 'Pirappanvalasai', lgdCode: '227267' },
    { district: 'RAMANATHAPURAM', block: 'MANDAPAM', name: 'Maraikayarpattinam', lgdCode: '227260' },
    { district: 'RAMANATHAPURAM', block: 'MANDAPAM', name: 'Vellariodai', lgdCode: '227278' },
    { district: 'RAMANATHAPURAM', block: 'MANDAPAM', name: 'Koravalli', lgdCode: '227256' },
    { district: 'RAMANATHAPURAM', block: 'MANDAPAM', name: 'Nochiyurani', lgdCode: '227262' },
    { district: 'RAMANATHAPURAM', block: 'MANDAPAM', name: 'Puduvalasai', lgdCode: '227269' },
    { district: 'RAMANATHAPURAM', block: 'RAMANATHAPURAM', name: 'Devipattinam', lgdCode: '227440' },
    { district: 'RAMANATHAPURAM', block: 'RAMANATHAPURAM', name: 'Chitharkottai', lgdCode: '227439' },
    { district: 'RAMANATHAPURAM', block: 'RAMANATHAPURAM', name: 'Sakkarakkottai', lgdCode: '227456' },
    { district: 'RAMANATHAPURAM', block: 'RAMANATHAPURAM', name: 'Surankottai', lgdCode: '227457' },
    { district: 'RAMANATHAPURAM', block: 'RAMANATHAPURAM', name: 'Therkutharavai', lgdCode: '227458' },
    { district: 'RAMANATHAPURAM', block: 'RAMANATHAPURAM', name: 'Rajasooriyamadai', lgdCode: '227455' },
    { district: 'RAMANATHAPURAM', block: 'RAMANATHAPURAM', name: 'Thoruvaloor', lgdCode: '227459' },
    { district: 'RAMANATHAPURAM', block: 'RAMANATHAPURAM', name: 'Peravoor', lgdCode: '227451' },
    { district: 'RAMANATHAPURAM', block: 'RAMANATHAPURAM', name: 'Athiyuthu', lgdCode: '227437' },
    { district: 'RAMANATHAPURAM', block: 'RAMANATHAPURAM', name: 'Vennathoor', lgdCode: '227460' },
    { district: 'RAMANATHAPURAM', block: 'RAMANATHAPURAM', name: 'Madavanoor', lgdCode: '227448' },
    { district: 'RAMANATHAPURAM', block: 'RAMANATHAPURAM', name: 'Chithoor', lgdCode: '227438' },
    { district: 'RAMANATHAPURAM', block: 'RAMANATHAPURAM', name: 'Kavanoor', lgdCode: '227446' },
    { district: 'RAMANATHAPURAM', block: 'RAMANATHAPURAM', name: 'Karugudi', lgdCode: '227445' },
    { district: 'RAMANATHAPURAM', block: 'RAMANATHAPURAM', name: 'Puthendhal', lgdCode: '227454' },
    { district: 'RAMANATHAPURAM', block: 'RAMANATHAPURAM', name: 'Pullangudi', lgdCode: '227453' },
    { district: 'RAMANATHAPURAM', block: 'RAMANATHAPURAM', name: 'Achundanvayal', lgdCode: '227436' },
    { district: 'RAMANATHAPURAM', block: 'RAMANATHAPURAM', name: 'Kalugoorani', lgdCode: '227443' },
    { district: 'RAMANATHAPURAM', block: 'RAMANATHAPURAM', name: 'Naranamangalam', lgdCode: '227449' },
    { district: 'RAMANATHAPURAM', block: 'RAMANATHAPURAM', name: 'Madakkottan', lgdCode: '227447' },
    { district: 'RAMANATHAPURAM', block: 'RAMANATHAPURAM', name: 'Peruvayal', lgdCode: '227452' },
    { district: 'RAMANATHAPURAM', block: 'RAMANATHAPURAM', name: 'Ilamanoor', lgdCode: '227441' },
    { district: 'RAMANATHAPURAM', block: 'RAMANATHAPURAM', name: 'Pandamangalam', lgdCode: '227450' },
    { district: 'RAMANATHAPURAM', block: 'RAMANATHAPURAM', name: 'Karendhal', lgdCode: '227444' },
    { district: 'RAMANATHAPURAM', block: 'RAMANATHAPURAM', name: 'Kalanikudi', lgdCode: '227442' },
    { district: 'RAMANATHAPURAM', block: 'R.S. MANGALAM', name: 'Thiruppalaikkudi', lgdCode: '227430' },
    { district: 'RAMANATHAPURAM', block: 'R.S. MANGALAM', name: 'Govindamangalam', lgdCode: '227407' },
    { district: 'RAMANATHAPURAM', block: 'R.S. MANGALAM', name: 'Pullamadai', lgdCode: '227422' },
    { district: 'RAMANATHAPURAM', block: 'R.S. MANGALAM', name: 'Kadalur', lgdCode: '227410' },
    { district: 'RAMANATHAPURAM', block: 'R.S. MANGALAM', name: 'Karungudi', lgdCode: '227413' },
    { district: 'RAMANATHAPURAM', block: 'R.S. MANGALAM', name: 'Aananthoor', lgdCode: '227403' },
    { district: 'RAMANATHAPURAM', block: 'R.S. MANGALAM', name: 'Varavani', lgdCode: '227435' },
    { district: 'RAMANATHAPURAM', block: 'R.S. MANGALAM', name: 'Rathaanur', lgdCode: '227423' },
    { district: 'RAMANATHAPURAM', block: 'R.S. MANGALAM', name: 'Sengudi', lgdCode: '227425' },
    { district: 'RAMANATHAPURAM', block: 'R.S. MANGALAM', name: 'Satthanur', lgdCode: '227424' },
    { district: 'RAMANATHAPURAM', block: 'R.S. MANGALAM', name: 'Sanaveli', lgdCode: '227409' },
    { district: 'RAMANATHAPURAM', block: 'R.S. MANGALAM', name: 'Kothidal_kalakkudi', lgdCode: '227416' },
    { district: 'RAMANATHAPURAM', block: 'R.S. MANGALAM', name: 'Thumbadaikkakottai', lgdCode: '227432' },
    { district: 'RAMANATHAPURAM', block: 'R.S. MANGALAM', name: 'A. R. Mangalam', lgdCode: '227404' },
    { district: 'RAMANATHAPURAM', block: 'R.S. MANGALAM', name: 'Chithoorvadi', lgdCode: '227406' },
    { district: 'RAMANATHAPURAM', block: 'R.S. MANGALAM', name: 'Aayingudi', lgdCode: '227405' },
    { district: 'RAMANATHAPURAM', block: 'R.S. MANGALAM', name: 'Paaranur', lgdCode: '227420' },
    { district: 'RAMANATHAPURAM', block: 'R.S. MANGALAM', name: 'Sevvaipettai', lgdCode: '227427' },
    { district: 'RAMANATHAPURAM', block: 'R.S. MANGALAM', name: 'A. Manakkudi', lgdCode: '227401' },
    { district: 'RAMANATHAPURAM', block: 'R.S. MANGALAM', name: 'Karkatthakudi', lgdCode: '227412' },
    { district: 'RAMANATHAPURAM', block: 'R.S. MANGALAM', name: 'Kavanoor', lgdCode: '227415' },
    { district: 'RAMANATHAPURAM', block: 'R.S. MANGALAM', name: 'Kavanakkottai', lgdCode: '227414' },
    { district: 'RAMANATHAPURAM', block: 'R.S. MANGALAM', name: 'Alagarthevankottai', lgdCode: '227402' },
    { district: 'RAMANATHAPURAM', block: 'R.S. MANGALAM', name: 'Kottakudi', lgdCode: '227417' },
    { district: 'RAMANATHAPURAM', block: 'R.S. MANGALAM', name: 'Sethidal', lgdCode: '227426' },
    { district: 'RAMANATHAPURAM', block: 'R.S. MANGALAM', name: 'Odaikkaal', lgdCode: '227419' },
    { district: 'RAMANATHAPURAM', block: 'R.S. MANGALAM', name: 'Thirutthervalai', lgdCode: '227431' },
    { district: 'RAMANATHAPURAM', block: 'R.S. MANGALAM', name: 'Uranangudi', lgdCode: '227433' },
    { district: 'RAMANATHAPURAM', block: 'R.S. MANGALAM', name: 'Kallikkudi', lgdCode: '227411' },
    { district: 'RAMANATHAPURAM', block: 'R.S. MANGALAM', name: 'Gudaloor', lgdCode: '227408' },
    { district: 'RAMANATHAPURAM', block: 'R.S. MANGALAM', name: 'Pichangurichi', lgdCode: '227421' },
    { district: 'RAMANATHAPURAM', block: 'R.S. MANGALAM', name: 'Sholandur', lgdCode: '227428' },
    { district: 'RAMANATHAPURAM', block: 'R.S. MANGALAM', name: 'Sirunagudi', lgdCode: '227429' },
    { district: 'RAMANATHAPURAM', block: 'R.S. MANGALAM', name: 'Melpanaiyur', lgdCode: '227418' },
    { district: 'RAMANATHAPURAM', block: 'R.S. MANGALAM', name: 'Vadakkalur', lgdCode: '227434' },
    { district: 'RAMANATHAPURAM', block: 'THIRUPPULLANI', name: 'Periyapattinam', lgdCode: '227482' },
    { district: 'RAMANATHAPURAM', block: 'THIRUPPULLANI', name: 'Kanjirangudi', lgdCode: '227466' },
    { district: 'RAMANATHAPURAM', block: 'THIRUPPULLANI', name: 'Thillaiyenthal', lgdCode: '227486' },
    { district: 'RAMANATHAPURAM', block: 'THIRUPPULLANI', name: 'Mayakulam', lgdCode: '227473' },
    { district: 'RAMANATHAPURAM', block: 'THIRUPPULLANI', name: 'Regunathapuram', lgdCode: '227483' },
    { district: 'RAMANATHAPURAM', block: 'THIRUPPULLANI', name: 'Vannankundu', lgdCode: '227492' },
    { district: 'RAMANATHAPURAM', block: 'THIRUPPULLANI', name: 'Mallal', lgdCode: '227472' },
    { district: 'RAMANATHAPURAM', block: 'THIRUPPULLANI', name: 'Kalimankundu', lgdCode: '227465' },
    { district: 'RAMANATHAPURAM', block: 'THIRUPPULLANI', name: 'Vellamarichukkatti', lgdCode: '227493' },
    { district: 'RAMANATHAPURAM', block: 'THIRUPPULLANI', name: 'Thiru Uthirakosamangai', lgdCode: '227490' },
    { district: 'RAMANATHAPURAM', block: 'THIRUPPULLANI', name: 'Lanthai', lgdCode: '227471' },
    { district: 'RAMANATHAPURAM', block: 'THIRUPPULLANI', name: 'Kuthakkottai', lgdCode: '227469' },
    { district: 'RAMANATHAPURAM', block: 'THIRUPPULLANI', name: 'Sethukarai', lgdCode: '227484' },
    { district: 'RAMANATHAPURAM', block: 'THIRUPPULLANI', name: 'Thinaikkulam', lgdCode: '227487' },
    { district: 'RAMANATHAPURAM', block: 'THIRUPPULLANI', name: 'Thathanenthal', lgdCode: '227485' },
    { district: 'RAMANATHAPURAM', block: 'THIRUPPULLANI', name: 'Thiruppullani', lgdCode: '227488' },
    { district: 'RAMANATHAPURAM', block: 'THIRUPPULLANI', name: 'Nainamaraikkan', lgdCode: '227477' },
    { district: 'RAMANATHAPURAM', block: 'THIRUPPULLANI', name: 'Muthupettai', lgdCode: '227476' },
    { district: 'RAMANATHAPURAM', block: 'THIRUPPULLANI', name: 'Kalari', lgdCode: '227464' },
    { district: 'RAMANATHAPURAM', block: 'THIRUPPULLANI', name: 'Kulapatham', lgdCode: '227470' },
    { district: 'RAMANATHAPURAM', block: 'THIRUPPULLANI', name: 'Chinnandivalasai', lgdCode: '227462' },
    { district: 'RAMANATHAPURAM', block: 'THIRUPPULLANI', name: 'Ekkakudi', lgdCode: '227463' },
    { district: 'RAMANATHAPURAM', block: 'THIRUPPULLANI', name: 'Nallirukkai', lgdCode: '227478' },
    { district: 'RAMANATHAPURAM', block: 'THIRUPPULLANI', name: 'Utharavai', lgdCode: '227489' },
    { district: 'RAMANATHAPURAM', block: 'THIRUPPULLANI', name: 'Panaiyadiyenthal', lgdCode: '227480' },
    { district: 'RAMANATHAPURAM', block: 'THIRUPPULLANI', name: 'Melamadai', lgdCode: '227474' },
    { district: 'RAMANATHAPURAM', block: 'THIRUPPULLANI', name: 'Panaikkulam', lgdCode: '227479' },
    { district: 'RAMANATHAPURAM', block: 'THIRUPPULLANI', name: 'Alangulam', lgdCode: '227461' },
    { district: 'RAMANATHAPURAM', block: 'THIRUPPULLANI', name: 'Komboothi', lgdCode: '227467' },
    { district: 'RAMANATHAPURAM', block: 'THIRUPPULLANI', name: 'Methalodai', lgdCode: '227475' },
    { district: 'RAMANATHAPURAM', block: 'THIRUPPULLANI', name: 'Velanur', lgdCode: '227491' },
    { district: 'RAMANATHAPURAM', block: 'THIRUPPULLANI', name: 'Pathiratharavai', lgdCode: '227481' },
    { district: 'RAMANATHAPURAM', block: 'THIRUPPULLANI', name: 'Koraikuttam', lgdCode: '227468' },
    { district: 'RAMANATHAPURAM', block: 'THIRUVADANAI', name: 'Nambuthalai', lgdCode: '227517' },
    { district: 'RAMANATHAPURAM', block: 'THIRUVADANAI', name: 'TIRUVADANAI', lgdCode: '227537' },
    { district: 'RAMANATHAPURAM', block: 'THIRUVADANAI', name: 'SUNDARAPANDIANPATTINAM', lgdCode: '227532' },
    { district: 'RAMANATHAPURAM', block: 'THIRUVADANAI', name: 'ORIUR', lgdCode: '227521' },
    { district: 'RAMANATHAPURAM', block: 'THIRUVADANAI', name: 'PANDUKUDI', lgdCode: '227525' },
    { district: 'RAMANATHAPURAM', block: 'THIRUVADANAI', name: 'ANJUKOTTAI', lgdCode: '227496' },
    { district: 'RAMANATHAPURAM', block: 'THIRUVADANAI', name: 'KALLUR', lgdCode: '227502' },
    { district: 'RAMANATHAPURAM', block: 'THIRUVADANAI', name: 'Kookudi', lgdCode: '227509' },
    { district: 'RAMANATHAPURAM', block: 'THIRUVADANAI', name: 'Thelur', lgdCode: '227535' },
    { district: 'RAMANATHAPURAM', block: 'THIRUVADANAI', name: 'Arasathur', lgdCode: '227497' },
    { district: 'RAMANATHAPURAM', block: 'THIRUVADANAI', name: 'Periyakeeramangalam', lgdCode: '227527' },
    { district: 'RAMANATHAPURAM', block: 'THIRUVADANAI', name: 'KODANNOR', lgdCode: '227507' },
    { district: 'RAMANATHAPURAM', block: 'THIRUVADANAI', name: 'KADAMBUR', lgdCode: '227500' },
    { district: 'RAMANATHAPURAM', block: 'THIRUVADANAI', name: 'THALIRMARUNGUR A/B', lgdCode: '227534' },
    { district: 'RAMANATHAPURAM', block: 'THIRUVADANAI', name: 'Mugilthagam', lgdCode: '227514' },
    { district: 'RAMANATHAPURAM', block: 'THIRUVADANAI', name: 'Andavoorani', lgdCode: '227495' },
    { district: 'RAMANATHAPURAM', block: 'THIRUVADANAI', name: 'Kaliyanagari', lgdCode: '227501' },
    { district: 'RAMANATHAPURAM', block: 'THIRUVADANAI', name: 'VELLAYAPURAM', lgdCode: '227540' },
    { district: 'RAMANATHAPURAM', block: 'THIRUVADANAI', name: 'T. NAGANI', lgdCode: '227533' },
    { district: 'RAMANATHAPURAM', block: 'THIRUVADANAI', name: 'Pullakkadamban', lgdCode: '227529' },
    { district: 'RAMANATHAPURAM', block: 'THIRUVADANAI', name: 'ARUMBOOR', lgdCode: '227498' },
    { district: 'RAMANATHAPURAM', block: 'THIRUVADANAI', name: 'ATHIYUR', lgdCode: '227499' },
    { district: 'RAMANATHAPURAM', block: 'THIRUVADANAI', name: 'ACHANGUDI', lgdCode: '227494' },
    { district: 'RAMANATHAPURAM', block: 'THIRUVADANAI', name: 'Kunjangulam', lgdCode: '227511' },
    { district: 'RAMANATHAPURAM', block: 'THIRUVADANAI', name: 'Sirugambaiyur', lgdCode: '227530' },
    { district: 'RAMANATHAPURAM', block: 'THIRUVADANAI', name: 'Mangalakkudi', lgdCode: '227512' },
    { district: 'RAMANATHAPURAM', block: 'THIRUVADANAI', name: 'Palangulam', lgdCode: '227523' },
    { district: 'RAMANATHAPURAM', block: 'THIRUVADANAI', name: 'NEYVAYAL', lgdCode: '227518' },
    { district: 'RAMANATHAPURAM', block: 'THIRUVADANAI', name: 'KODIPPANGU', lgdCode: '227508' },
    { district: 'RAMANATHAPURAM', block: 'THIRUVADANAI', name: 'KULATHUR B/D', lgdCode: '227510' },
    { district: 'RAMANATHAPURAM', block: 'THIRUVADANAI', name: 'MULLIMUNAI', lgdCode: '227515' },
    { district: 'RAMANATHAPURAM', block: 'THIRUVADANAI', name: 'Kattavilagam', lgdCode: '227505' },
    { district: 'RAMANATHAPURAM', block: 'THIRUVADANAI', name: 'Nilamalgiyamangalam', lgdCode: '227519' },
    { district: 'RAMANATHAPURAM', block: 'THIRUVADANAI', name: 'PUDUPATTINAM', lgdCode: '227528' },
    { district: 'RAMANATHAPURAM', block: 'THIRUVADANAI', name: 'Thiruvetriyur', lgdCode: '227536' },
    { district: 'RAMANATHAPURAM', block: 'THIRUVADANAI', name: 'VATTANAM', lgdCode: '227539' },
    { district: 'RAMANATHAPURAM', block: 'THIRUVADANAI', name: 'Kattivayal', lgdCode: '227506' },
    { district: 'RAMANATHAPURAM', block: 'THIRUVADANAI', name: 'Karumoli', lgdCode: '227504' },
    { district: 'RAMANATHAPURAM', block: 'THIRUVADANAI', name: 'PANANJAYAL', lgdCode: '227524' },
    { district: 'RAMANATHAPURAM', block: 'THIRUVADANAI', name: 'PAGANUR', lgdCode: '227522' },
    { district: 'RAMANATHAPURAM', block: 'THIRUVADANAI', name: 'Karangadu', lgdCode: '227503' },
    { district: 'RAMANATHAPURAM', block: 'THIRUVADANAI', name: 'SIRUMALAIKKOTTAI', lgdCode: '227531' },
    { district: 'RAMANATHAPURAM', block: 'THIRUVADANAI', name: 'Nagarikathan', lgdCode: '227516' },
    { district: 'RAMANATHAPURAM', block: 'THIRUVADANAI', name: 'Thuthakudi', lgdCode: '227538' },
    { district: 'RAMANATHAPURAM', block: 'THIRUVADANAI', name: 'Orikottai A/B', lgdCode: '227520' },
    { district: 'RAMANATHAPURAM', block: 'THIRUVADANAI', name: 'MAVUR', lgdCode: '227513' },
    { district: 'RAMANATHAPURAM', block: 'THIRUVADANAI', name: 'PATHANAKUDI', lgdCode: '227526' },
    { district: 'RAMANATHAPURAM', block: 'BOGALUR', name: 'Bogalur', lgdCode: '227113' },
    { district: 'RAMANATHAPURAM', block: 'BOGALUR', name: 'A.Puthur', lgdCode: '227112' },
    { district: 'RAMANATHAPURAM', block: 'BOGALUR', name: 'Kamankottai', lgdCode: '227117' },
    { district: 'RAMANATHAPURAM', block: 'BOGALUR', name: 'Mennanthi Nagachi', lgdCode: '227126' },
    { district: 'RAMANATHAPURAM', block: 'BOGALUR', name: 'Manjur', lgdCode: '227123' },
    { district: 'RAMANATHAPURAM', block: 'BOGALUR', name: 'K.Valasai', lgdCode: '227116' },
    { district: 'RAMANATHAPURAM', block: 'BOGALUR', name: 'Muthuvayal', lgdCode: '227125' },
    { district: 'RAMANATHAPURAM', block: 'BOGALUR', name: 'Ettivayal', lgdCode: '227115' },
    { district: 'RAMANATHAPURAM', block: 'BOGALUR', name: 'Muthalur', lgdCode: '227124' },
    { district: 'RAMANATHAPURAM', block: 'BOGALUR', name: 'Vairavanendal', lgdCode: '227136' },
    { district: 'RAMANATHAPURAM', block: 'BOGALUR', name: 'T.Karungulam', lgdCode: '227133' },
    { district: 'RAMANATHAPURAM', block: 'BOGALUR', name: 'Sevvur', lgdCode: '227131' },
    { district: 'RAMANATHAPURAM', block: 'BOGALUR', name: 'Keelampal', lgdCode: '227121' },
    { district: 'RAMANATHAPURAM', block: 'BOGALUR', name: 'Semanur', lgdCode: '227130' },
    { district: 'RAMANATHAPURAM', block: 'BOGALUR', name: 'Deivendranallur', lgdCode: '227114' },
    { district: 'RAMANATHAPURAM', block: 'BOGALUR', name: 'Pottithatti', lgdCode: '227128' },
    { district: 'RAMANATHAPURAM', block: 'BOGALUR', name: 'Veeravanur', lgdCode: '227137' },
    { district: 'RAMANATHAPURAM', block: 'BOGALUR', name: 'Urathur', lgdCode: '227135' },
    { district: 'RAMANATHAPURAM', block: 'BOGALUR', name: 'Kumukkottai', lgdCode: '227118' },
    { district: 'RAMANATHAPURAM', block: 'BOGALUR', name: 'Pandikanmai', lgdCode: '227127' },
    { district: 'RAMANATHAPURAM', block: 'BOGALUR', name: 'Theeyanur', lgdCode: '227134' },
    { district: 'RAMANATHAPURAM', block: 'BOGALUR', name: 'Manjakkollai', lgdCode: '227122' },
    { district: 'RAMANATHAPURAM', block: 'BOGALUR', name: 'S.Kodikulam', lgdCode: '227129' },
    { district: 'RAMANATHAPURAM', block: 'BOGALUR', name: 'Sheiyalur', lgdCode: '227132' },
    { district: 'RAMANATHAPURAM', block: 'BOGALUR', name: 'Kavithaikudi', lgdCode: '227120' },
    { district: 'RAMANATHAPURAM', block: 'BOGALUR', name: 'Karuthanenthal', lgdCode: '227119' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'ERVADI', lgdCode: '227144' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'NARIPPAIYUR R.F B/B', lgdCode: '227172' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'SIKKAL A/C', lgdCode: '227190' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'Valinokkam', lgdCode: '227197' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'MARIYUR A/C', lgdCode: '227166' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'KANNIRAJPURAM', lgdCode: '227152' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'Appanur', lgdCode: '227140' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'S.THARAIKUDI', lgdCode: '227185' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'Sevalpatti', lgdCode: '227189' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'POTHIKULAM', lgdCode: '227181' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'KEELACHIRUPODHU', lgdCode: '227154' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'Elajembur', lgdCode: '227146' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'KADALADI', lgdCode: '227148' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'KEELAKIDARAM', lgdCode: '227155' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'SIRAIKULAM', lgdCode: '227191' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'KIDATHIRUKKAI', lgdCode: '227159' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'Meenagudi', lgdCode: '227167' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'Avathandai', lgdCode: '227141' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'KARUNKULAM', lgdCode: '227153' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'PILLAIARKULAM', lgdCode: '227180' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'MELASELVANUR', lgdCode: '227170' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'KADUGUSANDAI', lgdCode: '227149' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'MOOKKAIYUR', lgdCode: '227171' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'KEELASELVANUR', lgdCode: '227157' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'MELAKIDARAM A/C', lgdCode: '227169' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'PERIAKULAM A/E', lgdCode: '227179' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'Ithampadal', lgdCode: '227145' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'T.Veppangulam', lgdCode: '227195' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'A.Punavaasal A/E', lgdCode: '227138' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'Kotthangulam', lgdCode: '227162' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'Oppilaan', lgdCode: '227173' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'P.Keeranthai', lgdCode: '227158' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'MELACHIRUPODHU', lgdCode: '227168' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'ORIVAYAL', lgdCode: '227174' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'Severiyarpattinam', lgdCode: '227147' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'Kandilan', lgdCode: '227150' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'Enathi A/B', lgdCode: '227143' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'Sokkanai', lgdCode: '227186' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'THANICHIYAM A/C', lgdCode: '227193' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'S. KEERANTHAI', lgdCode: '227182' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'KEELASAKULAM', lgdCode: '227156' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'MARANDAI', lgdCode: '227165' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'PEIKULAM', lgdCode: '227178' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'Kaanikoor', lgdCode: '227151' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'PANIVASAL A/B', lgdCode: '227176' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'S. VAGAIKULAM', lgdCode: '227183' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'UCHINATHAM', lgdCode: '227196' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'MANGALAM', lgdCode: '227164' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'A.USILANKULAM', lgdCode: '227139' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'M.KARISALKULAM', lgdCode: '227163' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'T.KARISALKULAM', lgdCode: '227192' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'CHITHIRANGUDI', lgdCode: '227142' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'Oruvanenthal', lgdCode: '227175' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'THIRUMALUGANDANKOTTAI A/B', lgdCode: '227194' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'KONDUNALLANPATTI A/B', lgdCode: '227161' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'Senjadainathapuram', lgdCode: '227187' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'S.P.KOTTAI', lgdCode: '227184' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'Kokkarasankottai', lgdCode: '227160' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'PANNANTHAI', lgdCode: '227177' },
    { district: 'RAMANATHAPURAM', block: 'KADALADI', name: 'V.SETHURAJAPURAM', lgdCode: '227188' },
    { district: 'RAMANATHAPURAM', block: 'KAMUTHI', name: 'Mandalamanickam', lgdCode: '227217' },
    { district: 'RAMANATHAPURAM', block: 'KAMUTHI', name: 'Peraiyur', lgdCode: '227236' },
    { district: 'RAMANATHAPURAM', block: 'KAMUTHI', name: 'Mustakkurichi', lgdCode: '227223' },
    { district: 'RAMANATHAPURAM', block: 'KAMUTHI', name: 'Perunali', lgdCode: '227237' },
    { district: 'RAMANATHAPURAM', block: 'KAMUTHI', name: 'Ramasamypatti', lgdCode: '227241' },
    { district: 'RAMANATHAPURAM', block: 'KAMUTHI', name: 'Kovilangulam', lgdCode: '227215' },
    { district: 'RAMANATHAPURAM', block: 'KAMUTHI', name: 'Pakkuvetti', lgdCode: '227230' },
    { district: 'RAMANATHAPURAM', block: 'KAMUTHI', name: 'Narayanapuram', lgdCode: '227226' },
    { district: 'RAMANATHAPURAM', block: 'KAMUTHI', name: 'Achangulam', lgdCode: '227199' },
    { district: 'RAMANATHAPURAM', block: 'KAMUTHI', name: 'Keelamudimannarkottai', lgdCode: '227212' },
    { district: 'RAMANATHAPURAM', block: 'KAMUTHI', name: 'Udaiyanathapuram', lgdCode: '227247' },
    { district: 'RAMANATHAPURAM', block: 'KAMUTHI', name: 'T.Punavasal', lgdCode: '227245' },
    { district: 'RAMANATHAPURAM', block: 'KAMUTHI', name: 'Neeravi', lgdCode: '227228' },
    { district: 'RAMANATHAPURAM', block: 'KAMUTHI', name: 'Ilandaikulam', lgdCode: '227206' },
    { district: 'RAMANATHAPURAM', block: 'KAMUTHI', name: 'O.Karisalkulam', lgdCode: '227229' },
    { district: 'RAMANATHAPURAM', block: 'KAMUTHI', name: 'N.Karisalkulam', lgdCode: '227224' },
    { district: 'RAMANATHAPURAM', block: 'KAMUTHI', name: 'Natham', lgdCode: '227227' },
    { district: 'RAMANATHAPURAM', block: 'KAMUTHI', name: 'Pasumpon', lgdCode: '227235' },
    { district: 'RAMANATHAPURAM', block: 'KAMUTHI', name: 'Pappangulam', lgdCode: '227233' },
    { district: 'RAMANATHAPURAM', block: 'KAMUTHI', name: 'Thimmanathapuram', lgdCode: '227246' },
    { district: 'RAMANATHAPURAM', block: 'KAMUTHI', name: 'Sadayanendal', lgdCode: '227242' },
    { district: 'RAMANATHAPURAM', block: 'KAMUTHI', name: 'K.Nedungulam', lgdCode: '227207' },
    { district: 'RAMANATHAPURAM', block: 'KAMUTHI', name: 'Pulvoikulam', lgdCode: '227240' },
    { district: 'RAMANATHAPURAM', block: 'KAMUTHI', name: 'Valaiyapookulam', lgdCode: '227248' },
    { district: 'RAMANATHAPURAM', block: 'KAMUTHI', name: 'Pappurettiapatti', lgdCode: '227234' },
    { district: 'RAMANATHAPURAM', block: 'KAMUTHI', name: 'Keelaramanathi', lgdCode: '227213' },
    { district: 'RAMANATHAPURAM', block: 'KAMUTHI', name: 'Melaramanathi', lgdCode: '227221' },
    { district: 'RAMANATHAPURAM', block: 'KAMUTHI', name: 'M.Pudukulam', lgdCode: '227216' },
    { district: 'RAMANATHAPURAM', block: 'KAMUTHI', name: 'Vallanthai', lgdCode: '227249' },
    { district: 'RAMANATHAPURAM', block: 'KAMUTHI', name: 'Vangarupuram', lgdCode: '227250' },
    { district: 'RAMANATHAPURAM', block: 'KAMUTHI', name: 'Kathanendal', lgdCode: '227211' },
    { district: 'RAMANATHAPURAM', block: 'KAMUTHI', name: 'Kadamangalam', lgdCode: '227209' },
    { district: 'RAMANATHAPURAM', block: 'KAMUTHI', name: 'K.Veppangulam', lgdCode: '227208' },
    { district: 'RAMANATHAPURAM', block: 'KAMUTHI', name: 'Idivilagi', lgdCode: '227205' },
    { district: 'RAMANATHAPURAM', block: 'KAMUTHI', name: 'A.Tharaikudi', lgdCode: '227198' },
    { district: 'RAMANATHAPURAM', block: 'KAMUTHI', name: 'Anaiyur', lgdCode: '227200' },
    { district: 'RAMANATHAPURAM', block: 'KAMUTHI', name: 'Sengappadai', lgdCode: '227243' },
    { district: 'RAMANATHAPURAM', block: 'KAMUTHI', name: 'Marakkulam', lgdCode: '227218' },
    { district: 'RAMANATHAPURAM', block: 'KAMUTHI', name: 'Erumaikulam', lgdCode: '227203' },
    { district: 'RAMANATHAPURAM', block: 'KAMUTHI', name: 'Muthalnadu', lgdCode: '227222' },
    { district: 'RAMANATHAPURAM', block: 'KAMUTHI', name: 'Pammanendal', lgdCode: '227231' },
    { district: 'RAMANATHAPURAM', block: 'KAMUTHI', name: 'T.Valasubramaniapuram', lgdCode: '227244' },
    { district: 'RAMANATHAPURAM', block: 'KAMUTHI', name: 'Kakkudi', lgdCode: '227210' },
    { district: 'RAMANATHAPURAM', block: 'KAMUTHI', name: 'Komboothi', lgdCode: '227214' },
    { district: 'RAMANATHAPURAM', block: 'KAMUTHI', name: 'Melamudimannarkottai', lgdCode: '227220' },
    { district: 'RAMANATHAPURAM', block: 'KAMUTHI', name: 'Ponthampuli', lgdCode: '227238' },
    { district: 'RAMANATHAPURAM', block: 'KAMUTHI', name: 'Pappanam', lgdCode: '227232' },
    { district: 'RAMANATHAPURAM', block: 'KAMUTHI', name: 'Mavilangai', lgdCode: '227219' },
    { district: 'RAMANATHAPURAM', block: 'KAMUTHI', name: 'Ariamangalam', lgdCode: '227201' },
    { district: 'RAMANATHAPURAM', block: 'KAMUTHI', name: 'Pudukkottai', lgdCode: '227239' },
    { district: 'RAMANATHAPURAM', block: 'KAMUTHI', name: 'Eluvanur', lgdCode: '227202' },
    { district: 'RAMANATHAPURAM', block: 'KAMUTHI', name: 'Idaiyankulam', lgdCode: '227204' },
    { district: 'RAMANATHAPURAM', block: 'KAMUTHI', name: 'Nagaratharkurichi', lgdCode: '227225' },
    { district: 'RAMANATHAPURAM', block: 'MUDUKULATHUR', name: 'THERIRUVELI', lgdCode: '227317' },
    { district: 'RAMANATHAPURAM', block: 'MUDUKULATHUR', name: 'VILANKULATHUR', lgdCode: '227324' },
    { district: 'RAMANATHAPURAM', block: 'MUDUKULATHUR', name: 'KEELATHOOVAL', lgdCode: '227292' },
    { district: 'RAMANATHAPURAM', block: 'MUDUKULATHUR', name: 'KOLUNTHURAI', lgdCode: '227293' },
    { district: 'RAMANATHAPURAM', block: 'MUDUKULATHUR', name: 'KAKKUR', lgdCode: '227285' },
    { district: 'RAMANATHAPURAM', block: 'MUDUKULATHUR', name: 'SELLUR', lgdCode: '227312' },
    { district: 'RAMANATHAPURAM', block: 'MUDUKULATHUR', name: 'PONNAKKANERI', lgdCode: '227305' },
    { district: 'RAMANATHAPURAM', block: 'MUDUKULATHUR', name: 'Pirabukkalur', lgdCode: '227304' },
    { district: 'RAMANATHAPURAM', block: 'MUDUKULATHUR', name: 'PULIYANGUDI', lgdCode: '227309' },
    { district: 'RAMANATHAPURAM', block: 'MUDUKULATHUR', name: 'MELAKODUMALUR', lgdCode: '227298' },
    { district: 'RAMANATHAPURAM', block: 'MUDUKULATHUR', name: 'KEELAKULAM', lgdCode: '227291' },
    { district: 'RAMANATHAPURAM', block: 'MUDUKULATHUR', name: 'ULAIYUR', lgdCode: '227319' },
    { district: 'RAMANATHAPURAM', block: 'MUDUKULATHUR', name: 'KEERANUR', lgdCode: '227288' },
    { district: 'RAMANATHAPURAM', block: 'MUDUKULATHUR', name: 'THIRUVARANGAM', lgdCode: '227318' },
    { district: 'RAMANATHAPURAM', block: 'MUDUKULATHUR', name: 'VALANADU', lgdCode: '227320' },
    { district: 'RAMANATHAPURAM', block: 'MUDUKULATHUR', name: 'VENGALAKURICHI', lgdCode: '227322' },
    { district: 'RAMANATHAPURAM', block: 'MUDUKULATHUR', name: 'ALANGAANOOR', lgdCode: '227279' },
    { district: 'RAMANATHAPURAM', block: 'MUDUKULATHUR', name: 'POOSERI', lgdCode: '227306' },
    { district: 'RAMANATHAPURAM', block: 'MUDUKULATHUR', name: 'NALLUKURICHI', lgdCode: '227300' },
    { district: 'RAMANATHAPURAM', block: 'MUDUKULATHUR', name: 'MAKINDI', lgdCode: '227295' },
    { district: 'RAMANATHAPURAM', block: 'MUDUKULATHUR', name: 'ARAPOTHU', lgdCode: '227281' },
    { district: 'RAMANATHAPURAM', block: 'MUDUKULATHUR', name: 'SAMBAKULAM', lgdCode: '227310' },
    { district: 'RAMANATHAPURAM', block: 'MUDUKULATHUR', name: 'SATHANUR', lgdCode: '227311' },
    { district: 'RAMANATHAPURAM', block: 'MUDUKULATHUR', name: 'KEELAKODUMALUR', lgdCode: '227290' },
    { district: 'RAMANATHAPURAM', block: 'MUDUKULATHUR', name: 'SIRUTHALAI', lgdCode: '227316' },
    { district: 'RAMANATHAPURAM', block: 'MUDUKULATHUR', name: 'SELVANAYAGAPURAM', lgdCode: '227313' },
    { district: 'RAMANATHAPURAM', block: 'MUDUKULATHUR', name: 'ATHANAKURICHI', lgdCode: '227282' },
    { district: 'RAMANATHAPURAM', block: 'MUDUKULATHUR', name: 'PULITHIKULAM', lgdCode: '227308' },
    { district: 'RAMANATHAPURAM', block: 'MUDUKULATHUR', name: 'ATHANKOTHANKUDI', lgdCode: '227283' },
    { district: 'RAMANATHAPURAM', block: 'MUDUKULATHUR', name: 'POSUKKUDI', lgdCode: '227307' },
    { district: 'RAMANATHAPURAM', block: 'MUDUKULATHUR', name: 'ATHIKULAM', lgdCode: '227284' },
    { district: 'RAMANATHAPURAM', block: 'MUDUKULATHUR', name: 'MANALOOR', lgdCode: '227296' },
    { district: 'RAMANATHAPURAM', block: 'MUDUKULATHUR', name: 'KUMARAKURICHI', lgdCode: '227294' },
    { district: 'RAMANATHAPURAM', block: 'MUDUKULATHUR', name: 'Anaiseri', lgdCode: '227280' },
    { district: 'RAMANATHAPURAM', block: 'MUDUKULATHUR', name: 'KARUMAL', lgdCode: '227286' },
    { district: 'RAMANATHAPURAM', block: 'MUDUKULATHUR', name: 'VIKKIRAMAPANDIAPURAM', lgdCode: '227323' },
    { district: 'RAMANATHAPURAM', block: 'MUDUKULATHUR', name: 'MELAKKANNISERI', lgdCode: '227297' },
    { district: 'RAMANATHAPURAM', block: 'MUDUKULATHUR', name: 'PERIYA ILAI', lgdCode: '227303' },
    { district: 'RAMANATHAPURAM', block: 'MUDUKULATHUR', name: 'Michealpattanam', lgdCode: '227299' },
    { district: 'RAMANATHAPURAM', block: 'MUDUKULATHUR', name: 'VILAKKANENTHAL', lgdCode: '227321' },
    { district: 'RAMANATHAPURAM', block: 'MUDUKULATHUR', name: 'SEMPONKUDI', lgdCode: '227314' },
    { district: 'RAMANATHAPURAM', block: 'MUDUKULATHUR', name: 'NALLUR', lgdCode: '227301' },
    { district: 'RAMANATHAPURAM', block: 'MUDUKULATHUR', name: 'SIRUGUDI', lgdCode: '227315' },
    { district: 'RAMANATHAPURAM', block: 'MUDUKULATHUR', name: 'KATHAKULAM', lgdCode: '227287' },
    { district: 'RAMANATHAPURAM', block: 'MUDUKULATHUR', name: 'KEELAKANCHIRANKULAM', lgdCode: '227289' },
    { district: 'RAMANATHAPURAM', block: 'MUDUKULATHUR', name: 'S.R.N.PALANKULAM', lgdCode: '227302' },
    { district: 'RAMANATHAPURAM', block: 'NAINARKOIL', name: 'Potagavayal', lgdCode: '234349' },
    { district: 'RAMANATHAPURAM', block: 'NAINARKOIL', name: 'Vallam', lgdCode: '234360' },
    { district: 'RAMANATHAPURAM', block: 'NAINARKOIL', name: 'Thaliyadikottai', lgdCode: '234354' },
    { district: 'RAMANATHAPURAM', block: 'NAINARKOIL', name: 'Siruvayal', lgdCode: '234353' },
    { district: 'RAMANATHAPURAM', block: 'NAINARKOIL', name: 'Akkiramesi', lgdCode: '234326' },
    { district: 'RAMANATHAPURAM', block: 'NAINARKOIL', name: 'Ariyankottai', lgdCode: '234328' },
    { district: 'RAMANATHAPURAM', block: 'NAINARKOIL', name: 'Karadarnthakudi', lgdCode: '234332' },
    { district: 'RAMANATHAPURAM', block: 'NAINARKOIL', name: 'Nainarkovil', lgdCode: '234342' },
    { district: 'RAMANATHAPURAM', block: 'NAINARKOIL', name: 'Anjamadaikatchan', lgdCode: '234325' },
    { district: 'RAMANATHAPURAM', block: 'NAINARKOIL', name: 'Kiliyur', lgdCode: '234334' },
    { district: 'RAMANATHAPURAM', block: 'NAINARKOIL', name: 'Attangudi', lgdCode: '234329' },
    { district: 'RAMANATHAPURAM', block: 'NAINARKOIL', name: 'Nagaram', lgdCode: '234340' },
    { district: 'RAMANATHAPURAM', block: 'NAINARKOIL', name: 'Radhappuli', lgdCode: '234350' },
    { district: 'RAMANATHAPURAM', block: 'NAINARKOIL', name: 'Pandiyur', lgdCode: '234347' },
    { district: 'RAMANATHAPURAM', block: 'NAINARKOIL', name: 'Panthappanenthal', lgdCode: '234346' },
    { district: 'RAMANATHAPURAM', block: 'NAINARKOIL', name: 'Nagaramangalam', lgdCode: '234341' },
    { district: 'RAMANATHAPURAM', block: 'NAINARKOIL', name: 'Kulathur', lgdCode: '234337' },
    { district: 'RAMANATHAPURAM', block: 'NAINARKOIL', name: 'P. Kodikulam', lgdCode: '234343' },
    { district: 'RAMANATHAPURAM', block: 'NAINARKOIL', name: 'Kottakudi', lgdCode: '234336' },
    { district: 'RAMANATHAPURAM', block: 'NAINARKOIL', name: 'Sirakikottai', lgdCode: '234352' },
    { district: 'RAMANATHAPURAM', block: 'NAINARKOIL', name: 'Vaniyavallam', lgdCode: '234361' },
    { district: 'RAMANATHAPURAM', block: 'NAINARKOIL', name: 'Thethangal', lgdCode: '234356' },
    { district: 'RAMANATHAPURAM', block: 'NAINARKOIL', name: 'Gangaikondan', lgdCode: '234330' },
    { district: 'RAMANATHAPURAM', block: 'NAINARKOIL', name: 'Arasanur', lgdCode: '234327' },
    { district: 'RAMANATHAPURAM', block: 'NAINARKOIL', name: 'Vadhavanery', lgdCode: '234358' },
    { district: 'RAMANATHAPURAM', block: 'NAINARKOIL', name: 'Sadurvedamangalam', lgdCode: '234351' },
    { district: 'RAMANATHAPURAM', block: 'NAINARKOIL', name: 'A. Panaiyoor', lgdCode: '234345' },
    { district: 'RAMANATHAPURAM', block: 'NAINARKOIL', name: 'Pagaiventri', lgdCode: '234344' },
    { district: 'RAMANATHAPURAM', block: 'NAINARKOIL', name: 'Vagavayal', lgdCode: '234359' },
    { district: 'RAMANATHAPURAM', block: 'NAINARKOIL', name: 'Keelakavnur', lgdCode: '234333' },
    { district: 'RAMANATHAPURAM', block: 'NAINARKOIL', name: 'Mummudi Chathan', lgdCode: '234339' },
    { district: 'RAMANATHAPURAM', block: 'NAINARKOIL', name: 'Koluvur', lgdCode: '234335' },
    { district: 'RAMANATHAPURAM', block: 'NAINARKOIL', name: 'Thavalaikulam', lgdCode: '234355' },
    { district: 'RAMANATHAPURAM', block: 'NAINARKOIL', name: 'Kalliyadiyenthal', lgdCode: '234331' },
    { district: 'RAMANATHAPURAM', block: 'NAINARKOIL', name: 'Thiyagavanseri', lgdCode: '234357' },
    { district: 'RAMANATHAPURAM', block: 'NAINARKOIL', name: 'Manakudi', lgdCode: '234338' },
    { district: 'RAMANATHAPURAM', block: 'NAINARKOIL', name: 'Perungalur', lgdCode: '234348' },
    { district: 'RAMANATHAPURAM', block: 'PARAMAKUDI', name: 'melappaarthibanur', lgdCode: '227374' },
    { district: 'RAMANATHAPURAM', block: 'PARAMAKUDI', name: 'THELICHATHANALLUR', lgdCode: '227389' },
    { district: 'RAMANATHAPURAM', block: 'PARAMAKUDI', name: 'KAMUTHAKUDI', lgdCode: '227367' },
    { district: 'RAMANATHAPURAM', block: 'PARAMAKUDI', name: 'vendhoni', lgdCode: '227397' },
    { district: 'RAMANATHAPURAM', block: 'PARAMAKUDI', name: 'melaaykkudi', lgdCode: '227375' },
    { district: 'RAMANATHAPURAM', block: 'PARAMAKUDI', name: 'PERUNGARAI', lgdCode: '227382' },
    { district: 'RAMANATHAPURAM', block: 'PARAMAKUDI', name: 'KALAYUR', lgdCode: '227365' },
    { district: 'RAMANATHAPURAM', block: 'PARAMAKUDI', name: 'venkittankurichchi', lgdCode: '227399' },
    { district: 'RAMANATHAPURAM', block: 'PARAMAKUDI', name: 'moosukudi', lgdCode: '227376' },
    { district: 'RAMANATHAPURAM', block: 'PARAMAKUDI', name: 'ARIYANENDAL A/B', lgdCode: '227362' },
    { district: 'RAMANATHAPURAM', block: 'PARAMAKUDI', name: 'vengaaloor', lgdCode: '227398' },
    { district: 'RAMANATHAPURAM', block: 'PARAMAKUDI', name: 'keelapparuththiyur', lgdCode: '227369' },
    { district: 'RAMANATHAPURAM', block: 'PARAMAKUDI', name: 'PAMBUR', lgdCode: '227380' },
    { district: 'RAMANATHAPURAM', block: 'PARAMAKUDI', name: 'vilaththur', lgdCode: '227400' },
    { district: 'RAMANATHAPURAM', block: 'PARAMAKUDI', name: 'kanjiyae ndhal', lgdCode: '227368' },
    { district: 'RAMANATHAPURAM', block: 'PARAMAKUDI', name: 'PUDUKKKUDI', lgdCode: '227384' },
    { district: 'RAMANATHAPURAM', block: 'PARAMAKUDI', name: 'kulandhaapuri', lgdCode: '227371' },
    { district: 'RAMANATHAPURAM', block: 'PARAMAKUDI', name: 'VALIMARICHAN A/C', lgdCode: '227396' },
    { district: 'RAMANATHAPURAM', block: 'PARAMAKUDI', name: 'NENMENI', lgdCode: '227378' },
    { district: 'RAMANATHAPURAM', block: 'PARAMAKUDI', name: 'es.andakkudi', lgdCode: '227386' },
    { district: 'RAMANATHAPURAM', block: 'PARAMAKUDI', name: 'SOODIYUR B/C', lgdCode: '227387' },
    { district: 'RAMANATHAPURAM', block: 'PARAMAKUDI', name: 'urappuli', lgdCode: '227394' },
    { district: 'RAMANATHAPURAM', block: 'PARAMAKUDI', name: 'MADANTHAI', lgdCode: '227372' },
    { district: 'RAMANATHAPURAM', block: 'PARAMAKUDI', name: 'THADUTHALANKOTTAI A/B', lgdCode: '227388' },
    { district: 'RAMANATHAPURAM', block: 'PARAMAKUDI', name: 'peerkkankurichchi', lgdCode: '227381' },
    { district: 'RAMANATHAPURAM', block: 'PARAMAKUDI', name: 'vaalangudi', lgdCode: '227395' },
    { district: 'RAMANATHAPURAM', block: 'PARAMAKUDI', name: 'tholoor', lgdCode: '227392' },
    { district: 'RAMANATHAPURAM', block: 'PARAMAKUDI', name: 'S. KAVANUR', lgdCode: '227385' },
    { district: 'RAMANATHAPURAM', block: 'PARAMAKUDI', name: 'URAKUDI', lgdCode: '227393' },
    { district: 'RAMANATHAPURAM', block: 'PARAMAKUDI', name: 'nelmadoor', lgdCode: '227377' },
    { district: 'RAMANATHAPURAM', block: 'PARAMAKUDI', name: 'K.KARUNGULAM', lgdCode: '227364' },
    { district: 'RAMANATHAPURAM', block: 'PARAMAKUDI', name: 'THINAIKULAM', lgdCode: '227391' },
    { district: 'RAMANATHAPURAM', block: 'PARAMAKUDI', name: 'KALLIKUDI A/B', lgdCode: '227366' },
    { district: 'RAMANATHAPURAM', block: 'PARAMAKUDI', name: 'MELAKAVANUR', lgdCode: '227373' },
    { district: 'RAMANATHAPURAM', block: 'PARAMAKUDI', name: 'P.PUTHUR', lgdCode: '227379' },
    { district: 'RAMANATHAPURAM', block: 'PARAMAKUDI', name: 'ENATHIKOTTAI', lgdCode: '227363' },
    { district: 'RAMANATHAPURAM', block: 'PARAMAKUDI', name: 'podhuvakkudi', lgdCode: '227383' },
    { district: 'RAMANATHAPURAM', block: 'PARAMAKUDI', name: 'KEELAPARTHIBANUR', lgdCode: '227370' },
    { district: 'RAMANATHAPURAM', block: 'PARAMAKUDI', name: 'thenpodhuvakkudi', lgdCode: '227390' }
];

    