import type { Panchayat } from './types';

export const SALEM_PANCHAYATS: Panchayat[] = [
    { district: 'SALEM', block: 'SALEM', name: 'ERUMAPALAYAM', lgdCode: '227788' },
    { district: 'SALEM', block: 'SALEM', name: 'SANYASIGUNDU', lgdCode: '227793' },
    { district: 'SALEM', block: 'SALEM', name: 'ANDIPATTI', lgdCode: '227784' },
    { district: 'SALEM', block: 'SALEM', name: 'INAMVEDUGATHAMPATTI', lgdCode: '227789' },
    { district: 'SALEM', block: 'SALEM', name: 'SELATHAMPATTI', lgdCode: '227795' },
    { district: 'SALEM', block: 'SALEM', name: 'THIRUMALAIGIRI', lgdCode: '227796' },
    { district: 'SALEM', block: 'SALEM', name: 'MAJARAGOLLAPATTI', lgdCode: '227791' },
    { district: 'SALEM', block: 'SALEM', name: 'DHALAVAIPATTI', lgdCode: '227787' },
    { district: 'SALEM', block: 'SALEM', name: 'MALLAMOOPPAMPATTI', lgdCode: '227792' },
    { district: 'SALEM', block: 'SALEM', name: 'SARKARGOLLAPATTI', lgdCode: '227794' },
    { district: 'SALEM', block: 'SALEM', name: 'VATTAMUTHAMPATTI', lgdCode: '227797' },
    { district: 'SALEM', block: 'SALEM', name: 'CHETTICHAVADI', lgdCode: '227786' },
    { district: 'SALEM', block: 'SALEM', name: 'KONDAPPANAICKENPATTI', lgdCode: '227790' },
    { district: 'SALEM', block: 'SALEM', name: 'AYYAMPERUMAMPATTI', lgdCode: '227785' },
    { district: 'SALEM', block: 'VEERAPANDY', name: 'ARIGOUNDAMPATTY', lgdCode: '227894' },
    { district: 'SALEM', block: 'VEERAPANDY', name: 'MURUNGAPATTY', lgdCode: '227904' },
    { district: 'SALEM', block: 'VEERAPANDY', name: 'PERUMAGOUNDAMPATTI', lgdCode: '227907' },
    { district: 'SALEM', block: 'VEERAPANDY', name: 'ANAIKUTTAPATTI', lgdCode: '227893' },
    { district: 'SALEM', block: 'VEERAPANDY', name: 'KALPARAPATTI', lgdCode: '227899' },
    { district: 'SALEM', block: 'VEERAPANDY', name: 'RAKKIPATTI', lgdCode: '227912' },
    { district: 'SALEM', block: 'VEERAPANDY', name: 'SENAIPALAYAM', lgdCode: '227913' },
    { district: 'SALEM', block: 'VEERAPANDY', name: 'VEMBADITHALAM', lgdCode: '227916' },
    { district: 'SALEM', block: 'VEERAPANDY', name: 'POOLAVARI AGRAHARAM', lgdCode: '227909' },
    { district: 'SALEM', block: 'VEERAPANDY', name: 'PUTHUR AGRAHARAM', lgdCode: '227910' },
    { district: 'SALEM', block: 'VEERAPANDY', name: 'UTHAMASOLAPURAM', lgdCode: '227914' },
    { district: 'SALEM', block: 'VEERAPANDY', name: 'MOODUTHURAI', lgdCode: '227903' },
    { district: 'SALEM', block: 'VEERAPANDY', name: 'PERUMAMPATTY', lgdCode: '227908' },
    { district: 'SALEM', block: 'VEERAPANDY', name: 'AKKARAPALAYAM', lgdCode: '227892' },
    { district: 'SALEM', block: 'VEERAPANDY', name: 'INAMBAIROJI', lgdCode: '227897' },
    { district: 'SALEM', block: 'VEERAPANDY', name: 'PERIYA SEERAGAPADI', lgdCode: '227906' },
    { district: 'SALEM', block: 'VEERAPANDY', name: 'VEERAPANDY', lgdCode: '227915' },
    { district: 'SALEM', block: 'VEERAPANDY', name: 'MARAMANGALATHUPATTI', lgdCode: '227901' },
    { district: 'SALEM', block: 'VEERAPANDY', name: 'CHENNAGIRI', lgdCode: '227895' },
    { district: 'SALEM', block: 'VEERAPANDY', name: 'ETTIMANICKAMPATTI', lgdCode: '227896' },
    { district: 'SALEM', block: 'VEERAPANDY', name: 'KADATHUR AGRAHARAM', lgdCode: '227898' },
    { district: 'SALEM', block: 'VEERAPANDY', name: 'MARULAYAMPALAYAM', lgdCode: '227902' },
    { district: 'SALEM', block: 'VEERAPANDY', name: 'PAPPARAPATTY', lgdCode: '227905' },
    { district: 'SALEM', block: 'VEERAPANDY', name: 'RAJAPALAYAM', lgdCode: '227911' },
    { district: 'SALEM', block: 'VEERAPANDY', name: 'KEERAPAPPAMBADI', lgdCode: '227900' },
    { district: 'SALEM', block: 'PANAMARATHUPATTI', name: 'KURALNATHAM', lgdCode: '227734' },
    { district: 'SALEM', block: 'PANAMARATHUPATTI', name: 'PALLITHERUPATTI', lgdCode: '227739' },
    { district: 'SALEM', block: 'PANAMARATHUPATTI', name: 'THIPPAMPATTY', lgdCode: '227745' },
    { district: 'SALEM', block: 'PANAMARATHUPATTI', name: 'AMANIKONDALAMPATTI', lgdCode: '227728' },
    { district: 'SALEM', block: 'PANAMARATHUPATTI', name: 'NEIKKARAPATTY', lgdCode: '227737' },
    { district: 'SALEM', block: 'PANAMARATHUPATTI', name: 'THAMMANAICKENPATTY', lgdCode: '227744' },
    { district: 'SALEM', block: 'PANAMARATHUPATTI', name: 'DASANAICKENPATTI', lgdCode: '227730' },
    { district: 'SALEM', block: 'PANAMARATHUPATTI', name: 'GAJJALNAICKENPATTI', lgdCode: '227732' },
    { district: 'SALEM', block: 'PANAMARATHUPATTI', name: 'NAZHIKKALPATTI', lgdCode: '227736' },
    { district: 'SALEM', block: 'PANAMARATHUPATTI', name: 'NILAVARAPATTI', lgdCode: '227738' },
    { district: 'SALEM', block: 'PANAMARATHUPATTI', name: 'PARAPATTI', lgdCode: '227740' },
    { district: 'SALEM', block: 'PANAMARATHUPATTI', name: 'AMMAPALAYAM', lgdCode: '227729' },
    { district: 'SALEM', block: 'PANAMARATHUPATTI', name: 'ERVADIVANIYAMPADI', lgdCode: '227731' },
    { district: 'SALEM', block: 'PANAMARATHUPATTI', name: 'MOOKKUTHIPALAYAM', lgdCode: '227735' },
    { district: 'SALEM', block: 'PANAMARATHUPATTI', name: 'PERAMANUR', lgdCode: '227741' },
    { district: 'SALEM', block: 'PANAMARATHUPATTI', name: 'SANTHIYUR', lgdCode: '227742' },
    { district: 'SALEM', block: 'PANAMARATHUPATTI', name: 'SANTHIYUR ATTAYAMPATTY', lgdCode: '227743' },
    { district: 'SALEM', block: 'PANAMARATHUPATTI', name: 'VAZHAKKUTTAPATTI', lgdCode: '227747' },
    { district: 'SALEM', block: 'PANAMARATHUPATTI', name: 'KAMMALAPATTI', lgdCode: '227733' },
    { district: 'SALEM', block: 'PANAMARATHUPATTI', name: 'THUMBALPATTI', lgdCode: '227746' },
    { district: 'SALEM', block: 'AYOTHIYAPATTINAM', name: 'Aachankuttapatti', lgdCode: '227562' },
    { district: 'SALEM', block: 'AYOTHIYAPATTINAM', name: 'D. Perumapalayam', lgdCode: '227568' },
    { district: 'SALEM', block: 'AYOTHIYAPATTINAM', name: 'Korathupatti', lgdCode: '227573' },
    { district: 'SALEM', block: 'AYOTHIYAPATTINAM', name: 'Kuppanoor', lgdCode: '227575' },
    { district: 'SALEM', block: 'AYOTHIYAPATTINAM', name: 'Dasanaickenpatti', lgdCode: '227569' },
    { district: 'SALEM', block: 'AYOTHIYAPATTINAM', name: 'M. Palapatti', lgdCode: '227576' },
    { district: 'SALEM', block: 'AYOTHIYAPATTINAM', name: 'Pallipatti', lgdCode: '227582' },
    { district: 'SALEM', block: 'AYOTHIYAPATTINAM', name: 'Poovanoor', lgdCode: '227584' },
    { district: 'SALEM', block: 'AYOTHIYAPATTINAM', name: 'Sukkampatti', lgdCode: '227586' },
    { district: 'SALEM', block: 'AYOTHIYAPATTINAM', name: 'Thailanoor', lgdCode: '227587' },
    { district: 'SALEM', block: 'AYOTHIYAPATTINAM', name: 'Valasaiyur', lgdCode: '227590' },
    { district: 'SALEM', block: 'AYOTHIYAPATTINAM', name: 'Valaiyakaranur', lgdCode: '227589' },
    { district: 'SALEM', block: 'AYOTHIYAPATTINAM', name: 'Chinnagoundapuram', lgdCode: '227566' },
    { district: 'SALEM', block: 'AYOTHIYAPATTINAM', name: 'Chinnanur', lgdCode: '227567' },
    { district: 'SALEM', block: 'AYOTHIYAPATTINAM', name: 'Kullampatti', lgdCode: '227574' },
    { district: 'SALEM', block: 'AYOTHIYAPATTINAM', name: 'M. Thathanoor', lgdCode: '227578' },
    { district: 'SALEM', block: 'AYOTHIYAPATTINAM', name: 'Masinaickenpatti', lgdCode: '227579' },
    { district: 'SALEM', block: 'AYOTHIYAPATTINAM', name: 'Minnampalli', lgdCode: '227581' },
    { district: 'SALEM', block: 'AYOTHIYAPATTINAM', name: 'Periyagoundapuram', lgdCode: '227583' },
    { district: 'SALEM', block: 'AYOTHIYAPATTINAM', name: 'A. N. Mangalam', lgdCode: '227561' },
    { district: 'SALEM', block: 'AYOTHIYAPATTINAM', name: 'Anupur', lgdCode: '227565' },
    { district: 'SALEM', block: 'AYOTHIYAPATTINAM', name: 'Kootathupatti', lgdCode: '227572' },
    { district: 'SALEM', block: 'AYOTHIYAPATTINAM', name: 'S. N. Mangalam', lgdCode: '227585' },
    { district: 'SALEM', block: 'AYOTHIYAPATTINAM', name: 'Adhikaripatti', lgdCode: '227563' },
    { district: 'SALEM', block: 'AYOTHIYAPATTINAM', name: 'Udayapatti', lgdCode: '227588' },
    { district: 'SALEM', block: 'AYOTHIYAPATTINAM', name: 'Veeranam', lgdCode: '227591' },
    { district: 'SALEM', block: 'AYOTHIYAPATTINAM', name: 'Karumapuram', lgdCode: '227570' },
    { district: 'SALEM', block: 'AYOTHIYAPATTINAM', name: 'M. Perumapalayam', lgdCode: '227577' },
    { district: 'SALEM', block: 'AYOTHIYAPATTINAM', name: 'Mettupatti', lgdCode: '227580' },
    { district: 'SALEM', block: 'AYOTHIYAPATTINAM', name: 'Vellalagundam', lgdCode: '227592' },
    { district: 'SALEM', block: 'AYOTHIYAPATTINAM', name: 'Karipatti', lgdCode: '227570' },
    { district: 'SALEM', block: 'AYOTHIYAPATTINAM', name: 'Aladipatti', lgdCode: '227564' },
    { district: 'SALEM', block: 'VALAPADY', name: 'KOLATHUKOMBAI', lgdCode: '227876' },
    { district: 'SALEM', block: 'VALAPADY', name: 'ATHANURPATTI', lgdCode: '227872' },
    { district: 'SALEM', block: 'VALAPADY', name: 'CHANDRAPILLAIVALASU', lgdCode: '227873' },
    { district: 'SALEM', block: 'VALAPADY', name: 'CHINNAMANAICKENPALAYAM', lgdCode: '227874' },
    { district: 'SALEM', block: 'VALAPADY', name: 'KURICHI', lgdCode: '227878' },
    { district: 'SALEM', block: 'VALAPADY', name: 'NEERMULLIKUTTAI', lgdCode: '227882' },
    { district: 'SALEM', block: 'VALAPADY', name: 'PUZHUTHIKUTTAI', lgdCode: '227884' },
    { district: 'SALEM', block: 'VALAPADY', name: 'THUKKIYAMPALAYAM', lgdCode: '227889' },
    { district: 'SALEM', block: 'VALAPADY', name: 'MANNARPALAYAM', lgdCode: '227880' },
    { district: 'SALEM', block: 'VALAPADY', name: 'SINGIPURAM', lgdCode: '227885' },
    { district: 'SALEM', block: 'VALAPADY', name: 'SOMAMPATTI', lgdCode: '227886' },
    { district: 'SALEM', block: 'VALAPADY', name: 'VILARIPALAYAM', lgdCode: '227891' },
    { district: 'SALEM', block: 'VALAPADY', name: 'KOMARAPALAYAM', lgdCode: '227877' },
    { district: 'SALEM', block: 'VALAPADY', name: 'THEKKALPATTI', lgdCode: '227887' },
    { district: 'SALEM', block: 'VALAPADY', name: 'THIRUMANUR', lgdCode: '227888' },
    { district: 'SALEM', block: 'VALAPADY', name: 'VEPPILAIPATTI', lgdCode: '227890' },
    { district: 'SALEM', block: 'VALAPADY', name: 'KATTUVEPPILAIPATTI', lgdCode: '227875' },
    { district: 'SALEM', block: 'VALAPADY', name: 'MANNAICKENPATTI', lgdCode: '227879' },
    { district: 'SALEM', block: 'VALAPADY', name: 'MUTHAMPATTI', lgdCode: '227881' },
    { district: 'SALEM', block: 'VALAPADY', name: 'PONNARAMPATTI', lgdCode: '227883' },
    { district: 'SALEM', block: 'YERCAUD', name: 'MANJAKUTTAI', lgdCode: '227917' },
    { district: 'SALEM', block: 'YERCAUD', name: 'YERCAUD', lgdCode: '227925' },
    { district: 'SALEM', block: 'YERCAUD', name: 'NAGALUR', lgdCode: '227919' },
    { district: 'SALEM', block: 'YERCAUD', name: 'VELUR', lgdCode: '227924' },
    { district: 'SALEM', block: 'YERCAUD', name: 'VAZHAVANTHI', lgdCode: '227922' },
    { district: 'SALEM', block: 'YERCAUD', name: 'SEMMANATHAM', lgdCode: '227920' },
    { district: 'SALEM', block: 'YERCAUD', name: 'THALAISOLAI', lgdCode: '227921' },
    { district: 'SALEM', block: 'YERCAUD', name: 'VELLAKKADAI', lgdCode: '227923' },
    { district: 'SALEM', block: 'YERCAUD', name: 'MARAMANGALAM', lgdCode: '227918' },
    { district: 'SALEM', block: 'PEDDANAICKENPALAYAM', name: 'Gopalapuram', lgdCode: '227757' },
    { district: 'SALEM', block: 'PEDDANAICKENPALAYAM', name: 'Kalarampatty', lgdCode: '227758' },
    { district: 'SALEM', block: 'PEDDANAICKENPALAYAM', name: 'Mettudayarpalayam', lgdCode: '227762' },
    { district: 'SALEM', block: 'PEDDANAICKENPALAYAM', name: 'Puthiragoundanpalayam', lgdCode: '227772' },
    { district: 'SALEM', block: 'PEDDANAICKENPALAYAM', name: 'Vadugathampatty', lgdCode: '227779' },
    { district: 'SALEM', block: 'PEDDANAICKENPALAYAM', name: 'C.K.Hills Therkku Nadu', lgdCode: '227752' },
    { district: 'SALEM', block: 'PEDDANAICKENPALAYAM', name: 'C.K.Hills Vadakku Nadu', lgdCode: '227753' },
    { district: 'SALEM', block: 'PEDDANAICKENPALAYAM', name: 'P.K.Hills Keelnadu', lgdCode: '227766' },
    { district: 'SALEM', block: 'PEDDANAICKENPALAYAM', name: 'P.K.Hills Meelnadu', lgdCode: '227767' },
    { district: 'SALEM', block: 'PEDDANAICKENPALAYAM', name: 'Edayapatty', lgdCode: '227756' },
    { district: 'SALEM', block: 'PEDDANAICKENPALAYAM', name: 'Panamadal', lgdCode: '227769' },
    { district: 'SALEM', block: 'PEDDANAICKENPALAYAM', name: 'Pappanaickenpatty', lgdCode: '227770' },
    { district: 'SALEM', block: 'PEDDANAICKENPALAYAM', name: 'Thandanur', lgdCode: '227775' },
    { district: 'SALEM', block: 'PEDDANAICKENPALAYAM', name: 'Thumbal', lgdCode: '227777' },
    { district: 'SALEM', block: 'PEDDANAICKENPALAYAM', name: 'Vellalapatty', lgdCode: '227782' },
    { district: 'SALEM', block: 'PEDDANAICKENPALAYAM', name: 'Kalleripatty', lgdCode: '227759' },
    { district: 'SALEM', block: 'PEDDANAICKENPALAYAM', name: 'A.Komarapalayam', lgdCode: '227749' },
    { district: 'SALEM', block: 'PEDDANAICKENPALAYAM', name: 'B.Karadipatty', lgdCode: '227751' },
    { district: 'SALEM', block: 'PEDDANAICKENPALAYAM', name: 'Kalyanagiri', lgdCode: '227760' },
    { district: 'SALEM', block: 'PEDDANAICKENPALAYAM', name: 'Kottavadi', lgdCode: '227761' },
    { district: 'SALEM', block: 'PEDDANAICKENPALAYAM', name: 'Sekkadipatty', lgdCode: '227773' },
    { district: 'SALEM', block: 'PEDDANAICKENPALAYAM', name: 'Tamayanur', lgdCode: '227774' },
    { district: 'SALEM', block: 'PEDDANAICKENPALAYAM', name: 'West Rajapalayam', lgdCode: '227783' },
    { district: 'SALEM', block: 'PEDDANAICKENPALAYAM', name: 'A.Karadipatty', lgdCode: '227748' },
    { district: 'SALEM', block: 'PEDDANAICKENPALAYAM', name: 'Ariyapalayam', lgdCode: '227750' },
    { district: 'SALEM', block: 'PEDDANAICKENPALAYAM', name: 'Thalavaipatty', lgdCode: '227755' },
    { district: 'SALEM', block: 'PEDDANAICKENPALAYAM', name: 'Muthagoundanoor', lgdCode: '227763' },
    { district: 'SALEM', block: 'PEDDANAICKENPALAYAM', name: 'Ottapatty', lgdCode: '227764' },
    { district: 'SALEM', block: 'PEDDANAICKENPALAYAM', name: 'Olappady', lgdCode: '227765' },
    { district: 'SALEM', block: 'PEDDANAICKENPALAYAM', name: 'Palaniyapuri', lgdCode: '227768' },
    { district: 'SALEM', block: 'PEDDANAICKENPALAYAM', name: 'Thennampillaiyur', lgdCode: '227776' },
    { district: 'SALEM', block: 'PEDDANAICKENPALAYAM', name: 'Umayalpuram', lgdCode: '227778' },
    { district: 'SALEM', block: 'PEDDANAICKENPALAYAM', name: 'Vaithiyagoundanpudur', lgdCode: '227780' },
    { district: 'SALEM', block: 'PEDDANAICKENPALAYAM', name: 'Veeragoundanoor', lgdCode: '227781' },
    { district: 'SALEM', block: 'PEDDANAICKENPALAYAM', name: 'Chinnakrishnapuram', lgdCode: '227754' },
    { district: 'SALEM', block: 'PEDDANAICKENPALAYAM', name: 'Periyakrishnapuram', lgdCode: '227771' },
    { district: 'SALEM', block: 'ATTUR', name: 'ARASANATHAM', lgdCode: '227544' },
    { district: 'SALEM', block: 'ATTUR', name: 'SEELIAMPATTY', lgdCode: '227556' },
    { district: 'SALEM', block: 'ATTUR', name: 'CHOKKANATHAPURAM', lgdCode: '227545' },
    { district: 'SALEM', block: 'ATTUR', name: 'EACHAMPATTY', lgdCode: '227546' },
    { district: 'SALEM', block: 'ATTUR', name: 'MALLIAKARAI', lgdCode: '227551' },
    { district: 'SALEM', block: 'ATTUR', name: 'AMMAMPALAYAM', lgdCode: '227542' },
    { district: 'SALEM', block: 'ATTUR', name: 'KALPAGANUR', lgdCode: '227548' },
    { district: 'SALEM', block: 'ATTUR', name: 'THULUKANUR', lgdCode: '227559' },
    { district: 'SALEM', block: 'ATTUR', name: 'KOOLAMEDU', lgdCode: '227549' },
    { district: 'SALEM', block: 'ATTUR', name: 'MANJINI', lgdCode: '227552' },
    { district: 'SALEM', block: 'ATTUR', name: 'PAITHUR', lgdCode: '227553' },
    { district: 'SALEM', block: 'ATTUR', name: 'PUNGAVADI', lgdCode: '227554' },
    { district: 'SALEM', block: 'ATTUR', name: 'VALAIYAMADEVI', lgdCode: '227560' },
    { district: 'SALEM', block: 'ATTUR', name: 'AKKICHETTIPALAYAM', lgdCode: '227541' },
    { district: 'SALEM', block: 'ATTUR', name: 'APPAMASAMUDRAM', lgdCode: '227543' },
    { district: 'SALEM', block: 'ATTUR', name: 'THANDAVARAYAPURAM', lgdCode: '227557' },
    { district: 'SALEM', block: 'ATTUR', name: 'KALLANATHAM', lgdCode: '227547' },
    { district: 'SALEM', block: 'ATTUR', name: 'KOTHAMPADI', lgdCode: '227550' },
    { district: 'SALEM', block: 'ATTUR', name: 'RAMANAICKENPALAYAM', lgdCode: '227555' },
    { district: 'SALEM', block: 'ATTUR', name: 'THENNAKUDIPALAYAM', lgdCode: '227558' },
    { district: 'SALEM', block: 'GANGAVALLI', name: 'Naduvalur', lgdCode: '227601' },
    { district: 'SALEM', block: 'GANGAVALLI', name: '95, Belur', lgdCode: '227594' },
    { district: 'SALEM', block: 'GANGAVALLI', name: 'Goodamalai', lgdCode: '227595' },
    { district: 'SALEM', block: 'GANGAVALLI', name: 'Manmalai', lgdCode: '227600' },
    { district: 'SALEM', block: 'GANGAVALLI', name: 'Pachamalai', lgdCode: '227604' },
    { district: 'SALEM', block: 'GANGAVALLI', name: 'Thagarapudur', lgdCode: '227605' },
    { district: 'SALEM', block: 'GANGAVALLI', name: 'Anaiyampatty', lgdCode: '227593' },
    { district: 'SALEM', block: 'GANGAVALLI', name: 'Kadambur', lgdCode: '227597' },
    { district: 'SALEM', block: 'GANGAVALLI', name: '74, Krishnapuram', lgdCode: '227599' },
    { district: 'SALEM', block: 'GANGAVALLI', name: 'Odhiyathur', lgdCode: '227603' },
    { district: 'SALEM', block: 'GANGAVALLI', name: 'Jangamasamudram', lgdCode: '227596' },
    { district: 'SALEM', block: 'GANGAVALLI', name: 'Kondaiyampalli', lgdCode: '227598' },
    { district: 'SALEM', block: 'GANGAVALLI', name: 'Nagiyampatti', lgdCode: '227602' },
    { district: 'SALEM', block: 'GANGAVALLI', name: 'Ulipuram', lgdCode: '227606' },
    { district: 'SALEM', block: 'THALAIVASAL', name: 'Punalvasal', lgdCode: '227837' },
    { district: 'SALEM', block: 'THALAIVASAL', name: 'Sathappadi', lgdCode: '227842' },
    { district: 'SALEM', block: 'THALAIVASAL', name: 'Thenkumarai', lgdCode: '227846' },
    { district: 'SALEM', block: 'THALAIVASAL', name: 'Arathi Agraharam', lgdCode: '227821' },
    { district: 'SALEM', block: 'THALAIVASAL', name: 'Deviyakurichi', lgdCode: '227822' },
    { district: 'SALEM', block: 'THALAIVASAL', name: 'Kamakkapalayam', lgdCode: '227826' },
    { district: 'SALEM', block: 'THALAIVASAL', name: 'Manivilundan', lgdCode: '227830' },
    { district: 'SALEM', block: 'THALAIVASAL', name: 'NavakKurichi', lgdCode: '227831' },
    { district: 'SALEM', block: 'THALAIVASAL', name: 'Pattudurai', lgdCode: '227834' },
    { district: 'SALEM', block: 'THALAIVASAL', name: 'Thalaivasal', lgdCode: '227845' },
    { district: 'SALEM', block: 'THALAIVASAL', name: 'Aragalur', lgdCode: '227820' },
    { district: 'SALEM', block: 'THALAIVASAL', name: 'Govindampalayam', lgdCode: '227824' },
    { district: 'SALEM', block: 'THALAIVASAL', name: 'Periyeri', lgdCode: '227835' },
    { district: 'SALEM', block: 'THALAIVASAL', name: 'Puliyankurichi', lgdCode: '227836' },
    { district: 'SALEM', block: 'THALAIVASAL', name: 'Sitheri', lgdCode: '227844' },
    { district: 'SALEM', block: 'THALAIVASAL', name: 'Thiyaganur', lgdCode: '227848' },
    { district: 'SALEM', block: 'THALAIVASAL', name: 'Veppampoondi', lgdCode: '227853' },
    { district: 'SALEM', block: 'THALAIVASAL', name: 'KattukKottai', lgdCode: '227827' },
    { district: 'SALEM', block: 'THALAIVASAL', name: 'Sadasivapuram', lgdCode: '227839' },
    { district: 'SALEM', block: 'THALAIVASAL', name: 'Sarvoy', lgdCode: '227840' },
    { district: 'SALEM', block: 'THALAIVASAL', name: 'Sarvoy Pudur', lgdCode: '227841' },
    { district: 'SALEM', block: 'THALAIVASAL', name: 'Vadakumarai', lgdCode: '227850' },
    { district: 'SALEM', block: 'THALAIVASAL', name: 'East Rajapalayam', lgdCode: '227823' },
    { district: 'SALEM', block: 'THALAIVASAL', name: 'Iluppanatham', lgdCode: '227825' },
    { district: 'SALEM', block: 'THALAIVASAL', name: 'Kavarpanai', lgdCode: '227828' },
    { district: 'SALEM', block: 'THALAIVASAL', name: 'Lathuvadi', lgdCode: '227829' },
    { district: 'SALEM', block: 'THALAIVASAL', name: 'Navalur', lgdCode: '227832' },
    { district: 'SALEM', block: 'THALAIVASAL', name: 'Pagadapadi', lgdCode: '227833' },
    { district: 'SALEM', block: 'THALAIVASAL', name: 'Thittacherri', lgdCode: '227847' },
    { district: 'SALEM', block: 'THALAIVASAL', name: 'Vellaiyur', lgdCode: '227852' },
    { district: 'SALEM', block: 'THALAIVASAL', name: 'Puthur', lgdCode: '227838' },
    { district: 'SALEM', block: 'THALAIVASAL', name: 'Siruvachur', lgdCode: '227843' },
    { district: 'SALEM', block: 'THALAIVASAL', name: 'Unathur', lgdCode: '227849' },
    { district: 'SALEM', block: 'THALAIVASAL', name: 'Varagur', lgdCode: '227851' },
    { district: 'SALEM', block: 'THALAIVASAL', name: 'Veppanatham', lgdCode: '227854' },
    { district: 'SALEM', block: 'KOLATHUR', name: 'SAMPALLI', lgdCode: '227646' },
    { district: 'SALEM', block: 'KOLATHUR', name: 'KARUNGALLUR', lgdCode: '227638' },
    { district: 'SALEM', block: 'KOLATHUR', name: 'KAVERIPURAM', lgdCode: '227639' },
    { district: 'SALEM', block: 'KOLATHUR', name: 'ALAMARATHUPATTI', lgdCode: '227634' },
    { district: 'SALEM', block: 'KOLATHUR', name: 'CHITHIRAPATTIPUDUR', lgdCode: '227635' },
    { district: 'SALEM', block: 'KOLATHUR', name: 'DHINNAPATTI', lgdCode: '227636' },
    { district: 'SALEM', block: 'KOLATHUR', name: 'KANNAMOOCHI', lgdCode: '227637' },
    { district: 'SALEM', block: 'KOLATHUR', name: 'LAKKAMPATTI', lgdCode: '227641' },
    { district: 'SALEM', block: 'KOLATHUR', name: 'PALAMALAI', lgdCode: '227644' },
    { district: 'SALEM', block: 'KOLATHUR', name: 'PANNAVADI', lgdCode: '227645' },
    { district: 'SALEM', block: 'KOLATHUR', name: 'SINGIRIPATTI', lgdCode: '227647' },
    { district: 'SALEM', block: 'KOLATHUR', name: 'MOOLAKKADU', lgdCode: '227642' },
    { district: 'SALEM', block: 'KOLATHUR', name: 'NAVAPATTI', lgdCode: '227643' },
    { district: 'SALEM', block: 'KOLATHUR', name: 'KOLNAICKENPATTI', lgdCode: '227640' },
    { district: 'SALEM', block: 'NANGAVALLI', name: 'SANARAPATTI', lgdCode: '227691' },
    { district: 'SALEM', block: 'NANGAVALLI', name: 'GONUR', lgdCode: '227688' },
    { district: 'SALEM', block: 'NANGAVALLI', name: 'AVADATHUR', lgdCode: '227686' },
    { district: 'SALEM', block: 'NANGAVALLI', name: 'KARIKKAPATTI', lgdCode: '227689' },
    { district: 'SALEM', block: 'NANGAVALLI', name: 'SURAPALLI', lgdCode: '227692' },
    { district: 'SALEM', block: 'NANGAVALLI', name: 'THORAMANGALAM', lgdCode: '227693' },
    { district: 'SALEM', block: 'NANGAVALLI', name: 'CHINNASORAGAI', lgdCode: '227687' },
    { district: 'SALEM', block: 'NANGAVALLI', name: 'PERIYASORAGAI', lgdCode: '227690' },
    { district: 'SALEM', block: 'NANGAVALLI', name: 'VEERAKKAL', lgdCode: '227694' },
    { district: 'SALEM', block: 'MECHERI', name: 'Thethigiripatti', lgdCode: '227683' },
    { district: 'SALEM', block: 'MECHERI', name: 'Vellar', lgdCode: '227684' },
    { district: 'SALEM', block: 'MECHERI', name: 'Amaram', lgdCode: '227669' },
    { district: 'SALEM', block: 'MECHERI', name: 'Banapuram', lgdCode: '227671' },
    { district: 'SALEM', block: 'MECHERI', name: 'Bukkampatti', lgdCode: '227672' },
    { district: 'SALEM', block: 'MECHERI', name: 'Koppampatti', lgdCode: '227674' },
    { district: 'SALEM', block: 'MECHERI', name: 'M. Kalipatti', lgdCode: '227676' },
    { district: 'SALEM', block: 'MECHERI', name: 'Mallikundam', lgdCode: '227678' },
    { district: 'SALEM', block: 'MECHERI', name: 'Sathapadi', lgdCode: '227682' },
    { district: 'SALEM', block: 'MECHERI', name: 'Pottaneri', lgdCode: '227681' },
    { district: 'SALEM', block: 'MECHERI', name: 'M. N. Patti', lgdCode: '227677' },
    { district: 'SALEM', block: 'MECHERI', name: 'Pallipatti', lgdCode: '227680' },
    { district: 'SALEM', block: 'MECHERI', name: 'Koonandiyur', lgdCode: '227673' },
    { district: 'SALEM', block: 'MECHERI', name: 'Kuttapatti', lgdCode: '227675' },
    { district: 'SALEM', block: 'MECHERI', name: 'Virudhasampatti', lgdCode: '227685' },
    { district: 'SALEM', block: 'MECHERI', name: 'Aranganoor', lgdCode: '227670' },
    { district: 'SALEM', block: 'MECHERI', name: 'Olaipatti', lgdCode: '227679' },
    { district: 'SALEM', block: 'OMALUR', name: 'Kottagoundampatti', lgdCode: '227699' },
    { district: 'SALEM', block: 'OMALUR', name: 'Kottamariammankoil', lgdCode: '227700' },
    { district: 'SALEM', block: 'OMALUR', name: 'M. Chettipatti', lgdCode: '227702' },
    { district: 'SALEM', block: 'OMALUR', name: 'Pachanampatti', lgdCode: '227708' },
    { district: 'SALEM', block: 'OMALUR', name: 'Pagalpatti', lgdCode: '227709' },
    { district: 'SALEM', block: 'OMALUR', name: 'Sellapillaikuttai', lgdCode: '227716' },
    { district: 'SALEM', block: 'OMALUR', name: 'Thindamangalam', lgdCode: '227722' },
    { district: 'SALEM', block: 'OMALUR', name: 'Thumbipadi', lgdCode: '227724' },
    { district: 'SALEM', block: 'OMALUR', name: 'Periyeripatti', lgdCode: '227710' },
    { district: 'SALEM', block: 'OMALUR', name: 'Tholasampatti', lgdCode: '227723' },
    { district: 'SALEM', block: 'OMALUR', name: 'U. Maramangalam', lgdCode: '227725' },
    { district: 'SALEM', block: 'OMALUR', name: 'Gollapatti', lgdCode: '227697' },
    { district: 'SALEM', block: 'OMALUR', name: 'Moogilpadi', lgdCode: '227704' },
    { district: 'SALEM', block: 'OMALUR', name: 'Naranampalayam', lgdCode: '227707' },
    { district: 'SALEM', block: 'OMALUR', name: 'S. Chettipatti', lgdCode: '227713' },
    { district: 'SALEM', block: 'OMALUR', name: 'Thekkampatti', lgdCode: '227721' },
    { district: 'SALEM', block: 'OMALUR', name: 'Vellalapatti', lgdCode: '227727' },
    { district: 'SALEM', block: 'OMALUR', name: 'Manguppai', lgdCode: '227703' },
    { district: 'SALEM', block: 'OMALUR', name: 'Balbakki', lgdCode: '227695' },
    { district: 'SALEM', block: 'OMALUR', name: 'Ettikuttapatti', lgdCode: '227696' },
    { district: 'SALEM', block: 'OMALUR', name: 'Kamalapuram', lgdCode: '227698' },
    { district: 'SALEM', block: 'OMALUR', name: 'Kottamettupatti', lgdCode: '227701' },
    { district: 'SALEM', block: 'OMALUR', name: 'Muthunaikenpatti', lgdCode: '227705' },
    { district: 'SALEM', block: 'OMALUR', name: 'Nallagoundampatti', lgdCode: '227706' },
    { district: 'SALEM', block: 'OMALUR', name: 'Pottipuram', lgdCode: '227711' },
    { district: 'SALEM', block: 'OMALUR', name: 'Puliampatti', lgdCode: '227712' },
    { district: 'SALEM', block: 'OMALUR', name: 'Saminaikenpatti', lgdCode: '227714' },
    { district: 'SALEM', block: 'OMALUR', name: 'Sangeethapatti', lgdCode: '227715' },
    { district: 'SALEM', block: 'OMALUR', name: 'Sikkanampatti', lgdCode: '227719' },
    { district: 'SALEM', block: 'OMALUR', name: 'Thathiyampatti', lgdCode: '227720' },
    { district: 'SALEM', block: 'OMALUR', name: 'Vellakkalpatti', lgdCode: '227726' },
    { district: 'SALEM', block: 'OMALUR', name: 'Semmankoodal', lgdCode: '227717' },
    { district: 'SALEM', block: 'OMALUR', name: 'Sikkampatty', lgdCode: '227718' },
    { district: 'SALEM', block: 'THARAMANGALAM', name: 'PANIKKANUR', lgdCode: '227867' },
    { district: 'SALEM', block: 'THARAMANGALAM', name: 'PAPPAMPADI', lgdCode: '227868' },
    { district: 'SALEM', block: 'THARAMANGALAM', name: 'ALAGUSAMUDRAM', lgdCode: '227855' },
    { district: 'SALEM', block: 'THARAMANGALAM', name: 'KARUKKALVADI', lgdCode: '227863' },
    { district: 'SALEM', block: 'THARAMANGALAM', name: 'MANATHAL', lgdCode: '227866' },
    { district: 'SALEM', block: 'THARAMANGALAM', name: 'ARIYAMPATTI', lgdCode: '227857' },
    { district: 'SALEM', block: 'THARAMANGALAM', name: 'ARURPATTI', lgdCode: '227858' },
    { district: 'SALEM', block: 'THARAMANGALAM', name: 'RAMIREDDIPATTI', lgdCode: '227869' },
    { district: 'SALEM', block: 'THARAMANGALAM', name: 'SELAVADAI', lgdCode: '227870' },
    { district: 'SALEM', block: 'THARAMANGALAM', name: 'DESAVILAKKU', lgdCode: '227859' },
    { district: 'SALEM', block: 'THARAMANGALAM', name: 'AMARAGUNDHI', lgdCode: '227856' },
    { district: 'SALEM', block: 'THARAMANGALAM', name: 'T.KONAGAPADI', lgdCode: '227871' },
    { district: 'SALEM', block: 'THARAMANGALAM', name: 'EDAYAPATTI', lgdCode: '227861' },
    { district: 'SALEM', block: 'THARAMANGALAM', name: 'ELAVAMPATTI', lgdCode: '227862' },
    { district: 'SALEM', block: 'THARAMANGALAM', name: 'KURUKKUPATTI', lgdCode: '227864' },
    { district: 'SALEM', block: 'THARAMANGALAM', name: 'MALLIKUTTAI', lgdCode: '227865' },
    { district: 'SALEM', block: 'THARAMANGALAM', name: 'DUTTAMPATTI', lgdCode: '227860' },
    { district: 'SALEM', block: 'KADAYAAMPATTI', name: 'KANJANAICKENPATTI', lgdCode: '227623' },
    { district: 'SALEM', block: 'KADAYAAMPATTI', name: 'KOOKUTTAPATTI', lgdCode: '227626' },
    { district: 'SALEM', block: 'KADAYAAMPATTI', name: 'PANNAPATTI', lgdCode: '227629' },
    { district: 'SALEM', block: 'KADAYAAMPATTI', name: 'POOSARIPATTI', lgdCode: '227630' },
    { district: 'SALEM', block: 'KADAYAAMPATTI', name: 'GUNDUKKAL', lgdCode: '227621' },
    { district: 'SALEM', block: 'KADAYAAMPATTI', name: 'NADUPATTI', lgdCode: '227628' },
    { district: 'SALEM', block: 'KADAYAAMPATTI', name: 'DEEVATTIPATTI', lgdCode: '227619' },
    { district: 'SALEM', block: 'KADAYAAMPATTI', name: 'UMBLICKAMPATTI', lgdCode: '227632' },
    { district: 'SALEM', block: 'KADAYAAMPATTI', name: 'BOMMIYAMPATTI', lgdCode: '227617' },
    { district: 'SALEM', block: 'KADAYAAMPATTI', name: 'DANISHPET', lgdCode: '227618' },
    { district: 'SALEM', block: 'KADAYAAMPATTI', name: 'VEPPILAI', lgdCode: '227633' },
    { district: 'SALEM', block: 'KADAYAAMPATTI', name: 'KARUVALLI', lgdCode: '227624' },
    { district: 'SALEM', block: 'KADAYAAMPATTI', name: 'KONGUPATTI', lgdCode: '227625' },
    { district: 'SALEM', block: 'KADAYAAMPATTI', name: 'SEMMANDAPATTI', lgdCode: '227631' },
    { district: 'SALEM', block: 'KADAYAAMPATTI', name: 'MOOKANUR', lgdCode: '227627' },
    { district: 'SALEM', block: 'KADAYAAMPATTI', name: 'DHARAPURAM', lgdCode: '227620' },
    { district: 'SALEM', block: 'KADAYAAMPATTI', name: 'KANAVAIPUDUR', lgdCode: '227622' },
    { district: 'SALEM', block: 'SANKARI', name: 'Katheri', lgdCode: '227804' },
    { district: 'SALEM', block: 'SANKARI', name: 'Pullagoundampatti agraharam.', lgdCode: '227815' },
    { district: 'SALEM', block: 'SANKARI', name: 'Kaveripatti', lgdCode: '227805' },
    { district: 'SALEM', block: 'SANKARI', name: 'Koneripatti agraharam', lgdCode: '227808' },
    { district: 'SALEM', block: 'SANKARI', name: 'Morur West', lgdCode: '227811' },
    { district: 'SALEM', block: 'SANKARI', name: 'Irugalur', lgdCode: '227802' },
    { district: 'SALEM', block: 'SANKARI', name: 'Annathanapatti', lgdCode: '227799' },
    { district: 'SALEM', block: 'SANKARI', name: 'Kottavaradhampatti', lgdCode: '227809' },
    { district: 'SALEM', block: 'SANKARI', name: 'Sungudivaradhampatti', lgdCode: '227817' },
    { district: 'SALEM', block: 'SANKARI', name: 'Vadugappatti', lgdCode: '227818' },
    { district: 'SALEM', block: 'SANKARI', name: 'Kaveripatti agraharam', lgdCode: '227806' },
    { district: 'SALEM', block: 'SANKARI', name: 'Koneripatti', lgdCode: '227807' },
    { district: 'SALEM', block: 'SANKARI', name: 'Pullagoundampatti', lgdCode: '227814' },
    { district: 'SALEM', block: 'SANKARI', name: 'Alathur', lgdCode: '227798' },
    { district: 'SALEM', block: 'SANKARI', name: 'Chinnagoundanur', lgdCode: '227800' },
    { district: 'SALEM', block: 'SANKARI', name: 'Mothaiyanur', lgdCode: '227812' },
    { district: 'SALEM', block: 'SANKARI', name: 'Sanyasipatti agraharam', lgdCode: '227816' },
    { district: 'SALEM', block: 'SANKARI', name: 'Veerachipalayam', lgdCode: '227819' },
    { district: 'SALEM', block: 'SANKARI', name: 'Devannagoundanur', lgdCode: '227801' },
    { district: 'SALEM', block: 'SANKARI', name: 'Iveli', lgdCode: '227803' },
    { district: 'SALEM', block: 'SANKARI', name: 'Morur East', lgdCode: '227810' },
    { district: 'SALEM', block: 'SANKARI', name: 'Olakkachinnaanur', lgdCode: '227813' },
    { district: 'SALEM', block: 'IDAPPADY', name: 'NEDUNGULAM', lgdCode: '227613' },
    { district: 'SALEM', block: 'IDAPPADY', name: 'AVANIPERUR EAST', lgdCode: '227608' },
    { district: 'SALEM', block: 'IDAPPADY', name: 'DADHAPURAM', lgdCode: '227611' },
    { district: 'SALEM', block: 'IDAPPADY', name: 'VELLARIVELLI', lgdCode: '227615' },
    { district: 'SALEM', block: 'IDAPPADY', name: 'CHETTIMANKURICHI', lgdCode: '227609' },
    { district: 'SALEM', block: 'IDAPPADY', name: 'VEMBANERI', lgdCode: '227616' },
    { district: 'SALEM', block: 'IDAPPADY', name: 'CHITTOOR', lgdCode: '227610' },
    { district: 'SALEM', block: 'IDAPPADY', name: 'ADAIYUR', lgdCode: '227607' },
    { district: 'SALEM', block: 'IDAPPADY', name: 'IRUPPALI', lgdCode: '227612' },
    { district: 'SALEM', block: 'IDAPPADY', name: 'PAKKANADU', lgdCode: '227614' },
    { district: 'SALEM', block: 'KONGANAPURAM', name: 'PUDUPALAYAM', lgdCode: '227653' },
    { district: 'SALEM', block: 'KONGANAPURAM', name: 'SAMUDRAM', lgdCode: '227654' },
    { district: 'SALEM', block: 'KONGANAPURAM', name: 'VELLALAPURAM', lgdCode: '227656' },
    { district: 'SALEM', block: 'KONGANAPURAM', name: 'ERUMAIPATTI', lgdCode: '227648' },
    { district: 'SALEM', block: 'KONGANAPURAM', name: 'KATCHUPALLI', lgdCode: '227649' },
    { district: 'SALEM', block: 'KONGANAPURAM', name: 'KONASAMUDRAM', lgdCode: '227650' },
    { district: 'SALEM', block: 'KONGANAPURAM', name: 'KORANAMPATTI', lgdCode: '227651' },
    { district: 'SALEM', block: 'KONGANAPURAM', name: 'THANGAYUR', lgdCode: '227655' },
    { district: 'SALEM', block: 'KONGANAPURAM', name: 'KURUMBAPATTI', lgdCode: '227652' },
    { district: 'SALEM', block: 'MAC. CHOULTRY', name: 'A.PUDUR', lgdCode: '227657' },
    { district: 'SALEM', block: 'MAC. CHOULTRY', name: 'GUDALUR', lgdCode: '227660' },
    { district: 'SALEM', block: 'MAC. CHOULTRY', name: 'KANAGAGIRI', lgdCode: '227662' },
    { district: 'SALEM', block: 'MAC. CHOULTRY', name: 'KANDARKULAMANICKAM', lgdCode: '227663' },
    { district: 'SALEM', block: 'MAC. CHOULTRY', name: 'KANNANDERI', lgdCode: '227664' },
    { district: 'SALEM', block: 'MAC. CHOULTRY', name: 'MAC.DONALD CHOULTRY', lgdCode: '227665' },
    { district: 'SALEM', block: 'MAC. CHOULTRY', name: 'EGAPURAM', lgdCode: '227659' },
    { district: 'SALEM', block: 'MAC. CHOULTRY', name: 'AGR.THALAIYUR', lgdCode: '227658' },
    { district: 'SALEM', block: 'MAC. CHOULTRY', name: 'KALIGOUNDAMPALAYAM', lgdCode: '227661' },
    { district: 'SALEM', block: 'MAC. CHOULTRY', name: 'VAIKUNDAM', lgdCode: '227668' },
    { district: 'SALEM', block: 'MAC. CHOULTRY', name: 'NADUVANERI', lgdCode: '227666' },
    { district: 'SALEM', block: 'MAC. CHOULTRY', name: 'THAPPAKUTTAI', lgdCode: '227667' },
];
