import type { Panchayat } from './types';

export const SIVAGANGA_PANCHAYATS: Panchayat[] = [
    { district: 'SIVAGANGA', block: 'SIVAGANGA', name: 'Alangulam', lgdCode: '228308' },
    { district: 'SIVAGANGA', block: 'SIVAGANGA', name: 'Arasanoor', lgdCode: '228309' },
    { district: 'SIVAGANGA', block: 'SIVAGANGA', name: 'Budamangalam', lgdCode: '228310' },
    { district: 'SIVAGANGA', block: 'SIVAGANGA', name: 'Edayamelur', lgdCode: '228311' },
    { district: 'SIVAGANGA', block: 'SIVAGANGA', name: 'Enathi', lgdCode: '228312' },
    { district: 'SIVAGANGA', block: 'SIVAGANGA', name: 'K. Sukkanurani', lgdCode: '228314' },
    { district: 'SIVAGANGA', block: 'SIVAGANGA', name: 'Kaliyandur', lgdCode: '228315' },
    { district: 'SIVAGANGA', block: 'SIVAGANGA', name: 'Kallal', lgdCode: '228316' },
    { district: 'SIVAGANGA', block: 'SIVAGANGA', name: 'Kandankulam', lgdCode: '228317' },
    { district: 'SIVAGANGA', block: 'SIVAGANGA', name: 'Kandani', lgdCode: '228318' },
    { district: 'SIVAGANGA', block: 'SIVAGANGA', name: 'Kanjirangal', lgdCode: '228319' },
    { district: 'SIVAGANGA', block: 'SIVAGANGA', name: 'Kannariruppu', lgdCode: '228320' },
    { district: 'SIVAGANGA', block: 'SIVAGANGA', name: 'Karungulam', lgdCode: '228321' },
    { district: 'SIVAGANGA', block: 'SIVAGANGA', name: 'Kathikulam', lgdCode: '228322' },
    { district: 'SIVAGANGA', block: 'SIVAGANGA', name: 'Keelapoongudi', lgdCode: '228323' },
    { district: 'SIVAGANGA', block: 'SIVAGANGA', name: 'Kondanagaram', lgdCode: '228324' },
    { district: 'SIVAGANGA', block: 'SIVAGANGA', name: 'Kottakudi Keelpathi', lgdCode: '228325' },
    { district: 'SIVAGANGA', block: 'SIVAGANGA', name: 'Kottakudi Melpathi', lgdCode: '228326' },
    { district: 'SIVAGANGA', block: 'SIVAGANGA', name: 'Lakshmipuram', lgdCode: '228327' },
    { district: 'SIVAGANGA', block: 'SIVAGANGA', name: 'Madagupatti', lgdCode: '228328' },
    { district: 'SIVAGANGA', block: 'SIVAGANGA', name: 'Malampatti', lgdCode: '228329' },
    { district: 'SIVAGANGA', block: 'SIVAGANGA', name: 'Melapoongudi', lgdCode: '228330' },
    { district: 'SIVAGANGA', block: 'SIVAGANGA', name: 'Muthalur', lgdCode: '228331' },
    { district: 'SIVAGANGA', block: 'SIVAGANGA', name: 'Muthupatti', lgdCode: '228332' },
    { district: 'SIVAGANGA', block: 'SIVAGANGA', name: 'Nattarasankottai', lgdCode: '228333' },
    { district: 'SIVAGANGA', block: 'SIVAGANGA', name: 'Okkur', lgdCode: '228334' },
    { district: 'SIVAGANGA', block: 'SIVAGANGA', name: 'Piranpatti', lgdCode: '228335' },
    { district: 'SIVAGANGA', block: 'SIVAGANGA', name: 'Salamangalam', lgdCode: '228336' },
    { district: 'SIVAGANGA', block: 'SIVAGANGA', name: 'Salippur', lgdCode: '228337' },
    { district: 'SIVAGANGA', block: 'SIVAGANGA', name: 'Satharasankottai', lgdCode: '228338' },
    { district: 'SIVAGANGA', block: 'SIVAGANGA', name: 'Sawarikottai', lgdCode: '228339' },
    { district: 'SIVAGANGA', block: 'SIVAGANGA', name: 'Sunnambur', lgdCode: '228340' },
    { district: 'SIVAGANGA', block: 'SIVAGANGA', name: 'T. Soorakudi', lgdCode: '228341' },
    { district: 'SIVAGANGA', block: 'SIVAGANGA', name: 'Thamarakki (N)', lgdCode: '228342' },
    { district: 'SIVAGANGA', block: 'SIVAGANGA', name: 'Thamarakki (S)', lgdCode: '228343' },
    { district: 'SIVAGANGA', block: 'SIVAGANGA', name: 'Thimaravuthampatti', lgdCode: '228344' },
    { district: 'SIVAGANGA', block: 'SIVAGANGA', name: 'Vaniangudi', lgdCode: '228345' },
];
