
import type { Panchayat } from './types';

export const TENKASI_PANCHAYATS: Panchayat[] = [
    { district: 'TENKASI', block: 'MELANEELITHANALLUR', name: 'Serndamangalam kasba', lgdCode: '230715' },
    { district: 'TENKASI', block: 'MELANEELITHANALLUR', name: 'Vadakkupanavadali', lgdCode: '230719' },
    { district: 'TENKASI', block: 'MELANEELITHANALLUR', name: 'Serndamangalam majara', lgdCode: '230716' },
    { district: 'TENKASI', block: 'MELANEELITHANALLUR', name: 'Keelaneelithanallur', lgdCode: '230703' },
    { district: 'TENKASI', block: 'MELANEELITHANALLUR', name: 'Kulasekaramangalam', lgdCode: '230705' },
    { district: 'TENKASI', block: 'MELANEELITHANALLUR', name: 'Kurukkalpatty', lgdCode: '230706' },
    { district: 'TENKASI', block: 'MELANEELITHANALLUR', name: 'Echanda', lgdCode: '230701' },
    { district: 'TENKASI', block: 'MELANEELITHANALLUR', name: 'Vellalankulam', lgdCode: '230721' },
    { district: 'TENKASI', block: 'MELANEELITHANALLUR', name: 'Naduvakurichi major', lgdCode: '230710' },
    { district: 'TENKASI', block: 'MELANEELITHANALLUR', name: 'Periakovilankulam', lgdCode: '230714' },
    { district: 'TENKASI', block: 'MELANEELITHANALLUR', name: 'Ko.maruthappapuram', lgdCode: '230704' },
    { district: 'TENKASI', block: 'MELANEELITHANALLUR', name: 'Pattadaikatti', lgdCode: '230713' },
    { district: 'TENKASI', block: 'MELANEELITHANALLUR', name: 'Melaneelithanallur', lgdCode: '230708' },
    { district: 'TENKASI', block: 'MELANEELITHANALLUR', name: 'Naduvakurichi minor', lgdCode: '230711' },
    { district: 'TENKASI', block: 'MELANEELITHANALLUR', name: 'Ilandhaikulam', lgdCode: '230702' },
    { district: 'TENKASI', block: 'MELANEELITHANALLUR', name: 'Chinnakovilankulam', lgdCode: '230699' },
    { district: 'TENKASI', block: 'MELANEELITHANALLUR', name: 'Mahenderavadi', lgdCode: '230631' },
    { district: 'TENKASI', block: 'MELANEELITHANALLUR', name: 'Malayankulam', lgdCode: '230633' },
    { district: 'TENKASI', block: 'MELANEELITHANALLUR', name: 'Maruthankinaru', lgdCode: '230634' },
    { district: 'TENKASI', block: 'MELANEELITHANALLUR', name: 'Usilankulam', lgdCode: '230649' },
    { district: 'TENKASI', block: 'KURUVIKULAM', name: 'Kalingapatti', lgdCode: '230627' },
    { district: 'TENKASI', block: 'KURUVIKULAM', name: 'Perunkottur', lgdCode: '230639' },
    { district: 'TENKASI', block: 'KURUVIKULAM', name: 'Palankottai', lgdCode: '230638' },
    { district: 'TENKASI', block: 'KURUVIKULAM', name: 'Vadakku Kuruvikulam', lgdCode: '230650' },
    { district: 'TENKASI', block: 'KURUVIKULAM', name: 'Sayamalai', lgdCode: '230645' },
    { district: 'TENKASI', block: 'KURUVIKULAM', name: 'Sevalkulam', lgdCode: '230646' },
    { district: 'TENKASI', block: 'KURUVIKULAM', name: 'Karisathan', lgdCode: '230628' },
    { district: 'TENKASI', block: 'KURUVIKULAM', name: 'Alagapuri', lgdCode: '230615' },
    { district: 'TENKASI', block: 'KURUVIKULAM', name: 'A. Karisalkulam', lgdCode: '230614' },
    { district: 'TENKASI', block: 'KURUVIKULAM', name: 'Vellakulam', lgdCode: '230653' },
    { district: 'TENKASI', block: 'KURUVIKULAM', name: 'Varaganoor', lgdCode: '230654' },
    { district: 'TENKASI', block: 'KURUVIKULAM', name: 'Ayyaneri', lgdCode: '230617' },
    { district: 'TENKASI', block: 'KURUVIKULAM', name: 'T. Kuruvikulam', lgdCode: '230647' },
    { district: 'TENKASI', block: 'KURUVIKULAM', name: 'Chathirakondan', lgdCode: '230619' },
    { district: 'TENKASI', block: 'KURUVIKULAM', name: 'Nalandula', lgdCode: '230637' },
    { district: 'TENKASI', block: 'KURUVIKULAM', name: 'Sangupatti', lgdCode: '230644' },
    { district: 'TENKASI', block: 'KURUVIKULAM', name: 'Appaneri', lgdCode: '230624' },
    { district: 'TENKASI', block: 'KURUVIKULAM', name: 'Maiparai', lgdCode: '230632' },
    { district: 'TENKASI', block: 'KURUVIKULAM', name: 'Ramalingapuram', lgdCode: '230643' },
    { district: 'TENKASI', block: 'KURUVIKULAM', name: 'Kalappalankulam', lgdCode: '230626' },
    { district: 'TENKASI', block: 'KURUVIKULAM', name: 'Mukkuttumalai', lgdCode: '230635' },
    { district: 'TENKASI', block: 'KURUVIKULAM', name: 'Pillaiyarnatham', lgdCode: '230641' },
    { district: 'TENKASI', block: 'KURUVIKULAM', name: 'Chathirapatti', lgdCode: '230620' },
    { district: 'TENKASI', block: 'KURUVIKULAM', name: 'Vagaikulam', lgdCode: '230652' },
    { district: 'TENKASI', block: 'KURUVIKULAM', name: 'Kurunjakulam', lgdCode: '230630' },
    { district: 'TENKASI', block: 'KURUVIKULAM', name: 'Zameen Devarkulam', lgdCode: '230656' },
    { district: 'TENKASI', block: 'KURUVIKULAM', name: 'Venkatachalapuram', lgdCode: '230655' },
    { district: 'TENKASI', block: 'KURUVIKULAM', name: 'Chidhambarapuram', lgdCode: '230621' },
    { district: 'TENKASI', block: 'KURUVIKULAM', name: 'Athipatti', lgdCode: '230618' },
    { district: 'TENKASI', block: 'KURUVIKULAM', name: 'Pitchaithalaivanpatti', lgdCode: '230640' },
    { district: 'TENKASI', block: 'KURUVIKULAM', name: 'Puliyankulam', lgdCode: '230642' },
    { district: 'TENKASI', block: 'KURUVIKULAM', name: 'K. Alankulam', lgdCode: '230616' },
    { district: 'TENKASI', block: 'KURUVIKULAM', name: 'Umaiyathalaivanpatty', lgdCode: '230648' },
    { district: 'TENKASI', block: 'KURUVIKULAM', name: 'Vadakkupatti', lgdCode: '230651' },
    { district: 'TENKASI', block: 'KURUVIKULAM', name: 'Ilayarasanendal', lgdCode: '230623' },
    { district: 'TENKASI', block: 'KURUVIKULAM', name: 'Chithirampatti', lgdCode: '230622' },
    { district: 'TENKASI', block: 'KURUVIKULAM', name: 'Nakkalamuthanpatti', lgdCode: '230636' },
    { district: 'TENKASI', block: 'KURUVIKULAM', name: 'K. Karisalkulam', lgdCode: '230625' },
    { district: 'TENKASI', block: 'KURUVIKULAM', name: 'Kulakattakuruchi', lgdCode: '230629' },
    { district: 'TENKASI', block: 'SANKARANKOIL', name: 'Veerasigamani', lgdCode: '230848' },
    { district: 'TENKASI', block: 'SANKARANKOIL', name: 'Kalappakulam', lgdCode: '230823' },
    { district: 'TENKASI', block: 'SANKARANKOIL', name: 'Karivalamvandanallur', lgdCode: '230824' },
    { district: 'TENKASI', block: 'SANKARANKOIL', name: 'Ariyanayagipuram', lgdCode: '230822' },
    { district: 'TENKASI', block: 'SANKARANKOIL', name: 'Panaiyoor', lgdCode: '230832' },
    { district: 'TENKASI', block: 'SANKARANKOIL', name: 'T.sankarankoil', lgdCode: '230843' },
    { district: 'TENKASI', block: 'SANKARANKOIL', name: 'Madathupatty', lgdCode: '230827' },
    { district: 'TENKASI', block: 'SANKARANKOIL', name: 'Pandapuli', lgdCode: '230831' },
    { district: 'TENKASI', block: 'SANKARANKOIL', name: 'Perumpathur', lgdCode: '230836' },
    { district: 'TENKASI', block: 'SANKARANKOIL', name: 'Vadakkupudur', lgdCode: '230845' },
    { district: 'TENKASI', block: 'SANKARANKOIL', name: 'Thiruvettanallur', lgdCode: '230844' },
    { district: 'TENKASI', block: 'SANKARANKOIL', name: 'Perumalpatty', lgdCode: '230835' },
    { district: 'TENKASI', block: 'SANKARANKOIL', name: 'Paruvakudi', lgdCode: '230833' },
    { district: 'TENKASI', block: 'SANKARANKOIL', name: 'Subbulapuram', lgdCode: '230842' },
    { district: 'TENKASI', block: 'SANKARANKOIL', name: 'Sennikulam', lgdCode: '230840' },
    { district: 'TENKASI', block: 'SANKARANKOIL', name: 'Keelaveerasigamanai', lgdCode: '230825' },
    { district: 'TENKASI', block: 'SANKARANKOIL', name: 'Mangudi', lgdCode: '230829' },
    { district: 'TENKASI', block: 'SANKARANKOIL', name: 'Kuvalaikanni', lgdCode: '230826' },
    { district: 'TENKASI', block: 'SANKARANKOIL', name: 'Vayali', lgdCode: '230847' },
    { district: 'TENKASI', block: 'SANKARANKOIL', name: 'Vadikottai', lgdCode: '230846' },
    { district: 'TENKASI', block: 'SANKARANKOIL', name: 'Ramanathapuram', lgdCode: '230839' },
    { district: 'TENKASI', block: 'SANKARANKOIL', name: 'Veereruppu', lgdCode: '230849' },
    { district: 'TENKASI', block: 'SANKARANKOIL', name: 'Senthatiyapuram', lgdCode: '230841' },
    { district: 'TENKASI', block: 'SANKARANKOIL', name: 'Manaloor', lgdCode: '230828' },
    { district: 'TENKASI', block: 'SANKARANKOIL', name: 'Periyoor', lgdCode: '230834' },
    { district: 'TENKASI', block: 'SANKARANKOIL', name: 'Nochikulam', lgdCode: '230830' },
    { district: 'TENKASI', block: 'SANKARANKOIL', name: 'Punnaivanam', lgdCode: '230838' },
    { district: 'TENKASI', block: 'SANKARANKOIL', name: 'Poigai', lgdCode: '230837' },
    { district: 'TENKASI', block: 'KADAYAM', name: 'Vengadampatti', lgdCode: '230574' },
    { district: 'TENKASI', block: 'KADAYAM', name: 'keela Kadayam', lgdCode: '230561' },
    { district: 'TENKASI', block: 'KADAYAM', name: 'Pottalpudur', lgdCode: '230567' },
    { district: 'TENKASI', block: 'KADAYAM', name: 'Keela Ambur', lgdCode: '230560' },
    { district: 'TENKASI', block: 'KADAYAM', name: 'Kadayam', lgdCode: '230558' },
    { district: 'TENKASI', block: 'KADAYAM', name: 'Kadayam Perumpathu', lgdCode: '230559' },
    { district: 'TENKASI', block: 'KADAYAM', name: 'Pappankulam', lgdCode: '230566' },
    { district: 'TENKASI', block: 'KADAYAM', name: 'Servaikaranpatti', lgdCode: '230569' },
    { district: 'TENKASI', block: 'KADAYAM', name: 'Anaintha Perumal Nadanoor', lgdCode: '230553' },
    { district: 'TENKASI', block: 'KADAYAM', name: 'Mela Ambur', lgdCode: '230564' },
    { district: 'TENKASI', block: 'KADAYAM', name: 'Ravanasamudram', lgdCode: '230568' },
    { district: 'TENKASI', block: 'KADAYAM', name: 'Therkkumadathur', lgdCode: '230571' },
    { district: 'TENKASI', block: 'KADAYAM', name: 'Adaichani', lgdCode: '230554' },
    { district: 'TENKASI', block: 'KADAYAM', name: 'Dharmapurammadam', lgdCode: '230556' },
    { district: 'TENKASI', block: 'KADAYAM', name: 'Manthiyoor', lgdCode: '230563' },
    { district: 'TENKASI', block: 'KADAYAM', name: 'Ainthnkattalai', lgdCode: '230555' },
    { district: 'TENKASI', block: 'KADAYAM', name: 'Mudaliyarpatti', lgdCode: '230565' },
    { district: 'TENKASI', block: 'KADAYAM', name: 'Thirumalaiyappapuram', lgdCode: '230572' },
    { district: 'TENKASI', block: 'KADAYAM', name: 'Thuppakudi', lgdCode: '230573' },
    { district: 'TENKASI', block: 'KADAYAM', name: 'Govindaperi', lgdCode: '230557' },
    { district: 'TENKASI', block: 'KADAYAM', name: 'Madathur', lgdCode: '230562' },
    { district: 'TENKASI', block: 'KADAYAM', name: 'Sivasailam', lgdCode: '230570' },
    { district: 'TENKASI', block: 'KADAYAM', name: 'Veerasamudram', lgdCode: '230575' },
    { district: 'TENKASI', block: 'ALANKULAM', name: 'Uthumalai', lgdCode: '230510' },
    { district: 'TENKASI', block: 'ALANKULAM', name: 'Kadanganeri', lgdCode: '230488' },
    { district: 'TENKASI', block: 'ALANKULAM', name: 'Nallur', lgdCode: '230504' },
    { district: 'TENKASI', block: 'ALANKULAM', name: 'Keelaveeranam', lgdCode: '230493' },
    { district: 'TENKASI', block: 'ALANKULAM', name: 'Mayamankuruchi', lgdCode: '230500' },
    { district: 'TENKASI', block: 'ALANKULAM', name: 'Karuvantha', lgdCode: '230490' },
    { district: 'TENKASI', block: 'ALANKULAM', name: 'Vadiyoor', lgdCode: '230512' },
    { district: 'TENKASI', block: 'ALANKULAM', name: 'Balapathiramapuram', lgdCode: '230487' },
    { district: 'TENKASI', block: 'ALANKULAM', name: 'Nettur', lgdCode: '230506' },
    { district: 'TENKASI', block: 'ALANKULAM', name: 'Kavalakuruchi', lgdCode: '230491' },
    { district: 'TENKASI', block: 'ALANKULAM', name: 'Keelakalangal', lgdCode: '230492' },
    { district: 'TENKASI', block: 'ALANKULAM', name: 'Achankuttam', lgdCode: '230485' },
    { district: 'TENKASI', block: 'ALANKULAM', name: 'Kurippankulam', lgdCode: '230496' },
    { district: 'TENKASI', block: 'ALANKULAM', name: 'M.M.Puram', lgdCode: '230497' },
    { district: 'TENKASI', block: 'ALANKULAM', name: 'Marukalankulam', lgdCode: '230499' },
    { district: 'TENKASI', block: 'ALANKULAM', name: 'V. Kavalakuruchi', lgdCode: '230511' },
    { district: 'TENKASI', block: 'ALANKULAM', name: 'Maranthai', lgdCode: '230498' },
    { district: 'TENKASI', block: 'ALANKULAM', name: 'Melakalangal', lgdCode: '230501' },
    { district: 'TENKASI', block: 'ALANKULAM', name: 'Sivalarkulam', lgdCode: '230508' },
    { district: 'TENKASI', block: 'ALANKULAM', name: 'Naranapuram', lgdCode: '230505' },
    { district: 'TENKASI', block: 'ALANKULAM', name: 'Ayyanarkulam', lgdCode: '230486' },
    { district: 'TENKASI', block: 'ALANKULAM', name: 'Kurichanpatty', lgdCode: '230495' },
    { district: 'TENKASI', block: 'ALANKULAM', name: 'Kidarakulam', lgdCode: '230494' },
    { district: 'TENKASI', block: 'ALANKULAM', name: 'N.Krishnapuram', lgdCode: '230503' },
    { district: 'TENKASI', block: 'ALANKULAM', name: 'S.V.P.Karadiudaippu', lgdCode: '230507' },
    { district: 'TENKASI', block: 'ALANKULAM', name: 'Subbihapuram', lgdCode: '230509' },
    { district: 'TENKASI', block: 'ALANKULAM', name: 'Kaduvetti', lgdCode: '230489' },
    { district: 'TENKASI', block: 'ALANKULAM', name: 'Melaveeranam', lgdCode: '230502' },
    { district: 'TENKASI', block: 'ALANKULAM', name: 'Kuthapanchan', lgdCode: '230784' },
    { district: 'TENKASI', block: 'ALANKULAM', name: 'Maruthamputhur', lgdCode: '230786' },
    { district: 'TENKASI', block: 'ALANKULAM', name: 'Oodaimarichan', lgdCode: '230787' },
    { district: 'TENKASI', block: 'ALANKULAM', name: 'Pudupatti', lgdCode: '230790' },
    { district: 'TENKASI', block: 'KEELAPAVOOR', name: 'Gurnaramanallur', lgdCode: '230596' },
    { district: 'TENKASI', block: 'KEELAPAVOOR', name: 'Avodiyanoor', lgdCode: '230595' },
    { district: 'TENKASI', block: 'KEELAPAVOOR', name: 'Kulasekarapatti', lgdCode: '230602' },
    { district: 'TENKASI', block: 'KEELAPAVOOR', name: 'Thippanampatty', lgdCode: '230611' },
    { district: 'TENKASI', block: 'KEELAPAVOOR', name: 'Veerakaralampudur', lgdCode: '230613' },
    { district: 'TENKASI', block: 'KEELAPAVOOR', name: 'Pethanadarpatty', lgdCode: '230606' },
    { district: 'TENKASI', block: 'KEELAPAVOOR', name: 'Sivanadanoor', lgdCode: '230610' },
    { district: 'TENKASI', block: 'KEELAPAVOOR', name: 'Ariappapuram', lgdCode: '230594' },
    { district: 'TENKASI', block: 'KEELAPAVOOR', name: 'Poolankulam', lgdCode: '230607' },
    { district: 'TENKASI', block: 'KEELAPAVOOR', name: 'Kallurani', lgdCode: '230599' },
    { district: 'TENKASI', block: 'KEELAPAVOOR', name: 'kaluneerkulam', lgdCode: '230600' },
    { district: 'TENKASI', block: 'KEELAPAVOOR', name: 'Melapavoor', lgdCode: '230604' },
    { district: 'TENKASI', block: 'KEELAPAVOOR', name: 'Rajagopalaperi', lgdCode: '230608' },
    { district: 'TENKASI', block: 'KEELAPAVOOR', name: 'Andipatti', lgdCode: '230593' },
    { district: 'TENKASI', block: 'KEELAPAVOOR', name: 'Melakrishnaperi', lgdCode: '230603' },
    { district: 'TENKASI', block: 'KEELAPAVOOR', name: 'Keelavellakal', lgdCode: '230601' },
    { district: 'TENKASI', block: 'KEELAPAVOOR', name: 'Rajapandi', lgdCode: '230609' },
    { district: 'TENKASI', block: 'KEELAPAVOOR', name: 'Nagalkulam', lgdCode: '230605' },
    { district: 'TENKASI', block: 'KEELAPAVOOR', name: 'Thuthikulam', lgdCode: '230612' },
    { district: 'TENKASI', block: 'KEELAPAVOOR', name: 'Inamvellakal', lgdCode: '230598' },
    { district: 'TENKASI', block: 'KEELAPAVOOR', name: 'Idayarthavanai', lgdCode: '230597' },
    { district: 'TENKASI', block: 'KADAYANALLUR', name: 'Nainaragaram', lgdCode: '230545' },
    { district: 'TENKASI', block: 'KADAYANALLUR', name: 'Chockampatti', lgdCode: '230539' },
    { district: 'TENKASI', block: 'KADAYANALLUR', name: 'Punnaiyapuram', lgdCode: '230549' },
    { district: 'TENKASI', block: 'KADAYANALLUR', name: 'Boganallur', lgdCode: '230538' },
    { district: 'TENKASI', block: 'KADAYANALLUR', name: 'Thirikoodapuram', lgdCode: '230550' },
    { district: 'TENKASI', block: 'KADAYANALLUR', name: 'Poigai', lgdCode: '230547' },
    { district: 'TENKASI', block: 'KADAYANALLUR', name: 'Kambaneri', lgdCode: '230541' },
    { district: 'TENKASI', block: 'KADAYANALLUR', name: 'Pudukudi', lgdCode: '230548' },
    { district: 'TENKASI', block: 'KADAYANALLUR', name: 'Kasitharmam', lgdCode: '230542' },
    { district: 'TENKASI', block: 'KADAYANALLUR', name: 'Kodikuruchi', lgdCode: '230543' },
    { district: 'TENKASI', block: 'KADAYANALLUR', name: 'Kulaiyaneri', lgdCode: '230544' },
    { district: 'TENKASI', block: 'KADAYANALLUR', name: 'Urmelalagiyan', lgdCode: '230551' },
    { district: 'TENKASI', block: 'KADAYANALLUR', name: 'Neduvayal', lgdCode: '230546' },
    { district: 'TENKASI', block: 'KADAYANALLUR', name: 'Anaikulam', lgdCode: '230537' },
    { district: 'TENKASI', block: 'KADAYANALLUR', name: 'Idaikal', lgdCode: '230540' },
    { district: 'TENKASI', block: 'KADAYANALLUR', name: 'Velayuthapuram', lgdCode: '230552' },
    { district: 'TENKASI', block: 'SHENCOTTAI', name: 'Puliyarai', lgdCode: '230853' },
    { district: 'TENKASI', block: 'SHENCOTTAI', name: 'Elathur', lgdCode: '230850' },
    { district: 'TENKASI', block: 'SHENCOTTAI', name: 'Kilankadu', lgdCode: '230852' },
    { district: 'TENKASI', block: 'SHENCOTTAI', name: 'Karkudi', lgdCode: '230851' },
    { district: 'TENKASI', block: 'SHENCOTTAI', name: 'Seevanallur', lgdCode: '230854' },
    { district: 'TENKASI', block: 'SHENCOTTAI', name: 'Therkumedu', lgdCode: '230855' },
    { district: 'TENKASI', block: 'TENKASI', name: 'Kuthukalvalasai', lgdCode: '230859' },
    { district: 'TENKASI', block: 'TENKASI', name: 'Periyapillaivalasai', lgdCode: '230863' },
    { district: 'TENKASI', block: 'TENKASI', name: 'Piranoor', lgdCode: '230864' },
    { district: 'TENKASI', block: 'TENKASI', name: 'Sumaithernthapuram', lgdCode: '230866' },
    { district: 'TENKASI', block: 'TENKASI', name: 'Thenpothai', lgdCode: '230867' },
    { district: 'TENKASI', block: 'TENKASI', name: 'Vallam', lgdCode: '230869' },
    { district: 'TENKASI', block: 'TENKASI', name: 'Kannakkapillaivalasai', lgdCode: '230857' },
    { district: 'TENKASI', block: 'TENKASI', name: 'Kasimajorpuram', lgdCode: '230858' },
    { district: 'TENKASI', block: 'TENKASI', name: 'Pattapathu', lgdCode: '230862' },
    { district: 'TENKASI', block: 'TENKASI', name: 'Mathalamparai', lgdCode: '230860' },
    { district: 'TENKASI', block: 'TENKASI', name: 'Thiruchittrambalam', lgdCode: '230868' },
    { district: 'TENKASI', block: 'TENKASI', name: 'Pattakuruchi', lgdCode: '230861' },
    { district: 'TENKASI', block: 'TENKASI', name: 'Sillaraipuravoo', lgdCode: '230865' },
    { district: 'TENKASI', block: 'TENKASI', name: 'Ayiraperi', lgdCode: '230856' },
    { district: 'TENKASI', block: 'VASUDEVANALLUR', name: 'Nelkattumseval', lgdCode: '230899' },
    { district: 'TENKASI', block: 'VASUDEVANALLUR', name: 'Thenmalai', lgdCode: '230906' },
    { district: 'TENKASI', block: 'VASUDEVANALLUR', name: 'Devipattanam', lgdCode: '230889' },
    { district: 'TENKASI', block: 'VASUDEVANALLUR', name: 'Ramanathapuram', lgdCode: '230900' },
    { district: 'TENKASI', block: 'VASUDEVANALLUR', name: 'Thirumalapuram', lgdCode: '230907' },
    { district: 'TENKASI', block: 'VASUDEVANALLUR', name: 'Ramasamiyapuram', lgdCode: '230901' },
    { district: 'TENKASI', block: 'VASUDEVANALLUR', name: 'Subramaniyapuram', lgdCode: '230904' },
    { district: 'TENKASI', block: 'VASUDEVANALLUR', name: 'Duraisamiyapuram', lgdCode: '230891' },
    { district: 'TENKASI', block: 'VASUDEVANALLUR', name: 'Viswanathaperi', lgdCode: '230909' },
    { district: 'TENKASI', block: 'VASUDEVANALLUR', name: 'Thalaivankottai', lgdCode: '230905' },
    { district: 'TENKASI', block: 'VASUDEVANALLUR', name: 'Nagaram', lgdCode: '230897' },
    { district: 'TENKASI', block: 'VASUDEVANALLUR', name: 'Naranapuram', lgdCode: '230898' },
    { district: 'TENKASI', block: 'VASUDEVANALLUR', name: 'Gudalur', lgdCode: '230892' },
    { district: 'TENKASI', block: 'VASUDEVANALLUR', name: 'Malaiyadikuruchi', lgdCode: '230895' },
    { district: 'TENKASI', block: 'VASUDEVANALLUR', name: 'Inamkovilpatti', lgdCode: '230893' },
    { district: 'TENKASI', block: 'VASUDEVANALLUR', name: 'Sangupuram', lgdCode: '230903' },
    { district: 'TENKASI', block: 'VASUDEVANALLUR', name: 'Kottaiyoor', lgdCode: '230894' },
    { district: 'TENKASI', block: 'VASUDEVANALLUR', name: 'Mullikkulam', lgdCode: '230896' },
    { district: 'TENKASI', block: 'VASUDEVANALLUR', name: 'Ullar Thalavaipuram', lgdCode: '230908' },
    { district: 'TENKASI', block: 'VASUDEVANALLUR', name: 'Ariyoor', lgdCode: '230888' },
    { district: 'TENKASI', block: 'VASUDEVANALLUR', name: 'Dharugapuram', lgdCode: '230890' },
    { district: 'TENKASI', block: 'VASUDEVANALLUR', name: 'Sanganaperi', lgdCode: '230902' }
];

```
