
import type { Panchayat } from './types';

export const THE_NILGIRIS_PANCHAYATS: Panchayat[] = [
    { district: 'THE NILGIRIS', block: 'UDHAGAI', name: 'Doddabetta', lgdCode: '228983' },
    { district: 'THE NILGIRIS', block: 'UDHAGAI', name: 'Ebbanad', lgdCode: '228984' },
    { district: 'THE NILGIRIS', block: 'UDHAGAI', name: 'Hullathy', lgdCode: '228985' },
    { district: 'THE NILGIRIS', block: 'UDHAGAI', name: 'Kadanad', lgdCode: '228987' },
    { district: 'THE NILGIRIS', block: 'UDHAGAI', name: 'Kagguchi', lgdCode: '228988' },
    { district: 'THE NILGIRIS', block: 'UDHAGAI', name: 'Kookal', lgdCode: '228989' },
    { district: 'THE NILGIRIS', block: 'UDHAGAI', name: 'Mel Kundha', lgdCode: '228990' },
    { district: 'THE NILGIRIS', block: 'UDHAGAI', name: 'Nanjanad', lgdCode: '228992' },
    { district: 'THE NILGIRIS', block: 'UDHAGAI', name: 'Thummanatty', lgdCode: '228993' },
    { district: 'THE NILGIRIS', block: 'UDHAGAI', name: 'Thuneri', lgdCode: '228994' },
    { district: 'THE NILGIRIS', block: 'UDHAGAI', name: 'Balacola', lgdCode: '228982' },
    { district: 'THE NILGIRIS', block: 'UDHAGAI', name: 'Mulligoor', lgdCode: '228991' },
    { district: 'THE NILGIRIS', block: 'UDHAGAI', name: 'Ithalar', lgdCode: '228986' },
    { district: 'THE NILGIRIS', block: 'COONOOR', name: 'Bandishola', lgdCode: '228960' },
    { district: 'THE NILGIRIS', block: 'COONOOR', name: 'Beratty', lgdCode: '228961' },
    { district: 'THE NILGIRIS', block: 'COONOOR', name: 'Burliar', lgdCode: '228962' },
    { district: 'THE NILGIRIS', block: 'COONOOR', name: 'Hubbathalai', lgdCode: '228963' },
    { district: 'THE NILGIRIS', block: 'COONOOR', name: 'Yedappalli', lgdCode: '228965' },
    { district: 'THE NILGIRIS', block: 'COONOOR', name: 'Melur', lgdCode: '228964' },
    { district: 'THE NILGIRIS', block: 'KOTAGIRI', name: 'Aracode', lgdCode: '228971' },
    { district: 'THE NILGIRIS', block: 'KOTAGIRI', name: 'Denad', lgdCode: '228972' },
    { district: 'THE NILGIRIS', block: 'KOTAGIRI', name: 'Kadinamala', lgdCode: '228974' },
    { district: 'THE NILGIRIS', block: 'KOTAGIRI', name: 'Kengarai', lgdCode: '228975' },
    { district: 'THE NILGIRIS', block: 'KOTAGIRI', name: 'Kodanad', lgdCode: '228976' },
    { district: 'THE NILGIRIS', block: 'KOTAGIRI', name: 'Kunjappanai', lgdCode: '228978' },
    { district: 'THE NILGIRIS', block: 'KOTAGIRI', name: 'Naduhatty', lgdCode: '228979' },
    { district: 'THE NILGIRIS', block: 'KOTAGIRI', name: 'Nedugula', lgdCode: '228980' },
    { district: 'THE NILGIRIS', block: 'KOTAGIRI', name: 'Thengumarahada', lgdCode: '228981' },
    { district: 'THE NILGIRIS', block: 'KOTAGIRI', name: 'Jackanarai', lgdCode: '228973' },
    { district: 'THE NILGIRIS', block: 'KOTAGIRI', name: 'Konavakkarai', lgdCode: '228977' },
    { district: 'THE NILGIRIS', block: 'GUDALUR', name: 'Mudumalai', lgdCode: '228968' },
    { district: 'THE NILGIRIS', block: 'GUDALUR', name: 'Masinagudi', lgdCode: '228967' },
    { district: 'THE NILGIRIS', block: 'GUDALUR', name: 'Sreemadurai', lgdCode: '228970' },
    { district: 'THE NILGIRIS', block: 'GUDALUR', name: 'Cherangodu', lgdCode: '228966' },
    { district: 'THE NILGIRIS', block: 'GUDALUR', name: 'Nellakotta', lgdCode: '228969' }
];
