import type { Panchayat } from './types';

export const THENI_PANCHAYATS: Panchayat[] = [
    { district: 'THENI', block: 'ANDIPATTI', name: 'Ammachiyapuram', lgdCode: '228995' },
    { district: 'THENI', block: 'ANDIPATTI', name: 'Anuppapatti', lgdCode: '228996' },
    { district: 'THENI', block: 'ANDIPATTI', name: 'Bodithasanpatti', lgdCode: '228997' },
    { district: 'THENI', block: 'ANDIPATTI', name: 'Ethakoil', lgdCode: '228998' },
    { district: 'THENI', block: 'ANDIPATTI', name: 'Kathirnarasingapuram', lgdCode: '229001' },
    { district: 'THENI', block: 'ANDIPATTI', name: 'Kanniappapillaipatti', lgdCode: '229000' },
    { district: 'THENI', block: 'ANDIPATTI', name: 'Kothaloothu', lgdCode: '229002' },
    { district: 'THENI', block: 'ANDIPATTI', name: 'Kothapatti', lgdCode: '229003' },
    { district: 'THENI', block: 'ANDIPATTI', name: 'Kovilpatti', lgdCode: '229004' },
    { district: 'THENI', block: 'ANDIPATTI', name: 'Kunnur', lgdCode: '229005' },
    { district: 'THENI', block: 'ANDIPATTI', name: 'Marikundu', lgdCode: '229006' },
    { district: 'THENI', block: 'ANDIPATTI', name: 'Mottanuthu', lgdCode: '229007' },
    { district: 'THENI', block: 'ANDIPATTI', name: 'Okkaraipatti', lgdCode: '229008' },
    { district: 'THENI', block: 'ANDIPATTI', name: 'Palacombai', lgdCode: '229009' },
    { district: 'THENI', block: 'ANDIPATTI', name: 'Palayakottai', lgdCode: '229010' },
    { district: 'THENI', block: 'ANDIPATTI', name: 'Pitchampatti', lgdCode: '229011' },
    { district: 'THENI', block: 'ANDIPATTI', name: 'Pullimancombai', lgdCode: '229012' },
    { district: 'THENI', block: 'ANDIPATTI', name: 'Rajagopalanpatti', lgdCode: '229014' },
    { district: 'THENI', block: 'ANDIPATTI', name: 'Rajakkalpatti', lgdCode: '229015' },
    { district: 'THENI', block: 'ANDIPATTI', name: 'Rajadhani', lgdCode: '229013' },
    { district: 'THENI', block: 'ANDIPATTI', name: 'Ramakrishnapuram', lgdCode: '229016' },
    { district: 'THENI', block: 'ANDIPATTI', name: 'Rengasamudram', lgdCode: '229017' },
    { district: 'THENI', block: 'ANDIPATTI', name: 'Shunmugasundarapuram', lgdCode: '229018' },
    { district: 'THENI', block: 'ANDIPATTI', name: 'Sitharpatti', lgdCode: '229019' },
    { district: 'THENI', block: 'ANDIPATTI', name: 'T Subbulapuram', lgdCode: '229020' },
    { district: 'THENI', block: 'ANDIPATTI', name: 'Thekkampatti', lgdCode: '229021' },
    { district: 'THENI', block: 'ANDIPATTI', name: 'Theppampatti', lgdCode: '229022' },
    { district: 'THENI', block: 'ANDIPATTI', name: 'Thimmarasanaickanur', lgdCode: '229023' },
    { district: 'THENI', block: 'ANDIPATTI', name: 'Thirumalapuram', lgdCode: '229024' },
    { district: 'THENI', block: 'ANDIPATTI', name: 'G Usilampatti', lgdCode: '228999' },
    { district: 'THENI', block: 'K MYLADUMPARAI', name: 'Athankaraipatti', lgdCode: '229054' },
    { district: 'THENI', block: 'K MYLADUMPARAI', name: 'Duraichamypuram', lgdCode: '229055' },
    { district: 'THENI', block: 'K MYLADUMPARAI', name: 'Ettapparajapuram', lgdCode: '229056' },
    { district: 'THENI', block: 'K MYLADUMPARAI', name: 'Gandamanur', lgdCode: '229057' },
    { district: 'THENI', block: 'K MYLADUMPARAI', name: 'Kadamalaikundu', lgdCode: '229058' },
    { district: 'THENI', block: 'K MYLADUMPARAI', name: 'Kumananthozhu', lgdCode: '229059' },
    { district: 'THENI', block: 'K MYLADUMPARAI', name: 'Manthisunai-Moolakadai', lgdCode: '229060' },
    { district: 'THENI', block: 'K MYLADUMPARAI', name: 'Megamalai', lgdCode: '229061' },
    { district: 'THENI', block: 'K MYLADUMPARAI', name: 'Muthalamparai', lgdCode: '229063' },
    { district: 'THENI', block: 'K MYLADUMPARAI', name: 'Myladumparai', lgdCode: '229064' },
    { district: 'THENI', block: 'K MYLADUMPARAI', name: 'Murukkodai', lgdCode: '229062' },
    { district: 'THENI', block: 'K MYLADUMPARAI', name: 'Nariyuthu', lgdCode: '229065' },
    { district: 'THENI', block: 'K MYLADUMPARAI', name: 'Paaloothu', lgdCode: '229066' },
    { district: 'THENI', block: 'K MYLADUMPARAI', name: 'Ponnanpadugai', lgdCode: '229067' },
    { district: 'THENI', block: 'K MYLADUMPARAI', name: 'Singarajapuram', lgdCode: '229068' },
    { district: 'THENI', block: 'K MYLADUMPARAI', name: 'Thummakundu', lgdCode: '229070' },
    { district: 'THENI', block: 'K MYLADUMPARAI', name: 'Thangammalpuram', lgdCode: '229069' },
    { district: 'THENI', block: 'K MYLADUMPARAI', name: 'Varusanadu', lgdCode: '229071' },
    { district: 'THENI', block: 'PERIYAKULAM', name: 'Alagarnaickanpatti', lgdCode: '229078' },
    { district: 'THENI', block: 'PERIYAKULAM', name: 'Bomminaickanpatti', lgdCode: '229079' },
    { district: 'THENI', block: 'PERIYAKULAM', name: 'Endapuli', lgdCode: '229081' },
    { district: 'THENI', block: 'PERIYAKULAM', name: 'Erumalainaickanpatti', lgdCode: '229082' },
    { district: 'THENI', block: 'PERIYAKULAM', name: 'Gullapuram', lgdCode: '229084' },
    { district: 'THENI', block: 'PERIYAKULAM', name: 'Jallipatti', lgdCode: '229085' },
    { district: 'THENI', block: 'PERIYAKULAM', name: 'Jeyamangalam', lgdCode: '229086' },
    { district: 'THENI', block: 'PERIYAKULAM', name: 'G.Kallupatti', lgdCode: '229083' },
    { district: 'THENI', block: 'PERIYAKULAM', name: 'Keelavadakarai', lgdCode: '229087' },
    { district: 'THENI', block: 'PERIYAKULAM', name: 'Lakshmipuram', lgdCode: '229088' },
    { district: 'THENI', block: 'PERIYAKULAM', name: 'Melmangalam', lgdCode: '229089' },
    { district: 'THENI', block: 'PERIYAKULAM', name: 'Muthalakkampatti', lgdCode: '229090' },
    { district: 'THENI', block: 'PERIYAKULAM', name: 'Saruthupatti', lgdCode: '229091' },
    { district: 'THENI', block: 'PERIYAKULAM', name: 'Silvarpatti', lgdCode: '229092' },
    { district: 'THENI', block: 'PERIYAKULAM', name: 'Vadapudupatti', lgdCode: '229093' },
    { district: 'THENI', block: 'PERIYAKULAM', name: 'A Vadipatti', lgdCode: '229077' },
    { district: 'THENI', block: 'PERIYAKULAM', name: 'D.Vadipatti', lgdCode: '229080' },
    { district: 'THENI', block: 'THENI', name: 'Ambasamudram', lgdCode: '229094' },
    { district: 'THENI', block: 'THENI', name: 'Aranmanaiputhur', lgdCode: '229095' },
    { district: 'THENI', block: 'THENI', name: 'Dharmapuri', lgdCode: '229096' },
    { district: 'THENI', block: 'THENI', name: 'Govindanagaram', lgdCode: '229097' },
    { district: 'THENI', block: 'THENI', name: 'Jangalpatti', lgdCode: '229098' },
    { district: 'THENI', block: 'THENI', name: 'Kattunaickenpatti', lgdCode: '229099' },
    { district: 'THENI', block: 'THENI', name: 'Koduvilarpatti', lgdCode: '229100' },
    { district: 'THENI', block: 'THENI', name: 'Kottur', lgdCode: '229101' },
    { district: 'THENI', block: 'THENI', name: 'Kuppinaickenpatti', lgdCode: '229102' },
    { district: 'THENI', block: 'THENI', name: 'Nagalapuram', lgdCode: '229103' },
    { district: 'THENI', block: 'THENI', name: 'Poomalaikundu', lgdCode: '229104' },
    { district: 'THENI', block: 'THENI', name: 'Seelayampatti', lgdCode: '229105' },
    { district: 'THENI', block: 'THENI', name: 'Srirengapuram', lgdCode: '229106' },
    { district: 'THENI', block: 'THENI', name: 'Thadicheri', lgdCode: '229107' },
    { district: 'THENI', block: 'THENI', name: 'Thappukundu', lgdCode: '229108' },
    { district: 'THENI', block: 'THENI', name: 'Upparpatti', lgdCode: '229110' },
    { district: 'THENI', block: 'THENI', name: 'Unjampatti', lgdCode: '229109' },
    { district: 'THENI', block: 'THENI', name: 'Venkatachalapuram', lgdCode: '229111' },
    { district: 'THENI', block: 'BODINAICKANUR', name: 'Agamalai', lgdCode: '229025' },
    { district: 'THENI', block: 'BODINAICKANUR', name: 'Ammapatti', lgdCode: '229026' },
    { district: 'THENI', block: 'BODINAICKANUR', name: 'Anaikaraipatti', lgdCode: '229027' },
    { district: 'THENI', block: 'BODINAICKANUR', name: 'Dombuchery', lgdCode: '229028' },
    { district: 'THENI', block: 'BODINAICKANUR', name: 'Kamarajapuram', lgdCode: '229029' },
    { district: 'THENI', block: 'BODINAICKANUR', name: 'Kodangipatti', lgdCode: '229030' },
    { district: 'THENI', block: 'BODINAICKANUR', name: 'Kottakudi', lgdCode: '229032' },
    { district: 'THENI', block: 'BODINAICKANUR', name: 'Koolayanur', lgdCode: '229031' },
    { district: 'THENI', block: 'BODINAICKANUR', name: 'Maniyampatti', lgdCode: '229033' },
    { district: 'THENI', block: 'BODINAICKANUR', name: 'Manjinaickenpatti', lgdCode: '229034' },
    { district: 'THENI', block: 'BODINAICKANUR', name: 'Nagalapuram', lgdCode: '229035' },
    { district: 'THENI', block: 'BODINAICKANUR', name: 'Rasingapuram', lgdCode: '229036' },
    { district: 'THENI', block: 'BODINAICKANUR', name: 'Silamalai', lgdCode: '229037' },
    { district: 'THENI', block: 'BODINAICKANUR', name: 'Sillamarathupatti', lgdCode: '229038' },
    { district: 'THENI', block: 'BODINAICKANUR', name: 'Uppukottai', lgdCode: '229039' },
    { district: 'THENI', block: 'CHINNAMANUR', name: 'Alagapuri', lgdCode: '229040' },
    { district: 'THENI', block: 'CHINNAMANUR', name: 'Ayyampatti', lgdCode: '229041' },
    { district: 'THENI', block: 'CHINNAMANUR', name: 'Chinnaovulapuram', lgdCode: '229042' },
    { district: 'THENI', block: 'CHINNAMANUR', name: 'Eranampatti', lgdCode: '229043' },
    { district: 'THENI', block: 'CHINNAMANUR', name: 'Erasakkanaickanur', lgdCode: '229044' },
    { district: 'THENI', block: 'CHINNAMANUR', name: 'Kamatchipuram', lgdCode: '229045' },
    { district: 'THENI', block: 'CHINNAMANUR', name: 'Kanniservaipatti', lgdCode: '229046' },
    { district: 'THENI', block: 'CHINNAMANUR', name: 'Muthulapuram', lgdCode: '229047' },
    { district: 'THENI', block: 'CHINNAMANUR', name: 'Pottipuram', lgdCode: '229049' },
    { district: 'THENI', block: 'CHINNAMANUR', name: 'Poolananthapuram', lgdCode: '229048' },
    { district: 'THENI', block: 'CHINNAMANUR', name: 'Pulikuthi', lgdCode: '229050' },
    { district: 'THENI', block: 'CHINNAMANUR', name: 'Sankarapuram', lgdCode: '229051' },
    { district: 'THENI', block: 'CHINNAMANUR', name: 'Seepalakottai', lgdCode: '229052' },
    { district: 'THENI', block: 'CHINNAMANUR', name: 'Veppampatti', lgdCode: '229053' },
    { district: 'THENI', block: 'UTHAMAPALAYAM', name: 'Anaimalaiyanpatti', lgdCode: '229112' },
    { district: 'THENI', block: 'UTHAMAPALAYAM', name: 'Gokilapuram', lgdCode: '229113' },
    { district: 'THENI', block: 'UTHAMAPALAYAM', name: 'Lakshminaickenpatti', lgdCode: '229114' },
    { district: 'THENI', block: 'UTHAMAPALAYAM', name: 'Melasindalaicherri', lgdCode: '229115' },
    { district: 'THENI', block: 'UTHAMAPALAYAM', name: 'Nagayagoundanpatti', lgdCode: '229116' },
    { district: 'THENI', block: 'UTHAMAPALAYAM', name: 'Pallavarayanpatti', lgdCode: '229117' },
    { district: 'THENI', block: 'UTHAMAPALAYAM', name: 'Ramasamynaickanpatty', lgdCode: '229118' },
    { district: 'THENI', block: 'UTHAMAPALAYAM', name: 'Royappanpatti', lgdCode: '229119' },
    { district: 'THENI', block: 'UTHAMAPALAYAM', name: 'T.Meenakshipuram', lgdCode: '229120' },
    { district: 'THENI', block: 'UTHAMAPALAYAM', name: 'T Renganathapuram', lgdCode: '229121' },
    { district: 'THENI', block: 'UTHAMAPALAYAM', name: 'T.Sindalachery', lgdCode: '229122' },
    { district: 'THENI', block: 'UTHAMAPALAYAM', name: 'Thamminaickanpatty', lgdCode: '229123' },
    { district: 'THENI', block: 'UTHAMAPALAYAM', name: 'U.Ammapatti', lgdCode: '229124' },
    { district: 'THENI', block: 'CUMBUM', name: 'Angoorpalayam', lgdCode: '229072' },
    { district: 'THENI', block: 'CUMBUM', name: 'Karunakkamuthanpatti', lgdCode: '229073' },
    { district: 'THENI', block: 'CUMBUM', name: 'Kullappagoundanpatti', lgdCode: '229074' },
    { district: 'THENI', block: 'CUMBUM', name: 'Narayanathevanpatti', lgdCode: '229075' },
    { district: 'THENI', block: 'CUMBUM', name: 'Surulipatti', lgdCode: '229076' },
];
