import type { Panchayat } from './types';

export const THOOTHUKKUDI_PANCHAYATS: Panchayat[] = [
    { district: 'THOOTHUKKUDI', block: 'THOOTHUKKUDI', name: 'Alligulam', lgdCode: '232074' },
    { district: 'THOOTHUKKUDI', block: 'THOOTHUKKUDI', name: 'Ayyanadaippu', lgdCode: '232075' },
    { district: 'THOOTHUKKUDI', block: 'THOOTHUKKUDI', name: 'Dalavaipuram', lgdCode: '232076' },
    { district: 'THOOTHUKKUDI', block: 'THOOTHUKKUDI', name: 'Kattalankulam', lgdCode: '232077' },
    { district: 'THOOTHUKKUDI', block: 'THOOTHUKKUDI', name: 'Keelathattaparai', lgdCode: '232078' },
    { district: 'THOOTHUKKUDI', block: 'THOOTHUKKUDI', name: 'Kootudankadu', lgdCode: '232079' },
    { district: 'THOOTHUKKUDI', block: 'THOOTHUKKUDI', name: 'Korampallam', lgdCode: '232080' },
    { district: 'THOOTHUKKUDI', block: 'THOOTHUKKUDI', name: 'Kulayankarisal', lgdCode: '232081' },
    { district: 'THOOTHUKKUDI', block: 'THOOTHUKKUDI', name: 'Kumaragiri', lgdCode: '232082' },
    { district: 'THOOTHUKKUDI', block: 'THOOTHUKKUDI', name: 'Mappillaiurani', lgdCode: '232083' },
    { district: 'THOOTHUKKUDI', block: 'THOOTHUKKUDI', name: 'Maravanmadam', lgdCode: '232084' },
    { district: 'THOOTHUKKUDI', block: 'THOOTHUKKUDI', name: 'Melathattaparai', lgdCode: '232085' },
    { district: 'THOOTHUKKUDI', block: 'THOOTHUKKUDI', name: 'Mudivaithanendal', lgdCode: '232086' },
    { district: 'THOOTHUKKUDI', block: 'THOOTHUKKUDI', name: 'Mullakadu', lgdCode: '232087' },
    { district: 'THOOTHUKKUDI', block: 'THOOTHUKKUDI', name: 'Servaikaranmadam', lgdCode: '232088' },
    { district: 'THOOTHUKKUDI', block: 'THOOTHUKKUDI', name: 'Therkkusilukkanpatti', lgdCode: '232089' },
    { district: 'THOOTHUKKUDI', block: 'THOOTHUKKUDI', name: 'Thimmarajapuram', lgdCode: '232090' },
    { district: 'THOOTHUKKUDI', block: 'THOOTHUKKUDI', name: 'Umarikottai', lgdCode: '232091' },
    { district: 'THOOTHUKKUDI', block: 'THOOTHUKKUDI', name: 'Vadakkusilukkanpatti', lgdCode: '232092' },
    { district: 'THOOTHUKKUDI', block: 'THOOTHUKKUDI', name: 'Varthagareddipatti', lgdCode: '232093' },
    { district: 'THOOTHUKKUDI', block: 'KARUNGULAM', name: 'ALANDA', lgdCode: '231800' },
    { district: 'THOOTHUKKUDI', block: 'KARUNGULAM', name: 'ALIGUDI', lgdCode: '231801' },
    { district: 'THOOTHUKKUDI', block: 'KARUNGULAM', name: 'ALWARKARKULM', lgdCode: '231802' },
    { district: 'THOOTHUKKUDI', block: 'KARUNGULAM', name: 'ARAMPANNAI', lgdCode: '231803' },
    { district: 'THOOTHUKKUDI', block: 'KARUNGULAM', name: 'ELLAINAICKKENPATTI', lgdCode: '231804' },
    { district: 'THOOTHUKKUDI', block: 'KARUNGULAM', name: 'KALIAVOOR', lgdCode: '231805' },
    { district: 'THOOTHUKKUDI', block: 'KARUNGULAM', name: 'KALVAI', lgdCode: '231806' },
    { district: 'THOOTHUKKUDI', block: 'KARUNGULAM', name: 'KARUNGULAM', lgdCode: '231807' },
    { district: 'THOOTHUKKUDI', block: 'KARUNGULAM', name: 'KEELA PUTHANERI', lgdCode: '231809' },
    { district: 'THOOTHUKKUDI', block: 'KARUNGULAM', name: 'KEELA VALLANADU', lgdCode: '231808' },
    { district: 'THOOTHUKKUDI', block: 'KARUNGULAM', name: 'KONGARAYAKURICHI', lgdCode: '231810' },
    { district: 'THOOTHUKKUDI', block: 'KARUNGULAM', name: 'MANAKKARAI', lgdCode: '231811' },
    { district: 'THOOTHUKKUDI', block: 'KARUNGULAM', name: 'MUTHALAMKURICHI', lgdCode: '231814' },
    { district: 'THOOTHUKKUDI', block: 'KARUNGULAM', name: 'MURAPPANADU KOVILPATHU', lgdCode: '231812' },
    { district: 'THOOTHUKKUDI', block: 'KARUNGULAM', name: 'MURAPPANADU PUTHUGRAMAM', lgdCode: '231813' },
    { district: 'THOOTHUKKUDI', block: 'KARUNGULAM', name: 'NANAL KADU', lgdCode: '231815' },
    { district: 'THOOTHUKKUDI', block: 'KARUNGULAM', name: 'POOVANI', lgdCode: '231816' },
    { district: 'THOOTHUKKUDI', block: 'KARUNGULAM', name: 'RAMANUJAMPUDUR', lgdCode: '231817' },
    { district: 'THOOTHUKKUDI', block: 'KARUNGULAM', name: 'SEYTHUNGANALLUR', lgdCode: '231820' },
    { district: 'THOOTHUKKUDI', block: 'KARUNGULAM', name: 'SINGATHAKURICHI', lgdCode: '231821' },
    { district: 'THOOTHUKKUDI', block: 'KARUNGULAM', name: 'SEKKARAKUDI', lgdCode: '231818' },
    { district: 'THOOTHUKKUDI', block: 'KARUNGULAM', name: 'SERAKULAM', lgdCode: '231819' },
    { district: 'THOOTHUKKUDI', block: 'KARUNGULAM', name: 'THATHANKULAM', lgdCode: '231822' },
    { district: 'THOOTHUKKUDI', block: 'KARUNGULAM', name: 'VADAKKU KARASERI', lgdCode: '231825' },
    { district: 'THOOTHUKKUDI', block: 'KARUNGULAM', name: 'VADA VALLANADU', lgdCode: '231824' },
    { district: 'THOOTHUKKUDI', block: 'KARUNGULAM', name: 'VALLAKULAM', lgdCode: '231826' },
    { district: 'THOOTHUKKUDI', block: 'KARUNGULAM', name: 'VALLANADU', lgdCode: '231827' },
    { district: 'THOOTHUKKUDI', block: 'KARUNGULAM', name: 'VASAVAPPAPURAM', lgdCode: '231828' },
    { district: 'THOOTHUKKUDI', block: 'KARUNGULAM', name: 'VITTILAPURAM', lgdCode: '231829' },
    { district: 'THOOTHUKKUDI', block: 'KARUNGULAM', name: 'VITTILAPURAM KOVILPATHU', lgdCode: '231830' },
    { district: 'THOOTHUKKUDI', block: 'KARUNGULAM', name: 'THERKKU KARASERI', lgdCode: '231823' },
    { district: 'THOOTHUKKUDI', block: 'SRIVAIKUNDAM', name: 'Agaram', lgdCode: '232043' },
    { district: 'THOOTHUKKUDI', block: 'SRIVAIKUNDAM', name: 'Aniyaparanallur', lgdCode: '232044' },
    { district: 'THOOTHUKKUDI', block: 'SRIVAIKUNDAM', name: 'Arumugamangalam', lgdCode: '232045' },
    { district: 'THOOTHUKKUDI', block: 'SRIVAIKUNDAM', name: 'Idayar Kadu', lgdCode: '232046' },
    { district: 'THOOTHUKKUDI', block: 'SRIVAIKUNDAM', name: 'Kilpidagai Appankovil', lgdCode: '232048' },
    { district: 'THOOTHUKKUDI', block: 'SRIVAIKUNDAM', name: 'Kilpidagai Kaspa', lgdCode: '232049' },
    { district: 'THOOTHUKKUDI', block: 'SRIVAIKUNDAM', name: 'Kilpidagai Varatharajapuram', lgdCode: '232047' },
    { district: 'THOOTHUKKUDI', block: 'SRIVAIKUNDAM', name: 'Korkai', lgdCode: '232050' },
    { district: 'THOOTHUKKUDI', block: 'SRIVAIKUNDAM', name: 'Kottarakurichi', lgdCode: '232051' },
    { district: 'THOOTHUKKUDI', block: 'SRIVAIKUNDAM', name: 'Kovankadu', lgdCode: '232052' },
    { district: 'THOOTHUKKUDI', block: 'SRIVAIKUNDAM', name: 'Mangalakurichi', lgdCode: '232053' },
    { district: 'THOOTHUKKUDI', block: 'SRIVAIKUNDAM', name: 'Manjalneerkayal', lgdCode: '232054' },
    { district: 'THOOTHUKKUDI', block: 'SRIVAIKUNDAM', name: 'Maramangalam', lgdCode: '232055' },
    { district: 'THOOTHUKKUDI', block: 'SRIVAIKUNDAM', name: 'Mukkani', lgdCode: '232056' },
    { district: 'THOOTHUKKUDI', block: 'SRIVAIKUNDAM', name: 'Nattathi', lgdCode: '232057' },
    { district: 'THOOTHUKKUDI', block: 'SRIVAIKUNDAM', name: 'Padmanabamangalam', lgdCode: '232058' },
    { district: 'THOOTHUKKUDI', block: 'SRIVAIKUNDAM', name: 'Palayakayal', lgdCode: '232059' },
    { district: 'THOOTHUKKUDI', block: 'SRIVAIKUNDAM', name: 'Parakiramapandi', lgdCode: '232060' },
    { district: 'THOOTHUKKUDI', block: 'SRIVAIKUNDAM', name: 'Peroor', lgdCode: '232061' },
    { district: 'THOOTHUKKUDI', block: 'SRIVAIKUNDAM', name: 'Siruthondanallur', lgdCode: '232066' },
    { district: 'THOOTHUKKUDI', block: 'SRIVAIKUNDAM', name: 'Sivagalai', lgdCode: '232062' },
    { district: 'THOOTHUKKUDI', block: 'SRIVAIKUNDAM', name: 'Soolaivaikal', lgdCode: '232063' },
    { district: 'THOOTHUKKUDI', block: 'SRIVAIKUNDAM', name: 'Sriparangusanallur', lgdCode: '232065' },
    { district: 'THOOTHUKKUDI', block: 'SRIVAIKUNDAM', name: 'Thirupannichettikulam', lgdCode: '232067' },
    { district: 'THOOTHUKKUDI', block: 'SRIVAIKUNDAM', name: 'Thirupuliyangudi', lgdCode: '232068' },
    { district: 'THOOTHUKKUDI', block: 'SRIVAIKUNDAM', name: 'Tholappan Pannai', lgdCode: '232069' },
    { district: 'THOOTHUKKUDI', block: 'SRIVAIKUNDAM', name: 'Umarikadu', lgdCode: '232070' },
    { district: 'THOOTHUKKUDI', block: 'SRIVAIKUNDAM', name: 'Valavallan', lgdCode: '232072' },
    { district: 'THOOTHUKKUDI', block: 'SRIVAIKUNDAM', name: 'Velloor', lgdCode: '232073' },
    { district: 'THOOTHUKKUDI', block: 'SRIVAIKUNDAM', name: 'V. Athichanallur', lgdCode: '232071' },
    { district: 'THOOTHUKKUDI', block: 'SRIVAIKUNDAM', name: 'Srimoolakarai', lgdCode: '232064' },
    { district: 'THOOTHUKKUDI', block: 'ALWARTHIRUNAGARI', name: 'Alagappapuram', lgdCode: '231770' },
    { district: 'THOOTHUKKUDI', block: 'ALWARTHIRUNAGARI', name: 'Alagiyamanvalapuram', lgdCode: '231771' },
    { district: 'THOOTHUKKUDI', block: 'ALWARTHIRUNAGARI', name: 'Angamangalam', lgdCode: '231772' },
    { district: 'THOOTHUKKUDI', block: 'ALWARTHIRUNAGARI', name: 'Athinathapuram', lgdCode: '231773' },
    { district: 'THOOTHUKKUDI', block: 'ALWARTHIRUNAGARI', name: 'Cambellabad', lgdCode: '231774' },
    { district: 'THOOTHUKKUDI', block: 'ALWARTHIRUNAGARI', name: 'Kadayanodai', lgdCode: '231775' },
    { district: 'THOOTHUKKUDI', block: 'ALWARTHIRUNAGARI', name: 'Karungadal', lgdCode: '231776' },
    { district: 'THOOTHUKKUDI', block: 'ALWARTHIRUNAGARI', name: 'Karuvelambadu', lgdCode: '231777' },
    { district: 'THOOTHUKKUDI', block: 'ALWARTHIRUNAGARI', name: 'Katchanavilai', lgdCode: '231778' },
    { district: 'THOOTHUKKUDI', block: 'ALWARTHIRUNAGARI', name: 'Kattarimangalam', lgdCode: '231779' },
    { district: 'THOOTHUKKUDI', block: 'ALWARTHIRUNAGARI', name: 'Kurangani', lgdCode: '231780' },
    { district: 'THOOTHUKKUDI', block: 'ALWARTHIRUNAGARI', name: 'Kurippankulam', lgdCode: '231781' },
    { district: 'THOOTHUKKUDI', block: 'ALWARTHIRUNAGARI', name: 'Kurukattoor', lgdCode: '231782' },
    { district: 'THOOTHUKKUDI', block: 'ALWARTHIRUNAGARI', name: 'Malavarayanatham', lgdCode: '231783' },
    { district: 'THOOTHUKKUDI', block: 'ALWARTHIRUNAGARI', name: 'Meerankulam', lgdCode: '231784' },
    { district: 'THOOTHUKKUDI', block: 'ALWARTHIRUNAGARI', name: 'Melathoor', lgdCode: '231785' },
    { district: 'THOOTHUKKUDI', block: 'ALWARTHIRUNAGARI', name: 'Mookuperi', lgdCode: '231786' },
    { district: 'THOOTHUKKUDI', block: 'ALWARTHIRUNAGARI', name: 'Nalumavadi', lgdCode: '231787' },
    { district: 'THOOTHUKKUDI', block: 'ALWARTHIRUNAGARI', name: 'Punnakayal', lgdCode: '231788' },
    { district: 'THOOTHUKKUDI', block: 'ALWARTHIRUNAGARI', name: 'Puraiyoor', lgdCode: '231789' },
    { district: 'THOOTHUKKUDI', block: 'ALWARTHIRUNAGARI', name: 'Rajapathy', lgdCode: '231790' },
    { district: 'THOOTHUKKUDI', block: 'ALWARTHIRUNAGARI', name: 'Sernthamangalam', lgdCode: '231791' },
    { district: 'THOOTHUKKUDI', block: 'ALWARTHIRUNAGARI', name: 'Sethukkuvaithan', lgdCode: '231792' },
    { district: 'THOOTHUKKUDI', block: 'ALWARTHIRUNAGARI', name: 'Srivenkatesapuram', lgdCode: '231793' },
    { district: 'THOOTHUKKUDI', block: 'ALWARTHIRUNAGARI', name: 'Suganthalai', lgdCode: '231794' },
    { district: 'THOOTHUKKUDI', block: 'ALWARTHIRUNAGARI', name: 'Themankulam', lgdCode: '231795' },
    { district: 'THOOTHUKKUDI', block: 'ALWARTHIRUNAGARI', name: 'Thirukkaloor', lgdCode: '231796' },
    { district: 'THOOTHUKKUDI', block: 'ALWARTHIRUNAGARI', name: 'Udaiyarkulam', lgdCode: '231797' },
    { district: 'THOOTHUKKUDI', block: 'ALWARTHIRUNAGARI', name: 'Vellamadam', lgdCode: '231799' },
    { district: 'THOOTHUKKUDI', block: 'ALWARTHIRUNAGARI', name: 'Varandiavel', lgdCode: '231798' },
    { district: 'THOOTHUKKUDI', block: 'TIRUCHENDUR', name: 'AMMANPURAM', lgdCode: '232094' },
    { district: 'THOOTHUKKUDI', block: 'TIRUCHENDUR', name: 'KAYAMOZHI', lgdCode: '232095' },
    { district: 'THOOTHUKKUDI', block: 'TIRUCHENDUR', name: 'MOOLAKARAI', lgdCode: '232098' },
    { district: 'THOOTHUKKUDI', block: 'TIRUCHENDUR', name: 'MELA THIRUCHENDUR', lgdCode: '232097' },
    { district: 'THOOTHUKKUDI', block: 'TIRUCHENDUR', name: 'MELA PUDUKKUDI', lgdCode: '232096' },
    { district: 'THOOTHUKKUDI', block: 'TIRUCHENDUR', name: 'NALLUR', lgdCode: '232099' },
    { district: 'THOOTHUKKUDI', block: 'TIRUCHENDUR', name: 'PALLIPATHU', lgdCode: '232100' },
    { district: 'THOOTHUKKUDI', block: 'TIRUCHENDUR', name: 'PITCHI VILAI', lgdCode: '232101' },
    { district: 'THOOTHUKKUDI', block: 'TIRUCHENDUR', name: 'VEERAPANDIAN PATNAM', lgdCode: '232103' },
    { district: 'THOOTHUKKUDI', block: 'TIRUCHENDUR', name: 'VERAPANDIANPATNAM.R.', lgdCode: '232104' },
    { district: 'THOOTHUKKUDI', block: 'TIRUCHENDUR', name: 'VEERAMANICKAM', lgdCode: '232102' },
    { district: 'THOOTHUKKUDI', block: 'UDANGUDI', name: 'Athiyakurichi', lgdCode: '232105' },
    { district: 'THOOTHUKKUDI', block: 'UDANGUDI', name: 'Chettiyapathu', lgdCode: '232106' },
    { district: 'THOOTHUKKUDI', block: 'UDANGUDI', name: 'Kulasekaranpattinam', lgdCode: '232107' },
    { district: 'THOOTHUKKUDI', block: 'UDANGUDI', name: 'Kuthiraimozhi', lgdCode: '232108' },
    { district: 'THOOTHUKKUDI', block: 'UDANGUDI', name: 'Lakshimipuram', lgdCode: '232109' },
    { district: 'THOOTHUKKUDI', block: 'UDANGUDI', name: 'Manapadu', lgdCode: '232111' },
    { district: 'THOOTHUKKUDI', block: 'UDANGUDI', name: 'Manadu Thandupathu', lgdCode: '232110' },
    { district: 'THOOTHUKKUDI', block: 'UDANGUDI', name: 'Mathavankurichi', lgdCode: '232112' },
    { district: 'THOOTHUKKUDI', block: 'UDANGUDI', name: 'Meingnanapuram', lgdCode: '232113' },
    { district: 'THOOTHUKKUDI', block: 'UDANGUDI', name: 'Nainarpathu', lgdCode: '232114' },
    { district: 'THOOTHUKKUDI', block: 'UDANGUDI', name: 'Nangaimozhi', lgdCode: '232115' },
    { district: 'THOOTHUKKUDI', block: 'UDANGUDI', name: 'Paramankurichi', lgdCode: '232116' },
    { district: 'THOOTHUKKUDI', block: 'UDANGUDI', name: 'Seerkatchi', lgdCode: '232117' },
    { district: 'THOOTHUKKUDI', block: 'UDANGUDI', name: 'Semmarikulam', lgdCode: '232118' },
    { district: 'THOOTHUKKUDI', block: 'UDANGUDI', name: 'Sirunadarkudieruppu', lgdCode: '232119' },
    { district: 'THOOTHUKKUDI', block: 'UDANGUDI', name: 'Vellalanvillai', lgdCode: '232120' },
    { district: 'THOOTHUKKUDI', block: 'UDANGUDI', name: 'Venkattaramanujapuram', lgdCode: '232121' },
    { district: 'THOOTHUKKUDI', block: 'SATTANKULAM', name: 'ALAGAPPAPURAM', lgdCode: '232019' },
    { district: 'THOOTHUKKUDI', block: 'SATTANKULAM', name: 'AMUTHUNNAKKUDI', lgdCode: '232020' },
    { district: 'THOOTHUKKUDI', block: 'SATTANKULAM', name: 'ARASOOR', lgdCode: '232021' },
    { district: 'THOOTHUKKUDI', block: 'SATTANKULAM', name: 'CETTIKULAM', lgdCode: '232038' },
    { district: 'THOOTHUKKUDI', block: 'SATTANKULAM', name: 'EZHUVARAIMUKKI', lgdCode: '232022' },
    { district: 'THOOTHUKKUDI', block: 'SATTANKULAM', name: 'KOMANERI', lgdCode: '232023' },
    { district: 'THOOTHUKKUDI', block: 'SATTANKULAM', name: 'KOMBANKULAM', lgdCode: '232024' },
    { district: 'THOOTHUKKUDI', block: 'SATTANKULAM', name: 'KOMMADIKKOTTAI', lgdCode: '232025' },
    { district: 'THOOTHUKKUDI', block: 'SATTANKULAM', name: 'MUDALUR', lgdCode: '232026' },
    { district: 'THOOTHUKKUDI', block: 'SATTANKULAM', name: 'NADUVAKKURICHI', lgdCode: '232027' },
    { district: 'THOOTHUKKUDI', block: 'SATTANKULAM', name: 'NEDUNKULAM', lgdCode: '232028' },
    { district: 'THOOTHUKKUDI', block: 'SATTANKULAM', name: 'PADUKKAPATTU', lgdCode: '232029' },
    { district: 'THOOTHUKKUDI', block: 'SATTANKULAM', name: 'PAZHANKULAM', lgdCode: '232033' },
    { district: 'THOOTHUKKUDI', block: 'SATTANKULAM', name: 'PALLAKKURICHI', lgdCode: '232030' },
    { district: 'THOOTHUKKUDI', block: 'SATTANKULAM', name: 'PANDARAPURAM', lgdCode: '232031' },
    { district: 'THOOTHUKKUDI', block: 'SATTANKULAM', name: 'PANNAMPARAI', lgdCode: '232032' },
    { district: 'THOOTHUKKUDI', block: 'SATTANKULAM', name: 'PERIYATHAZHAI', lgdCode: '232034' },
    { district: 'THOOTHUKKUDI', block: 'SATTANKULAM', name: 'PIDANERI', lgdCode: '232035' },
    { district: 'THOOTHUKKUDI', block: 'SATTANKULAM', name: 'PUDUKULAM', lgdCode: '232036' },
    { district: 'THOOTHUKKUDI', block: 'SATTANKULAM', name: 'SASTHAVINALLUR', lgdCode: '232037' },
    { district: 'THOOTHUKKUDI', block: 'SATTANKULAM', name: 'SUBBARAYAPURAM', lgdCode: '232039' },
    { district: 'THOOTHUKKUDI', block: 'SATTANKULAM', name: 'THAMARAIMOZHI', lgdCode: '232040' },
    { district: 'THOOTHUKKUDI', block: 'SATTANKULAM', name: 'THATCHAMOZHI', lgdCode: '232041' },
    { district: 'THOOTHUKKUDI', block: 'SATTANKULAM', name: 'THIRUPPANI PUTHANTHARUVAI', lgdCode: '232042' },
    { district: 'THOOTHUKKUDI', block: 'KOVILPATTI', name: 'AVALNATHAM', lgdCode: '231876' },
    { district: 'THOOTHUKKUDI', block: 'KOVILPATTI', name: 'AYYAKOTTAIYUR', lgdCode: '231877' },
    { district: 'THOOTHUKKUDI', block: 'KOVILPATTI', name: 'CHATRAPATTI', lgdCode: '231878' },
    { district: 'THOOTHUKKUDI', block: 'KOVILPATTI', name: 'CHIDAMBARAPURAM', lgdCode: '231879' },
    { district: 'THOOTHUKKUDI', block: 'KOVILPATTI', name: 'CHINNAMALAIKUNDRU', lgdCode: '231880' },
    { district: 'THOOTHUKKUDI', block: 'KOVILPATTI', name: 'ERACHI', lgdCode: '231881' },
    { district: 'THOOTHUKKUDI', block: 'KOVILPATTI', name: 'IDAISEVAL', lgdCode: '231882' },
    { district: 'THOOTHUKKUDI', block: 'KOVILPATTI', name: 'ILAMPUVANAM', lgdCode: '231883' },
    { district: 'THOOTHUKKUDI', block: 'KOVILPATTI', name: 'ILUPPAIYOORANI', lgdCode: '231884' },
    { district: 'THOOTHUKKUDI', block: 'KOVILPATTI', name: 'INAMMANIYACHI', lgdCode: '231885' },
    { district: 'THOOTHUKKUDI', block: 'KOVILPATTI', name: 'KADALAIYUR', lgdCode: '231886' },
    { district: 'THOOTHUKKUDI', block: 'KOVILPATTI', name: 'KEELA ERAL', lgdCode: '231887' },
    { district: 'THOOTHUKKUDI', block: 'KOVILPATTI', name: 'KILAVIPATTI', lgdCode: '231888' },
    { district: 'THOOTHUKKUDI', block: 'KOVILPATTI', name: 'KODUKKAMPARAI', lgdCode: '231889' },
    { district: 'THOOTHUKKUDI', block: 'KOVILPATTI', name: 'KULASEKARAPURAM', lgdCode: '231890' },
    { district: 'THOOTHUKKUDI', block: 'KOVILPATTI', name: 'LINGAMPATTI', lgdCode: '231891' },
    { district: 'THOOTHUKKUDI', block: 'KOVILPATTI', name: 'MANTHITHOPPU', lgdCode: '231893' },
    { district: 'THOOTHUKKUDI', block: 'KOVILPATTI', name: 'MANJANAICKENPATTI', lgdCode: '231892' },
    { district: 'THOOTHUKKUDI', block: 'KOVILPATTI', name: 'MEENAKSHIPURAM', lgdCode: '231894' },
    { district: 'THOOTHUKKUDI', block: 'KOVILPATTI', name: 'MELA ERAL', lgdCode: '231895' },
    { district: 'THOOTHUKKUDI', block: 'KOVILPATTI', name: 'MOOPANPATTI', lgdCode: '231896' },
    { district: 'THOOTHUKKUDI', block: 'KOVILPATTI', name: 'MUDUKKUMEENTANPATTI', lgdCode: '231897' },
    { district: 'THOOTHUKKUDI', block: 'KOVILPATTI', name: 'NALATINPUDUR', lgdCode: '231898' },
    { district: 'THOOTHUKKUDI', block: 'KOVILPATTI', name: 'SEMAPUDUR', lgdCode: '231901' },
    { district: 'THOOTHUKKUDI', block: 'KOVILPATTI', name: 'T.SHUNMUGAPURAM', lgdCode: '231902' },
    { district: 'THOOTHUKKUDI', block: 'KOVILPATTI', name: 'SINDALAKARAI', lgdCode: '231903' },
    { district: 'THOOTHUKKUDI', block: 'KOVILPATTI', name: 'SIVANTHIPATTI', lgdCode: '231904' },
    { district: 'THOOTHUKKUDI', block: 'KOVILPATTI', name: 'SURAIKKAIPATTI', lgdCode: '231905' },
    { district: 'THOOTHUKKUDI', block: 'KOVILPATTI', name: 'PANDAVARMANGALAM', lgdCode: '231900' },
    { district: 'THOOTHUKKUDI', block: 'KOVILPATTI', name: 'THEETHAMPATTI', lgdCode: '231906' },
    { district: 'THOOTHUKKUDI', block: 'KOVILPATTI', name: 'THITTANKULAM', lgdCode: '231907' },
    { district: 'THOOTHUKKUDI', block: 'KOVILPATTI', name: 'THURAIYOOR', lgdCode: '231909' },
    { district: 'THOOTHUKKUDI', block: 'KOVILPATTI', name: 'URULAIKKUDI', lgdCode: '231910' },
    { district: 'THOOTHUKKUDI', block: 'KOVILPATTI', name: 'OOTHUPATTI', lgdCode: '231899' },
    { district: 'THOOTHUKKUDI', block: 'KOVILPATTI', name: 'VARATHAMPATTI', lgdCode: '231911' },
    { district: 'THOOTHUKKUDI', block: 'KOVILPATTI', name: 'R.VENKATESHVARAPURAM', lgdCode: '231912' },
    { district: 'THOOTHUKKUDI', block: 'KOVILPATTI', name: 'VILLISERI', lgdCode: '231913' },
    { district: 'THOOTHUKKUDI', block: 'KOVILPATTI', name: 'THONUGAL', lgdCode: '231908' },
    { district: 'THOOTHUKKUDI', block: 'KAYATHAR', name: 'Achankulam', lgdCode: '231831' },
    { district: 'THOOTHUKKUDI', block: 'KAYATHAR', name: 'Ahilandapuram', lgdCode: '231832' },
    { district: 'THOOTHUKKUDI', block: 'KAYATHAR', name: 'Asoor', lgdCode: '231833' },
    { district: 'THOOTHUKKUDI', block: 'KAYATHAR', name: 'Ayyanaroothu', lgdCode: '231834' },
    { district: 'THOOTHUKKUDI', block: 'KAYATHAR', name: 'Chettikurichi', lgdCode: '231835' },
    { district: 'THOOTHUKKUDI', block: 'KAYATHAR', name: 'Chidambarampatti', lgdCode: '231836' },
    { district: 'THOOTHUKKUDI', block: 'KAYATHAR', name: 'Cholapuram', lgdCode: '231837' },
    { district: 'THOOTHUKKUDI', block: 'KAYATHAR', name: 'K. Chidambarapuram', lgdCode: '231838' },
    { district: 'THOOTHUKKUDI', block: 'KAYATHAR', name: 'K. Duraisamypuram', lgdCode: '231839' },
    { district: 'THOOTHUKKUDI', block: 'KAYATHAR', name: 'Kalampatti', lgdCode: '231843' },
    { district: 'THOOTHUKKUDI', block: 'KAYATHAR', name: 'Kalankaraipatti', lgdCode: '231844' },
    { district: 'THOOTHUKKUDI', block: 'KAYATHAR', name: 'Kamanaickenpatti', lgdCode: '231845' },
    { district: 'THOOTHUKKUDI', block: 'KAYATHAR', name: 'Kannakattai', lgdCode: '231846' },
    { district: 'THOOTHUKKUDI', block: 'KAYATHAR', name: 'Kappulingampatti', lgdCode: '231847' },
    { district: 'THOOTHUKKUDI', block: 'KAYATHAR', name: 'Karadikulam', lgdCode: '231848' },
    { district: 'THOOTHUKKUDI', block: 'KAYATHAR', name: 'Kattalankulam', lgdCode: '231849' },
    { district: 'THOOTHUKKUDI', block: 'KAYATHAR', name: 'Koppampatti', lgdCode: '231850' },
    { district: 'THOOTHUKKUDI', block: 'KAYATHAR', name: 'K. Sivagnanapuram', lgdCode: '231840' },
    { district: 'THOOTHUKKUDI', block: 'KAYATHAR', name: 'K. Subramaniapuram', lgdCode: '231841' },
    { district: 'THOOTHUKKUDI', block: 'KAYATHAR', name: 'Kumareddiapuram', lgdCode: '231851' },
    { district: 'THOOTHUKKUDI', block: 'KAYATHAR', name: 'Kuppanapuram', lgdCode: '231852' },
    { district: 'THOOTHUKKUDI', block: 'KAYATHAR', name: 'Kuruvinatham', lgdCode: '231854' },
    { district: 'THOOTHUKKUDI', block: 'KAYATHAR', name: 'Kurumalai', lgdCode: '231853' },
    { district: 'THOOTHUKKUDI', block: 'KAYATHAR', name: 'K. Venkateswarapuram', lgdCode: '231842' },
    { district: 'THOOTHUKKUDI', block: 'KAYATHAR', name: 'Mudukkulankulam', lgdCode: '231855' },
    { district: 'THOOTHUKKUDI', block: 'KAYATHAR', name: 'Pannirkulam', lgdCode: '231857' },
    { district: 'THOOTHUKKUDI', block: 'KAYATHAR', name: 'Panikkarkulam', lgdCode: '231856' },
    { district: 'THOOTHUKKUDI', block: 'KAYATHAR', name: 'Podupatti', lgdCode: '231858' },
    { district: 'THOOTHUKKUDI', block: 'KAYATHAR', name: 'Pungavarnatham', lgdCode: '231859' },
    { district: 'THOOTHUKKUDI', block: 'KAYATHAR', name: 'Sannadu Pudukudi', lgdCode: '231861' },
    { district: 'THOOTHUKKUDI', block: 'KAYATHAR', name: 'Raja Pudukudi', lgdCode: '231860' },
    { district: 'THOOTHUKKUDI', block: 'KAYATHAR', name: 'Savalaperi', lgdCode: '231862' },
    { district: 'THOOTHUKKUDI', block: 'KAYATHAR', name: 'Theethampatti', lgdCode: '231863' },
    { district: 'THOOTHUKKUDI', block: 'KAYATHAR', name: 'Therku Ilandhikulam', lgdCode: '231864' },
    { district: 'THOOTHUKKUDI', block: 'KAYATHAR', name: 'Therku Kalugumalai', lgdCode: '231865' },
    { district: 'THOOTHUKKUDI', block: 'KAYATHAR', name: 'Therku Mylodai', lgdCode: '231866' },
    { district: 'THOOTHUKKUDI', block: 'KAYATHAR', name: 'Therkuvandanam', lgdCode: '231867' },
    { district: 'THOOTHUKKUDI', block: 'KAYATHAR', name: 'Thirumangalakurichi', lgdCode: '231869' },
    { district: 'THOOTHUKKUDI', block: 'KAYATHAR', name: 'Thirumalapuram', lgdCode: '231868' },
    { district: 'THOOTHUKKUDI', block: 'KAYATHAR', name: 'Thottampatti', lgdCode: '231870' },
    { district: 'THOOTHUKKUDI', block: 'KAYATHAR', name: 'Usilankulam', lgdCode: '231871' },
    { district: 'THOOTHUKKUDI', block: 'KAYATHAR', name: 'Vadakkuilandhikulam', lgdCode: '231872' },
    { district: 'THOOTHUKKUDI', block: 'KAYATHAR', name: 'Vadakku Vandanam', lgdCode: '231873' },
    { district: 'THOOTHUKKUDI', block: 'KAYATHAR', name: 'Vanaramutti', lgdCode: '231874' },
    { district: 'THOOTHUKKUDI', block: 'KAYATHAR', name: 'Vellalankottai', lgdCode: '231875' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'AHILANDAPURAM', lgdCode: '231915' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'ACKKANICKENPATTI', lgdCode: '231914' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'ARAIKULAM', lgdCode: '231916' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'ATHANOOR', lgdCode: '231917' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'CHANDIRAGIRI', lgdCode: '231918' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'P.DURAISAMYPURAM', lgdCode: '231952' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'GOVERNAGIRI', lgdCode: '231921' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'ELAVELANGAL', lgdCode: '231919' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'JEGAVEERAPANDIAPURAM', lgdCode: '231923' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'JAMBULINGAPURAM', lgdCode: '231922' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'S.KAILASAPURAM', lgdCode: '231961' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'KALAPPAI PATTI', lgdCode: '231926' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'KATTUNAICKENPATTI', lgdCode: '231927' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'KEELA ARASADI', lgdCode: '231928' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'KELLAKOTTAI', lgdCode: '231931' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'KEELA MUDIMAN', lgdCode: '231929' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'KODIYANKULAM', lgdCode: '231932' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'KOLLAMPARAMBU', lgdCode: '231933' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'KOLLANKINAR', lgdCode: '231934' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'KOTHALI', lgdCode: '231935' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'KULASEKARANALLUR', lgdCode: '231936' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'KUMAREDDIYARPURAM', lgdCode: '231937' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'KURUKKUCHALAI', lgdCode: '231938' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'KUTHIRAIKULAM', lgdCode: '231939' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'MALAIPATTI', lgdCode: '231940' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'MANIYATCHI', lgdCode: '231941' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'MARUTHAN VALVOO', lgdCode: '231942' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'MELA ARASADI', lgdCode: '231944' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'MEENACHIPURAM', lgdCode: '231943' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'MELA PANDIYAPURAM', lgdCode: '231945' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'MULLUR', lgdCode: '231946' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'MURAMBAN', lgdCode: '231947' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'NAGAMPATTI', lgdCode: '231948' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'ONAMAKULAM', lgdCode: '231949' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'OTTANATHAM', lgdCode: '231950' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'OTTAPIDARAM', lgdCode: '231951' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'PANCHALANKURICHI', lgdCode: '231953' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'PARAIKUTTAM', lgdCode: '231954' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'PARIVALLIKOTTAI', lgdCode: '231955' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'PASUVANTHANAI', lgdCode: '231956' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'PATTINAMARUTHUR', lgdCode: '231957' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'PUDUR PANDIYAPURAM', lgdCode: '231958' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'PUTHIYAMPUTHUR', lgdCode: '231959' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'RAJAVINKOVIL', lgdCode: '231960' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'SANGAMPATTI', lgdCode: '231963' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'K.SHUNMUGAPURAM', lgdCode: '231924' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'SILLANATHAM', lgdCode: '231964' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'SILLANKULAM', lgdCode: '231965' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'K.THALAVAIPURAM', lgdCode: '231925' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'THARUVAIKULAM', lgdCode: '231967' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'THENNAM PATTI', lgdCode: '231968' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'THERKKU KALMEDU', lgdCode: '231969' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'T.VEERAPANDIANPURAM', lgdCode: '231966' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'VALASAMUTHIRAM', lgdCode: '231970' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'VEDANATHAM', lgdCode: '231972' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'VELLARAM', lgdCode: '231973' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'VEPPALODAI', lgdCode: '231974' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'EPPODUMVENDRAN', lgdCode: '231920' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'KEELAMANGALAM', lgdCode: '231930' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'SAMINATHAM', lgdCode: '231962' },
    { district: 'THOOTHUKKUDI', block: 'OTTAPIDARAM', name: 'VALLINAYAGIPURAM', lgdCode: '231971' },
    { district: 'THOOTHUKKUDI', block: 'VILATHIKULAM', name: 'ARUNKULAM', lgdCode: '232123' },
    { district: 'THOOTHUKKUDI', block: 'VILATHIKULAM', name: 'ARIYANAYAGIPURAM', lgdCode: '232122' },
    { district: 'THOOTHUKKUDI', block: 'VILATHIKULAM', name: 'ATTRANKARAI', lgdCode: '232124' },
    { district: 'THOOTHUKKUDI', block: 'VILATHIKULAM', name: 'AYANBOMMAIAHPURAM', lgdCode: '232126' },
    { district: 'THOOTHUKKUDI', block: 'VILATHIKULAM', name: 'AYANSENGALPADAI', lgdCode: '232125' },
    { district: 'THOOTHUKKUDI', block: 'VILATHIKULAM', name: 'GURUVARPATTI', lgdCode: '232127' },
    { district: 'THOOTHUKKUDI', block: 'VILATHIKULAM', name: 'INAMSUBRAMANIAPURAM', lgdCode: '232128' },
    { district: 'THOOTHUKKUDI', block: 'VILATHIKULAM', name: 'INAMVEDAPATTI', lgdCode: '232129' },
    { district: 'THOOTHUKKUDI', block: 'VILATHIKULAM', name: 'KALUGACHALAPURAM', lgdCode: '232133' },
    { district: 'THOOTHUKKUDI', block: 'VILATHIKULAM', name: 'KULATHUR', lgdCode: '232137' },
    { district: 'THOOTHUKKUDI', block: 'VILATHIKULAM', name: 'K.KUMAREDDIAPURAM', lgdCode: '232130' },
    { district: 'THOOTHUKKUDI', block: 'VILATHIKULAM', name: 'K.THANGAMMALPURAM', lgdCode: '232132' },
    { district: 'THOOTHUKKUDI', block: 'VILATHIKULAM', name: 'K.SUNDARESWARAPURAM', lgdCode: '232131' },
    { district: 'THOOTHUKKUDI', block: 'VILATHIKULAM', name: 'KEELA VILATHIKULAM', lgdCode: '232136' },
    { district: 'THOOTHUKKUDI', block: 'VILATHIKULAM', name: 'KEELA VAIPPAR', lgdCode: '232135' },
    { district: 'THOOTHUKKUDI', block: 'VILATHIKULAM', name: 'MARTHANDAMPATTI', lgdCode: '232140' },
    { district: 'THOOTHUKKUDI', block: 'VILATHIKULAM', name: 'MANTHIKULAM', lgdCode: '232139' },
    { district: 'THOOTHUKKUDI', block: 'VILATHIKULAM', name: 'MELMANTHAI', lgdCode: '232141' },
    { district: 'THOOTHUKKUDI', block: 'VILATHIKULAM', name: 'M.SHANMUGAPURAM', lgdCode: '232138' },
    { district: 'THOOTHUKKUDI', block: 'VILATHIKULAM', name: 'NAMASIVAYAPURAM', lgdCode: '232142' },
    { district: 'THOOTHUKKUDI', block: 'VILATHIKULAM', name: 'NEERAVIPUDUPATTI', lgdCode: '232144' },
    { district: 'THOOTHUKKUDI', block: 'VILATHIKULAM', name: 'NEDUNGULAM', lgdCode: '232143' },
    { district: 'THOOTHUKKUDI', block: 'VILATHIKULAM', name: 'PADARNTHAPULI', lgdCode: '232146' },
    { district: 'THOOTHUKKUDI', block: 'VILATHIKULAM', name: 'PERILOVANPATTI', lgdCode: '232148' },
    { district: 'THOOTHUKKUDI', block: 'VILATHIKULAM', name: 'PILLAIYARNATHAM', lgdCode: '232149' },
    { district: 'THOOTHUKKUDI', block: 'VILATHIKULAM', name: 'POOSANUR', lgdCode: '232150' },
    { district: 'THOOTHUKKUDI', block: 'VILATHIKULAM', name: 'PULIANKULAM', lgdCode: '232151' },
    { district: 'THOOTHUKKUDI', block: 'VILATHIKULAM', name: 'PERIASAMYPURAM', lgdCode: '232147' },
    { district: 'THOOTHUKKUDI', block: 'VILATHIKULAM', name: 'P.MEENAKSHIPURAM', lgdCode: '232145' },
    { district: 'THOOTHUKKUDI', block: 'VILATHIKULAM', name: 'RAMANOOTHU', lgdCode: '232152' },
    { district: 'THOOTHUKKUDI', block: 'VILATHIKULAM', name: 'SOORANGUDI', lgdCode: '232157' },
    { district: 'THOOTHUKKUDI', block: 'VILATHIKULAM', name: 'SAKKAMMALPURAM', lgdCode: '232154' },
    { district: 'THOOTHUKKUDI', block: 'VILATHIKULAM', name: 'SIVAGNANAPURAM', lgdCode: '232156' },
    { district: 'THOOTHUKKUDI', block: 'VILATHIKULAM', name: 'M.KUMARASAKKANAPURAM', lgdCode: '254921' },
    { district: 'THOOTHUKKUDI', block: 'VILATHIKULAM', name: 'T.SUBBAIAHPURAM', lgdCode: '232158' },
    { district: 'THOOTHUKKUDI', block: 'VILATHIKULAM', name: 'THALAIKKATTUPURAM', lgdCode: '232159' },
    { district: 'THOOTHUKKUDI', block: 'VILATHIKULAM', name: 'THATHANERI', lgdCode: '232160' },
    { district: 'THOOTHUKKUDI', block: 'VILATHIKULAM', name: 'VAIPPAR', lgdCode: '232161' },
    { district: 'THOOTHUKKUDI', block: 'VILATHIKULAM', name: 'VEMBAR', lgdCode: '232166' },
    { district: 'THOOTHUKKUDI', block: 'VILATHIKULAM', name: 'VELIDUPATTI', lgdCode: '232164' },
    { district: 'THOOTHUKKUDI', block: 'VILATHIKULAM', name: 'VEERAPANDIAPURAM', lgdCode: '232163' },
    { district: 'THOOTHUKKUDI', block: 'VILATHIKULAM', name: 'VIRUSAMPATTI', lgdCode: '232169' },
    { district: 'THOOTHUKKUDI', block: 'VILATHIKULAM', name: 'VELLAIAMMALPURAM', lgdCode: '232165' },
    { district: 'THOOTHUKKUDI', block: 'VILATHIKULAM', name: 'VILVAMARATHUPATTI', lgdCode: '232168' },
    { district: 'THOOTHUKKUDI', block: 'VILATHIKULAM', name: 'VALLINAYAGIPURAM', lgdCode: '232162' },
    { district: 'THOOTHUKKUDI', block: 'VILATHIKULAM', name: 'VEMBAR SOUTH', lgdCode: '232167' },
    { district: 'THOOTHUKKUDI', block: 'VILATHIKULAM', name: 'ZAMIN KARISALKULAM', lgdCode: '232170' },
    { district: 'THOOTHUKKUDI', block: 'VILATHIKULAM', name: 'ZAMIN KODANGIPATTI', lgdCode: '232171' },
    { district: 'THOOTHUKKUDI', block: 'VILATHIKULAM', name: 'ZAMIN SENGALPADAI', lgdCode: '232172' },
    { district: 'THOOTHUKKUDI', block: 'VILATHIKULAM', name: 'KAMALAPURAM', lgdCode: '232134' },
    { district: 'THOOTHUKKUDI', block: 'VILATHIKULAM', name: 'CHITHTHAVANAYAKKENPATTI', lgdCode: '232155' },
    { district: 'THOOTHUKKUDI', block: 'PUDUR', name: 'Ayankarisalkulam', lgdCode: '231975' },
    { district: 'THOOTHUKKUDI', block: 'PUDUR', name: 'Ayanrajapatti', lgdCode: '231976' },
    { district: 'THOOTHUKKUDI', block: 'PUDUR', name: 'Ayanvadamalapuram', lgdCode: '231977' },
    { district: 'THOOTHUKKUDI', block: 'PUDUR', name: 'Boothalapuram', lgdCode: '231978' },
    { district: 'THOOTHUKKUDI', block: 'PUDUR', name: 'Chinnavanaickenpatti', lgdCode: '231979' },
    { district: 'THOOTHUKKUDI', block: 'PUDUR', name: 'K.Duraisamypuram', lgdCode: '231980' },
    { district: 'THOOTHUKKUDI', block: 'PUDUR', name: 'Inamarunachalapuram', lgdCode: '231981' },
    { district: 'THOOTHUKKUDI', block: 'PUDUR', name: 'N.Jeegaveerapuram', lgdCode: '231982' },
    { district: 'THOOTHUKKUDI', block: 'PUDUR', name: 'Kadalkudi', lgdCode: '231983' },
    { district: 'THOOTHUKKUDI', block: 'PUDUR', name: 'Kandasamypuram', lgdCode: '231984' },
    { district: 'THOOTHUKKUDI', block: 'PUDUR', name: 'Karuppur', lgdCode: '231985' },
    { district: 'THOOTHUKKUDI', block: 'PUDUR', name: 'Goundenpatti', lgdCode: '231989' },
    { district: 'THOOTHUKKUDI', block: 'PUDUR', name: 'Keelaarunachalapuram', lgdCode: '231986' },
    { district: 'THOOTHUKKUDI', block: 'PUDUR', name: 'Keelakaranthai', lgdCode: '231987' },
    { district: 'THOOTHUKKUDI', block: 'PUDUR', name: 'Keelnattukurichi', lgdCode: '231988' },
    { district: 'THOOTHUKKUDI', block: 'PUDUR', name: 'Lakshmipuram', lgdCode: '231990' },
    { district: 'THOOTHUKKUDI', block: 'PUDUR', name: 'Maniyakaranpatti', lgdCode: '231991' },
    { district: 'THOOTHUKKUDI', block: 'PUDUR', name: 'Maasarpatti', lgdCode: '231992' },
    { district: 'THOOTHUKKUDI', block: 'PUDUR', name: 'Mathalapuram', lgdCode: '231993' },
    { district: 'THOOTHUKKUDI', block: 'PUDUR', name: 'Mavilodai', lgdCode: '231994' },
    { district: 'THOOTHUKKUDI', block: 'PUDUR', name: 'Mavilpatti', lgdCode: '231995' },
    { district: 'THOOTHUKKUDI', block: 'PUDUR', name: 'Melaarunachalapuram', lgdCode: '231996' },
    { district: 'THOOTHUKKUDI', block: 'PUDUR', name: 'Melakallurani', lgdCode: '231997' },
    { district: 'THOOTHUKKUDI', block: 'PUDUR', name: 'Melakaranthai', lgdCode: '231998' },
    { district: 'THOOTHUKKUDI', block: 'PUDUR', name: 'Mettilpatti', lgdCode: '231999' },
    { district: 'THOOTHUKKUDI', block: 'PUDUR', name: 'Mittavadamalapuram', lgdCode: '232000' },
    { district: 'THOOTHUKKUDI', block: 'PUDUR', name: 'Muthaiahpuram', lgdCode: '232001' },
    { district: 'THOOTHUKKUDI', block: 'PUDUR', name: 'Muthulapuram', lgdCode: '232002' },
    { district: 'THOOTHUKKUDI', block: 'PUDUR', name: 'Muthusamypuram', lgdCode: '232003' },
    { district: 'THOOTHUKKUDI', block: 'PUDUR', name: 'Nagalapuram', lgdCode: '232004' },
    { district: 'THOOTHUKKUDI', block: 'PUDUR', name: 'Melanambipuram', lgdCode: '232005' },
    { district: 'THOOTHUKKUDI', block: 'PUDUR', name: 'Pattidevanpatti', lgdCode: '232006' },
    { district: 'THOOTHUKKUDI', block: 'PUDUR', name: 'Ramachandirapuram', lgdCode: '232007' },
    { district: 'THOOTHUKKUDI', block: 'PUDUR', name: 'Sankaralingapuram', lgdCode: '232008' },
    { district: 'THOOTHUKKUDI', block: 'PUDUR', name: 'Sennampatti', lgdCode: '232010' },
    { district: 'THOOTHUKKUDI', block: 'PUDUR', name: 'Shencottai', lgdCode: '232011' },
    { district: 'THOOTHUKKUDI', block: 'PUDUR', name: 'Sivalarpatti', lgdCode: '232012' },
    { district: 'THOOTHUKKUDI', block: 'PUDUR', name: 'Thappathi', lgdCode: '232013' },
    { district: 'THOOTHUKKUDI', block: 'PUDUR', name: 'Vathalakarai', lgdCode: '232014' },
    { district: 'THOOTHUKKUDI', block: 'PUDUR', name: 'Vedapatti', lgdCode: '232015' },
    { district: 'THOOTHUKKUDI', block: 'PUDUR', name: 'Veerapatti', lgdCode: '232016' },
    { district: 'THOOTHUKKUDI', block: 'PUDUR', name: 'Vembur', lgdCode: '232017' },
    { district: 'THOOTHUKKUDI', block: 'PUDUR', name: 'Vowalthothi', lgdCode: '232018' },
    { district: 'THOOTHUKKUDI', 'block': 'PUDUR', 'name': 'Sennamareddipaddi', 'lgdCode': '232009' },
];
