
import type { Panchayat } from './types';

export const TIRUCHIRAPPALLI_PANCHAYATS: Panchayat[] = [
    { district: 'TIRUCHIRAPPALLI', block: 'ANDHANALLUR', name: 'Allur', lgdCode: '230081' },
    { district: 'TIRUCHIRAPPALLI', block: 'ANDHANALLUR', name: 'Andhanallur', lgdCode: '230082' },
    { district: 'TIRUCHIRAPPALLI', block: 'ANDHANALLUR', name: 'Ettarai', lgdCode: '230083' },
    { district: 'TIRUCHIRAPPALLI', block: 'ANDHANALLUR', name: 'Kambarasampettai', lgdCode: '230084' },
    { district: 'TIRUCHIRAPPALLI', block: 'ANDHANALLUR', name: 'Kilikoodu', lgdCode: '230085' },
    { district: 'TIRUCHIRAPPALLI', block: 'ANDHANALLUR', name: 'Kodiyalam', lgdCode: '230086' },
    { district: 'TIRUCHIRAPPALLI', block: 'ANDHANALLUR', name: 'Koppu', lgdCode: '230087' },
    { district: 'TIRUCHIRAPPALLI', block: 'ANDHANALLUR', name: 'Kulumani', lgdCode: '230088' },
    { district: 'TIRUCHIRAPPALLI', block: 'ANDHANALLUR', name: 'Malliyampathu', lgdCode: '230089' },
    { district: 'TIRUCHIRAPPALLI', block: 'ANDHANALLUR', name: 'Maruthandakuruchi', lgdCode: '230090' },
    { district: 'TIRUCHIRAPPALLI', block: 'ANDHANALLUR', name: 'Mekkudi', lgdCode: '230091' },
    { district: 'TIRUCHIRAPPALLI', block: 'ANDHANALLUR', name: 'Mullikarumbur', lgdCode: '230092' },
    { district: 'TIRUCHIRAPPALLI', block: 'ANDHANALLUR', name: 'Mutharasanallur', lgdCode: '230093' },
    { district: 'TIRUCHIRAPPALLI', block: 'ANDHANALLUR', name: 'Palur', lgdCode: '230094' },
    { district: 'TIRUCHIRAPPALLI', block: 'ANDHANALLUR', name: 'Panaiyapuram', lgdCode: '230095' },
    { district: 'TIRUCHIRAPPALLI', block: 'ANDHANALLUR', name: 'Periyakaruppur', lgdCode: '230096' },
    { district: 'TIRUCHIRAPPALLI', block: 'ANDHANALLUR', name: 'Perugamani', lgdCode: '230097' },
    { district: 'TIRUCHIRAPPALLI', block: 'ANDHANALLUR', name: 'Perur', lgdCode: '230098' },
    { district: 'TIRUCHIRAPPALLI', block: 'ANDHANALLUR', name: 'Pettavaithalai', lgdCode: '230099' },
    { district: 'TIRUCHIRAPPALLI', block: 'ANDHANALLUR', name: 'Podhavur', lgdCode: '230100' },
    { district: 'TIRUCHIRAPPALLI', block: 'ANDHANALLUR', name: 'Posampatti', lgdCode: '230101' },
    { district: 'TIRUCHIRAPPALLI', block: 'ANDHANALLUR', name: 'Puliyur', lgdCode: '230102' },
    { district: 'TIRUCHIRAPPALLI', block: 'ANDHANALLUR', name: 'Thiruchendurai', lgdCode: '230103' },
    { district: 'TIRUCHIRAPPALLI', block: 'ANDHANALLUR', name: 'Thirupparaithurai', lgdCode: '230104' },
    { district: 'TIRUCHIRAPPALLI', block: 'ANDHANALLUR', name: 'Uthamarseeli', lgdCode: '230105' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANIKANDAM', name: 'ADAVATHUR', lgdCode: '230207' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANIKANDAM', name: 'ALUNDUR', lgdCode: '230209' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANIKANDAM', name: 'ALLITHURAI', lgdCode: '230208' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANIKANDAM', name: 'AMMAPETTAI', lgdCode: '230210' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANIKANDAM', name: 'ARIYAVUR', lgdCode: '230211' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANIKANDAM', name: 'K.KALLIKUDI', lgdCode: '230214' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANIKANDAM', name: 'INAM KULATHUR', lgdCode: '230213' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANIKANDAM', name: 'KUMARA VAYALUR', lgdCode: '230215' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANIKANDAM', name: 'MATHUR', lgdCode: '230216' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANIKANDAM', name: 'MEKKUDI', lgdCode: '230217' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANIKANDAM', name: 'MUDIKANDAM', lgdCode: '230218' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANIKANDAM', name: 'NACHIKURUCHI', lgdCode: '230220' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANIKANDAM', name: 'NAGAMANGALAM', lgdCode: '230221' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANIKANDAM', name: 'N. KUTTAPATTU', lgdCode: '230219' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANIKANDAM', name: 'PAGANUR', lgdCode: '230223' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANIKANDAM', name: 'PUNGANUR', lgdCode: '230224' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANIKANDAM', name: 'P.N. CHATHIRAM', lgdCode: '230222' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANIKANDAM', name: 'SETHURAPATTI', lgdCode: '230225' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANIKANDAM', name: 'SOMARASAMPETTAI', lgdCode: '230226' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANIKANDAM', name: 'THAYANUR', lgdCode: '230227' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANIKANDAM', name: 'DURAIKUDI', lgdCode: '230212' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANIKANDAM', name: 'THIRUMALAISAMUDRAM', lgdCode: '230228' },
    { district: 'TIRUCHIRAPPALLI', block: 'THIRUVERAMBUR', name: 'Arasangudi', lgdCode: '230369' },
    { district: 'TIRUCHIRAPPALLI', block: 'THIRUVERAMBUR', name: 'Asoor', lgdCode: '230370' },
    { district: 'TIRUCHIRAPPALLI', block: 'THIRUVERAMBUR', name: 'Gundur', lgdCode: '230371' },
    { district: 'TIRUCHIRAPPALLI', block: 'THIRUVERAMBUR', name: 'Kanthalur', lgdCode: '230372' },
    { district: 'TIRUCHIRAPPALLI', block: 'THIRUVERAMBUR', name: 'Keela Kuruchi', lgdCode: '230373' },
    { district: 'TIRUCHIRAPPALLI', block: 'THIRUVERAMBUR', name: 'Keelamullakudi', lgdCode: '230374' },
    { district: 'TIRUCHIRAPPALLI', block: 'THIRUVERAMBUR', name: 'Kiliyur', lgdCode: '230375' },
    { district: 'TIRUCHIRAPPALLI', block: 'THIRUVERAMBUR', name: 'Krishnasamuthram', lgdCode: '230376' },
    { district: 'TIRUCHIRAPPALLI', block: 'THIRUVERAMBUR', name: 'Kumbakudi', lgdCode: '230377' },
    { district: 'TIRUCHIRAPPALLI', block: 'THIRUVERAMBUR', name: 'Kuvalakudi', lgdCode: '230378' },
    { district: 'TIRUCHIRAPPALLI', block: 'THIRUVERAMBUR', name: 'Natarajapuram', lgdCode: '230379' },
    { district: 'TIRUCHIRAPPALLI', block: 'THIRUVERAMBUR', name: 'Navalpattu', lgdCode: '230380' },
    { district: 'TIRUCHIRAPPALLI', block: 'THIRUVERAMBUR', name: 'Palanganangudi', lgdCode: '230381' },
    { district: 'TIRUCHIRAPPALLI', block: 'THIRUVERAMBUR', name: 'Panaiyakuruchi', lgdCode: '230382' },
    { district: 'TIRUCHIRAPPALLI', block: 'THIRUVERAMBUR', name: 'Pathalapettai', lgdCode: '230383' },
    { district: 'TIRUCHIRAPPALLI', block: 'THIRUVERAMBUR', name: 'Solamadevi', lgdCode: '230384' },
    { district: 'TIRUCHIRAPPALLI', block: 'THIRUVERAMBUR', name: 'Suriyur', lgdCode: '230385' },
    { district: 'TIRUCHIRAPPALLI', block: 'THIRUVERAMBUR', name: 'Thirunedungulam', lgdCode: '230386' },
    { district: 'TIRUCHIRAPPALLI', block: 'THIRUVERAMBUR', name: 'Valavanthankottai', lgdCode: '230387' },
    { district: 'TIRUCHIRAPPALLI', block: 'THIRUVERAMBUR', name: 'Vengur', lgdCode: '230388' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANAPPARAI', name: 'Chettiappatti', lgdCode: '230186' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANAPPARAI', name: 'Siththanatham', lgdCode: '230201' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANAPPARAI', name: 'Karuppur', lgdCode: '230191' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANAPPARAI', name: 'Kalingappatty', lgdCode: '230189' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANAPPARAI', name: 'Kannudayanpatty', lgdCode: '230190' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANAPPARAI', name: 'F. Keelaiyur', lgdCode: '230187' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANAPPARAI', name: 'Malayadippatti', lgdCode: '230192' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANAPPARAI', name: 'Mondippatty', lgdCode: '230193' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANAPPARAI', name: 'Pannappatty', lgdCode: '230194' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANAPPARAI', name: 'K. Periyappatty', lgdCode: '230188' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANAPPARAI', name: 'Podanguppatty', lgdCode: '230195' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANAPPARAI', name: 'Poigaipatty', lgdCode: '230196' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANAPPARAI', name: 'Puthanatham', lgdCode: '230197' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANAPPARAI', name: 'Samuthiram', lgdCode: '230199' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANAPPARAI', name: 'Sampatty', lgdCode: '230198' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANAPPARAI', name: 'Sooliappatty', lgdCode: '230202' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANAPPARAI', name: 'Seegampatty', lgdCode: '230200' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANAPPARAI', name: 'Thoppampatty', lgdCode: '230203' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANAPPARAI', name: 'Usilampatty', lgdCode: '230204' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANAPPARAI', name: 'Vadugapatty', lgdCode: '230205' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANAPPARAI', name: 'Vengaikurichi', lgdCode: '230206' },
    { district: 'TIRUCHIRAPPALLI', block: 'MARUNGAPURI', name: 'Athikaram', lgdCode: '230235' },
    { district: 'TIRUCHIRAPPALLI', block: 'MARUNGAPURI', name: 'Adaikkampatti', lgdCode: '230231' },
    { district: 'TIRUCHIRAPPALLI', block: 'MARUNGAPURI', name: 'Amma Chathiram', lgdCode: '230234' },
    { district: 'TIRUCHIRAPPALLI', block: 'MARUNGAPURI', name: 'A.Poruvai', lgdCode: '230229' },
    { district: 'TIRUCHIRAPPALLI', block: 'MARUNGAPURI', name: 'Amanakkampatti', lgdCode: '230233' },
    { district: 'TIRUCHIRAPPALLI', block: 'MARUNGAPURI', name: 'Alampatti', lgdCode: '230232' },
    { district: 'TIRUCHIRAPPALLI', block: 'MARUNGAPURI', name: 'A. Pudupatti', lgdCode: '230230' },
    { district: 'TIRUCHIRAPPALLI', block: 'MARUNGAPURI', name: 'D. Pudupatti', lgdCode: '230236' },
    { district: 'TIRUCHIRAPPALLI', block: 'MARUNGAPURI', name: 'Endapuli', lgdCode: '230237' },
    { district: 'TIRUCHIRAPPALLI', block: 'MARUNGAPURI', name: 'Ikkaraikosikuruchi', lgdCode: '230239' },
    { district: 'TIRUCHIRAPPALLI', block: 'MARUNGAPURI', name: 'Kallakkampatti', lgdCode: '230241' },
    { district: 'TIRUCHIRAPPALLI', block: 'MARUNGAPURI', name: 'Karadipatti', lgdCode: '230246' },
    { district: 'TIRUCHIRAPPALLI', block: 'MARUNGAPURI', name: 'Kannukuli', lgdCode: '230244' },
    { district: 'TIRUCHIRAPPALLI', block: 'MARUNGAPURI', name: 'Kannivadugapatti', lgdCode: '230243' },
    { district: 'TIRUCHIRAPPALLI', block: 'MARUNGAPURI', name: 'Karumalai', lgdCode: '230248' },
    { district: 'TIRUCHIRAPPALLI', block: 'MARUNGAPURI', name: 'Kalingapatti', lgdCode: '230240' },
    { district: 'TIRUCHIRAPPALLI', block: 'MARUNGAPURI', name: 'Goundampatti', lgdCode: '230238' },
    { district: 'TIRUCHIRAPPALLI', block: 'MARUNGAPURI', name: 'Kannuthu', lgdCode: '230245' },
    { district: 'TIRUCHIRAPPALLI', block: 'MARUNGAPURI', name: 'Kanjanaickanpatti', lgdCode: '230242' },
    { district: 'TIRUCHIRAPPALLI', block: 'MARUNGAPURI', name: 'Karaipatti', lgdCode: '230247' },
    { district: 'TIRUCHIRAPPALLI', block: 'MARUNGAPURI', name: 'Kodumbapatti', lgdCode: '230249' },
    { district: 'TIRUCHIRAPPALLI', block: 'MARUNGAPURI', name: 'Maniyankuruchi', lgdCode: '230251' },
    { district: 'TIRUCHIRAPPALLI', block: 'MARUNGAPURI', name: 'Marungapuri', lgdCode: '230252' },
    { district: 'TIRUCHIRAPPALLI', block: 'MARUNGAPURI', name: 'Minikkiyur', lgdCode: '230253' },
    { district: 'TIRUCHIRAPPALLI', block: 'MARUNGAPURI', name: 'Muththalvarpatti', lgdCode: '230254' },
    { district: 'TIRUCHIRAPPALLI', block: 'MARUNGAPURI', name: 'M. Edayapatti', lgdCode: '230250' },
    { district: 'TIRUCHIRAPPALLI', block: 'MARUNGAPURI', name: 'Nallur', lgdCode: '230255' },
    { district: 'TIRUCHIRAPPALLI', block: 'MARUNGAPURI', name: 'Nattarpatti', lgdCode: '230256' },
    { district: 'TIRUCHIRAPPALLI', block: 'MARUNGAPURI', name: 'Paluvanji', lgdCode: '230259' },
    { district: 'TIRUCHIRAPPALLI', block: 'MARUNGAPURI', name: 'Palaya Palayam', lgdCode: '230258' },
    { district: 'TIRUCHIRAPPALLI', block: 'MARUNGAPURI', name: 'Palakuruchi', lgdCode: '230257' },
    { district: 'TIRUCHIRAPPALLI', block: 'MARUNGAPURI', name: 'Pidarappatti', lgdCode: '230260' },
    { district: 'TIRUCHIRAPPALLI', block: 'MARUNGAPURI', name: 'Pirampatti', lgdCode: '230261' },
    { district: 'TIRUCHIRAPPALLI', block: 'MARUNGAPURI', name: 'Sevalpatti', lgdCode: '230262' },
    { district: 'TIRUCHIRAPPALLI', block: 'MARUNGAPURI', name: 'Thalambadi', lgdCode: '230264' },
    { district: 'TIRUCHIRAPPALLI', block: 'MARUNGAPURI', name: 'Thathanoor', lgdCode: '230265' },
    { district: 'TIRUCHIRAPPALLI', block: 'MARUNGAPURI', name: 'Tirunellipatti', lgdCode: '230269' },
    { district: 'TIRUCHIRAPPALLI', block: 'MARUNGAPURI', name: 'Thethur', lgdCode: '230267' },
    { district: 'TIRUCHIRAPPALLI', block: 'MARUNGAPURI', name: 'Thenur', lgdCode: '230266' },
    { district: 'TIRUCHIRAPPALLI', block: 'MARUNGAPURI', name: 'Thottiyapatti', lgdCode: '230268' },
    { district: 'TIRUCHIRAPPALLI', block: 'MARUNGAPURI', name: 'T. Edayapatti', lgdCode: '230263' },
    { district: 'TIRUCHIRAPPALLI', block: 'MARUNGAPURI', name: 'Usilampatti', lgdCode: '230271' },
    { district: 'TIRUCHIRAPPALLI', block: 'MARUNGAPURI', name: 'Unaiyur', lgdCode: '230270' },
    { district: 'TIRUCHIRAPPALLI', block: 'MARUNGAPURI', name: 'Uthukuli', lgdCode: '230272' },
    { district: 'TIRUCHIRAPPALLI', block: 'MARUNGAPURI', name: 'Valanadu', lgdCode: '230276' },
    { district: 'TIRUCHIRAPPALLI', block: 'MARUNGAPURI', name: 'Vaguthalvarpatti', lgdCode: '230274' },
    { district: 'TIRUCHIRAPPALLI', block: 'MARUNGAPURI', name: 'Vairampatti', lgdCode: '230275' },
    { district: 'TIRUCHIRAPPALLI', block: 'MARUNGAPURI', name: 'Vembanur', lgdCode: '230277' },
    { district: 'TIRUCHIRAPPALLI', block: 'MARUNGAPURI', name: 'V. Edayapatti', lgdCode: '230273' },
    { district: 'TIRUCHIRAPPALLI', block: 'VAIYAMPATTY', name: 'Amayapuram', lgdCode: '230468' },
    { district: 'TIRUCHIRAPPALLI', block: 'VAIYAMPATTY', name: 'Aniyappur', lgdCode: '230469' },
    { district: 'TIRUCHIRAPPALLI', block: 'VAIYAMPATTY', name: 'Ayanreddiyapatti', lgdCode: '230467' },
    { district: 'TIRUCHIRAPPALLI', block: 'VAIYAMPATTY', name: 'Thavalaveeranpatty', lgdCode: '230481' },
    { district: 'TIRUCHIRAPPALLI', block: 'VAIYAMPATTY', name: 'Elamanam', lgdCode: '230470' },
    { district: 'TIRUCHIRAPPALLI', block: 'VAIYAMPATTY', name: 'Inamponnambalampatti', lgdCode: '230471' },
    { district: 'TIRUCHIRAPPALLI', block: 'VAIYAMPATTY', name: 'Inampudur', lgdCode: '230472' },
    { district: 'TIRUCHIRAPPALLI', block: 'VAIYAMPATTY', name: 'Inampuduvadi', lgdCode: '230473' },
    { district: 'TIRUCHIRAPPALLI', block: 'VAIYAMPATTY', name: 'Kumaravadi', lgdCode: '230474' },
    { district: 'TIRUCHIRAPPALLI', block: 'VAIYAMPATTY', name: 'Mugavanur', lgdCode: '230475' },
    { district: 'TIRUCHIRAPPALLI', block: 'VAIYAMPATTY', name: 'Nadupatti', lgdCode: '230476' },
    { district: 'TIRUCHIRAPPALLI', block: 'VAIYAMPATTY', name: 'Nallampillai', lgdCode: '230477' },
    { district: 'TIRUCHIRAPPALLI', block: 'VAIYAMPATTY', name: 'Palayakottai', lgdCode: '230478' },
    { district: 'TIRUCHIRAPPALLI', block: 'VAIYAMPATTY', name: 'V. Periyapatti', lgdCode: '230482' },
    { district: 'TIRUCHIRAPPALLI', block: 'VAIYAMPATTY', name: 'Pudukkottai', lgdCode: '230479' },
    { district: 'TIRUCHIRAPPALLI', block: 'VAIYAMPATTY', name: 'Sekkanam', lgdCode: '230480' },
    { district: 'TIRUCHIRAPPALLI', block: 'VAIYAMPATTY', name: 'Vaiyampatti', lgdCode: '230483' },
    { district: 'TIRUCHIRAPPALLI', block: 'VAIYAMPATTY', name: 'Vellalapatty', lgdCode: '230484' },
    { district: 'TIRUCHIRAPPALLI', block: 'LALGUDI', name: 'Agalanganallur', lgdCode: '230106' },
    { district: 'TIRUCHIRAPPALLI', block: 'LALGUDI', name: 'Alangudi Mahajanam', lgdCode: '230107' },
    { district: 'TIRUCHIRAPPALLI', block: 'LALGUDI', name: 'Angarai', lgdCode: '230108' },
    { district: 'TIRUCHIRAPPALLI', block: 'LALGUDI', name: 'Appadurai', lgdCode: '230109' },
    { district: 'TIRUCHIRAPPALLI', block: 'LALGUDI', name: 'Ariyur', lgdCode: '230110' },
    { district: 'TIRUCHIRAPPALLI', block: 'LALGUDI', name: 'Athikudi', lgdCode: '230111' },
    { district: 'TIRUCHIRAPPALLI', block: 'LALGUDI', name: 'Edayathumangalam', lgdCode: '230112' },
    { district: 'TIRUCHIRAPPALLI', block: 'LALGUDI', name: 'Esanakorai', lgdCode: '230113' },
    { district: 'TIRUCHIRAPPALLI', block: 'LALGUDI', name: 'Seventhinathapuram', lgdCode: '230140' },
    { district: 'TIRUCHIRAPPALLI', block: 'LALGUDI', name: 'T. Kalvikudi', lgdCode: '230143' },
    { district: 'TIRUCHIRAPPALLI', block: 'LALGUDI', name: 'Keelaanbil', lgdCode: '230116' },
    { district: 'TIRUCHIRAPPALLI', block: 'LALGUDI', name: 'Keela Perungavur', lgdCode: '230115' },
    { district: 'TIRUCHIRAPPALLI', block: 'LALGUDI', name: 'Komakudi', lgdCode: '230118' },
    { district: 'TIRUCHIRAPPALLI', block: 'LALGUDI', name: 'Konnaikudi', lgdCode: '230119' },
    { district: 'TIRUCHIRAPPALLI', block: 'LALGUDI', name: 'Khookur', lgdCode: '230117' },
    { district: 'TIRUCHIRAPPALLI', block: 'LALGUDI', name: 'Koppavali', lgdCode: '230120' },
    { district: 'TIRUCHIRAPPALLI', block: 'LALGUDI', name: 'Madakudi', lgdCode: '230121' },
    { district: 'TIRUCHIRAPPALLI', block: 'LALGUDI', name: 'Mahilambadi', lgdCode: '230122' },
    { district: 'TIRUCHIRAPPALLI', block: 'LALGUDI', name: 'Manakkal', lgdCode: '230123' },
    { district: 'TIRUCHIRAPPALLI', block: 'LALGUDI', name: 'Mangammalpuram', lgdCode: '230124' },
    { district: 'TIRUCHIRAPPALLI', block: 'LALGUDI', name: 'Maruthur', lgdCode: '230126' },
    { district: 'TIRUCHIRAPPALLI', block: 'LALGUDI', name: 'Mangudi', lgdCode: '230125' },
    { district: 'TIRUCHIRAPPALLI', block: 'LALGUDI', name: 'Mettupatti', lgdCode: '230127' },
    { district: 'TIRUCHIRAPPALLI', block: 'LALGUDI', name: 'Nagar', lgdCode: '230128' },
    { district: 'TIRUCHIRAPPALLI', block: 'LALGUDI', name: 'Natham', lgdCode: '230129' },
    { district: 'TIRUCHIRAPPALLI', block: 'LALGUDI', name: 'Neikuppai', lgdCode: '230130' },
    { district: 'TIRUCHIRAPPALLI', block: 'LALGUDI', name: 'Nerunjalakudi', lgdCode: '230131' },
    { district: 'TIRUCHIRAPPALLI', block: 'LALGUDI', name: 'Pallapuram', lgdCode: '230132' },
    { district: 'TIRUCHIRAPPALLI', block: 'LALGUDI', name: 'Pambaramsuthi', lgdCode: '230133' },
    { district: 'TIRUCHIRAPPALLI', block: 'LALGUDI', name: 'Peruvalanallur', lgdCode: '230134' },
    { district: 'TIRUCHIRAPPALLI', block: 'LALGUDI', name: 'Pudukudi', lgdCode: '230135' },
    { district: 'TIRUCHIRAPPALLI', block: 'LALGUDI', name: 'Pudur Uthamanur', lgdCode: '230136' },
    { district: 'TIRUCHIRAPPALLI', block: 'LALGUDI', name: 'Sathamangalam', lgdCode: '230138' },
    { district: 'TIRUCHIRAPPALLI', block: 'LALGUDI', name: 'Sembarai', lgdCode: '230139' },
    { district: 'TIRUCHIRAPPALLI', block: 'LALGUDI', name: 'Sirumaruthur', lgdCode: '230141' },
    { district: 'TIRUCHIRAPPALLI', block: 'LALGUDI', name: 'Sirumayankudi', lgdCode: '230142' },
    { district: 'TIRUCHIRAPPALLI', block: 'LALGUDI', name: 'Thatchankuruchi', lgdCode: '230146' },
    { district: 'TIRUCHIRAPPALLI', block: 'LALGUDI', name: 'Thalakudi', lgdCode: '230145' },
    { district: 'TIRUCHIRAPPALLI', block: 'LALGUDI', name: 'Thinniyam', lgdCode: '230147' },
    { district: 'TIRUCHIRAPPALLI', block: 'LALGUDI', name: 'Thirumanamedu', lgdCode: '230148' },
    { district: 'TIRUCHIRAPPALLI', block: 'LALGUDI', name: 'Thirumangalam', lgdCode: '230149' },
    { district: 'TIRUCHIRAPPALLI', block: 'LALGUDI', name: 'Valadi', lgdCode: '230150' },
    { district: 'TIRUCHIRAPPALLI', block: 'LALGUDI', name: 'R. Valavanur', lgdCode: '230137' },
    { district: 'TIRUCHIRAPPALLI', block: 'LALGUDI', name: 'T. Valavanur', lgdCode: '230144' },
    { district: 'TIRUCHIRAPPALLI', block: 'LALGUDI', name: 'Jengamarajapuram', lgdCode: '230114' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANACHANALLUR', name: 'Alagiyamanavalam', lgdCode: '230152' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANACHANALLUR', name: 'Ayyampalayam', lgdCode: '230154' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANACHANALLUR', name: 'Ayikudi', lgdCode: '230153' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANACHANALLUR', name: 'Irungalur', lgdCode: '230158' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANACHANALLUR', name: 'Inamkalpalayam', lgdCode: '230157' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANACHANALLUR', name: 'Inam Samayapuram', lgdCode: '230156' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANACHANALLUR', name: 'Edumalai', lgdCode: '230155' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANACHANALLUR', name: 'Omandur', lgdCode: '230166' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANACHANALLUR', name: '94. Kariyamanickam', lgdCode: '230151' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANACHANALLUR', name: 'Kiliyanallur', lgdCode: '230159' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANACHANALLUR', name: 'Koothur', lgdCode: '230161' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANACHANALLUR', name: 'Konalai', lgdCode: '230160' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANACHANALLUR', name: 'Kovathakudi', lgdCode: '230162' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANACHANALLUR', name: 'Sanamangalam', lgdCode: '230171' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANACHANALLUR', name: 'Sirugudi', lgdCode: '230173' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANACHANALLUR', name: 'Sirupathoor', lgdCode: '230174' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANACHANALLUR', name: 'Siruganur', lgdCode: '230172' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANACHANALLUR', name: 'Sridevimangalam', lgdCode: '230175' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANACHANALLUR', name: 'Thathamangalam', lgdCode: '230177' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANACHANALLUR', name: 'Thaludalapatti', lgdCode: '230176' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANACHANALLUR', name: 'Thiruppanjeeli', lgdCode: '230179' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANACHANALLUR', name: 'Thiruvellarai', lgdCode: '230182' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANACHANALLUR', name: 'Thiruvasi', lgdCode: '230181' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANACHANALLUR', name: 'Thiruppattur', lgdCode: '230180' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANACHANALLUR', name: 'Theerampalayam', lgdCode: '230178' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANACHANALLUR', name: 'Palayur', lgdCode: '230167' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANACHANALLUR', name: 'Pitchandarkovil', lgdCode: '230169' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANACHANALLUR', name: 'Poonampalayam', lgdCode: '230170' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANACHANALLUR', name: 'Perakambi', lgdCode: '230168' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANACHANALLUR', name: 'Madavaperumal Koil', lgdCode: '230163' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANACHANALLUR', name: 'Melpathu', lgdCode: '230164' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANACHANALLUR', name: 'Valaiyur', lgdCode: '230183' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANACHANALLUR', name: 'Vazhaiyur', lgdCode: '230184' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANACHANALLUR', name: 'Vengangudi', lgdCode: '230185' },
    { district: 'TIRUCHIRAPPALLI', block: 'MANACHANALLUR', name: 'No. 2 Kariyamanickam', lgdCode: '230165' },
    { district: 'TIRUCHIRAPPALLI', block: 'PULLAMPADY', name: 'Alambadi', lgdCode: '230311' },
    { district: 'TIRUCHIRAPPALLI', block: 'PULLAMPADY', name: 'Alambakkam', lgdCode: '230312' },
    { district: 'TIRUCHIRAPPALLI', block: 'PULLAMPADY', name: 'Garudamangalam', lgdCode: '230314' },
    { district: 'TIRUCHIRAPPALLI', block: 'PULLAMPADY', name: 'Kallagam', lgdCode: '230315' },
    { district: 'TIRUCHIRAPPALLI', block: 'PULLAMPADY', name: 'Kanakiliyanallur', lgdCode: '230316' },
    { district: 'TIRUCHIRAPPALLI', block: 'PULLAMPADY', name: 'Kannakudi', lgdCode: '230317' },
    { district: 'TIRUCHIRAPPALLI', block: 'PULLAMPADY', name: 'Keelarasur', lgdCode: '230318' },
    { district: 'TIRUCHIRAPPALLI', block: 'PULLAMPADY', name: 'Kovandakurichi', lgdCode: '230319' },
    { district: 'TIRUCHIRAPPALLI', block: 'PULLAMPADY', name: 'Kumulur', lgdCode: '230320' },
    { district: 'TIRUCHIRAPPALLI', block: 'PULLAMPADY', name: 'Melarasur', lgdCode: '230323' },
    { district: 'TIRUCHIRAPPALLI', block: 'PULLAMPADY', name: 'Malvai', lgdCode: '230322' },
    { district: 'TIRUCHIRAPPALLI', block: 'PULLAMPADY', name: 'M. Kannanur', lgdCode: '230321' },
    { district: 'TIRUCHIRAPPALLI', block: 'PULLAMPADY', name: 'Muduvathur', lgdCode: '230324' },
    { district: 'TIRUCHIRAPPALLI', block: 'PULLAMPADY', name: 'Nambukurichi', lgdCode: '230326' },
    { district: 'TIRUCHIRAPPALLI', block: 'PULLAMPADY', name: 'N. Sangenthi', lgdCode: '230325' },
    { district: 'TIRUCHIRAPPALLI', block: 'PULLAMPADY', name: 'Neikulam', lgdCode: '230327' },
    { district: 'TIRUCHIRAPPALLI', block: 'PULLAMPADY', name: 'Ootathur', lgdCode: '230328' },
    { district: 'TIRUCHIRAPPALLI', block: 'PULLAMPADY', name: 'Orathur', lgdCode: '230329' },
    { district: 'TIRUCHIRAPPALLI', block: 'PULLAMPADY', name: 'P. K. Agaram', lgdCode: '230330' },
    { district: 'TIRUCHIRAPPALLI', block: 'PULLAMPADY', name: 'Peruvalapur', lgdCode: '230332' },
    { district: 'TIRUCHIRAPPALLI', block: 'PULLAMPADY', name: 'Pudurpalayam', lgdCode: '230333' },
    { district: 'TIRUCHIRAPPALLI', block: 'PULLAMPADY', name: 'P. Sangenthi', lgdCode: '230331' },
    { district: 'TIRUCHIRAPPALLI', block: 'PULLAMPADY', name: 'Reddymangudi', lgdCode: '230334' },
    { district: 'TIRUCHIRAPPALLI', block: 'PULLAMPADY', name: 'Saradamangalam', lgdCode: '230335' },
    { district: 'TIRUCHIRAPPALLI', block: 'PULLAMPADY', name: 'Sirukalapur', lgdCode: '230336' },
    { district: 'TIRUCHIRAPPALLI', block: 'PULLAMPADY', name: 'Thinnakulam', lgdCode: '230338' },
    { district: 'TIRUCHIRAPPALLI', block: 'PULLAMPADY', name: 'Theranipalayam', lgdCode: '230339' },
    { district: 'TIRUCHIRAPPALLI', block: 'PULLAMPADY', name: 'Thappai', lgdCode: '230337' },
    { district: 'TIRUCHIRAPPALLI', block: 'PULLAMPADY', name: 'Vandalaikudalur', lgdCode: '230340' },
    { district: 'TIRUCHIRAPPALLI', block: 'PULLAMPADY', name: 'Varakuppai', lgdCode: '230341' },
    { district: 'TIRUCHIRAPPALLI', block: 'PULLAMPADY', name: 'E. Vellanur', lgdCode: '230313' },
    { district: 'TIRUCHIRAPPALLI', block: 'PULLAMPADY', name: 'Venkatachalapuram', lgdCode: '230342' },
    { district: 'TIRUCHIRAPPALLI', block: 'PULLAMPADY', name: 'Viragalur', lgdCode: '230343' },
    { district: 'TIRUCHIRAPPALLI', block: 'MUSIRI', name: 'Abinimangalam', lgdCode: '230278' },
    { district: 'TIRUCHIRAPPALLI', block: 'MUSIRI', name: 'Ayyampalayam', lgdCode: '230280' },
    { district: 'TIRUCHIRAPPALLI', block: 'MUSIRI', name: 'Amoor', lgdCode: '230279' },
    { district: 'TIRUCHIRAPPALLI', block: 'MUSIRI', name: 'Evoor', lgdCode: '230281' },
    { district: 'TIRUCHIRAPPALLI', block: 'MUSIRI', name: 'Karattampatti', lgdCode: '230285' },
    { district: 'TIRUCHIRAPPALLI', block: 'MUSIRI', name: 'Kattukulam', lgdCode: '230286' },
    { district: 'TIRUCHIRAPPALLI', block: 'MUSIRI', name: 'Kamatchipatti', lgdCode: '230284' },
    { district: 'TIRUCHIRAPPALLI', block: 'MUSIRI', name: 'Gunaseelam', lgdCode: '230282' },
    { district: 'TIRUCHIRAPPALLI', block: 'MUSIRI', name: 'Kodunthurai', lgdCode: '230287' },
    { district: 'TIRUCHIRAPPALLI', block: 'MUSIRI', name: 'Kottathur', lgdCode: '230289' },
    { district: 'TIRUCHIRAPPALLI', block: 'MUSIRI', name: 'Komangalam', lgdCode: '230288' },
    { district: 'TIRUCHIRAPPALLI', block: 'MUSIRI', name: 'Sithambur', lgdCode: '230299' },
    { district: 'TIRUCHIRAPPALLI', block: 'MUSIRI', name: 'Sukkampatti', lgdCode: '230300' },
    { district: 'TIRUCHIRAPPALLI', block: 'MUSIRI', name: 'Sevanthalingapuram', lgdCode: '230298' },
    { district: 'TIRUCHIRAPPALLI', block: 'MUSIRI', name: 'T. Puthur', lgdCode: '230302' },
    { district: 'TIRUCHIRAPPALLI', block: 'MUSIRI', name: 'Thinnanur', lgdCode: '230304' },
    { district: 'TIRUCHIRAPPALLI', block: 'MUSIRI', name: 'Thiruthalaiyur', lgdCode: '230305' },
    { district: 'TIRUCHIRAPPALLI', block: 'MUSIRI', name: 'Thiruthiyamalai', lgdCode: '230306' },
    { district: 'TIRUCHIRAPPALLI', block: 'MUSIRI', name: 'Thinnakonam', lgdCode: '230303' },
    { district: 'TIRUCHIRAPPALLI', block: 'MUSIRI', name: 'Neiveli', lgdCode: '230292' },
    { district: 'TIRUCHIRAPPALLI', block: 'MUSIRI', name: 'T. Pudupatti', lgdCode: '230301' },
    { district: 'TIRUCHIRAPPALLI', block: 'MUSIRI', name: 'Puthanampatti', lgdCode: '230296' },
    { district: 'TIRUCHIRAPPALLI', block: 'MUSIRI', name: 'Pulivalam', lgdCode: '230295' },
    { district: 'TIRUCHIRAPPALLI', block: 'MUSIRI', name: 'Peramangalam', lgdCode: '230293' },
    { district: 'TIRUCHIRAPPALLI', block: 'MUSIRI', name: 'Perur', lgdCode: '230294' },
    { district: 'TIRUCHIRAPPALLI', block: 'MUSIRI', name: 'Manbarai', lgdCode: '230290' },
    { district: 'TIRUCHIRAPPALLI', block: 'MUSIRI', name: 'Moovanur', lgdCode: '230291' },
    { district: 'TIRUCHIRAPPALLI', block: 'MUSIRI', name: 'Vellakkalpatti', lgdCode: '230308' },
    { district: 'TIRUCHIRAPPALLI', block: 'MUSIRI', name: 'Vellur', lgdCode: '230309' },
    { district: 'TIRUCHIRAPPALLI', block: 'MUSIRI', name: 'Vengaimandalam', lgdCode: '230310' },
    { district: 'TIRUCHIRAPPALLI', block: 'MUSIRI', name: 'Jayankondan', lgdCode: '230283' },
    { district: 'TIRUCHIRAPPALLI', block: 'MUSIRI', name: 'Veliyanur', lgdCode: '230307' },
    { district: 'TIRUCHIRAPPALLI', block: 'MUSIRI', name: 'Sathanur', lgdCode: '230297' },
    { district: 'TIRUCHIRAPPALLI', block: 'THOTTIAM', name: 'Arangoor', lgdCode: '230391' },
    { district: 'TIRUCHIRAPPALLI', block: 'THOTTIAM', name: 'Alagarai', lgdCode: '230389' },
    { district: 'TIRUCHIRAPPALLI', block: 'THOTTIAM', name: 'Appananallur', lgdCode: '230390' },
    { district: 'TIRUCHIRAPPALLI', block: 'THOTTIAM', name: 'Arasalur', lgdCode: '230392' },
    { district: 'TIRUCHIRAPPALLI', block: 'THOTTIAM', name: 'Chinnapallipalayam', lgdCode: '230393' },
    { district: 'TIRUCHIRAPPALLI', block: 'THOTTIAM', name: 'Elurpatti', lgdCode: '230394' },
    { district: 'TIRUCHIRAPPALLI', block: 'THOTTIAM', name: 'Kaduvetti', lgdCode: '230395' },
    { district: 'TIRUCHIRAPPALLI', block: 'THOTTIAM', name: 'Kamalapuram', lgdCode: '230396' },
    { district: 'TIRUCHIRAPPALLI', block: 'THOTTIAM', name: 'Kidaram', lgdCode: '230397' },
    { district: 'TIRUCHIRAPPALLI', block: 'THOTTIAM', name: 'Murungai', lgdCode: '230403' },
    { district: 'TIRUCHIRAPPALLI', block: 'THOTTIAM', name: 'Unniyur', lgdCode: '230413' },
    { district: 'TIRUCHIRAPPALLI', block: 'THOTTIAM', name: 'Periyapallipalayam', lgdCode: '230406' },
    { district: 'TIRUCHIRAPPALLI', block: 'THOTTIAM', name: 'Sriramasamudram', lgdCode: '230411' },
    { district: 'TIRUCHIRAPPALLI', block: 'THOTTIAM', name: 'Seelaipillaiyarputhur', lgdCode: '230408' },
    { district: 'TIRUCHIRAPPALLI', block: 'THOTTIAM', name: 'Seethapatti', lgdCode: '230409' },
    { district: 'TIRUCHIRAPPALLI', block: 'THOTTIAM', name: 'Pidaramangalam', lgdCode: '230407' },
    { district: 'TIRUCHIRAPPALLI', block: 'THOTTIAM', name: 'M-kalathur', lgdCode: '230399' },
    { district: 'TIRUCHIRAPPALLI', block: 'THOTTIAM', name: 'Valvelputhur', lgdCode: '230414' },
    { district: 'TIRUCHIRAPPALLI', block: 'THOTTIAM', name: 'Nagaiyanallur', lgdCode: '230404' },
    { district: 'TIRUCHIRAPPALLI', block: 'THOTTIAM', name: 'Natham', lgdCode: '230405' },
    { district: 'TIRUCHIRAPPALLI', block: 'THOTTIAM', name: 'M. Puthur', lgdCode: '230400' },
    { district: 'TIRUCHIRAPPALLI', block: 'THOTTIAM', name: 'Tholurpatti', lgdCode: '230412' },
    { district: 'TIRUCHIRAPPALLI', block: 'THOTTIAM', name: 'Srinivasanallur', lgdCode: '230410' },
    { district: 'TIRUCHIRAPPALLI', block: 'THOTTIAM', name: 'Manamedu', lgdCode: '230401' },
    { district: 'TIRUCHIRAPPALLI', block: 'THOTTIAM', name: 'Kolakkudi', lgdCode: '230398' },
    { district: 'TIRUCHIRAPPALLI', block: 'THOTTIAM', name: 'Mullipadi', lgdCode: '230402' },
    { district: 'TIRUCHIRAPPALLI', block: 'THANTHAIYANGARPET', name: 'Anjalam', lgdCode: '230344' },
    { district: 'TIRUCHIRAPPALLI', block: 'THANTHAIYANGARPET', name: 'Araichi', lgdCode: '230345' },
    { district: 'TIRUCHIRAPPALLI', block: 'THANTHAIYANGARPET', name: 'Devanoor', lgdCode: '230346' },
    { district: 'TIRUCHIRAPPALLI', block: 'THANTHAIYANGARPET', name: 'Jambumadai', lgdCode: '230347' },
    { district: 'TIRUCHIRAPPALLI', block: 'THANTHAIYANGARPET', name: 'Karugudi', lgdCode: '230349' },
    { district: 'TIRUCHIRAPPALLI', block: 'THANTHAIYANGARPET', name: 'Karigali', lgdCode: '230348' },
    { district: 'TIRUCHIRAPPALLI', block: 'THANTHAIYANGARPET', name: 'Konappampatti', lgdCode: '230350' },
    { district: 'TIRUCHIRAPPALLI', block: 'THANTHAIYANGARPET', name: 'Mahadevi', lgdCode: '230352' },
    { district: 'TIRUCHIRAPPALLI', block: 'THANTHAIYANGARPET', name: 'Mangalam', lgdCode: '230353' },
    { district: 'TIRUCHIRAPPALLI', block: 'THANTHAIYANGARPET', name: 'Mavilipatti', lgdCode: '230354' },
    { district: 'TIRUCHIRAPPALLI', block: 'THANTHAIYANGARPET', name: 'Muthampatti', lgdCode: '230355' },
    { district: 'TIRUCHIRAPPALLI', block: 'THANTHAIYANGARPET', name: 'M. Pudupatti', lgdCode: '230351' },
    { district: 'TIRUCHIRAPPALLI', block: 'THANTHAIYANGARPET', name: 'Paithamparai', lgdCode: '230358' },
    { district: 'TIRUCHIRAPPALLI', block: 'THANTHAIYANGARPET', name: 'Pillapalayam', lgdCode: '230359' },
    { district: 'TIRUCHIRAPPALLI', block: 'THANTHAIYANGARPET', name: 'Poolancheri', lgdCode: '230360' },
    { district: 'TIRUCHIRAPPALLI', block: 'THANTHAIYANGARPET', name: 'Serugudi', lgdCode: '230361' },
    { district: 'TIRUCHIRAPPALLI', block: 'THANTHAIYANGARPET', name: 'Sittilarai', lgdCode: '230362' },
    { district: 'TIRUCHIRAPPALLI', block: 'THANTHAIYANGARPET', name: 'Soorampatti', lgdCode: '230363' },
    { district: 'TIRUCHIRAPPALLI', block: 'THANTHAIYANGARPET', name: 'Thumbalam', lgdCode: '230365' },
    { district: 'TIRUCHIRAPPALLI', block: 'THANTHAIYANGARPET', name: 'Thulaiyanatham', lgdCode: '230364' },
    { district: 'TIRUCHIRAPPALLI', block: 'THANTHAIYANGARPET', name: 'Oorakkarai', lgdCode: '230356' },
    { district: 'TIRUCHIRAPPALLI', block: 'THANTHAIYANGARPET', name: 'Oorudaiyapatti', lgdCode: '230357' },
    { district: 'TIRUCHIRAPPALLI', block: 'THANTHAIYANGARPET', name: 'Valasiramani', lgdCode: '230367' },
    { district: 'TIRUCHIRAPPALLI', block: 'THANTHAIYANGARPET', name: 'Valaiyeduppu', lgdCode: '230366' },
    { district: 'TIRUCHIRAPPALLI', block: 'THANTHAIYANGARPET', name: 'Valavanthi', lgdCode: '230368' },
    { district: 'TIRUCHIRAPPALLI', block: 'THURAIYUR', name: 'Ammapatty', lgdCode: '230416' },
    { district: 'TIRUCHIRAPPALLI', block: 'THURAIYUR', name: 'Adhanur', lgdCode: '230415' },
    { district: 'TIRUCHIRAPPALLI', block: 'THURAIYUR', name: 'Kannanur', lgdCode: '230420' },
    { district: 'TIRUCHIRAPPALLI', block: 'THURAIYUR', name: 'Kalingamudayanpatty', lgdCode: '230419' },
    { district: 'TIRUCHIRAPPALLI', block: 'THURAIYUR', name: 'Keerambur', lgdCode: '230421' },
    { district: 'TIRUCHIRAPPALLI', block: 'THURAIYUR', name: 'Kunnupatty', lgdCode: '230425' },
    { district: 'TIRUCHIRAPPALLI', block: 'THURAIYUR', name: 'Kottaiyur', lgdCode: '230424' },
    { district: 'TIRUCHIRAPPALLI', block: 'THURAIYUR', name: 'Kollapatty', lgdCode: '230422' },
    { district: 'TIRUCHIRAPPALLI', block: 'THURAIYUR', name: 'Kombai', lgdCode: '230423' },
    { district: 'TIRUCHIRAPPALLI', block: 'THURAIYUR', name: 'Govindhapuram', lgdCode: '230417' },
    { district: 'TIRUCHIRAPPALLI', block: 'THURAIYUR', name: 'V. A. Samuthiram', lgdCode: '230443' },
    { district: 'TIRUCHIRAPPALLI', block: 'THURAIYUR', name: 'Sikkathambur', lgdCode: '230438' },
    { district: 'TIRUCHIRAPPALLI', block: 'THURAIYUR', name: 'Singalandhapuram', lgdCode: '230439' },
    { district: 'TIRUCHIRAPPALLI', block: 'THURAIYUR', name: 'Sellipalayam', lgdCode: '230436' },
    { district: 'TIRUCHIRAPPALLI', block: 'THURAIYUR', name: 'Senappanallur', lgdCode: '230437' },
    { district: 'TIRUCHIRAPPALLI', block: 'THURAIYUR', name: 'Chokkanadhapuram', lgdCode: '230440' },
    { district: 'TIRUCHIRAPPALLI', block: 'THURAIYUR', name: 'Sorathur', lgdCode: '230441' },
    { district: 'TIRUCHIRAPPALLI', block: 'THURAIYUR', name: 'Naduvalur', lgdCode: '230430' },
    { district: 'TIRUCHIRAPPALLI', block: 'THURAIYUR', name: 'Narasingapuram', lgdCode: '230432' },
    { district: 'TIRUCHIRAPPALLI', block: 'THURAIYUR', name: 'Nagalapuram', lgdCode: '230431' },
    { district: 'TIRUCHIRAPPALLI', block: 'THURAIYUR', name: 'Pagalavadi', lgdCode: '230433' },
    { district: 'TIRUCHIRAPPALLI', block: 'THURAIYUR', name: 'K. Palayam', lgdCode: '230418' },
    { district: 'TIRUCHIRAPPALLI', block: 'THURAIYUR', name: 'Perumalpalayam', lgdCode: '230434' },
    { district: 'TIRUCHIRAPPALLI', block: 'THURAIYUR', name: 'Ponnusangampatty', lgdCode: '230435' },
    { district: 'TIRUCHIRAPPALLI', block: 'THURAIYUR', name: 'Madurapuri', lgdCode: '230426' },
    { district: 'TIRUCHIRAPPALLI', block: 'THURAIYUR', name: 'Maruvathur', lgdCode: '230427' },
    { district: 'TIRUCHIRAPPALLI', block: 'THURAIYUR', name: 'Muthayampalayam', lgdCode: '230429' },
    { district: 'TIRUCHIRAPPALLI', block: 'THURAIYUR', name: 'Murugur', lgdCode: '230428' },
    { district: 'TIRUCHIRAPPALLI', block: 'THURAIYUR', name: 'T. Renganadhapuram', lgdCode: '230442' },
    { district: 'TIRUCHIRAPPALLI', block: 'THURAIYUR', name: 'Vannadu', lgdCode: '230444' },
    { district: 'TIRUCHIRAPPALLI', block: 'THURAIYUR', name: 'Varadharajapuram', lgdCode: '230445' },
    { district: 'TIRUCHIRAPPALLI', block: 'THURAIYUR', name: 'Veeramachanpatty', lgdCode: '230446' },
    { district: 'TIRUCHIRAPPALLI', block: 'THURAIYUR', name: 'Vengatesapuram', lgdCode: '230448' },
    { district: 'TIRUCHIRAPPALLI', block: 'THURAIYUR', name: 'Vengadathanur', lgdCode: '230447' },
    { district: 'TIRUCHIRAPPALLI', block: 'UPPILIYAPURAM', name: 'Alagapuri', lgdCode: '230449' },
    { district: 'TIRUCHIRAPPALLI', block: 'UPPILIYAPURAM', name: 'Ankiyam', lgdCode: '230451' },
    { district: 'TIRUCHIRAPPALLI', block: 'UPPILIYAPURAM', name: 'Alathudaiyanpatti', lgdCode: '230450' },
    { district: 'TIRUCHIRAPPALLI', block: 'UPPILIYAPURAM', name: 'Erakudi', lgdCode: '230453' },
    { district: 'TIRUCHIRAPPALLI', block: 'UPPILIYAPURAM', name: 'Okkarai', lgdCode: '230459' },
    { district: 'TIRUCHIRAPPALLI', block: 'UPPILIYAPURAM', name: 'Kamatchipuram', lgdCode: '230454' },
    { district: 'TIRUCHIRAPPALLI', block: 'UPPILIYAPURAM', name: 'Koppampatti', lgdCode: '230455' },
    { district: 'TIRUCHIRAPPALLI', block: 'UPPILIYAPURAM', name: 'Kottapalayam', lgdCode: '230456' },
    { district: 'TIRUCHIRAPPALLI', block: 'UPPILIYAPURAM', name: 'Sirunavalur', lgdCode: '230461' },
    { district: 'TIRUCHIRAPPALLI', block: 'UPPILIYAPURAM', name: 'Sobanapuram', lgdCode: '230462' },
    { district: 'TIRUCHIRAPPALLI', block: 'UPPILIYAPURAM', name: 'Thalugai', lgdCode: '230463' },
    { district: 'TIRUCHIRAPPALLI', block: 'UPPILIYAPURAM', name: 'Thenpuranadu', lgdCode: '230464' },
    { district: 'TIRUCHIRAPPALLI', block: 'UPPILIYAPURAM', name: 'Naganallur', lgdCode: '230458' },
    { district: 'TIRUCHIRAPPALLI', block: 'UPPILIYAPURAM', name: 'Maradi', lgdCode: '230457' },
    { district: 'TIRUCHIRAPPALLI', block: 'UPPILIYAPURAM', name: 'E.Bhadarpettai', lgdCode: '230452' },
    { district: 'TIRUCHIRAPPALLI', block: 'UPPILIYAPURAM', name: 'Pachaperumalpatti', lgdCode: '230460' },
    { district: 'TIRUCHIRAPPALLI', block: 'UPPILIYAPURAM', name: 'Venkatachalapuram', lgdCode: '230466' },
    { district: 'TIRUCHIRAPPALLI', block: 'UPPILIYAPURAM', name: 'Vairichettipalayam', lgdCode: '230465' },
];

  