
import type { Panchayat } from './types';

export const TIRUVANNAMALAI_PANCHAYATS: Panchayat[] = [
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Adaiyur', lgdCode: '231539' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Adiannamalai', lgdCode: '231540' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Alaganandal', lgdCode: '231541' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Allikondapattu', lgdCode: '231542' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Anaipirandan', lgdCode: '231543' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Ananandal', lgdCode: '231544' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Andampallam', lgdCode: '231545' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Aradapattu', lgdCode: '231546' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Arudirapattu', lgdCode: '231547' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Athiyandal', lgdCode: '231548' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Ayyampalayam', lgdCode: '231549' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Chinnakallapadi', lgdCode: '231550' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Chinnakangiyanur', lgdCode: '231551' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Devanandal', lgdCode: '231552' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Devanur', lgdCode: '231553' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Endal', lgdCode: '231554' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Isukalikatteri', lgdCode: '231555' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Kalleri', lgdCode: '231557' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Kadagaman', lgdCode: '231556' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Kallottu', lgdCode: '231558' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Kannapandal', lgdCode: '231561' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Kandiyangkuppam', lgdCode: '231559' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Kanandampoondi', lgdCode: '231560' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Kattampoondi', lgdCode: '231562' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Kilchettipattu', lgdCode: '231563' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Kilkachirapattu', lgdCode: '231564' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Kilkaripur', lgdCode: '231565' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Kolakudi', lgdCode: '231566' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Madurampattu', lgdCode: '231567' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Malappambadi', lgdCode: '231568' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Melathikkan', lgdCode: '231569' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Melchettipattu', lgdCode: '231570' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Melkachirapattu', lgdCode: '231571' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Meyyur', lgdCode: '231572' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Nachanandal', lgdCode: '231573' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Nadupattu', lgdCode: '231574' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Nallanpillaipetral', lgdCode: '231575' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Nallavanpalayam', lgdCode: '231576' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Naraiyur', lgdCode: '231577' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Nariyapattu', lgdCode: '231578' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Navampattu', lgdCode: '231579' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Nochimalai', lgdCode: '231580' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Palayanur', lgdCode: '231581' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Pandithapattu', lgdCode: '231583' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Panaiyur', lgdCode: '231582' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Parayampattu', lgdCode: '231584' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Pavithram', lgdCode: '231585' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Pavupattu', lgdCode: '231586' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Periyakallapadi', lgdCode: '231587' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Perumanam', lgdCode: '231588' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Savalpoondi', lgdCode: '231589' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'So kilnachipattu', lgdCode: '231590' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Su andapattu', lgdCode: '231591' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Su kambupattu', lgdCode: '231592' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Su nallur', lgdCode: '231593' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Su pappambadi', lgdCode: '231594' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Su valavetti', lgdCode: '231595' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Thatchampattu', lgdCode: '231600' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Thalayampallam', lgdCode: '231598' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Thandarai', lgdCode: '231599' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Thenmathur', lgdCode: '231601' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'T valasai', lgdCode: '231596' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'T valavetti', lgdCode: '231597' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Udayandal', lgdCode: '231602' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Velaiyambakkam', lgdCode: '231603' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Vengikkal', lgdCode: '231604' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Veraiyur', lgdCode: '231605' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Viruduvilanginan', lgdCode: '231606' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Viswanthangal', lgdCode: '231607' }
];
