
import type { Panchayat } from './types';

export const TIRUVANNAMALAI_PANCHAYATS: Panchayat[] = [
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Adaiyur', lgdCode: '231539' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Adiannamalai', lgdCode: '231540' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Alaganandal', lgdCode: '231541' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Allikondapattu', lgdCode: '231542' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Anaipirandan', lgdCode: '231543' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Ananandal', lgdCode: '231544' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Andampallam', lgdCode: '231545' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Aradapattu', lgdCode: '231546' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Arudirapattu', lgdCode: '231547' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Athiyandal', lgdCode: '231548' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Ayyampalayam', lgdCode: '231549' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Chinnakallapadi', lgdCode: '231550' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Chinnakangiyanur', lgdCode: '231551' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Devanandal', lgdCode: '231552' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Devanur', lgdCode: '231553' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Endal', lgdCode: '231554' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Isukalikatteri', lgdCode: '231555' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Kalleri', lgdCode: '231557' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Kadagaman', lgdCode: '231556' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Kallottu', lgdCode: '231558' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Kannapandal', lgdCode: '231561' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Kandiyangkuppam', lgdCode: '231559' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Kanandampoondi', lgdCode: '231560' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Kattampoondi', lgdCode: '231562' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Kilchettipattu', lgdCode: '231563' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Kilkachirapattu', lgdCode: '231564' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Kilkaripur', lgdCode: '231565' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Kolakudi', lgdCode: '231566' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Madurampattu', lgdCode: '231567' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Malappambadi', lgdCode: '231568' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Melathikkan', lgdCode: '231569' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Melchettipattu', lgdCode: '231570' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Melkachirapattu', lgdCode: '231571' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Meyyur', lgdCode: '231572' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Nachanandal', lgdCode: '231573' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Nadupattu', lgdCode: '231574' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Nallanpillaipetral', lgdCode: '231575' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Nallavanpalayam', lgdCode: '231576' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Naraiyur', lgdCode: '231577' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Nariyapattu', lgdCode: '231578' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Navampattu', lgdCode: '231579' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Nochimalai', lgdCode: '231580' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Palayanur', lgdCode: '231581' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Pandithapattu', lgdCode: '231583' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Panaiyur', lgdCode: '231582' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Parayampattu', lgdCode: '231584' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Pavithram', lgdCode: '231585' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Pavupattu', lgdCode: '231586' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Periyakallapadi', lgdCode: '231587' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Perumanam', lgdCode: '231588' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Savalpoondi', lgdCode: '231589' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'So kilnachipattu', lgdCode: '231590' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Su andapattu', lgdCode: '231591' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Su kambupattu', lgdCode: '231592' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Su nallur', lgdCode: '231593' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Su pappambadi', lgdCode: '231594' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Su valavetti', lgdCode: '231595' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Thatchampattu', lgdCode: '231600' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Thalayampallam', lgdCode: '231598' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Thandarai', lgdCode: '231599' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Thenmathur', lgdCode: '231601' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'T valasai', lgdCode: '231596' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'T valavetti', lgdCode: '231597' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Udayandal', lgdCode: '231602' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Velaiyambakkam', lgdCode: '231603' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Vengikkal', lgdCode: '231604' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Veraiyur', lgdCode: '231605' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Viruduvilanginan', lgdCode: '231606' },
    { district: 'TIRUVANNAMALAI', block: 'TIRUVANNAMALAI', name: 'Viswanthangal', lgdCode: '231607' },
    { district: 'TIRUVANNAMALAI', block: 'KILPENNATHUR', name: 'Agaram', lgdCode: '231205' },
    { district: 'TIRUVANNAMALAI', block: 'KILPENNATHUR', name: 'Angunam', lgdCode: '231206' },
    { district: 'TIRUVANNAMALAI', block: 'KILPENNATHUR', name: 'Aranji', lgdCode: '231208' },
    { district: 'TIRUVANNAMALAI', block: 'KILPENNATHUR', name: 'Arumbakkam', lgdCode: '231209' },
    { district: 'TIRUVANNAMALAI', block: 'KILPENNATHUR', name: 'Anukkumalai', lgdCode: '231207' },
    { district: 'TIRUVANNAMALAI', block: 'KILPENNATHUR', name: 'Avoor', lgdCode: '231210' },
    { district: 'TIRUVANNAMALAI', block: 'KILPENNATHUR', name: 'Chellankuppam', lgdCode: '231211' },
    { district: 'TIRUVANNAMALAI', block: 'KILPENNATHUR', name: 'Ganapapuram', lgdCode: '231213' },
    { district: 'TIRUVANNAMALAI', block: 'KILPENNATHUR', name: 'Ganalapadi', lgdCode: '231212' },
    { district: 'TIRUVANNAMALAI', block: 'KILPENNATHUR', name: 'Na gengapattu', lgdCode: '231230' },
    { district: 'TIRUVANNAMALAI', block: 'KILPENNATHUR', name: 'Zamin Gudalur', lgdCode: '231214' },
    { district: 'TIRUVANNAMALAI', block: 'KILPENNATHUR', name: 'Iyangunam', lgdCode: '231215' },
    { district: 'TIRUVANNAMALAI', block: 'KILPENNATHUR', name: 'Kadambai', lgdCode: '231216' },
    { district: 'TIRUVANNAMALAI', block: 'KILPENNATHUR', name: 'Kalingaleri', lgdCode: '231217' },
    { district: 'TIRUVANNAMALAI', block: 'KILPENNATHUR', name: 'Kallayee', lgdCode: '231218' },
    { district: 'TIRUVANNAMALAI', block: 'KILPENNATHUR', name: 'Kalpoondi', lgdCode: '231219' },
    { district: 'TIRUVANNAMALAI', block: 'KILPENNATHUR', name: 'Kaniyampoondi', lgdCode: '231220' },
    { district: 'TIRUVANNAMALAI', block: 'KILPENNATHUR', name: 'Karikalampadi', lgdCode: '231221' },
    { district: 'TIRUVANNAMALAI', block: 'KILPENNATHUR', name: 'Kathalampattu', lgdCode: '231222' },
    { district: 'TIRUVANNAMALAI', block: 'KILPENNATHUR', name: 'Kattumalaiyanur', lgdCode: '231223' },
    { district: 'TIRUVANNAMALAI', block: 'KILPENNATHUR', name: 'Kazhikulam', lgdCode: '231224' },
    { district: 'TIRUVANNAMALAI', block: 'KILPENNATHUR', name: 'Keekalur', lgdCode: '231225' },
    { district: 'TIRUVANNAMALAI', block: 'KILPENNATHUR', name: 'Keeranur', lgdCode: '231226' },
    { district: 'TIRUVANNAMALAI', block: 'KILPENNATHUR', name: 'Konalur', lgdCode: '231228' },
    { district: 'TIRUVANNAMALAI', block: 'KILPENNATHUR', name: 'Kolathur', lgdCode: '231227' },
    { district: 'TIRUVANNAMALAI', block: 'KILPENNATHUR', name: 'Mekkalur', lgdCode: '231229' },
    { district: 'TIRUVANNAMALAI', block: 'KILPENNATHUR', name: 'Nadalaganadal', lgdCode: '231231' },
    { district: 'TIRUVANNAMALAI', block: 'KILPENNATHUR', name: 'So namiyandal', lgdCode: '231242' },
    { district: 'TIRUVANNAMALAI', block: 'KILPENNATHUR', name: 'Nariyamangalam', lgdCode: '231232' },
    { district: 'TIRUVANNAMALAI', block: 'KILPENNATHUR', name: 'Neivanatham', lgdCode: '231234' },
    { district: 'TIRUVANNAMALAI', block: 'KILPENNATHUR', name: 'Neelanthangal', lgdCode: '231233' },
    { district: 'TIRUVANNAMALAI', block: 'KILPENNATHUR', name: 'Olaipadi', lgdCode: '231235' },
    { district: 'TIRUVANNAMALAI', block: 'KILPENNATHUR', name: 'Panniyur', lgdCode: '231236' },
    { district: 'TIRUVANNAMALAI', block: 'KILPENNATHUR', name: 'Su polakunam', lgdCode: '231244' },
    { district: 'TIRUVANNAMALAI', block: 'KILPENNATHUR', name: 'Rajanthangal', lgdCode: '231237' },
    { district: 'TIRUVANNAMALAI', block: 'KILPENNATHUR', name: 'Rayampettai', lgdCode: '231238' },
    { district: 'TIRUVANNAMALAI', block: 'KILPENNATHUR', name: 'Sanipoondi', lgdCode: '231239' },
    { district: 'TIRUVANNAMALAI', block: 'KILPENNATHUR', name: 'Sevarapoondi', lgdCode: '231240' },
    { district: 'TIRUVANNAMALAI', block: 'KILPENNATHUR', name: 'Sirunathur', lgdCode: '231241' },
    { district: 'TIRUVANNAMALAI', block: 'KILPENNATHUR', name: 'Somasipadi', lgdCode: '231243' },
    { district: 'TIRUVANNAMALAI', block: 'KILPENNATHUR', name: 'Vaipur', lgdCode: '231245' },
    { district: 'TIRUVANNAMALAI', block: 'KILPENNATHUR', name: 'Valudalangunam', lgdCode: '231246' },
    { district: 'TIRUVANNAMALAI', block: 'KILPENNATHUR', name: 'Vedanatham', lgdCode: '231248' },
    { district: 'TIRUVANNAMALAI', block: 'KILPENNATHUR', name: 'Vayalur', lgdCode: '231247' },
    { district: 'TIRUVANNAMALAI', block: 'KILPENNATHUR', name: 'Velanandal', lgdCode: '231249' },
    { district: 'TIRUVANNAMALAI', block: 'THURINJAPURAM', name: 'Arppakkam', lgdCode: '231492' },
    { district: 'TIRUVANNAMALAI', block: 'THURINJAPURAM', name: 'Boodamangalam', lgdCode: '231493' },
    { district: 'TIRUVANNAMALAI', block: 'THURINJAPURAM', name: 'Devanampattu', lgdCode: '231494' },
    { district: 'TIRUVANNAMALAI', block: 'THURINJAPURAM', name: 'Durgainammiyandal', lgdCode: '231495' },
    { district: 'TIRUVANNAMALAI', block: 'THURINJAPURAM', name: 'Erumpoondi', lgdCode: '231496' },
    { district: 'TIRUVANNAMALAI', block: 'THURINJAPURAM', name: 'Inamkariyandal', lgdCode: '231497' },
    { district: 'TIRUVANNAMALAI', block: 'THURINJAPURAM', name: 'Kalasthambadi', lgdCode: '231498' },
    { district: 'TIRUVANNAMALAI', block: 'THURINJAPURAM', name: 'Kamalaputhur', lgdCode: '231499' },
    { district: 'TIRUVANNAMALAI', block: 'THURINJAPURAM', name: 'Karkonam', lgdCode: '231501' },
    { district: 'TIRUVANNAMALAI', block: 'THURINJAPURAM', name: 'Kariyandal', lgdCode: '231500' },
    { district: 'TIRUVANNAMALAI', block: 'THURINJAPURAM', name: 'Karumarapatti', lgdCode: '231502' },
    { district: 'TIRUVANNAMALAI', block: 'THURINJAPURAM', name: 'Karunthuvambadi', lgdCode: '231503' },
    { district: 'TIRUVANNAMALAI', block: 'THURINJAPURAM', name: 'Kiliyapattu', lgdCode: '231504' },
    { district: 'TIRUVANNAMALAI', block: 'THURINJAPURAM', name: 'Kolakkaravadi', lgdCode: '231505' },
    { district: 'TIRUVANNAMALAI', block: 'THURINJAPURAM', name: 'Kothanthavadi', lgdCode: '231506' },
    { district: 'TIRUVANNAMALAI', block: 'THURINJAPURAM', name: 'Kovur', lgdCode: '231507' },
    { district: 'TIRUVANNAMALAI', block: 'THURINJAPURAM', name: 'Kunniyandal', lgdCode: '231508' },
    { district: 'TIRUVANNAMALAI', block: 'THURINJAPURAM', name: 'Madalampadi', lgdCode: '231510' },
    { district: 'TIRUVANNAMALAI', block: 'THURINJAPURAM', name: 'Mallavadi', lgdCode: '231511' },
    { district: 'TIRUVANNAMALAI', block: 'THURINJAPURAM', name: 'M  N  Palayam', lgdCode: '231509' },
    { district: 'TIRUVANNAMALAI', block: 'THURINJAPURAM', name: 'Mangalam', lgdCode: '231512' },
    { district: 'TIRUVANNAMALAI', block: 'THURINJAPURAM', name: 'Maruthuvambadi', lgdCode: '231513' },
    { district: 'TIRUVANNAMALAI', block: 'THURINJAPURAM', name: 'Meppathurai', lgdCode: '231514' },
    { district: 'TIRUVANNAMALAI', block: 'THURINJAPURAM', name: 'Mutharasampoondi', lgdCode: '231515' },
    { district: 'TIRUVANNAMALAI', block: 'THURINJAPURAM', name: 'Naidumangalam', lgdCode: '231516' },
    { district: 'TIRUVANNAMALAI', block: 'THURINJAPURAM', name: 'Nookkambadi', lgdCode: '231517' },
    { district: 'TIRUVANNAMALAI', block: 'THURINJAPURAM', name: 'Northampoondi', lgdCode: '231518' },
    { district: 'TIRUVANNAMALAI', block: 'THURINJAPURAM', name: 'Palanandal', lgdCode: '231519' },
    { district: 'TIRUVANNAMALAI', block: 'THURINJAPURAM', name: 'Periyakilambadi', lgdCode: '231520' },
    { district: 'TIRUVANNAMALAI', block: 'THURINJAPURAM', name: 'Porkunam', lgdCode: '231521' },
    { district: 'TIRUVANNAMALAI', block: 'THURINJAPURAM', name: 'Pudumallavadi', lgdCode: '231522' },
    { district: 'TIRUVANNAMALAI', block: 'THURINJAPURAM', name: 'Randam', lgdCode: '231523' },
    { district: 'TIRUVANNAMALAI', block: 'THURINJAPURAM', name: 'Sadayanodai', lgdCode: '231524' },
    { district: 'TIRUVANNAMALAI', block: 'THURINJAPURAM', name: 'Salaiyanur', lgdCode: '231525' },
    { district: 'TIRUVANNAMALAI', block: 'THURINJAPURAM', name: 'Sananandal', lgdCode: '231526' },
    { district: 'TIRUVANNAMALAI', block: 'THURINJAPURAM', name: 'Seelappandal', lgdCode: '231527' },
    { district: 'TIRUVANNAMALAI', block: 'THURINJAPURAM', name: 'Sorakulathur', lgdCode: '231528' },
    { district: 'TIRUVANNAMALAI', block: 'THURINJAPURAM', name: 'Thurinjapuram', lgdCode: '231529' },
    { district: 'TIRUVANNAMALAI', block: 'THURINJAPURAM', name: 'Usampadi', lgdCode: '231530' },
    { district: 'TIRUVANNAMALAI', block: 'THURINJAPURAM', name: 'Uthirampoondi', lgdCode: '231531' },
    { district: 'TIRUVANNAMALAI', block: 'THURINJAPURAM', name: 'Vadaandapattu', lgdCode: '231534' },
    { district: 'TIRUVANNAMALAI', block: 'THURINJAPURAM', name: 'Vadakarumbalore', lgdCode: '231532' },
    { district: 'TIRUVANNAMALAI', block: 'THURINJAPURAM', name: 'Vadakaringalipadi', lgdCode: '231533' },
    { district: 'TIRUVANNAMALAI', block: 'THURINJAPURAM', name: 'Vadapuzudiyur', lgdCode: '231535' },
    { district: 'TIRUVANNAMALAI', block: 'THURINJAPURAM', name: 'Vallivagai', lgdCode: '231536' },
    { district: 'TIRUVANNAMALAI', block: 'THURINJAPURAM', name: 'Vedandavadi', lgdCode: '231537' },
    { district: 'TIRUVANNAMALAI', block: 'THURINJAPURAM', name: 'Veluganandal', lgdCode: '231538' }
];
