import type { Panchayat } from './types';

export const VELLORE_PANCHAYATS: Panchayat[] = [
    { district: 'VELLORE', block: 'VELLORE', name: 'Abdullapuram', lgdCode: '232862' },
    { district: 'VELLORE', block: 'VELLORE', name: 'Anpoondi', lgdCode: '232863' },
    { district: 'VELLORE', block: 'VELLORE', name: 'Athiyur', lgdCode: '232864' },
    { district: 'VELLORE', block: 'VELLORE', name: 'Budur', lgdCode: '232865' },
    { district: 'VELLORE', block: 'VELLORE', name: 'Karugambathur', lgdCode: '232866' },
    { district: 'VELLORE', block: 'VELLORE', name: 'Kilmonavoor', lgdCode: '232867' },
    { district: 'VELLORE', block: 'VELLORE', name: 'Kuppam', lgdCode: '232868' },
    { district: 'VELLORE', block: 'VELLORE', name: 'Melmonavoor', lgdCode: '232869' },
    { district: 'VELLORE', block: 'VELLORE', name: 'Palamathi', lgdCode: '232870' },
    { district: 'VELLORE', block: 'VELLORE', name: 'Perumugai', lgdCode: '232871' },
    { district: 'VELLORE', block: 'VELLORE', name: 'Pulimedu', lgdCode: '232872' },
    { district: 'VELLORE', block: 'VELLORE', name: 'Saduperi', lgdCode: '232873' },
    { district: 'VELLORE', block: 'VELLORE', name: 'Sekkanur', lgdCode: '232874' },
    { district: 'VELLORE', block: 'VELLORE', name: 'Sembedu', lgdCode: '232875' },
    { district: 'VELLORE', block: 'VELLORE', name: 'Sirukanchi', lgdCode: '232876' },
    { district: 'VELLORE', block: 'VELLORE', name: 'Thellur', lgdCode: '232877' },
    { district: 'VELLORE', block: 'VELLORE', name: 'Ussoor', lgdCode: '232878' },
    { district: 'VELLORE', block: 'VELLORE', name: 'Venkatapuram', lgdCode: '232879' },
    { district: 'VELLORE', block: 'KANIYAMBADI', name: 'Adukkamparai', lgdCode: '232463' },
    { district: 'VELLORE', block: 'KANIYAMBADI', name: 'Kammasamudiram', lgdCode: '232464' },
    { district: 'VELLORE', block: 'KANIYAMBADI', name: 'Kammavanpettai', lgdCode: '232465' },
    { district: 'VELLORE', block: 'KANIYAMBADI', name: 'Kanikaniyan', lgdCode: '232466' },
    { district: 'VELLORE', block: 'KANIYAMBADI', name: 'Kaniyambadi', lgdCode: '232467' },
    { district: 'VELLORE', block: 'KANIYAMBADI', name: 'Kathalampet', lgdCode: '232468' },
    { district: 'VELLORE', block: 'KANIYAMBADI', name: 'Kattuputhur', lgdCode: '232469' },
    { district: 'VELLORE', block: 'KANIYAMBADI', name: 'Kilarasampet', lgdCode: '232470' },
    { district: 'VELLORE', block: 'KANIYAMBADI', name: 'Kilpallipattu', lgdCode: '232471' },
    { district: 'VELLORE', block: 'KANIYAMBADI', name: 'Mothakkal', lgdCode: '232472' },
    { district: 'VELLORE', block: 'KANIYAMBADI', name: 'Mottupalayam', lgdCode: '232473' },
    { district: 'VELLORE', block: 'KANIYAMBADI', name: 'Munjurpattu', lgdCode: '232474' },
    { district: 'VELLORE', block: 'KANIYAMBADI', name: 'Nanjukondapuram', lgdCode: '232475' },
    { district: 'VELLORE', block: 'KANIYAMBADI', name: 'Nelvoy', lgdCode: '232476' },
    { district: 'VELLORE', block: 'KANIYAMBADI', name: 'Palampakkam', lgdCode: '232477' },
    { district: 'VELLORE', block: 'KANIYAMBADI', name: 'Palathuvannan', lgdCode: '232478' },
    { district: 'VELLORE', block: 'KANIYAMBADI', name: 'Salamanatham', lgdCode: '232479' },
    { district: 'VELLORE', block: 'KANIYAMBADI', name: 'Sathumadurai', lgdCode: '232480' },
    { district: 'VELLORE', block: 'KANIYAMBADI', name: 'Sathupalayam', lgdCode: '232481' },
    { district: 'VELLORE', block: 'KANIYAMBADI', name: 'Sholavaram', lgdCode: '232482' },
    { district: 'VELLORE', block: 'KANIYAMBADI', name: 'Thuthikadu', lgdCode: '232483' },
    { district: 'VELLORE', block: 'KANIYAMBADI', name: 'Thuthipet', lgdCode: '232484' },
    { district: 'VELLORE', block: 'KANIYAMBADI', name: 'Vallam', lgdCode: '232485' },
    { district: 'VELLORE', block: 'KANIYAMBADI', name: 'Veppambut', lgdCode: '232486' },
    { district: 'VELLORE', block: 'ANAICUT', name: 'Anaicut', lgdCode: '232202' },
    { district: 'VELLORE', block: 'ANAICUT', name: 'Appukkal', lgdCode: '232203' },
    { district: 'VELLORE', block: 'ANAICUT', name: 'Athikuppam', lgdCode: '232204' },
    { district: 'VELLORE', block: 'ANAICUT', name: 'Bramanamangalam', lgdCode: '232205' },
    { district: 'VELLORE', block: 'ANAICUT', name: 'Devichettikuppam', lgdCode: '232206' },
    { district: 'VELLORE', block: 'ANAICUT', name: 'Elavambadi', lgdCode: '232207' },
    { district: 'VELLORE', block: 'ANAICUT', name: 'Eraivangadu', lgdCode: '232208' },
    { district: 'VELLORE', block: 'ANAICUT', name: 'Genganallure', lgdCode: '232209' },
    { district: 'VELLORE', block: 'ANAICUT', name: 'Jarthanakollai', lgdCode: '232210' },
    { district: 'VELLORE', block: 'ANAICUT', name: 'Kalanipakkam', lgdCode: '232211' },
    { district: 'VELLORE', block: 'ANAICUT', name: 'Kandaneri', lgdCode: '232212' },
    { district: 'VELLORE', block: 'ANAICUT', name: 'Karadikudi', lgdCode: '232213' },
    { district: 'VELLORE', block: 'ANAICUT', name: 'Karungali', lgdCode: '232214' },
    { district: 'VELLORE', block: 'ANAICUT', name: 'Kilkothur', lgdCode: '232215' },
    { district: 'VELLORE', block: 'ANAICUT', name: 'Kilkrishnapuram', lgdCode: '232216' },
    { district: 'VELLORE', block: 'ANAICUT', name: 'Madayapattu', lgdCode: '232217' },
    { district: 'VELLORE', block: 'ANAICUT', name: 'Mohamadupuram', lgdCode: '232220' },
    { district: 'VELLORE', block: 'ANAICUT', name: 'Maruthavallipalayam', lgdCode: '232218' },
    { district: 'VELLORE', block: 'ANAICUT', name: 'Melarasampattu', lgdCode: '232219' },
    { district: 'VELLORE', block: 'ANAICUT', name: 'Nemandapuram', lgdCode: '232221' },
    { district: 'VELLORE', block: 'ANAICUT', name: 'Othiyathur', lgdCode: '232223' },
    { district: 'VELLORE', block: 'ANAICUT', name: 'Ongapadi', lgdCode: '232222' },
    { district: 'VELLORE', block: 'ANAICUT', name: 'Palambattu', lgdCode: '232224' },
    { district: 'VELLORE', block: 'ANAICUT', name: 'Peenjamandhai', lgdCode: '232225' },
    { district: 'VELLORE', block: 'ANAICUT', name: 'Pinnathurai', lgdCode: '232226' },
    { district: 'VELLORE', block: 'ANAICUT', name: 'Poigai', lgdCode: '232227' },
    { district: 'VELLORE', block: 'ANAICUT', name: 'Puthur', lgdCode: '232228' },
    { district: 'VELLORE', block: 'ANAICUT', name: 'Sathiyamangalam', lgdCode: '232229' },
    { district: 'VELLORE', block: 'ANAICUT', name: 'Seduvalai', lgdCode: '232230' },
    { district: 'VELLORE', block: 'ANAICUT', name: 'Serpadi', lgdCode: '232231' },
    { district: 'VELLORE', block: 'ANAICUT', name: 'Tippasamudram', lgdCode: '232232' },
    { district: 'VELLORE', block: 'ANAICUT', name: 'Unai', lgdCode: '232233' },
    { district: 'VELLORE', block: 'ANAICUT', name: 'Vallandaramam', lgdCode: '232235' },
    { district: 'VELLORE', block: 'ANAICUT', name: 'Unaivaniyambadi', lgdCode: '232234' },
    { district: 'VELLORE', block: 'ANAICUT', name: 'Vannanthangal', lgdCode: '232236' },
    { district: 'VELLORE', block: 'ANAICUT', name: 'Varadalambut', lgdCode: '232237' },
    { district: 'VELLORE', block: 'ANAICUT', name: 'Vasanthanadai', lgdCode: '232238' },
    { district: 'VELLORE', block: 'ANAICUT', name: 'Virinchipuram', lgdCode: '232239' },
    { district: 'VELLORE', block: 'ANAICUT', name: 'AGARAM', lgdCode: '232563' },
    { district: 'VELLORE', block: 'ANAICUT', name: 'AGRAHARAM', lgdCode: '232305' },
    { district: 'VELLORE', block: 'ANAICUT', name: 'ARIMALAI', lgdCode: '232567' },
    { district: 'VELLORE', block: 'ANAICUT', name: 'ASANAMPET', lgdCode: '232568' },
    { district: 'VELLORE', block: 'ANAICUT', name: 'CHINNAPALLIKUPPAM', lgdCode: '232571' },
    { district: 'VELLORE', block: 'ANAICUT', name: 'GURUVARAJAPALAYAM', lgdCode: '232573' },
    { district: 'VELLORE', block: 'ANAICUT', name: 'KUPPAMPATTU', lgdCode: '232579' },
    { district: 'VELLORE', block: 'ANAICUT', name: 'KUPPAMAPALAYAM', lgdCode: '232578' },
    { district: 'VELLORE', block: 'ANAICUT', name: 'MELPALLIPET', lgdCode: '232581' },
    { district: 'VELLORE', block: 'ANAICUT', name: 'PAKKAMPALAYAM', lgdCode: '232585' },
    { district: 'VELLORE', block: 'ANAICUT', name: 'RAMANAYANIKUPPAM', lgdCode: '232589' },
    { district: 'VELLORE', block: 'ANAICUT', name: 'THOLAPALLI', lgdCode: '232592' },
    { district: 'VELLORE', block: 'ANAICUT', name: 'VEPPANKUPPAM', lgdCode: '232597' },
    { district: 'VELLORE', block: 'KATPADI', name: 'AMMUNDI', lgdCode: '232487' },
    { district: 'VELLORE', block: 'KATPADI', name: 'ARIMUTHUMOTTUR', lgdCode: '232488' },
    { district: 'VELLORE', block: 'KATPADI', name: 'ARUMPARUTHI', lgdCode: '232489' },
    { district: 'VELLORE', block: 'KATPADI', name: 'BRAMMAPURAM', lgdCode: '232490' },
    { district: 'VELLORE', block: 'KATPADI', name: 'ERANTHANGAL', lgdCode: '232491' },
    { district: 'VELLORE', block: 'KATPADI', name: 'JAFFRAPET', lgdCode: '232492' },
    { district: 'VELLORE', block: 'KATPADI', name: 'KANDIPEDU', lgdCode: '232493' },
    { district: 'VELLORE', block: 'KATPADI', name: 'KARASAMANGALAM', lgdCode: '232494' },
    { district: 'VELLORE', block: 'KATPADI', name: 'KARIGIRI', lgdCode: '232495' },
    { district: 'VELLORE', block: 'KATPADI', name: 'KARNAMBUT', lgdCode: '232496' },
    { district: 'VELLORE', block: 'KATPADI', name: 'KUGAIYANALLORE', lgdCode: '254902' },
    { district: 'VELLORE', block: 'KATPADI', name: 'KUPPATHAMOTTUR', lgdCode: '232498' },
    { district: 'VELLORE', block: 'KATPADI', name: 'METTUKULAM', lgdCode: '232499' },
    { district: 'VELLORE', block: 'KATPADI', name: 'PUTHUR', lgdCode: '232500' },
    { district: 'VELLORE', block: 'KATPADI', name: 'SEMBARAYANALLORE', lgdCode: '232501' },
    { district: 'VELLORE', block: 'KATPADI', name: 'SENUR', lgdCode: '232502' },
    { district: 'VELLORE', block: 'KATPADI', name: 'SERKADU', lgdCode: '232503' },
    { district: 'VELLORE', block: 'KATPADI', name: 'SEVOOR', lgdCode: '232504' },
    { district: 'VELLORE', block: 'KATPADI', name: 'T.K.PURAM', lgdCode: '232505' },
    { district: 'VELLORE', block: 'KATPADI', name: 'VANDRANTHANGAL', lgdCode: '232506' },
    { district: 'VELLORE', block: 'KATPADI', name: 'VANJUR', lgdCode: '232507' },
    { district: 'VELLORE', block: 'KATPADI', name: 'AMMAVARIPALLI', lgdCode: '232728' },
    { district: 'VELLORE', block: 'KATPADI', name: 'AVULARANGAPALLI', lgdCode: '232729' },
    { district: 'VELLORE', block: 'KATPADI', name: 'BALEKUPPAM', lgdCode: '232730' },
    { district: 'VELLORE', block: 'KATPADI', name: 'ELAYANELLORE', lgdCode: '232731' },
    { district: 'VELLORE', block: 'KATPADI', name: 'ERRUKKAMPATTU', lgdCode: '232732' },
    { district: 'VELLORE', block: 'KATPADI', name: 'GOLLAPALLI', lgdCode: '232733' },
    { district: 'VELLORE', block: 'KATPADI', name: 'KEERAISATHU', lgdCode: '232741' },
    { district: 'VELLORE', block: 'KATPADI', name: 'KONDAMANAIDUPALAYAM', lgdCode: '232745' },
    { district: 'VELLORE', block: 'KATPADI', name: 'MADHANDAKUPPAM', lgdCode: '232746' },
    { district: 'VELLORE', block: 'KATPADI', name: 'MAHIMANDALAM', lgdCode: '232747' },
    { district: 'VELLORE', block: 'KATPADI', name: 'MELPADI', lgdCode: '232750' },
    { district: 'VELLORE', block: 'KATPADI', name: 'THENGAL', lgdCode: '232765' },
    { district: 'VELLORE', block: 'KATPADI', name: 'THENPALLI', lgdCode: '232766' },
    { district: 'VELLORE', block: 'KATPADI', name: 'VINNAMPALLI', lgdCode: '232769' },
    { district: 'VELLORE', block: 'KATPADI', name: 'VALLIMALAI', lgdCode: '232767' },
    { district: 'VELLORE', block: 'KATPADI', name: 'VEPPALAI', lgdCode: '232772' },
    { district: 'VELLORE', block: 'KATPADI', name: 'MUTHARASIKUPPAM', lgdCode: '232751' },
    { district: 'VELLORE', block: 'KATPADI', name: 'PARAMASATHU', lgdCode: '232754' },
    { district: 'VELLORE', block: 'KATPADI', name: 'PERUMALKUPPAM', lgdCode: '232755' },
    { district: 'VELLORE', block: 'KATPADI', name: 'PONNAI', lgdCode: '232756' },
    { district: 'VELLORE', block: 'K.V. KUPPAM', name: 'Alanganeri', lgdCode: '232385' },
    { district: 'VELLORE', block: 'K.V. KUPPAM', name: 'Ammanankuppam', lgdCode: '232386' },
    { district: 'VELLORE', block: 'K.V. KUPPAM', name: 'Angarangkuppam', lgdCode: '232387' },
    { district: 'VELLORE', block: 'K.V. KUPPAM', name: 'Annangudi', lgdCode: '232388' },
    { district: 'VELLORE', block: 'K.V. KUPPAM', name: 'Arumbakkam', lgdCode: '232389' },
    { district: 'VELLORE', block: 'K.V. KUPPAM', name: 'Bomminaickanpalayam', lgdCode: '232390' },
    { district: 'VELLORE', block: 'K.V. KUPPAM', name: 'Chenji', lgdCode: '232391' },
    { district: 'VELLORE', block: 'K.V. KUPPAM', name: 'Cholamoor', lgdCode: '232392' },
    { district: 'VELLORE', block: 'K.V. KUPPAM', name: 'Devarishikuppam', lgdCode: '232393' },
    { district: 'VELLORE', block: 'K.V. KUPPAM', name: 'Kalampattu', lgdCode: '232394' },
    { district: 'VELLORE', block: 'K.V. KUPPAM', name: 'Kanguppam', lgdCode: '232395' },
    { district: 'VELLORE', block: 'K.V. KUPPAM', name: 'Kavanur', lgdCode: '232396' },
    { district: 'VELLORE', block: 'K.V. KUPPAM', name: 'Kavasampattu', lgdCode: '232397' },
    { district: 'VELLORE', block: 'K.V. KUPPAM', name: 'Keelalathur', lgdCode: '232398' },
    { district: 'VELLORE', block: 'K.V. KUPPAM', name: 'Kilmuttukur', lgdCode: '232399' },
    { district: 'VELLORE', block: 'K.V. KUPPAM', name: 'Kilvaithinankuppam', lgdCode: '232400' },
    { district: 'VELLORE', block: 'K.V. KUPPAM', name: 'Kosavanpudur', lgdCode: '232401' },
    { district: 'VELLORE', block: 'K.V. KUPPAM', name: 'Kothamangalam', lgdCode: '232402' },
    { district: 'VELLORE', block: 'K.V. KUPPAM', name: 'Latheri', lgdCode: '232403' },
    { district: 'VELLORE', block: 'K.V. KUPPAM', name: 'Machanur', lgdCode: '232404' },
    { district: 'VELLORE', block: 'K.V. KUPPAM', name: 'Maliyapattu', lgdCode: '232405' },
    { district: 'VELLORE', block: 'K.V. KUPPAM', name: 'Melmoil', lgdCode: '232406' },
    { district: 'VELLORE', block: 'K.V. KUPPAM', name: 'Mudinampattu', lgdCode: '232407' },
    { district: 'VELLORE', block: 'K.V. KUPPAM', name: 'Murukkampattu', lgdCode: '232408' },
    { district: 'VELLORE', block: 'K.V. KUPPAM', name: 'Nagal', lgdCode: '232409' },
    { district: 'VELLORE', block: 'K.V. KUPPAM', name: 'Netteri', lgdCode: '232410' },
    { district: 'VELLORE', block: 'K.V. KUPPAM', name: 'P. K. Puram', lgdCode: '232411' },
    { district: 'VELLORE', block: 'K.V. KUPPAM', name: 'Pasumathur', lgdCode: '232413' },
    { district: 'VELLORE', block: 'K.V. KUPPAM', name: 'Panamadangi', lgdCode: '232412' },
    { district: 'VELLORE', block: 'K.V. KUPPAM', name: 'Pillanthipattu', lgdCode: '232414' },
    { district: 'VELLORE', block: 'K.V. KUPPAM', name: 'Sennanguppam', lgdCode: '232415' },
    { district: 'VELLORE', block: 'K.V. KUPPAM', name: 'Sethuvandai', lgdCode: '232416' },
    { district: 'VELLORE', block: 'K.V. KUPPAM', name: 'Thirumani', lgdCode: '232417' },
    { district: 'VELLORE', block: 'K.V. KUPPAM', name: 'Thondanthulasi', lgdCode: '232418' },
    { district: 'VELLORE', block: 'K.V. KUPPAM', name: 'Vaduganthangal', lgdCode: '232419' },
    { district: 'VELLORE', block: 'K.V. KUPPAM', name: 'Velampattu', lgdCode: '232420' },
    { district: 'VELLORE', block: 'K.V. KUPPAM', name: 'Veppanganeri', lgdCode: '232421' },
    { district: 'VELLORE', block: 'K.V. KUPPAM', name: 'Veppur', lgdCode: '232422' },
    { district: 'VELLORE', block: 'K.V. KUPPAM', name: 'Vilunthakal', lgdCode: '232423' },
    { district: 'VELLORE', block: 'GUDIYATHAM', name: 'Agravaram', lgdCode: '232565' },
    { district: 'VELLORE', block: 'GUDIYATHAM', name: 'Ananganallore', lgdCode: '232306' },
    { district: 'VELLORE', block: 'GUDIYATHAM', name: 'Bojanapuram', lgdCode: '232307' },
    { district: 'VELLORE', block: 'GUDIYATHAM', name: 'Chengundram', lgdCode: '232308' },
    { district: 'VELLORE', block: 'GUDIYATHAM', name: 'Cheruvangi', lgdCode: '232309' },
    { district: 'VELLORE', block: 'GUDIYATHAM', name: 'Chettikuppam', lgdCode: '232310' },
    { district: 'VELLORE', block: 'GUDIYATHAM', name: 'Chinnalapalli', lgdCode: '232311' },
    { district: 'VELLORE', block: 'GUDIYATHAM', name: 'Chinnathottalam', lgdCode: '232312' },
    { district: 'VELLORE', block: 'GUDIYATHAM', name: 'D.p.palayam', lgdCode: '232313' },
    { district: 'VELLORE', block: 'GUDIYATHAM', name: 'Dhanakondapalli', lgdCode: '232314' },
    { district: 'VELLORE', block: 'GUDIYATHAM', name: 'Erthangal', lgdCode: '232315' },
    { district: 'VELLORE', block: 'GUDIYATHAM', name: 'Goodanagaram', lgdCode: '232316' },
    { district: 'VELLORE', block: 'GUDIYATHAM', name: 'Kallapadi', lgdCode: '232317' },
    { district: 'VELLORE', block: 'GUDIYATHAM', name: 'Karuneegasamuthiram', lgdCode: '232318' },
    { district: 'VELLORE', block: 'GUDIYATHAM', name: 'Kilpatti', lgdCode: '232319' },
    { district: 'VELLORE', block: 'GUDIYATHAM', name: 'Kondasamuthiram', lgdCode: '232320' },
    { district: 'VELLORE', block: 'GUDIYATHAM', name: 'Kothakuppam', lgdCode: '232321' },
    { district: 'VELLORE', block: 'GUDIYATHAM', name: 'Kulithigai', lgdCode: '232322' },
    { district: 'VELLORE', block: 'GUDIYATHAM', name: 'Melalathur', lgdCode: '232323' },
    { district: 'VELLORE', block: 'GUDIYATHAM', name: 'Melmuttukur', lgdCode: '232324' },
    { district: 'VELLORE', block: 'GUDIYATHAM', name: 'Modikuppam', lgdCode: '232325' },
    { district: 'VELLORE', block: 'GUDIYATHAM', name: 'Moongapattu', lgdCode: '232326' },
    { district: 'VELLORE', block: 'GUDIYATHAM', name: 'Mukkundram', lgdCode: '232327' },
    { district: 'VELLORE', block: 'GUDIYATHAM', name: 'Nellorepet', lgdCode: '232328' },
    { district: 'VELLORE', block: 'GUDIYATHAM', name: 'Olakasi', lgdCode: '232329' },
    { district: 'VELLORE', block: 'GUDIYATHAM', name: 'Pakkam', lgdCode: '232330' },
    { district: 'VELLORE', block: 'GUDIYATHAM', name: 'Paradharami', lgdCode: '232331' },
    { district: 'VELLORE', block: 'GUDIYATHAM', name: 'Pattu', lgdCode: '232332' },
    { district: 'VELLORE', block: 'GUDIYATHAM', name: 'Perumbadi', lgdCode: '232333' },
    { district: 'VELLORE', block: 'GUDIYATHAM', name: 'Puttavaripalli', lgdCode: '232334' },
    { district: 'VELLORE', block: 'GUDIYATHAM', name: 'Rajakuppam', lgdCode: '232335' },
    { district: 'VELLORE', block: 'GUDIYATHAM', name: 'Ramalai', lgdCode: '232336' },
    { district: 'VELLORE', block: 'GUDIYATHAM', name: 'Sempalli', lgdCode: '232339' },
    { district: 'VELLORE', block: 'GUDIYATHAM', name: 'Sembedu', lgdCode: '232338' },
    { district: 'VELLORE', block: 'GUDIYATHAM', name: 'Seevoor', lgdCode: '232337' },
    { district: 'VELLORE', block: 'GUDIYATHAM', name: 'Singalpadi', lgdCode: '232340' },
    { district: 'VELLORE', block: 'GUDIYATHAM', name: 'Thazhaiyatham', lgdCode: '232341' },
    { district: 'VELLORE', block: 'GUDIYATHAM', name: 'Thattaparai', lgdCode: '232342' },
    { district: 'VELLORE', block: 'GUDIYATHAM', name: 'Thattimanapalli', lgdCode: '232343' },
    { district: 'VELLORE', block: 'GUDIYATHAM', name: 'Ulli', lgdCode: '232344' },
    { district: 'VELLORE', block: 'GUDIYATHAM', name: 'Valathur', lgdCode: '232345' },
    { district: 'VELLORE', block: 'GUDIYATHAM', name: 'Varadhareddipalli', lgdCode: '232346' },
    { district: 'VELLORE', block: 'GUDIYATHAM', name: 'Veerichettipalli', lgdCode: '232347' },
    { district: 'VELLORE', block: 'GUDIYATHAM', name: 'Viluthonpalayam', lgdCode: '232348' },
    { district: 'VELLORE', block: 'GUDIYATHAM', name: 'AGARAMCHERI', lgdCode: '232564' },
    { district: 'VELLORE', block: 'GUDIYATHAM', name: 'CHINNACHERI', lgdCode: '232570' },
    { district: 'VELLORE', block: 'GUDIYATHAM', name: 'GOLLAMANGALAM', lgdCode: '232572' },
    { district: 'VELLORE', block: 'GUDIYATHAM', name: 'KOOTHAMBAKKAM', lgdCode: '232576' },
    { district: 'VELLORE', block: 'GUDIYATHAM', name: 'PALLIKUPPAM', lgdCode: '232586' },
    { district: 'VELLORE', block: 'GUDIYATHAM', name: 'Morthana', lgdCode: '232709' },
    { district: 'VELLORE', block: 'PERNAMBET', name: 'Alinjikuppam', lgdCode: '232678' },
    { district: 'VELLORE', block: 'PERNAMBET', name: 'Aravatla', lgdCode: '232680' },
    { district: 'VELLORE', block: 'PERNAMBET', name: 'Balur', lgdCode: '232681' },
    { district: 'VELLORE', block: 'PERNAMBET', name: 'Chendathur', lgdCode: '232684' },
    { district: 'VELLORE', block: 'PERNAMBET', name: 'Chinnathamalcheruvu', lgdCode: '232686' },
    { district: 'VELLORE', block: 'PERNAMBET', name: 'Chokkarishikuppam', lgdCode: '232688' },
    { district: 'VELLORE', block: 'PERNAMBET', name: 'Erikuthi', lgdCode: '232690' },
    { district: 'VELLORE', block: 'PERNAMBET', name: 'Erukkambattu', lgdCode: '232691' },
    { district: 'VELLORE', block: 'PERNAMBET', name: 'Gundalapalli', lgdCode: '232693' },
    { district: 'VELLORE', block: 'PERNAMBET', name: 'Karkoor', lgdCode: '232696' },
    { district: 'VELLORE', block: 'PERNAMBET', name: 'Kothapalli', lgdCode: '232698' },
    { district: 'VELLORE', block: 'PERNAMBET', name: 'Kothur', lgdCode: '232699' },
    { district: 'VELLORE', block: 'PERNAMBET', name: 'Machampattu', lgdCode: '232701' },
    { district: 'VELLORE', block: 'PERNAMBET', name: 'Mailpatti', lgdCode: '232702' },
    { district: 'VELLORE', block: 'PERNAMBET', name: 'Masigam', lgdCode: '232704' },
    { district: 'VELLORE', block: 'PERNAMBET', name: 'Melvaithinankuppam', lgdCode: '232706' },
    { district: 'VELLORE', block: 'PERNAMBET', name: 'Morasapalli', lgdCode: '232708' },
    { district: 'VELLORE', block: 'PERNAMBET', name: 'Pallalakuppam', lgdCode: '232712' },
    { district: 'VELLORE', block: 'PERNAMBET', name: 'Paravakkal', lgdCode: '232714' },
    { district: 'VELLORE', block: 'PERNAMBET', name: 'Bathalapalli', lgdCode: '232683' },
    { district: 'VELLORE', block: 'PERNAMBET', name: 'Pogalur', lgdCode: '232717' },
    { district: 'VELLORE', block: 'PERNAMBET', name: 'Rajakkal', lgdCode: '232718' },
    { district: 'VELLORE', block: 'PERNAMBET', name: 'Sathgur', lgdCode: '232720' },
    { district: 'VELLORE', block: 'PERNAMBET', name: 'T. T. Mottur', lgdCode: '232721' },
];